### ISSUE TITLE
Python twitter sentimental analysis

### ISSUE THREAD

**Issue by Bruder011** [tweepy/tweepy#1000]
import re
import tweepy
from tweepy import OAuthHandler
from textblob import TextBlob
from twitter import Twitter

class TwitterClient(object):
	'''
	Generic Twitter Class for sentiment analysis.
	'''
	def __init__(self):
		'''
		Class constructor or initialization method.
		'''
		# keys and tokens from the Twitter Dev Console
consumer_key=''
consumer_secret=''    
access_token=''
access_token_secret =''

		# attempt authentication
try:
			# create OAuthHandler object
			self.auth = OAuthHandler(consumer_key, consumer_secret)
			# set access token and secret
			self.auth.set_access_token(access_token, access_token_secret)
			# create tweepy API object to fetch tweets
			self.api = tweepy.API(self.auth)
except:
			print("Error: Authentication Failed")

def clean_tweet(self, tweet):
		'''
		Utility function to clean tweet text by removing links, special characters
		using simple regex statements.
		'''
		return ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t]) | (\w+:\/\/\S+)", " ", tweet).split())

def get_tweet_sentiment(self, tweet):
		'''
		Utility function to classify sentiment of passed tweet
		using textblob's sentiment method
		'''
		# create TextBlob object of passed tweet text
		analysis = TextBlob(self.clean_tweet(tweet))
		# set sentiment
		if analysis.sentiment.polarity > 0:
			return 'positive'
		elif analysis.sentiment.polarity == 0:
			return 'neutral'
		else:
			return 'negative'

class TwitterClient:
    api = tweepy.API(auth)
    def get_tweets(self, query, count = 10):
        tweets = []
        try:
            fetched_tweets = self.api.search(q = query, count = count)

            for tweet in fetched_tweets:
                parsed_tweet = {}
                parsed_tweet['text'] = tweet.text
                parsed_tweet['sentiment'] = self.get_tweet_sentiment(tweet.text)

                if tweet.retweet_count > 0:
                    if parsed_tweet not in tweets:
                        tweets.append(parsed_tweet)
                else:
                    tweets.append(parsed_tweet)

            return tweets

        except tweepy.TweepError as e:
            print("Error : " + str(e))

def main():
    client = TwitterClient()
    tweets = client.get_tweets(query = 'Dengue', count = 200)

	# picking positive tweets from tweets
	# percentage of positive tweets
print("Positive tweets percentage: {} %".format(100*len(ptweets)/len(tweets)))
	# picking negative tweets from tweets
ntweets = [tweet for tweet in tweets if tweet['sentiment'] == 'negative']
	# percentage of negative tweets
print("Negative tweets percentage: {} %".format(100*len(ntweets)/len(tweets)))
	# percentage of neutral tweets
print("Neutral tweets percentage: {} % \
		".format(100*len(tweets - ntweets - ptweets)/len(tweets)))

	# printing first 5 positive tweets
print("\n\nPositive tweets:")
for tweet in ptweets[:10]:
        print(tweet['text'])

	# printing first 5 negative tweets
print("\n\nNegative tweets:")
for tweet in ntweets[:10]:
        print(tweet['text'])

if __name__ == "__main__":
	# calling main function
        main()

**Comment by Bruder011** [comment]
Traceback (most recent call last):
  File "C:\Python27\gra.py", line 54, in <module>
    class TwitterClient:
  File "C:\Python27\gra.py", line 55, in TwitterClient
    api = tweepy.API(auth)
NameError: name 'auth' is not defined

**Comment by braian87b** [comment]
please, edit your post and format it well using code button.

**Comment by manoadamro** [comment]
@Bruder011 I assume you wanted `self.auth`

**Comment by Harmon758** [comment]
It seems like you're attempting to redefine `TwitterClient` and as the error says, referencing a variable, `auth`, that is not defined in it.

This is not an issue with Tweepy.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
