### ISSUE TITLE
Status object from get_status different from stream status

### ISSUE THREAD

**Issue by LRAbbade** [tweepy/tweepy#1006]
I have a running stream saving tweets to a local DB, I've made some changes in my code and my older tweets are missing some information.
I'm trying to get the original tweet using the get_status method, in order to collect the information I don't have, the problem is that the status returned from get_status has some differences from the status I get from the stream, eg.: the stream object has the 'extended_tweet' field for truncated texts and a 'reply_count', both of them are not present in the status returned from get_status.

I want to know if there's another method for getting an original status with the complete information.

Thank you.

**Comment by Harmon758** [comment]
For the `extended_tweet` field, the equivalent for REST APIs is to use the extended mode by passing it as the `tweet_mode` parameter. You'll get back an extended Tweet with the equivalent `full_text` and `display_text_range` and proper `entities` and `extended_entities` fields.
For more information, see https://developer.twitter.com/en/docs/tweets/tweet-updates.

As for `reply_count`:
> This object is only available with the Premium and Enterprise tier products.

See https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object.html.
