### ISSUE TITLE
Documentation: api.look_up users is missing

### ISSUE THREAD

**Issue by skilfullycurled** [tweepy/tweepy#1008]
Hello,

I don't believe [api.look_up](https://github.com/tweepy/tweepy/blob/master/tweepy/api.py#L325) users is documented in the API reference.  Not terribly difficult to figure out but historically, some libraries have required lists, others a list that is string joined, and some accept both.

Thanks!

**Comment by skilfullycurled** [comment]
Oops!  Seems like this issue is referenced [here](https://github.com/tweepy/tweepy/issues/539).  Title was a bit different so didn't come up in my search.  Sorry!

**Comment by Harmon758** [comment]
Duplicate of #539
