### ISSUE TITLE
the num limitation 

### ISSUE THREAD

**Issue by githublr** [tweepy/tweepy#1009]
`for tweet in tweepy.Cursor(api.user_timeline, id='user_id').items():`
by this way , I can only get 1052 tweets. It seems a bit less, How can I get more data?

**Comment by Harmon758** [comment]
I'm unable to reproduce this.
The Twitter API's [statuses/user_timeline endpoint](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline) has a limit of up to 3,200 of a user's most recent Tweets.
Currently, the only way to get older Tweets is via the [premium](https://developer.twitter.com/en/docs/tweets/search/overview/premium) or [enterprise](https://developer.twitter.com/en/docs/tweets/search/overview/enterprise) search APIs.
