### ISSUE TITLE
Permission denied

### ISSUE THREAD

**Issue by Jujurh** [tweepy/tweepy#1010]
I use Mac terminal ..
and I got this error when I type " python setup.py install "
[Errno 13] Permission denied: '/Library/Python/2.7/site-packages/test-easy-install-1129.pth'
Please make the appropriate changes for your system and try again.

any help ? I am beginner .

**Comment by yankskwesi** [comment]
Please make sure you are able to write to the folder you are attempting to install to.

**Comment by lamar-frankie** [comment]
You could change the folder permissions (chmod 755 path/to/folder) or run the command with super user permissions ( sudo python setup.py install ).

**Comment by Harmon758** [comment]
As explained, this is an issue with your OS permissions during installation, not an issue with Tweepy.
