### ISSUE TITLE
no module named tweepy.streaming and tweepy is not a package

### ISSUE THREAD

**Issue by hadhila** [tweepy/tweepy#1011]
hi i am getting the error message as
from tweepy.streaming import StreamListener
ModuleNotFoundError: No module named 'tweepy.streaming'; 'tweepy' is not a package
please help me

**Comment by hadhila** [comment]
please help me as soon as possible.

**Comment by fitnr** [comment]
It seems like you haven't properly installed tweepy. On your command line, try running `pip install --user tweepy` again.

**Comment by hadhila** [comment]
Thank you so much. It worked for me.

**Comment by KC2016** [comment]
> 
> 
> It seems like you haven't properly installed tweepy. On your command line, try running `pip install --user tweepy` again.

I tried this but  I received: 
WARNING: No metadata found in c:\users\...\anaconda3\envs\p3.6\lib\site-packages
ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: 'c:\\users\\...\\anaconda3\\envs\\p3.6\\lib\\site-packages\\tweepy-3.8.0.dist-info\\METADATA'

What can I do?

**Comment by MahmoodabadiHamid** [comment]
Hey Hadhila, 
Please note that your file name should not have the same name as the packages that you are importing.

**Comment by widyastuti** [comment]
my suggestion is to create new file.py and paste your code there. then run again. it works on my problem

**Comment by bharat-chandra** [comment]
> Hey Hadhila,
> Please note that your file name should not have the same name as the packages that you are importing.

cool ! it worked for me
thank you.

**Comment by bharat-chandra** [comment]
> my suggestion is to create new file.py and paste your code there. then run again. it works on my problem

cool ! it worked for me
thank you.

**Comment by DavidGehlert** [comment]
test

**Comment by sagar8557** [comment]
ImportError: cannot import name 'TweepError' from 'tweepy' (C:\Users\ssvrm\.conda\envs\geo_env\lib\site-packages\tweepy\__init__.py)

Any help or suggestion how  can i fixed this error

**Comment by Harmon758** [comment]
Please don't necrobump old closed issues.
`TweepError` was replaced with `TweepyException` and `HTTPException` in [v4.0.0](https://github.com/tweepy/tweepy/releases/tag/v4.0.0),
