### ISSUE TITLE
Tweepy.org docs are inaccessible

### ISSUE THREAD

**Issue by Honza-m** [tweepy/tweepy#1012]
![preview](https://user-images.githubusercontent.com/32596100/36985570-855daeca-208f-11e8-8c88-7ccdf201003a.png)

**Comment by joshthecoder** [comment]
Renewed domain should be back shortly

**Comment by grofte** [comment]
Forum still dead tho http://discuss.tweepy.org/

**Comment by Harmon758** [comment]
@grofte Note, as of right now, it has been replaced with a [Discord server](https://discord.gg/bJvqnhg). See #1025.
