### ISSUE TITLE
Listing likes of a tweet

### ISSUE THREAD

**Issue by ThibaultVlacich** [tweepy/tweepy#1014]
Hello, is there a way to get a list of people who liked a tweet ? I've read the documentation and I don't seem to find a way.

**Comment by imranrajjad** [comment]
well what happened?

**Comment by Harmon758** [comment]
This is not possible with Twitter's API.
See https://twittercommunity.com/t/list-of-people-who-favorited-a-particular-tweet/11083, https://twittercommunity.com/t/tweet-favoriters/77709, etc.

**Comment by poojadesur** [comment]
Twitter API v2 has an endpoint for it - GET /2/tweets/:id/liking_users. See https://developer.twitter.com/en/docs/twitter-api/tweets/likes/introduction

**Comment by Harmon758** [comment]
Please don't necrobump old closed issues.
Support for that endpoint was added with [`Client.get_liking_users`](https://tweepy.readthedocs.io/en/v4.4.0/client.html#tweepy.Client.get_liking_users) in Tweepy v4.0.0. See #1472.
