### ISSUE TITLE
ignore tweepy log messages

### ISSUE THREAD

**Issue by sp1thas** [tweepy/tweepy#1018]
I'm newbie with `logging` and I trying to find a way to ignore tweepy log messages. For example these debug messages generated from `API.get_user` method:
```
Tue, 13 Mar 2018 07:44:41 DEBUG    Signature: sdfsdf958zEptbJ0M=
Tue, 13 Mar 2018 07:44:41 DEBUG    Updated url: https://api.twitter.com/1.1/users/show.json?id=740903288871096320
Tue, 13 Mar 2018 07:44:41 DEBUG    Updated headers: {u'Host': u'api.twitter.com', u'Authorization': u'OAuth oauth_nonce="3453453451520941481", oauth_timestamp="1520941481", oauth_version="1.0", oauth_signature_method="HMAC-SHA1", oauth_consumer_key="sdfsdfsdfsdfISm8r8ELDvUqNlDn", oauth_token="sdfsdf496-eFyAJ3YTiMein8G0UTsrrN90YynrXl4", oauth_signature="sdfsdfsdfEptbJ0M%3D"'}
```
Some unsuccessfull tries to get tweepy logger:
```
logging.getLogger('tweepy.bind.bind_api').setLevel(logging.ERROR)
logging.getLogger('tweepy').setLevel(logging.ERROR)
logging.getLogger('tweepy.bind').setLevel(logging.ERROR)
```
Have you any idea how to catch these log messages?

**Comment by Harmon758** [comment]
You can include the name of the logger with the [LogRecord name attribute](https://docs.python.org/3/library/logging.html#logrecord-attributes) by using `%(name)s` in your [`logging.Formatter`](https://docs.python.org/3/library/logging.html#logging.Formatter)'s format to see where certain log messages are from.

In this case, you would be able to see that the first line is from `oauthlib.oauth1.rfc5849`:
https://github.com/oauthlib/oauthlib/blob/30321dd3c0ca784d3508a1970cf90d9f76835c79/oauthlib/oauth1/rfc5849/__init__.py#L150
and the latter two lines are from `requests_oauthlib.oauth1_auth`:
https://github.com/requests/requests-oauthlib/blob/800976faab3b827a42fa1cb80f13fcc03961d2c9/requests_oauthlib/oauth1_auth.py#L114-L115

None of those log messages are directly from Tweepy.
