### ISSUE TITLE
Search_users is obsolete?

### ISSUE THREAD

**Issue by alvgarvar** [tweepy/tweepy#1022]
Hi, I'm a new user of Tweepy and I have a question about the API.

I have the next code:

```
if request.method == 'POST':
            if buscador_form.is_valid():
                cd = buscador_form.cleaned_data
                buscar = cd['buscar']
                user_busqueda = api.search_users(buscar)

                context['user_busqueda'] = user_busqueda
```

And the error that I get is the next:

> [{'message': 'Your credentials do not allow access to this resource', 'code': 220}]
In this part:
> user_busqueda = api.search_users(buscar) 

I test the code put que parameter "q and page" and my Twitter APP have permission to read and write.

I want to know if the error is a code problem or with the API. Thanks.

**Comment by Harmon758** [comment]
The [users/search](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-search) Twitter API endpoint requires authentication with user context.
This means that you need to provide the access token and secret with something like `auth.set_access_token(key, secret)` when initializing the OAuthHandler.
For more information, see https://tweepy.readthedocs.io/en/latest/auth_tutorial.html and https://developer.twitter.com/en/docs/basics/authentication/overview/oauth.
