### ISSUE TITLE
Community 

### ISSUE THREAD

**Issue by joshthecoder** [tweepy/tweepy#1025]
Hello all! I wanted to start a topic around better enabling community engagement. Tweepy is a group effort and we need to all contribute together to keep it going.
I would like to gather here any idea around how we can better do this.

As a first step I have setup a new place for us to chat. I would like to try using Discord which I have running anyways all the time so I should be around most of the time. This is the go to place for support related questions (rather than these ending up in Github Issues) and just general discussions around pending PRs or issues.

You can join the server by clicking this link: https://discord.gg/bJvqnhg
You may either download the desktop client or just use the web based version.

I might also look at setting up a forum again if that would be useful. But I feel like between Github issues and just asking things on Discord this might not be needed. I don't really have the time to be reading through forum posts or really managing the hosting of one.

**Comment by Harmon758** [comment]
Going to close this now as I've been handling support in the Discord server.
Any additional feedback can also be given there.
