### ISSUE TITLE
'NoneType' object has no attribute 'strip' - v 3.6

### ISSUE THREAD

**Issue by jhosn13** [tweepy/tweepy#1026]
Using tweepy python library, hit this error: 'NoneType' object has no attribute 'strip'
I noticed that it was an error is previous releases. Any hot fix for 3.6?

**Comment by joshthecoder** [comment]
Need a bit more info on this issue. Can you provide a reproducible example?

**Comment by jhosn13** [comment]
Normal implementation of tweepy (included below) - The error is not exactly reproducible simply because it showed up after days of data collection. Currently, I am using subprocess (popen) to call my script again whenever this error pops up not to lose any data. 

```
import tweepy
import datetime


consumer_key = 
consumer_secret = 
access_token= 
access_token_secret=

args = 

class MyStreamListener(tweepy.StreamListener):
    def get_filename(self):
        now = datetime.datetime.now()
        filename = now.strftime('%d') + "_" + now.strftime('%m') + "_" + now.strftime('%Y')
        return filename+'.json'

    def on_data(self, data):
        try:
            savefile=open(self.get_filename(),'a')
            savefile.write(data)
            savefile.close()
            return True
        except BaseException as e:
            print("Error on_data: %s" % str(e))
        return True
    def on_error(self, status_code):
        if status_code == 420:
            return False

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token,access_token_secret)

api = tweepy.API(auth)
myStreamListener = MyStreamListener()
myStream = tweepy.Stream(auth=api.auth, listener=myStreamListener)
myStream.filter(track=args, async=True)
```

**Comment by joshthecoder** [comment]
Cool thanks for the extra info. I suspect this change introduced the bug: https://github.com/tweepy/tweepy/commit/176061133bd5aa1592f222834498daf28018db0c

My guess we need to guard against `read_line()` returning `None` some of the time.

**Comment by joshthecoder** [comment]
Created a semi hacky fix here https://github.com/tweepy/tweepy/pull/1027
If you want to test that out and let me know if it helps.
