### ISSUE TITLE
pip 10 build failure

### ISSUE THREAD

**Issue by FRidh** [tweepy/tweepy#1029]
This package (latest stable, master) fails to build with pip 10 because it imports something which is now internal.

`setup.py`
```
from pip.req import parse_requirements
```

**Comment by Harmon758** [comment]
This should be fixed by https://github.com/tweepy/tweepy/commit/29e32cdf4a67b1fca25dbf04d7b8069ac1c9dd0d (#1030) in [3.7.0](https://github.com/tweepy/tweepy/releases/tag/3.7.0).
