### ISSUE TITLE
Installation failure with incompatible pygerrit package/module

### ISSUE THREAD

**Issue by rsamikan** [tweepy/tweepy#1032]
Hi,
i am trying to install tweepy for python3.5 with -m option, but i am seeing failure incompatible request of pygerrit package.

Logs:
samikanr@mymachine:/dev1/twitter$python3.5 -m pip install tweepy --user
Collecting tweepy
  Downloading https://files.pythonhosted.org/packages/05/f1/2e8c7b202dd04117a378ac0c55cc7dafa80280ebd7f692f1fa8f27fd6288/tweepy-3.6.0-py2.py3-none-any.whl
Collecting requests-oauthlib>=0.7.0 (from tweepy)
  Downloading https://files.pythonhosted.org/packages/77/34/d0957563f20b259a31c12f14e858d79f2e66eb539d3c1b9ab7077ef030ca/requests_oauthlib-0.8.0-py2.py3-none-any.whl
Requirement already satisfied: six>=1.10.0 in /usr/lib/python3/dist-packages (from tweepy) (1.10.0)
Requirement already satisfied: requests>=2.11.1 in /usr/local/lib/python3.5/dist-packages (from tweepy) (2.18.4)
Collecting PySocks>=1.5.7 (from tweepy)
  Downloading https://files.pythonhosted.org/packages/53/12/6bf1d764f128636cef7408e8156b7235b150ea31650d0260969215bb8e7d/PySocks-1.6.8.tar.gz (283kB)
    100% |████████████████████████████████| 286kB 342kB/s
Requirement already satisfied: oauthlib>=0.6.2 in /usr/lib/python3/dist-packages (from requests-oauthlib>=0.7.0->tweepy) (1.0.3)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /usr/local/lib/python3.5/dist-packages (from requests>=2.11.1->tweepy) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.5/dist-packages (from requests>=2.11.1->tweepy) (2018.4.16)
Requirement already satisfied: idna<2.7,>=2.5 in /usr/local/lib/python3.5/dist-packages (from requests>=2.11.1->tweepy) (2.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.5/dist-packages (from requests>=2.11.1->tweepy) (3.0.4)
Building wheels for collected packages: PySocks
  Running setup.py bdist_wheel for PySocks ... done
  Stored in directory: /users/samikanr/.cache/pip/wheels/22/5c/b5/12e0dfdfa85bea67b23628b6425fae715c687e947a45ee3df9
Successfully built PySocks
pygerrit 1.0.0 has requirement requests==2.9.1, but you'll have requests 2.18.4 which is incompatible.
Installing collected packages: requests-oauthlib, PySocks, tweepy
Successfully installed PySocks-1.6.8 requests-oauthlib-0.8.0 tweepy-3.6.0
samikanr@mymachine:/dev1/twitter$

Regards, Raja.

**Comment by NNTin** [comment]
pygerrit version 1.0.0 requires the exact library requests version 2.9.1 see: https://github.com/sonyxperiadev/pygerrit/blob/master/requirements.txt  
tweepy 3.6.0 requires the library requests version 2.11.1 or later see: https://github.com/tweepy/tweepy/blob/master/requirements.txt

The request library has different versions. Features are constantly added, modified and deleted. Tweepy does not support requests version 2.11.0 or earlier. While pygerrit only supports requests version 2.9.1.

How about using pygerrit2. Their package requirements are more sensible, see: https://github.com/dpursehouse/pygerrit2/blob/master/requirements.txt  
pygerrit2 v2.0.4 requires requests version between 2.10.0 and 2.18.4.

There is no requirements library version conflict when using pygerrit2.

**Comment by rsamikan** [comment]
Many thanks for your explanation. then this has to be fixed in requirement.txt file, please correct me if i am wrong.

**Comment by rsamikan** [comment]
Fine.. Many thanks!!

**Comment by Harmon758** [comment]
This is not an issue with Tweepy.
Your installation succeeded with the correct dependencies properly installed.
As explained, how you handle your dependency resolution with other libraries is not an issue with Tweepy, considering that this library supports the latest version of requests. This is especially true if you're using an outdated library that is no longer maintained and has dependencies that are locked to an older version more than three years out of date.
