### ISSUE TITLE
how to extract tweets in multiple languages

### ISSUE THREAD

**Issue by SakhriHoussem** [tweepy/tweepy#1038]
how we can set multiple languages in  `lang`  argument
```python
for tweet in tweepy.Cursor(api.search,q=tweet_about,since=shared_date,until=shared_date_to,lang=tweet_lang).items(item_numbre):
       # do somthing
```

**Comment by Harmon758** [comment]
Twitter's [standard search API](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets.html) only allows one language for the `lang` parameter.
Instead, you can [standard search operators](https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators) in your query to filter by multiple languages, e.g.:
`q="lang:en OR lang:es"`.
