### ISSUE TITLE
Tweepy - Proxy problems persist

### ISSUE THREAD

**Issue by diptabhas** [tweepy/tweepy#1039]
Hello All
   Is there any updated solution to the Tweepy proxy problem. I have attached a snippet of my code. Cant make this work at all. Would really appreciate any guidance or direction on this.

Thanks
Diptabhas

![capture](https://user-images.githubusercontent.com/30348320/39586134-ff509a1c-4ebb-11e8-8146-5236ac932742.JPG)

**Comment by Harmon758** [comment]
What are the "Proxy problems" and "the Tweepy proxy problem" that you're referring to?
I'm unable to reproduce any issues. Can you provide a full traceback?
Just the fact that it's not working doesn't provide any information at all.
