### ISSUE TITLE
Will streaming be removed?

### ISSUE THREAD

**Issue by kootenpv** [tweepy/tweepy#1046]
I have a trouble understanding what kind of data will be removed: http://apps-of-a-feather.com/

The way I read it, if I stream certain accounts (without authentication) that should not be affected?

**Comment by paulaldana23** [comment]
I'm concerned about this one too. My app is designed to stream tweets based on topics, hashtags, and/or location. Will this gravely affect tweepy's streaming capability?

**Comment by fREAST** [comment]
From what i've read, only [userstreams](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/api-reference/user-stream) and [sitestreams](https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/api-reference/site-stream) are being deprecated.

If you are using [statuses/filter](https://developer.twitter.com/en/docs/tweets/filter-realtime/overview) it will continue to work, [according to twitter staff](https://twittercommunity.com/t/will-the-streaming-api-endpoint-statuses-filter-be-deprecated-too/104851/2).

Would be good with some clarification on this though.

**Comment by hugovk** [comment]
Have a look at:

https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

via https://twitter.com/tinysubversions/status/996947225195438080

**Comment by Harmon758** [comment]
User and Site streams have been deprecated and retired in favor of the new Account Activity API.
`Stream.filter` using the [statuses/filter endpoint](https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter) is unaffected.
For Account Activity API support, see #1075.

Also see:
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/building-the-future-of-the-twitter-api-platform.html

https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746
https://twittercommunity.com/t/reminder-site-streams-user-streams-and-legacy-dm-endpoints-will-be-sunset-august-16th/109482
https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736
https://twittercommunity.com/t/date-for-full-deprecation-of-user-streams-site-streams-and-legacy-direct-message-api-endpoints/98734
