### ISSUE TITLE
on_delete event "seems" to get called only every third time (?)

### ISSUE THREAD

**Issue by rodeod** [tweepy/tweepy#1051]
class StreamListener(tweepy.StreamListener):

    def on_delete(self, status_id, user_id):
... etc
    def on_status(self, status):
... etc

Reproduce:
I tweet several tweets on twitter.  on_status event gets called every time...
But when starting to delete those tweets, first delete on_delete doesn't get called, second one doesn't get called, but third delete on_delete gets called.  If continue deleting tweets, it appears only for every third delete on_delete handler gets called.

Is the code (above) correct?

tweep version: 3.6.0

**Comment by Harmon758** [comment]
This seems to have been an issue with User Streams, which have now been deprecated and retired in favor of the new Account Activity API.
For Account Activity API support, see #1075.

See:
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/building-the-future-of-the-twitter-api-platform.html

https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746
https://twittercommunity.com/t/reminder-site-streams-user-streams-and-legacy-dm-endpoints-will-be-sunset-august-16th/109482
https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736
https://twittercommunity.com/t/date-for-full-deprecation-of-user-streams-site-streams-and-legacy-direct-message-api-endpoints/98734
