### ISSUE TITLE
How to make streaming resume after dropping connection and reconnectting

### ISSUE THREAD

**Issue by ahoora08** [tweepy/tweepy#1053]
Using the following code I get some tweets using Tweepy Streaming and write them as a JSON file.
```
class MyStreamListener(tweepy.StreamListener):

    def on_data(self, tweet):
        decoded = json.loads(tweet)
        json.dump(decoded, file, sort_keys=True, indent=4)
        global tweetNum
        tweetNum += 1
        print "Writing tweet number " + str(tweetNum) + " to file"

    def on_status(self, status):
        print(status.text)

    def on_error(self, status_code):
        file.close()
        print status_code
        if status_code == 420:
            # returning False in on_error disconnects the stream
            return False
file = open('stream.json', 'a')
tweetNum = 0


myStreamListener = MyStreamListener()
myStream = tweepy.Stream(auth=api.auth, listener=myStreamListener, timeout=30)


myStream.filter(track=['A'], async=True)
```

But when the internet connection dropped a while and reconnect again, the code will not resume getting tweets! How can I modify the code to be fault-tolerant against losing connection? 

I tried [this question thread](https://stackoverflow.com/questions/29582080/tweepy-make-stream-run-forever) but it's for 3 years ago and creating a connection in a loop continuously will eventuate in error 420!

**Comment by Nismirno** [comment]
This should do the work for you.
```python
def start_stream(stream, **kwargs):
    try:
        stream.filter(**kwargs)
    except ReadTimeoutError:
        stream.disconnect()
        logger.exception("ReadTimeoutError exception")
        start_stream(stream, **kwargs)
    except Exception:
        stream.disconnect()
        logger.exception("Fatal exception. Consult logs.")
        start_stream(stream, **kwargs)
```

```python
start_stream(myStream, track=['A'], async=True)
```

**Comment by scriptykid-afk** [comment]
FYI the above will not work if you are setting is_async true, as the exceptions are being raised in a different thread than start_stream is running in. Would be interested to see how/if others have solved this issue when async streaming.

**Comment by Harmon758** [comment]
Are you encountering a specific error?
Without the actual error or traceback, it's impossible to determine what exactly the issue you're encountering is.

@scriptykid-afk See #1072.
