### ISSUE TITLE
Replies from tweepy not visible when logged out of bot account

### ISSUE THREAD

**Issue by alipphardt** [tweepy/tweepy#1057]
Replies posted using update_with_media appear on bot account's timeline and the original tweet itself when logged into bot account. Otherwise, the replies are hidden.  

If logged into the bot account in the browser and submitting a reply by manually clicking on the reply icon and submitting a tweet as a reply, the reply is visible whether logged into the account or not.

Is this a limitation of tweepy or the Twitter API? I have copied a snippet of code below

message = (".@" + tweet['user'] + " " + status)[0:140]
api.update_with_media(filename=image, status=message, in_reply_to_status_id=tweet['id'])

**Comment by victoraldir** [comment]
I know it's been open for while now, but I am facing the same problem. Any idea on that?

**Comment by ndrezn** [comment]
Also seeing this issue, incl. when using other twitter python interfaces (I've also tested [python-twitter](https://github.com/bear/python-twitter) and [twitter](https://github.com/sixohsix/twitter)).

It's possible to somewhat get around this issue by using the `auto_populate_reply_metadata` attribute. In Tweepy this looks like:

```python
api = tweepy.API(auth)
api.update_status(
    status=reply_status_test,
    in_reply_to_status_id=other_status.id,
)
```
but this still doesn't quite work properly, and the new tweet won't be connected, showing an error like this when viewing the reply:
<img width="460" alt="Screen Shot 2020-11-05 at 4 02 18 PM" src="https://user-images.githubusercontent.com/38958867/98296009-4a6f1180-1f80-11eb-8950-3b4fab54e7e8.png">
and not showing the reply at all when viewing the thread below the original status.

If anyone has a complete solution I'm all ears!

**Comment by ndrezn** [comment]
#1422 has a better explanation of this issue.

**Comment by rishab-sharma** [comment]
@ndrezn You got any solution yet for this reply visibility problem.

**Comment by ndrezn** [comment]
Following these suggestions solved it for me: https://twittercommunity.com/t/replies-posted-are-being-hidden-below-show-additional-replies/140364/2

**Comment by Harmon758** [comment]
As noted, this seems similar to #1422:
> I'm unable to reproduce this, but this seems like an issue on Twitter's end.
> There are various other similar reports of this:
> https://twittercommunity.com/t/tweets-sent-through-api-showing-up-as-unavailable/141639
> https://twittercommunity.com/t/only-me-can-see-my-replies-to-tweets/140052
> https://twittercommunity.com/t/replying-to-tweets-that-are-not-my-own-does-not-work/139901
> https://twittercommunity.com/t/bot-tweets-not-showing-up-to-users-other-than-me/140345
> 
> It could also be something specific to the account that Twitter is limiting. I would recommend following the suggestions in https://twittercommunity.com/t/replies-posted-are-being-hidden-below-show-additional-replies/140364/2.
> 
> This is unlikely to be an issue with Tweepy, so I'd recommend making a post on the Twitter Developers Forums as well.
> 
> If you'd like, you can provide a reproducible example (MCVE/SSCCE) so that I can test it to make sure it's an issue with the account or Twitter itself and not with Tweepy.
