### ISSUE TITLE
Help to make a retweet with the text

### ISSUE THREAD

**Issue by xxxxko** [tweepy/tweepy#1058]
Hey. I'm new. Help me to make a retweet with the text. I just happened to retweet the post

**Comment by LordDraagonLive** [comment]
I think you better close this issue as it makes a lot confusion. I think it will be better if you only posts issues about the tweepy library and not how to do something using it. Please refer the docs here http://docs.tweepy.org/en/v3.5.0/api.html for info,  there is a method called retweet() in the library which will help you. Thank you

**Comment by Harmon758** [comment]
I'm not exactly sure what you're asking, but as mentioned, [`API.retweet`](https://tweepy.readthedocs.io/en/latest/api.html#API.retweet) can be used to retweet a Tweet.
