### ISSUE TITLE
Tweepy not getting full text

### ISSUE THREAD

**Issue by Kyosuke2** [tweepy/tweepy#1059]
I am new to python and try to get tweets. But the problem is that it is not giving full Text. I tried to add 'extended' and 'full_text', but they did not work.

`import tweepy, TwitterAPIkey, csv, datetime

CK = TwitterAPIkey.consumer_key
CS = TwitterAPIkey.consumer_secret
AT = TwitterAPIkey.access_token
AS = TwitterAPIkey.access_token_secret

OUT_FILE = "/Users/------/Sample.txt" 

auth = tweepy.OAuthHandler(CK,CS)
api = tweepy.API(auth)

ow = csv.writer(open(OUT_FILE, "w", encoding = "UTF-8"), delimiter="\t")
keyword = "    " 

search_count = 100
repeat_count = 450

search_result = []
last_id = 0
for i in range(repeat_count):
    tweets = api.search(q=keyword, count=search_count, max_id=str(last_id-1), wait_on_rate_limit=True, tweets_mode= 'extend')
    search_result += tweets
    if len(tweets) == 0: break
    last_id = tweets[-1].id

for tw in search_result:
    ow.writerow([str(tw.created_at + datetime.timedelta(hours=9)), tw.id, tw.user.name, tw.user.screen_name, tw.full_text.replace("\n",r"\n")])`

**Comment by Ethiarpus** [comment]
There are a few typos in your code. "tweets_mode" should be "tweet_mode", and "extend" should be "extended".

**Comment by Harmon758** [comment]
See https://developer.twitter.com/en/docs/tweets/tweet-updates.
