### ISSUE TITLE
 import six ImportError: No module named six

### ISSUE THREAD

**Issue by sbabubo9** [tweepy/tweepy#1061]
I am trying to extract tweets using tweepy. I have installed tweepy by following steps suggested in github (https://github.com/tweepy/tweepy).

My OS is CentOS 7 with Hadoop installation. by default Python comes with 2.6 version which is not supported for tweepy so, I have upgraded Python to 2.7 from 2.6(edited)

This is my python code:
#Import the necessary methods from tweepy library
from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream

#Variables that contains the user credentials to access Twitter API
access_token = "XXXX"
access_token_secret = "XXXX"
consumer_key = "XXXX"
consumer_secret = "XXXX"

#This is a basic listener that just prints received tweets to stdout.
class StdOutListener(StreamListener):
def on_data(self, data):
print data
return True

For your confirmation, The above code is executing in Azure notebook but not in my Linux OS
Could you please help me.

error message is below

[root@sandbox-hdp tweepy]# python tweets.py
Traceback (most recent call last):
File "tweets.py", line 2, in <module>
from tweepy.streaming import StreamListener
File "/root/Python/tweepy/tweepy/init.py", line 12, in <module>
from tweepy.models import Status, User, DirectMessage, Friendship, SavedSearch, SearchResults, ModelFactory, Category
File "/root/Python/tweepy/tweepy/models.py", line 7, in <module>
from tweepy.utils import parse_datetime, parse_html_value, parse_a_href
File "/root/Python/tweepy/tweepy/utils.py", line 9, in <module>
import six
ImportError: No module named six

**Comment by fitnr** [comment]
This error means that your python install can't find a different python package, `six`. Running `python2.7 -m pip install six` on your command line should install it. If you don't have `pip` installed, then go ahead and [do that first](https://pip.pypa.io/en/stable/installing/).

This isn't an issue with tweepy, so please close this issue to ease the load on the maintainers.

**Comment by sbabubo9** [comment]
Dear fitnr,
thank you for your response,
I installed six then I am getting below error.
Traceback (most recent call last):                                                                                         
  File "tweets.py", line 2, in <module>                                                                                    
    from tweepy.streaming import StreamListener                                                                            
  File "/usr/lib/python2.6/site-packages/tweepy-3.6.0-py2.6.egg/tweepy/__init__.py", line 16, in <module>                  
    from tweepy.auth import OAuthHandler, AppAuthHandler                                                                   
  File "/usr/lib/python2.6/site-packages/tweepy-3.6.0-py2.6.egg/tweepy/auth.py", line 9, in <module>                       
    from requests_oauthlib import OAuth1Session, OAuth1                                                                    
  File "/usr/lib/python2.6/site-packages/requests_oauthlib-1.0.0-py2.6.egg/requests_oauthlib/__init__.py", line 16, in <mod
ule>                                                                                                                       
    logging.getLogger('requests_oauthlib').addHandler(logging.NullHandler())                                               
AttributeError: 'module' object has no attribute 'NullHandler'

**Comment by fitnr** [comment]
The important part of that error message is `python2.6`: while you may have installed Python 2.7, you're still using 2.6. As you note in your original question, v2.6 isn't supported. Try using the command `python2.7` instead of `python` to run your code, e.g:
```
$ python2.7 myscript.py
```

**Comment by Harmon758** [comment]
As explained, `six` is a required dependency for Tweepy and you're using Python 2.6, which as you noted, Tweepy does not support.
For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
