### ISSUE TITLE
Release for Python 3.7 support

### ISSUE THREAD

**Issue by Harmon758** [tweepy/tweepy#1063]
A new release should be made for changes from #1042, now that [Python 3.7.0](https://www.python.org/downloads/release/python-370/) has been [released](https://pythoninsider.blogspot.com/2018/06/python-3.html).

**Comment by hugovk** [comment]
@Aaron1011 Please could you make a new release? Or could we add another maintainer from https://github.com/tweepy/tweepy/issues/792?

**Comment by hugovk** [comment]
@joshthecoder Please could you make a new release? Or could we add another maintainer from #792? Thank you!

**Comment by Harmon758** [comment]
Resolved by [3.7.0 release](https://github.com/tweepy/tweepy/releases/tag/3.7.0)
