### ISSUE TITLE
Updates in tweepy with the effect of new twitter changes

### ISSUE THREAD

**Issue by ShaikAsifullah** [tweepy/tweepy#1065]
Can you help me understand if there will be any changes in Tweepy with the effect of [new twitter changes ](https://www.theverge.com/2018/5/16/17362138/twitter-api-third-party-apps-changes-explained )?

**Comment by NNTin** [comment]
The main source of the article you linked is this Twitter blog: https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html

If you are using tweepy's `stream.filter` you are definitely affected by this.  The free tier solution allows you to follow 15 users. It's the main way of getting live tweets.
https://developer.twitter.com/en/pricing/aaa-all
If you want to follow 250 users you need to pay $2,899.00 per month.  
In my Discord server I am mirroring the tweets of 1500 twitter users into text channels. (https://i.imgur.com/sjHGgVv.png) After this update I will have to limit myself to 15 twitter users.

http://apps-of-a-feather.com/

**Comment by shaikasif-mng1** [comment]
@NNTin Thanks for your help. Yes, I am using Stream.filter filtering 5 important keywords from the realtime streaming. Can you help me in knowing what does "follow 15 users" mean ? My app is simply filtering 5 keywords from the stream. Will this affect my app ?

**Comment by NNTin** [comment]
Actually after looking into it a bit more I'm unsure if stream.filter is really affected or not. Please disregard what I said. Sorry. 🙇

**Comment by allo-** [comment]
How is the support for the DirectMessage API changes? Will the old methods map to the new API or will there be a method like the new API endpoint?

**Comment by ryonakamura** [comment]
I don't clearly understand, but can we continue using the Public streams after updating?
https://developer.twitter.com/en/docs/tweets/sample-realtime/overview/GET_statuse_sample

**Comment by Harmon758** [comment]
User and Site streams have been deprecated and retired in favor of the new Account Activity API.
`Stream.filter` using the [statuses/filter endpoint](https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter) and `Stream.sample` using the [statuses/sample endpoint](https://developer.twitter.com/en/docs/tweets/sample-realtime/api-reference/get-statuses-sample) are unaffected.
For Account Activity API support, see #1075.
For Direct Message API changes, see #1081.

Also see:
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/building-the-future-of-the-twitter-api-platform.html

https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746
https://twittercommunity.com/t/reminder-site-streams-user-streams-and-legacy-dm-endpoints-will-be-sunset-august-16th/109482
https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736
https://twittercommunity.com/t/date-for-full-deprecation-of-user-streams-site-streams-and-legacy-direct-message-api-endpoints/98734
