### ISSUE TITLE
Max limit of tweets to be retrieved

### ISSUE THREAD

**Issue by emrecalisir** [tweepy/tweepy#1066]
I am trying to retrieve tweets of a user account, but I could retrieve only part of them. Even though that account has more than 13K tweets, I could retrieve only 3K of them. Do you know what could be the reason?
 
The code is:
cursor = tweepy.Cursor(api.user_timeline, screen_name='account_name')
for tweet in cursor.items():
    tweet_post_date=tweet.created_at

**Comment by sergegoussev** [comment]
The Twitter Search API returns at max 3200 of a users' most recent tweets, hence tweepy would not be able to give you more than that. See the Twitter dev <a href="https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline.html">GET statuses/user_timeline call</a> for more info.

**Comment by sarthak388** [comment]
Please share the Twitter API code for extraction of tweets in Python and R.

**Comment by Harmon758** [comment]
As explained, this is a limitation of the Twitter API's [statuses/user_timeline endpoint](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline.html):
> This method can only return up to 3,200 of a user's most recent Tweets. 

@sarthak388 Your request is not related to this issue.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Twitter's API, Python, or R.
