### ISSUE TITLE
Add pagination_mode to tweepy.models.User.followers and friends

### ISSUE THREAD

**Issue by rogeliorv** [tweepy/tweepy#107]
Right now we are able to cursor using

```
tweepy.Cursor(api.friends)
tweepy.Cursor(api.followers)
```

But if we have a user instance

```
u = api.get_user('rogeliorv')
tweepy.Cursor(u.friends)  # Does not work
tweepy.Cursor(u.followers) # Does not work
```

We get:

```
TweepError: This method does not perform pagination
```

We should be to benefit from the already implemented Cursor class.

This is fixed easily by adding 

```
friends.pagination_mode = 'cursor'
followers.pagination_mode = 'cursor'
```

in tweepy.models.User after the method declarations.

**Comment by syednh110** [comment]
you do not need to use
 tweepy.Cursor(u.friends)  # Does not work
tweepy.Cursor(u.followers) # Does not work

insteed use only:
print(u.friends)
print(u.followers_count)
