### ISSUE TITLE
Media in direct message

### ISSUE THREAD

**Issue by sharma-ji** [tweepy/tweepy#1073]
How to get image from the direct message?

**Comment by Harmon758** [comment]
It should be in the `entities` attribute of the `DirectMessage` object.
See https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object#entities-dm.

**Comment by miguelp25** [comment]
Hi, im experimenting some problems with direct messages, is it all okay for you with just "api.direct_messages()"?
I heard twitter is changing the way it manages direct messages, but I don't really know if the change has been implemented already...

**Comment by Harmon758** [comment]
@miguelp25 This is an unrelated issue. See #1081.
