### ISSUE TITLE
Tweepy not retrieving any tweet

### ISSUE THREAD

**Issue by hugoncosta** [tweepy/tweepy#1074]
Hey,

I've been using Tweepy for a while, and today I wanted to get more tweets usng the timeline api and Tweepy doesn't retrieve anything. I'm using the following code:

```
for status in tweepy.Cursor(api.user_timeline, id = 2831859546, tweet_mode = "extended", count = 200).items():
        status._json['full_text']
```
I thought that Twitter killed my API or smth, so I tried to use Birdy, and Birdy is able to retrieve the tweets I requested, so there has to be something wrong with Tweepy. What can I try?

Thanks

**Comment by Harmon758** [comment]
I'm unable to reproduce this.
How are you determining that Tweepy isn't retrieving anything?
In your snippet, you're not doing anything with the data returned.

**Comment by hugoncosta** [comment]
I did a test, check the following snippet:
```
temp = tweepy.Cursor(api.user_timeline, id = "twitter").items()
temp.num_tweets
```
And the response is 0. I've tried 2 different machines, 2 different environments, 2 different API key sets.

**Comment by Harmon758** [comment]
`Cursor.items` returns an iterator. `num_tweets` keeps track of what Tweet the iterator is at in the response.
As you haven't iterated through `temp` in that snippet, it'll return 0 as expected.

**Comment by hugoncosta** [comment]
What about `temp.current_page`? Shouldn't that return something? For me, it's a "NoneType" object. I remember running another snippet, I forgot which one, but it returned 104, and the 15m waiting period had long past.

**Comment by Harmon758** [comment]
Until you iterate through it, `ItemIterator.curent_page` will be `None`, again as expected:
https://github.com/tweepy/tweepy/blob/2efe385fc69385b57733f747ee62e6be12a1338b/tweepy/cursor.py#L182-L201

I don't think 104 is even a valid Twitter response code.

**Comment by hugoncosta** [comment]
Yeah 104 shouldn't be a valid Twitter response, but I got it and [some people have too](http://stackoverflow.com/questions/39619349/ddg#39627417). Anyway, it appears to have been resolved, thank you very much for your help!

**Comment by Harmon758** [comment]
That seems to be an HTTP response code caused by an error in the connection.

I'm not a collaborator, so I'm unable to close the issue, but you can do so yourself.

**Comment by hugoncosta** [comment]
Yeah that's what it seemed. Odd though, since I'm using Google Colab and the request originates from their servers, that's why I didn't even associate it with connection problems.

Oh, sorry, didn't see the button.
