### ISSUE TITLE
Support Account Activity API

### ISSUE THREAD

**Issue by NatCubed** [tweepy/tweepy#1075]
According to https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/api-reference/user-stream , user streaming and site streaming are deprecated and going to be removed. How soon can Tweepy be updated to use the webhooks that are going to replace this?

**Comment by Nismirno** [comment]
But tweepy already has `Stream.filter` for that. Or did I misunderstand something?
https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter.html

**Comment by wodim** [comment]
That has nothing to do with what streaming APIs could do, like return my own home timeline.

**Comment by Harmon758** [comment]
User and Site streams have been deprecated and retired in favor of the new Account Activity API.
`Stream.filter` using the statuses/filter endpoint is unaffected.

See:
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/building-the-future-of-the-twitter-api-platform.html

https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746
https://twittercommunity.com/t/reminder-site-streams-user-streams-and-legacy-dm-endpoints-will-be-sunset-august-16th/109482
https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736
https://twittercommunity.com/t/date-for-full-deprecation-of-user-streams-site-streams-and-legacy-direct-message-api-endpoints/98734

**Comment by bpluly** [comment]
I've subclassed API and published it at https://github.com/bpluly/AccountActivity
I haven't made it a pull request here solely because it is subclassing and it might well be implemented directly in api.py but that would involve considerably more testing than I have resources for.

**Comment by bpluly** [comment]
I've now branched and added the activityAPI sub-module which subclasses API. There are no automated tests. I have a web.py example use of all the of the API which should make general sense even if you're not familiar with web.py.

**Comment by saadmanrafat** [comment]
Created an API client for Account Activity. It does a lot of heavy lifting for the user. And is easy to use like Tweepy's `Streaming API`. 

![Imgur](https://i.imgur.com/fdV9zOc.gif)

```python3
# stream_events.py

>>> from twitivity import Event
>>> import json

>>> class StreamEvent(Event):
     CALLBACK_URL: str = "https://yourdomain.com/listener"
    
     def on_data(self, data: json) -> None:
         # process data

>>> stream_events = StreamEvent()
>>> stream_events.listen()
```

```
~$ pip3 install twitivity
```

You can find the [documentation here](https://github.com/saadmanrafat/twitivity).

**Comment by bpluly** [comment]
I have made a pull request for a tweepy implementation.

**Comment by JohnnyZ** [comment]
@bpluly Thanks for your pull request - is there any particular reason or better approach to accomplishing this functionality? 

I thank you for your contribution @saadmanrafat and will be utilizing this in the interim!

**Comment by bpluly** [comment]
> 
> 
> @bpluly Thanks for your pull request - is there any particular reason or better approach to accomplishing this functionality?
> 
> I thank you for your contribution @saadmanrafat and will be utilizing this in the interim!

The AccountActivity API is Twitter's and their choice to make it a webhook. This is a reasonable decision it means that Twitter has control over the resources needed to service the consumers.

From the consuming side treat the webhook as a notifier in your own backend and use something like queuing to separate the concerns and make is asynchronous. I despatch the events from the webhook to an AWS queue. Then I have workers reading that queue and parsing the events. That makes it scalable.

It's implemented the way it is to fit in with the architecture of Tweepy and extend it without breaking it. In other words it's easy to merge because it's a separate module.

**Comment by Harmon758** [comment]
This is stale now that [the Premium v1.1 API has been deprecated](https://twittercommunity.com/t/deprecating-the-premium-v1-1-api/191092) and with Tweepy currently having no intention of adding support for the Enterprise API.
