### ISSUE TITLE
issues in my new program (python)

### ISSUE THREAD

**Issue by FendiMon** [tweepy/tweepy#1076]
this is my coe
# themodelbot

import tweepy as tp
import time
import os

# credentials to login to twitter api
consumer_key = ''
consumer_secret = ''
access_token = ''
access_secret = ''

# login to twitter account api
auth = tp.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)
api = tp.API(auth)

os.chdir('models')

# iterates over pictures in models folder
for model_image in os.listdir('.'):
    api.update_with_media(model_image)
    time.sleep(120)

and this is my output
Traceback (most recent call last):
  File "C:/Users/Fendi/Desktop/twitter/tweepy.py", line 3, in <module>
    import tweepy as tp
  File "C:/Users/Fendi/Desktop/twitter\tweepy.py", line 14, in <module>
    auth = tp.OAuthHandler(consumer_key, consumer_secret)
AttributeError: 'module' object has no attribute 'OAuthHandler'
>>> 
can you help me , every time i try to run this program this happen  
"pip install tweepy" is already installed

**Comment by Harmon758** [comment]
Rename your file to something else besides `tweepy.py`.
You're attempting to import the file itself as a module instead of the Tweepy library package.
