### ISSUE TITLE
Inside Status text, '&' is represented as '&amp;'

### ISSUE THREAD

**Issue by junwoo091400** [tweepy/tweepy#1080]
**To verify this**

CODE:
#get 'api' set up before.
print(api.get_status(1017946621949173760).text)
***
It should print out

> Feels like a show **&** tell weekend. I wonder what the cat dragged in …

but instead, it prints out 

> Feels like a show **&amp**; tell weekend. I wonder what the cat dragged in …

**Comment by Harmon758** [comment]
`&amp;` is the HTML character entity for the ampersand.
This is how Twitter's API represents it and is not a bug.
See https://twittercommunity.com/t/ampersands-are-translated-to-amp-when-received-by-the-account-activity-api/107607/3.

**Comment by junwoo091400** [comment]
Oh. It's not tweetpy's fault😂 Got it. Thanks!
