### ISSUE TITLE
tweepy.org Nav not linking to newest version

### ISSUE THREAD

**Issue by SCasarotto** [tweepy/tweepy#1082]
In the navbar of http://www.tweepy.org/ it currently links to http://tweepy.readthedocs.io/en/v3.5.0/ and not http://tweepy.readthedocs.io/en/v3.6.0/.

**Comment by Harmon758** [comment]
This belongs as an issue for https://github.com/tweepy/tweepy.github.com and is a duplicate of https://github.com/tweepy/tweepy.github.com/issues/5 and https://github.com/tweepy/tweepy.github.com/pull/7.
