### ISSUE TITLE
Status.text not returning the complete text of a tweet

### ISSUE THREAD

**Issue by willkara** [tweepy/tweepy#1085]
Now, I may be missing a parameter, but when I tried using the `api.user_timeline` method and then accessed the tweet text by:

    user_tweets = api.user_timeline(screename=username, count=t_count)

    for t in user_tweets:
        print(t.text)

The resulting lines didn't contain the full text of the tweet. It seems like most were cutoff at 140 characters. I thought twitter double the max length allowed?

**Comment by willkara** [comment]
Ah, looks like it's only on ReTweets...

If this is how it's supposed to work. I'll close the issue....

**Comment by GotoCode** [comment]
Unfortunately, this isn't currently well documented in the Tweepy docs, but the `Status` objects returned by Tweepy actually come in three varieties:

1. "Basic" tweets (you "Compose" a tweet on Twitter)
2. Retweets (you hit "Retweet" on another person's tweet, but don't add any comment)
3. "Quote" tweets (you hit "Retweet" on another person's tweet and add a comment)

To get the full text for each of these, you need to access the `_json` property for each `Status` object (which is a Python `dict`).

- For "basic" & "quote" tweets <= 140 characters, you can simply use `status._json["text"]`.
- For "basic" & "quote" tweets > 140 characters, you use `status._json["extended_tweet"]["full_text"]`. In this case, `status._json["extended_tweet"]` contains a reference to the full non-truncated tweet.

- For retweets (of any length), using `status._json["retweeted_status"]` will give you a reference to the retweeted tweet
- If the retweeted tweet is <= 140 characters, use `status._json["retweeted_status"]["text"]`
- If the retweeted tweet is > 140 characters, use `status._json["retweeted_status"]["extended_tweet"]["full_text"]`

You can find an example of a typical `status._json` object [here](https://gist.github.com/dev-techmoe/ef676cdd03ac47ac503e856282077bf2) for a <= 140 character "basic" tweet.

**Comment by Harmon758** [comment]
I've added [a section in the documentation that covers extended Tweets](https://tweepy.readthedocs.io/en/latest/extended_tweets.html) to supplement [Twitter’s Tweet updates documentation](https://tweepy.readthedocs.io/en/latest/extended_tweets.html).

@GotoCode 
All three of these are represented as a Tweet object for Twitter's API, which is what Tweepy's Status object is reflective of.

> To get the full text for each of these, you need to access the `_json` property for each `Status` object

This shouldn't be necessary, as the Status object should be fully representative of the corresponding JSON data used to generate it.

> In this case, `status._json["extended_tweet"]` contains a reference to the full non-truncated tweet.

That is not the case. The `extended_tweet` field does not contain any representation of a Tweet object.
