### ISSUE TITLE
What about a way of managing pages in tweepy.Cursor ?

### ISSUE THREAD

**Issue by lpanichi** [tweepy/tweepy#1091]
Hello,
I may have missed something in the documentation but I don't see any way of setting manually the page I want to call at the beginning of an iteration with Cursor.
Yes, there are nice options and I can make the program wait automatically until the reset of the rate limit but it could be nice to suspend a Cursor during this waiting time and proceed to some other tasks. Right now I don't see any way to interrupt a Cursor and take it on again later ? I'm not sure I'm making myself clear? 
Will it be possible to set up the cursor manually (and read the state of the Cursor) in the future?
Anyway thank you for tweepy, it's great !

**Comment by Harmon758** [comment]
For the `PageIterator`, which you can retrieve using `Cursor.pages`, you can set and retrieve the `PageIterator.current_page` attribute:
https://github.com/tweepy/tweepy/blob/51f680c27af5bc55cde2688cb0ef7b5e0b05c38f/tweepy/cursor.py#L9-L29 https://github.com/tweepy/tweepy/blob/51f680c27af5bc55cde2688cb0ef7b5e0b05c38f/tweepy/cursor.py#L156-L177
