### ISSUE TITLE
Is Tweepy up to date?

### ISSUE THREAD

**Issue by pdeitel** [tweepy/tweepy#1095]
Wondering whether Tweepy is up to date with the latest Twitter APIs and rate limits. Does anyone know?

**Comment by rosscg** [comment]
I'm still using 3.5.0 for streaming and requesting User/Tweet data without issues. Rate limits and auto-queueing work fine. I haven't tested it for manipulating user timelines.

**Comment by pdeitel** [comment]
For example, I was playing around with my own user account, just trying to get the list of our followers, which is just over 3K people. Based on the rate limits (and with the automatic waiting enabled on the API object), I was expecting that I'd be able to get 1500 people quickly, wait 15 minutes, get the next 1500, wait 15 minutes then get the remaining 300 or so. However, it waited for 15 minutes 6 times before I finally killed it.

**Comment by rosscg** [comment]
Did it work beforehand? My app still works with the followers/ids and followers/list endpoints up to the full rate limit.

**Comment by pdeitel** [comment]
I just began using Tweepy for the first time this week. So I can't say whether it worked correctly previously. I'll go back and recheck my code, but I believe it's correct.

**Comment by pdeitel** [comment]
Feeling a bit stupid at the moment. I forgot to pass an argument to api.followers, so I was getting only 20 followers at a time, not 200. Sorry for bothering you.

**Comment by bakayim** [comment]
You can find my fix at forked repo (both getting and sending DMs): [https://github.com/bakayim/tweepy](https://github.com/bakayim/tweepy)
Pull Request about Getting DMs: [https://github.com/tweepy/tweepy/pull/1109](https://github.com/tweepy/tweepy/pull/1109)

Star my repo if it helps you please, thanks

**Comment by Harmon758** [comment]
> Wondering whether Tweepy is up to date with the latest Twitter APIs and rate limits. Does anyone know?

If it's not and you find an issue, this *is* an open source project, so you can always submit an issue and/or pull request.

As for direct messages, see #1081.
