### ISSUE TITLE
Python code not waiting for Tweepy wait_on_rate_limit

### ISSUE THREAD

**Issue by gregyjames** [tweepy/tweepy#1099]
I am using the Tweepy Twitter API and Python to retrieve a fairly large number of tweets (~40,000) using this code:
```python
def getTweets(query, num):
    #gets the specified number of tweets
    _max_queries = 100

    tweets = tweet_batch = api.search(q=query, count=num, tweet_mode='extended')
    ct = 1
    while len(tweets) < num and ct < _max_queries:
        print("Got %d tweets!" % (len(tweets)))
        tweet_batch = api.search(q=query, count=num-len(tweets), max_id=tweet_batch.max_id, tweet_mode='extended')
        tweets.extend(tweet_batch)
        ct += 1
    return tweets
```
I have api wait_on_rate_limit set to true. Immediately, after I call the getTweets() function I attempt to process the tweets. Only problem is that Python is not waiting for Tweepy's rate limit to reset and is proceeding with executing the process code prematurely. For example, if I try to pull 20,000 tweets Tweepy pulls about 9,000 and immediately processes them rather than waiting for the rate limit to reset, and pulling the rest of the tweets. Any suggestions?

**Comment by gregyjames** [comment]
I moved it to it's own thread and I think that it is not waiting for the 9000 tweets. It pulls the 9000 and continues. Any idea whats going on? Is there some kind of limit on the API or something?

**Comment by ottok92** [comment]
I would also appreciate an answer on that, as it seems that it makes no difference to use the wait_on_rate* flags whilst instantiating the API class

**Comment by XzavierDunn** [comment]
Why not just use the python method 'time.sleep()'?
https://www.tutorialspoint.com/python/time_sleep.htm

**Comment by Harmon758** [comment]
The maximum `count` for the [standard search API](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/search/api-reference/get-search-tweets) is 100.
This means you'll receive up to the maximum of 100 Tweets per request. (Twitter's API will sometimes return less than the set `count`/maximum.)

You set `_max_queries` to 100 (and `ct` to 1), so you only ever make 99 requests, meaning you'll get a maximum of 9,900 Tweets.
Your code is working, and this has nothing to do with `wait_on_rate_limit`.

I would recommend you look into using [`Cursor`](https://tweepy.readthedocs.io/en/v4.2.0/pagination.html#tweepy.Cursor) instead.
