### ISSUE TITLE
statuses_lookup(id_=id_list) not taking in all the ids provided in the list

### ISSUE THREAD

**Issue by nikitasalkar1997** [tweepy/tweepy#1103]
I have 13 ids in my id_list . However only 8 of the ids are taken in the tweets arg. My code is as follows : 

 `def` status_lookup(api, filename):

    id_list = [591672103788621824, 591673483832270848, 591675312032776192, 591677980394393600, 591678618935267328,
               591679831399477248, 591681597054652416, 591681654047023104, 591681941017100288, 591693321111744513,
               591712699421052928, 591712700138291201, 591714830446301184]

    print(len(id_list))

    # tweets = api.statuses_lookup(id_list)

    tweets = []
    tweets.extend(api.statuses_lookup(id_=id_list))
    for tweet in tweets:
        print(tweet.id)
    a = len(tweets)
    print(a)

I need to retrieve all 13 tweets . Please help!

**Comment by nikitasalkar1997** [comment]
This is the output that I get : 

13
591714830446301184
591672103788621824
591673483832270848
591675312032776192
591677980394393600
591681597054652416
591679831399477248
591678618935267328
8

**Comment by benhoff** [comment]
You sure that your Id's are strings?

See: https://github.com/benhoff/data-analysis/blob/84175ab28f9b4853d09685d430d87dd23d3e821d/data_analysis/update_tweets.py#L68

For an implementation.

**Comment by nikitasalkar1997** [comment]
Thank you ! 
Well it seems that some of the tweet ids have been suspended and hence cannot be retrieved. That is probably the reason I am getting 8 instead of 13 tweets....
As of the 'map_ = True' problem, I had put that as the argument to check if an id returns 'none'...to know if the tweet has been deleted ....but I got the error : 

AttributeError: 'str' object has no attribute 'items'

**Comment by Harmon758** [comment]
> Well it seems that some of the tweet ids have been suspended and hence cannot be retrieved. That is probably the reason I am getting 8 instead of 13 tweets

You are correct.
Specifically, the user(s) has been suspended for these Tweets: 591681654047023104, 591681941017100288, 591693321111744513, 591712699421052928, 591712700138291201. And the Tweet with ID 591714830446301184 now cannot be found.
And as the [documentation for the statuses/lookup endpoint](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-statuses-lookup) says, "If a requested Tweet is unknown or deleted, then that Tweet will not be returned in the results list".

As for your `AttributeError: 'str' object has no attribute 'items'` error, see #598.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

@benhoff A list of integers is acceptable as input to [`API.statuses_lookup`](https://tweepy.readthedocs.io/en/latest/api.html#API.statuses_lookup).
