### ISSUE TITLE
Stream listener not capturing anything

### ISSUE THREAD

**Issue by rohitfarmer** [tweepy/tweepy#1104]
Hi, I have this code that used to work fine like three months ago, but now it's not working. Stream listener is not capturing anything. It's just silent neither capturing tweets nor throwing errors. It's running but I can't observe any activity. I checked the API connection by updating the status. I am running it in a Google Cloud Instance.

```
# Standard library
import logging
import datetime, time
import sqlite3

# External library
import tweepy

# Logging configuration
logging.basicConfig(filename='../.log/tweets_capture.log',level=logging.INFO)

# Twitter OAuth authentication
# This is where your key and secrete for twitter login should go.
# More info at https://www.slickremix.com/docs/how-to-get-api-keys-and-tokens-for-twitter/
with open('../../cred/bioinfobotmain.txt', 'r') as f: # Reading the credentials from a text file.
    creds = f.readlines()
    consumer_key = creds[0].rstrip()
    consumer_secret = creds[1].rstrip()
    access_token = creds[2].rstrip()
    access_token_secret = creds[3].rstrip()
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)
#api.update_status('Start Streaming')

# Subclass for stream listener
class StreamListener(tweepy.StreamListener):
    def on_status(self, status):
        print(status.text)
        if status.lang == 'en' and 'RT'.upper() not in status.text :
            stat = status.text
            stat = stat.replace('\n','')
            stat = stat.replace('\t','')
            user_id = status.user.id_str
            stat_id = status.id_str
            create = str(status.created_at)
            name = status.user.screen_name
            data = (create, name, user_id, stat_id, stat)
            #Connecting to SQLite3 database
            try:
                db_file = '../../db/bioinfotweet.db'
                conn = sqlite3.connect(db_file, isolation_level=None)
                conn.execute('PRAGMA journal_mode=wal') # This will let concurrent read and write to the database. 
                c = conn.cursor()
                c.execute("INSERT INTO tweetscapture (Date, ScreenName, UserID, TweetID, Text) values (?, ?, ?, ?, ?)", data)
                conn.commit()
                cdate="Tweet inserted at: "+str(datetime.datetime.now())
                logging.info(cdate)
                conn.close()
            except Exception as ex:
                exname = str(ex)
                template = "An exception of type {0} occurred. Arguments:\n{1!r}"
                message = template.format(type(ex).__name__, ex.args)
                logging.info("Sqlite3 database exception occurred.")
                logging.info(message)

    def on_error(self, status_code):
        if status_code == 420:
            cdate = "Error code 420 at:"+str(datetime.datetime.now())
            logging.info(cdate)
            logging.info("Sleeping for 15 mins")
            time.sleep(900)
        return False

stream_listener = StreamListener()
stream = tweepy.Stream(auth=api.auth, listener=stream_listener)
cdate="Stream started at: "+str(datetime.datetime.now())
logging.info(cdate)

while True:
    try:
        stream.userstream(encoding='utf8')
    except Exception as ex:
        exname = str(ex)
        template = "An exception of type {0} occurred. Arguments:\n{1!r}"
        message = template.format(type(ex).__name__, ex.args)
        logging.info("Generic exception occurred.")
        logging.info(message)
        if "not defined" in exname:
            break
        else:
            logging.info("Sleeping for 60 sec")
            time.sleep(60)
            continue
```

**Comment by temannin** [comment]
@rohitfarmer  Make sure you are running the program in the correct version of Python. 

**Remember only Python 2.7, 3.4, 3.5 & 3.6 are supported.**

**Comment by haorenx** [comment]
I have the same question. Any progress?

**Comment by rohitfarmer** [comment]
> @rohitfarmer Make sure you are running the program in the correct version of Python.
> 
> **Remember only Python 2.7, 3.4, 3.5 & 3.6 are supported.**

I am running in Python 3.6.5. I think it has something to do with the recent changes in the Twitter API. It seems that now it doesn't support streaming API. There is an alternative called Account Activity API that should be used now. I am not sure if Tweepy supports that? See this https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736

**Comment by temannin** [comment]
My implementation of the StreamListener is still functional after the API changes. I cannot share the code because it is private however I ran into the same problem as you. 

Changing my runtime from 3.6 to 2.7 returned the functionality.

_I don't know why though._

**Comment by rohitfarmer** [comment]
> My implementation of the StreamListener is still functional after the API changes. I do not see anything wrong with your code off the bat, but I am unfamiliar with the userstream() function. I ran into the exact same problem as you recently.
> 
> Changing my runtime from 3.6 to 2.7 returned the functionality.
> 
> _I don't know why though._
> 
> https://gist.github.com/temannin/a83f2f0fbe97c3553018e1bacf9dc8e6

Thanks for your reply. In my current implementation userstream() captures all the tweets from the users that my twitter handle is following which is around 2500 ish. If I use your implementation then it will capture the tweets that are tweeted by individual users. I think the maximum limit right now is around 250 or maybe less for the standard API.

**Comment by temannin** [comment]
As far as troubleshooting goes, I would suggest testing your code with an account that is following an amount of users under the suspected limit. If your code is able to capture the smaller sample size it would suggest the API is now limited. If the code is still unable to capture tweets, then it has to be a problem with code.

That's my theory, anyway.

**Comment by temannin** [comment]
@rohitfarmer 

It seems that the User Stream functionality is indeed moving to the Account Activity API as of August 23rd, 2018.

https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

**Comment by Harmon758** [comment]
User streams have been deprecated and retired in favor of the new Account Activity API.
For Account Activity API support, see #1075.

Also see:
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/building-the-future-of-the-twitter-api-platform.html

https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746
https://twittercommunity.com/t/reminder-site-streams-user-streams-and-legacy-dm-endpoints-will-be-sunset-august-16th/109482
https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736
https://twittercommunity.com/t/date-for-full-deprecation-of-user-streams-site-streams-and-legacy-direct-message-api-endpoints/98734
