### ISSUE TITLE
Fix functions associated with Direct Messages

### ISSUE THREAD

**Issue by pedrochamberlain** [tweepy/tweepy#1108]
Twitter retired legacy Direct Message endpoints three days ago.

**Comment by bakayim** [comment]
I fixed "get" part of DM

You can find pull request at: [https://github.com/tweepy/tweepy/pull/1109](https://github.com/tweepy/tweepy/pull/1109)
You can use my forked repo: [https://github.com/bakayim/tweepy](https://github.com/bakayim/tweepy)

**Comment by bakayim** [comment]
I also fixed sending DM. You can find it at my forked repo

Star if it helps you please, thanks

**Comment by Harmon758** [comment]
#1081 is the open issue regarding this.
