### ISSUE TITLE
i can read only 200 tweets in my user time-line twitter api ,How to change it to 1000

### ISSUE THREAD

**Issue by Nahaj** [tweepy/tweepy#1110]
https://api.twitter.com/1.1/statuses/user_timeline.json?screen_name=google&count=1000&include_rts=false&tweet_mode=extended

**Comment by themoah** [comment]
hi @Nahaj 
which version of tweepy are you using ? 
I think you can solve your issue with pagination: 
[http://docs.tweepy.org/en/v3.6.0/cursor_tutorial.html#limits](http://docs.tweepy.org/en/v3.6.0/cursor_tutorial.html#limits )

Paste your code snippet if it doesn't work.

**Comment by Harmon758** [comment]
As mentioned, you can use a [Cursor](https://tweepy.readthedocs.io/en/latest/cursor_tutorial.html) to iterate over paginated results.
