### ISSUE TITLE
How To Overcome 15 Tweets Extraction Limit?

### ISSUE THREAD

**Issue by PalashSharma15** [tweepy/tweepy#1111]
I want to extract n tweets but api.search() returns only 15 tweets.
**Code:**
tweets = api.search(q='#example_query',lang='en', result_type='popular', tweet_mode="extended", **_count=20_**)
print(len(tweets))

**Output:**
15

**Comment by connorwaslo** [comment]
Use tweepy.Cursor instead of api.search

**Comment by Harmon758** [comment]
`count` is an upper limit. 

From the [standard search API documentation](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets):
> Keep in mind that the search index has a 7-day limit. In other words, no tweets will be found for a date older than one week.

> Please note that Twitter's search service and, by extension, the Search API is not meant to be an exhaustive source of Tweets. Not all Tweets will be indexed or made available via the search interface.

This could be why you're getting fewer results than your specified `count`.

Also, there are more factors on Twitter's end that could result in receiving fewer.
See https://twittercommunity.com/t/why-when-i-ask-for-100-tweets-less-than-100-are-returned/10789.

As recommended, you should look into using a [Cursor](https://tweepy.readthedocs.io/en/latest/cursor_tutorial.html) instead, to iterate over paginated results,
This will let you control and fine-tune exactly how many results to process.
