### ISSUE TITLE
Url Problem with method send_direct_message

### ISSUE THREAD

**Issue by zh4r0nax** [tweepy/tweepy#1114]
Hello, I am working with version 3.6.0, and the problem is that the url that calls the metro send_direct_message falls through

is calling [urllib3.connectionpool] [connectionpool.py:393] https://api.twitter.com:443 "POST /1.1/direct_messages/new.json?text=TEXT&user=USER_ID HTTP / 1.1" 404 69 
ERROR: [{u'message': u'Sorry, that page does not exist.', u'code': 34}]

and the twitter documentation says that I should be calling /1.1/direct_messages/events/new.json?

how i can fixed?

**Comment by bakayim** [comment]
You can find my fix at forked repo (both getting and sending DMs): [](https://github.com/bakayim/tweepy)
Pull Request about Getting DMs: [](https://github.com/tweepy/tweepy/pull/1109)

**Comment by jwpwhite** [comment]
Tried your forked repo @bakayim but still not able to send DM's :(

**Comment by bakayim** [comment]
> Tried your forked repo @bakayim but still not able to send DM's :(

Sorry for late response. Are you sure that you properly installed forked repo ( -e git+git://github.com/bakayim/tweepy.git#egg=tweepy )

I am sending without any problem

**Comment by bakayim** [comment]
> Having this issue too.

Are you sure that you properly installed forked repo ( -e git+git://github.com/bakayim/tweepy.git#egg=tweepy )

I am sending without any problem

**Comment by Harmon758** [comment]
#1081 is the open issue regarding this.
