### ISSUE TITLE
Direct messaging not working

### ISSUE THREAD

**Issue by rohitfarmer** [tweepy/tweepy#1115]
Hi all, I am getting `tweepy.error.TweepError: [{'code': 34, 'message': 'Sorry, that page does not exist.'}]
` . I am presuming this is due to Twitter API changes. Any fix?

**Comment by elg34** [comment]
I used this fix here and it works well in 3.6.0
https://github.com/tweepy/tweepy/issues/1081

**Comment by Harmon758** [comment]
Duplicate of #1081
