### ISSUE TITLE
how to find hashtags that contain a word?

### ISSUE THREAD

**Issue by monajalal** [tweepy/tweepy#1116]
I tried many methods including using regular expression for returning hashtags that contain a word. Do you know how I can do that using stream.filter? 

ex. be able to fine #MyCat #MyCat2018 when I search for #cat somehow.

**Comment by Harmon758** [comment]
You should be able to check if the word is in the text attribute for any [hashtag](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object#hashtags) [entities](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object) that the Tweet has.
