### ISSUE TITLE
a simple quick question

### ISSUE THREAD

**Issue by jerkoftheday1017** [tweepy/tweepy#1117]
Hi there, 

I'm thinking to use Tweepy. 
Would anyone tell me how to retrive twitter account? Would that be by user name? 
If I (managed to) install Tweepy, I'd have to search accounts with no specific information, such as their familynames. 

Thanks!
Yukiko

**Comment by Harmon758** [comment]
You can use [`API.get_user`](https://tweepy.readthedocs.io/en/latest/api.html#API.get_user) to retrieve a specific User by either user ID or screen/user name.
Alternatively, you can use [`API.search_users`](https://tweepy.readthedocs.io/en/latest/api.html#API.search_users) to search for users using a query.

Also see https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-show and https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-search.
