### ISSUE TITLE
@varadhbhatnagar change all instances of `status.text` to `status.full_text`.  The 'extended' tweet mode returns a different or additional object called `full_text` (with the entire tweet) but still allows 'text' to work (only returning truncated tweet).  Hope this was helpful, just had this issue a few days back!  see #988

### ISSUE THREAD

**Issue by Dubouskaya** [tweepy/tweepy#1123]
_Originally posted by @vism2889 in https://github.com/tweepy/tweepy/issues/935#issuecomment-358145055_

I am getting error: 
AttributeError: 'Status' object has no attribute 'full_text'

**Comment by Harmon758** [comment]
Are you using `tweet_mode="extended"` if you're using a standard REST API?
See https://developer.twitter.com/en/docs/tweets/tweet-updates and the other comments in that issue.
