### ISSUE TITLE
tweepy unable to authenticate, twurl successful

### ISSUE THREAD

**Issue by Kemp-J** [tweepy/tweepy#1128]
I am creating a new bot and am hitting an issue with tweepy failing to authenticate. The message I get back is
`tweepy.error.TweepError: [{'code': 32, 'message': 'Could not authenticate you.'}]`

As a small test I am doing:
```
auth = tweepy.OAuthHandler(keys.consumer_key, keys.consumer_secret)
auth.set_access_token(keys.access_token, keys.access_token_secret)
api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)
print(api.me())
```

(i.e. the same code you see everywhere)

twurl is able to authenticate and (for example) read direct messages or post new tweets using exactly the same consumer and access keys.

Where should I be looking to figure this out, because if the keys are good then I'm not sure what else I can do?

Python version is 3.7 and I've tried with the current release of tweepy from pypi and from git (today).

**Comment by Harmon758** [comment]
I'm unable to reproduce this.
Double check that the exact credentials you're passing are correct, e.g. by printing and comparing them.

**Comment by Billy1900** [comment]
Did you solve this problem? I have met the same one.

**Comment by Harmon758** [comment]
Please don't necrobump old closed issues.
