### ISSUE TITLE
No support for Python 3.7

### ISSUE THREAD

**Issue by RyChrome** [tweepy/tweepy#1131]
Currently, there is no support for Python 3.7, will there be in the future?

**Comment by Harmon758** [comment]
Duplicate of #1063

**Comment by RyChrome** [comment]
So can we do something about it lmao

**Comment by EmadFawaz** [comment]
I am using Python 3.7 as well. I could not install the package. I hope an upgrade comes very soon.‎

**Comment by Harmon758** [comment]
As stated in #1063, #1042 already fixed the issue.
Just upgrade to the development version from this GitHub repository.

**Comment by hugovk** [comment]
This issue can now be closed because there is now a Tweepy release supporting Python 3.7.

Thank you, @joshthecoder!
