### ISSUE TITLE
Error max retries exceeded with url.(Caused by ProxyError('Cannot connect to proxy.', NewConnectionError

### ISSUE THREAD

**Issue by aucorr** [tweepy/tweepy#1136]
I've been scrapping tweets succesfully with tweepy in python but suddenly yesterday, the following error popped up: 

Warning: Error in py_call_impl: TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/users/show.json?screen_name=xxxx (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000000008B62B470>: Failed to establish a new connection: [WinError 10060]

I am trying to download the tweets in my work  where they have a proxy but since now everything was fine. 
I don't know what is the main cause for this error....

**Comment by Harmon758** [comment]
This traceback is simply an error connecting to your proxy.
I'm unable to reproduce this with a working proxy.
If you're just not able to connect to your proxy at all, then this isn't an issue with Tweepy.
