### ISSUE TITLE
How can I read a DM and check if it is an username?

### ISSUE THREAD

**Issue by David99Aa** [tweepy/tweepy#1139]
I'm new on Python, and I am trying to build an App which should read direct messages received, check if the only information in the message is an username (@username) and then storing the username on a string to publish it as a tweet, adding some more information from a given list.

I already have the code for publishing one random phrase from a set when initialized, but I want to know how I can read a message and tweet:

@UsernameOnTheMessage + a randomly chosen phrase in the form:

tweet  = username + random.choice(tweetlist)

Is there a way of reading DMs, checking and saving its content for this purpose? Thank you.

**Comment by Harmon758** [comment]
Twitter has recently changed its Direct Message API endpoints. See #1081.
I've made a branch (https://github.com/tweepy/tweepy/tree/dm-migration) and draft PR (#1228) that should fully support these changes.
Feel free to test it and report any issues you encounter.

With it, you should now be able to use [the direct_messages/events/list endpoint](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/list-events) using  `API.list_direct_messages` to do what you want.
Note though, that only Direct Messages within the last 30 days can be accessed with this endpoint.
Alternatively, if you have the ID of the Direct Message, you can use [the direct_messages/events/show endpoint](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/get-event) with `API.get_direct_message`.
You should then be able to use the [Direct Message object](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/guides/message-create-object) to get the user mentions in the message, or alternatively, the raw text of the message.
