### ISSUE TITLE
DMs still not working?

### ISSUE THREAD

**Issue by Exceen** [tweepy/tweepy#1142]
Hey, I noticed that there's a new version of tweepy (v3.7.0) and installed it. I was hoping that DM functionality has been fixed but trying to send a DM it still says "Sorry, that page does not exist.". I checked all my paths and the installation itself and whatsoever. Am I missing something and doing something wrong with my configuration or am I right that DMs are still not working with 3.7.0?

**Comment by Harmon758** [comment]
#1081 is the open issue regarding this.
