### ISSUE TITLE
userstream() is not working

### ISSUE THREAD

**Issue by LeonardoLoureiro** [tweepy/tweepy#1148]
I've noticed that when calling the method "userstream()", it just returns a 404 code. Perhaps this has to do with the fact that Twitter has changed their API methods and spec about most things.
Stream is still working since you can still receive real-time statuses by using the 'filter' method. Example my code is as follows:

```
import tweepy
import json

consumer_key = "abc..."
consumer_secret = "abc..."
access_token = "abc..."
access_secret = "abc..."

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)
api = tweepy.API(auth)

class myStream(tweepy.StreamListener):
    def on_data(self, raw_data):
        data = json.loads(raw_data)
        print(data)

    def on_error(self, status_code):
        print(status_code)

    def on_direct_message(self, data):
        print(data)

        return

l = myStream()
streamer = tweepy.Stream(auth, l).userstream()
```

It worked fine months ago, but, as I've said, Twitter has been going through changes and perhaps that's what it is. Thoughts on solution?

Note: direct messages also seem to be 'down' if that's relevant.

**Comment by Harmon758** [comment]
User streams have been deprecated and retired in favor of the new Account Activity API.
`Stream.filter` using the [statuses/filter endpoint](https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter) is unaffected.
For Account Activity API support, see #1075.
As for Direct Message API changes, see #1081.

Also see:
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/building-the-future-of-the-twitter-api-platform.html

https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746
https://twittercommunity.com/t/reminder-site-streams-user-streams-and-legacy-dm-endpoints-will-be-sunset-august-16th/109482
https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736
https://twittercommunity.com/t/date-for-full-deprecation-of-user-streams-site-streams-and-legacy-direct-message-api-endpoints/98734
