### ISSUE TITLE
Why is stream_filter not finding search term?

### ISSUE THREAD

**Issue by hongjinwu** [tweepy/tweepy#1151]
Hi,
I'm working on tweepy stream.filter with particular keyword, but the result of it doesn't have the keyword that I set. tweepy stream track doesn't working. Can anyone help? Thanks!
I set track parameter as "trump", and one of results is as follows:
`{"time": "2019-01-11 03:19:30", "location": "Detroit, MI", "user_id": "52987681", "text": "In one month I\u2019ll be back in California where the sun shines so bright that there\u2019s a hazy glare and the palm trees are never ending. In one month I\u2019ll have to push through some pain and\u2026 https://t.co/YNx7Le5ZgT", "coordinates": "{'type': 'Point', 'coordinates': [-118.497345, 34.0093]}", "name": "MyThy Huynh"}`

Here is my code:

```
try:
    import json
except ImportError:
    import simplejson as json
import tweepy, sys
from time import sleep
import csv
from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream
import json



consumer_key = 'xxx'
consumer_secret = 'xxx'
access_token = 'xxx'
access_token_secret = 'xxx'

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)
box = [-178.2,6.6,-49.0,83.3]

class MyStreamListener(tweepy.StreamListener):
    def on_status(self, status):
        try:
            text = status.extended_tweet["full_text"]
        except AttributeError:
            text = status.text
        if status.coordinates:
            print(status.coordinates) 
            print(status.text.encode('utf-8')) 
            data={}  
            data.update({
                'time': str(status.created_at),
            })
            data.update({
                'location': str(status.user.location),
            })
            data.update({
                'user_id': str(status.user.id_str),
            })
            data.update({
                'text': str(text),
            })
            data.update({
                'coordinates': str(status.coordinates),
            })
            data.update({
                'name': str(status.user.name),
            })
            with open('FRB-1-10-time-location-userid-text-coordinatetes.json', 'a') as feedsjson:
                json.dump(data,feedsjson)

        
        
    def on_error(self, status_code):
        if status_code == 420:
            return False


if __name__ == '__main__':
    myStreamListener = MyStreamListener()
    myStream = tweepy.Stream(api.auth, listener=myStreamListener)
    myStream.filter(track=['trump'],locations=(box),languages=['en'])
```

**Comment by Harmon758** [comment]
Per the [documentation for the `locations` parameter for Twitter's streaming API](https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/basic-stream-parameters):
> Bounding boxes do not act as filters for other filter parameters. For example track=twitter&locations=-122.75,36.8,-121.75,37.8 would match any Tweets containing the term Twitter (even non-geo Tweets) OR coming from the San Francisco area.

You're receiving that result because its geolocation falls within the bounding box you set.
