### ISSUE TITLE
api.search returning an empty list

### ISSUE THREAD

**Issue by PandaWhoCodes** [tweepy/tweepy#1155]
If I do a search on twitter - https://twitter.com/search?f=tweets&q=education%20%40dorait&src=typd
i get a few results.
But doing the same query -  `@dorait education` with tweepy - it gives me an empty response.
```
for tweet in tweepy.Cursor(self.api.search, q=self.query, count=200, tweet_mode='extended',
                                       lang="en",
                                       ).items(1000):
        self.tweets.append(tweet) 
```

**Comment by Harmon758** [comment]
Per the [documentation of Twitter's search endpoint](https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators):
> The Search API is not a complete index of all Tweets, but instead an index of recent Tweets. The index includes between 6-9 days of Tweets.

None of the Tweets that satisfy your query are within the last 9 days.
Note, your use of the `@` operator is searching for Tweets mentioning the Twitter account `@dorait`.
There is a single Tweet from that account within the last day that matches the search query in the web search UI. You can search for Tweets from that account using the `from:` operator, e.g. `from:@dorait education`.
See [Twitter's documentation about standard search operators](https://developer.twitter.com/en/docs/tweets/rules-and-filtering/overview/standard-operators.html) for more information.
