### ISSUE TITLE
if you use location then track is ignore

### ISSUE THREAD

**Issue by werowe** [tweepy/tweepy#1171]
connecticut =  [ -73.504389, 41.222582, -71.804192 , 42.026518 ]
stream.filter(track=['Trump'],locations=connecticut,languages=["en","fr","es"])

This gets all tweets in those coordinates in those languages.  track is ignored.

**Comment by Harmon758** [comment]
I'm unable to reproduce this issue.
`Stream.filter` properly tracks keywords when given locations and languages.

**Comment by werowe** [comment]
Here it is.  None of these words appears in the JSON returned by the stream (unless you count "ct" in the word "protected", which I doubt since it's not in the Tweet text.

languages ['en', 'es', 'fr'] 
location [-73.504389, 41.222582, -71.804192, 42.026518] 
track ['Trump', 'ocean', 'Democrat', 'Republican', 'gardening', 'BMCSoftware', 'school', 'CT', '#metoo', 'governor', 'Iran']

 stream.filter(locations=region,languages=languages,track=track)

JSON output

https://pastebin.com/gk5ndGTj

**Comment by werowe** [comment]
Never mind.  It seems to be working correctly.  Not sure why it picked up the one above but the other tweets I am getting are tracking by location and words in tweet.
