### ISSUE TITLE
Document API.get_oembed

### ISSUE THREAD

**Issue by estianross** [tweepy/tweepy#1173]
API.get_oembed is completely undocumented

**Comment by De-ma** [comment]
I'd like to do this!

**Comment by Harmon758** [comment]
Pull requests are welcome

**Comment by kmcelwee** [comment]
@Harmon758 Do we have anything against auto-generated documentation from docstrings?

**Comment by Harmon758** [comment]
No, that's actually something I want to implement in the future, but that's not really specific to this issue.

**Comment by Harmon758** [comment]
#1433 was merged with improper formatting and some missing information, but I've fixed the formatting with https://github.com/tweepy/tweepy/commit/44a0cc58e2ad3f90087cf77d343bc2b6e2e394e6 and added the missing information with https://github.com/tweepy/tweepy/commit/f834b655fa4595d364b86e1fac4e6402608f4d6c. I've also gone ahead and updated the allowed parameters for the method with https://github.com/tweepy/tweepy/commit/e88a2f74fa4e129a1c86c993220a9b1bae20e1f3.
