### ISSUE TITLE
Filtering by both username and hashtag

### ISSUE THREAD

**Issue by rupsaijna** [tweepy/tweepy#1177]
Is there a way to filter only those tweets by a particular user that uses a hashtag?
I know the usage of tweepy.Cursor(api.user_timeline, screen_name='@username') and tweepy.Cursor(api.search,q="#hashtag"), but how do I merge the two?

**Comment by machine-uprising** [comment]
For the Search endpoint you could use this:
```python
tweepy.Cursor(api.search,q="from:<screen_name> #<hashtag>")
```
For example, search tweets from "Twitter" that have the hashtag "ForTheThrone"
```python
tweepy.Cursor(api.search,q="from:twitter #ForTheThrone")
```

Check out the Twitter Search page https://twitter.com/search-home#  There is a popup link that shows operators you can use to build some advanced queries. You can also test your queries and then copy them into your project querystring value.

If you want to use the user timeline endpoint you probably need something like this:
```python
# Do not include the hash symbol in the search tags
search_tags = ['hashtag']
for tweet in tweepy.Cursor(api.user_timeline, screen_name='@<screen_name>', tweet_mode='extended').items():
    if len(tweet._json['entities']['hashtags']) > 0:
        tweet_hashtags = [hashtag['text'] for hashtag in tweet._json['entities']['hashtags'] if hashtag['text'] in search_tags]
        if(len(tweet_hashtags)>0):
            print(tweet._json)
```
The only problem with this is it has to return all available tweets from the user timeline and then check for the hashtags you are searching for. I can't think of another way to do for the user timeline endpoint.

**Comment by rupsaijna** [comment]
The user_timeline method was the one I was intitally trying, but since I kept getting rate limits, I was thinking if I could filter with the hashtags "before" the whole timeline returned, it would return less number of tweets. Looks like that is not possible. 
Thank you for the help!

**Comment by NNTin** [comment]
Cursor is nice if you are looking up past tweets. It is not suited for getting live tweets since you are repeatedly polling the Twitter API thus you hit the rate limit

You should instead use the streaming API. See https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter.html or http://docs.tweepy.org/en/v3.4.0/streaming_how_to.html

As for your use case you just filter your to-be-tracked twitter guy and then look into the twitter message object for hashtag and do further filtering there.

**Comment by Harmon758** [comment]
See also: https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators

**Comment by allegro25** [comment]
Guys, does anyone know how I can only fetch the new tweets with the streamer? I have it set up, but i starts fetching me all the old tweets. I just want it to actively listen and show me the new tweets.

**Comment by NNTin** [comment]
I linked it before I link it again: https://docs.tweepy.org/en/latest/streaming_how_to.html

With this you don't get old tweets. It actively listens and shows you new tweets that get tweeted during runtime.

**Comment by allegro25** [comment]
> I linked it before I link it again: https://docs.tweepy.org/en/latest/streaming_how_to.html
> 
> With this you don't get old tweets. It actively listens and shows you new tweets that get tweeted during runtime.

It doesn't. I used that documentation in the first place. It gives me old tweets.

I also get tweets that mention the user, and not only from the user. Do you know a workaround for this?

**Comment by NNTin** [comment]
My highest starred GitHub project is using that endpoint. I am not getting old tweets from that endpoint and I do some filtering about tweets that mention the user depending on if this behavior is wanted or not.

**Comment by allegro25** [comment]
I cant decipher how you can filter only the tweets of that specific user and when the user is tagged.
Im getting all the tweets where the user is tagged. How do you avoid this? Thanks!

**Comment by Harmon758** [comment]
This is unrelated to this issue.
Please don't necrobump old closed issues.

You should receive realtime Tweets from streaming. If that's not the case, that's likely an issue with Twitter's API.

> I also get tweets that mention the user, and not only from the user. Do you know a workaround for this?
> Im getting all the tweets where the user is tagged. How do you avoid this? Thanks!

This is a limitation of streaming with the standard v1.1 API. You'll have to filter them out yourself.
