### ISSUE TITLE
What would be a good way to keep track of which tweet belongs to who when streaming? 

### ISSUE THREAD

**Issue by LuisAverhoff** [tweepy/tweepy#1183]
I have a use case where a user can enter in a search bar the type of tweets he/she would like to receive. Multiple users can be searching at once and I need a good way to detect that this tweet is for user1, this tweet is for user2 and etc. The tweepy documentation mentions that only one streaming object should be used and this poses a problem for me because if there is only one streaming object that is receiving messages, there is no way for me to know which tweet belongs to who. 

Sure I can keep a list of all the search terms everyone has made and matches those terms with each tweet that I receive from the stream but that is not going to work every time. What if a tweet matches with multiple terms? What do I do then? Which person would get the tweet at that instance?

essentially I want to do something like this:

```
class TweetStreamListener(StreamListener):

    def __init__(self, api):
        self.api = api
        self.stream = Stream(auth=self.api.auth, listener=self)
        self.currentUsers= {} # Current users who want to receive tweets. { userID -> searchTerm }

    def start_listening(self, userID, newSearchTerm): # This method will get called after each search request.
       self.currentUsers[userID] = newSearchTerm # new tweet to listen to.

        if self.stream.running: 
            self.stream.disconnect() # disconnect the stream momentarily. Now nobody is receiving tweets.
       
       searchTerms = self.currentUsers.values() # create new search term list

        self.stream.filter(track=searchTerms, is_async=True) # start listening for these tweets.

    def on_status(self, status):
        for id, topic in self.currentUsers.items():
             if topic == status.topic:
                 # Send status.text via some protocol. Maybe websocket.
```

**Comment by NNTin** [comment]
> Sure I can keep a list of all the search terms everyone has made and matches those terms with each tweet that I receive from the stream 

What's wrong with that?

>but that is not going to work every time. What if a tweet matches with multiple terms? What do I do then? Which person would get the tweet at that instance?  

If multiple persons subscribe to the same thing they all should get the tweet.

My [twitter project](https://github.com/NNTin/discord-twitter-bot) allows the configuration of multiple twitter feeds posting each of them to different text channels.

**Comment by LuisAverhoff** [comment]
You misunderstood what I said or at least I didn't explain the issue very well. Take for example user1 who is looking for tweets relating sports and user2 who is looking for tweets relating to pizza. So now we have two search terms on our list: ['pizza', 'sports']. Now what should I do if I have a tweet like 'I love eating pizza but not while watching sports'. Here, both search terms are in the tweet and I'm trying to do sentiment analysis on each tweet.  Maybe you are right and I should send the analysis of this tweet to both users but I don't know if that would be right in that case.

**Comment by Harmon758** [comment]
This really isn't an issue with Tweepy and more of how you process the Tweets.

> Take for example user1 who is looking for tweets relating to sports and user2 who is looking for tweets relating to pizza. So now we have two search terms on our list: ['pizza', 'sports']. Now what should I do if I have a tweet like 'I love eating pizza but not while watching sports'. Here, both search terms are in the tweet and I'm trying to do sentiment analysis on each tweet. Here the sentiment analysis is overall negative but in regards to sports. Now both would get that there is a negative trend for both pizza and sports. Maybe you are right and I should send the analysis of this tweet to both users but I don't know if that would be right in that case.

It seems to me like you should be doing sentiment analysis for each Tweet in regards to each search term in the list that appears in that Tweet, and then sending them to the corresponding users. Otherwise, I don't see what the difference is between this case and one where only one search term is in the Tweet and the overall sentiment analysis is negative, but in regards to something that's not the search term, e.g. "I love eating pizza but not while watching TV".
