### ISSUE TITLE
Cannot get tweet url

### ISSUE THREAD

**Issue by student-101** [tweepy/tweepy#1192]
I ran this code
```
for tweet in tweepy.Cursor(api.search, q='sample', count=100,tweet_mode='extended').items():
    print(tweet.url)
    print(tweet.text)
```
but cannot get url.
Now Status objects doesn't have url attribute and text attribute ? How can I get tweet url ?

**Comment by Harmon758** [comment]
`url` has never been an attribute of the [Tweet object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object.html).
Instead, you can simply reconstruct a link to the Tweet by using the `id`/`id_str` attribute and the `screen_name` of the [User object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/user-object)/attribute.
e.g. `f"https://twitter.com/{tweet.user.screen_name}/status/{tweet.id}"`
The text attribute still exists for Tweet objects, although you might want to use `full_text` instead since you're using the extended Tweet mode.

**Comment by student-101** [comment]
Thank you so much, Harmon758-san.
It succeeded.

**Comment by Ivanca** [comment]
For what is word you don't need the screen name, the **id** is enough:
```python
url = f"https://twitter.com/user/status/{tweet.id}"
```

**Comment by vonum** [comment]
Does it make sense to add it to the public API?

**Comment by gmehta1996** [comment]
i was trying to get text from tweets I got the following tweet as:

Episode 3 in our #Tax Tuesday series, 𝗠𝗮𝗻𝗮𝗴𝗶𝗻𝗴 𝗖𝗼𝘀𝘁 & #𝗣𝗿𝗼𝗳𝗶𝘁𝗮𝗯𝗶𝗹𝗶𝘁𝘆 𝗶𝗻 𝗖𝗵𝗮𝗹𝗹𝗲𝗻𝗴𝗶𝗻𝗴 𝗧𝗶𝗺𝗲𝘀, is up on our YouTube channel

but I got my output as :

Episode 3 in our #Tax Tuesday series, \xf0\x9d\x97\xa0\xf0\x9d\x97\xae\xf0\x9d\x97\xbb\xf0\x9d\x97\xae\xf0\x9d\x97\xb4\xf0\x9d\x97\xb6\xf0\x9d\x97\xbb\xf0\x9d\x97\xb4 \xf0\x9d\x97\x96\xf0\x9d\x97\xbc\xf0\x9d\x98\x80\xf0\x9d\x98\x81 &amp; #\xf0\x9d\x97\xa3\xf0\x9d\x97\xbf\xf0\x9d\x97\xbc\xf0\x9d\x97\xb3\xf0\x9d\x97\xb6\xf0\x9d\x98\x81\xf0\x9d\x97\xae\xf0\x9d\x97\xaf\xf0\x9d\x97\xb6\xf0\x9d\x97\xb9\xf0\x9d\x97\xb6\xf0\x9d\x98\x81\xf0\x9d\x98\x86 \xf0\x9d\x97\xb6\xf0\x9d\x97\xbb \xf0\x9d\x97\x96\xf0\x9d\x97\xb5\xf0\x9d\x97\xae\xf0\x9d\x97\xb9\xf0\x9d\x97\xb9\xf0\x9d\x97\xb2\xf0\x9d\x97\xbb\xf0\x9d\x97\xb4\xf0\x9d\x97\xb6\xf0\x9d\x97\xbb\xf0\x9d\x97\xb4 \xf0\x9d\x97\xa7\xf0\x9d\x97\xb6\xf0\x9d\x97\xba\xf0\x9d\x97\xb2\xf0\x9d\x98\x80, is up on our YouTube channel

It was not able to detect the bold text . Is there any solution for this???
I used 
tweet_text = str(tweet.full_text.replace('\n',' ').encode('utf-8'))
to take out the text.

**Comment by Harmon758** [comment]
@vonum Perhaps. Feel free to make an issue about it. It likely wouldn't be added until v4 though.

@gmehta1996 This is unrelated to this issue.
I'm not sure what you expect the output to be there. You're encoding the text to a bytes object and then casting it back to a string.
Twitter doesn't have native "bold text". That Tweet is simply using different Unicode characters; e.g. `\xf0\x9d\x97\xa0` represents [the Unicode character MATHEMATICAL SANS-SERIF BOLD CAPITAL M](http://www.fileformat.info/info/unicode/char/1d5e0/index.htm).
