### ISSUE TITLE
since_id parameter is invalid

### ISSUE THREAD

**Issue by KayHS** [tweepy/tweepy#1214]
Hi,

Im trying to use since_id as the twitter api documentation reccomends.

```
    tweets = self.api.user_timeline(
                id=id, tweet_mode='extended', count=200, include_rts=True, trim_user=True, since_id=since_id)
            
```

However i get an error from this library.

> [{'code': 44, 'message': 'since_id parameter is invalid.'}]

The documentation has this parameter. https://tweepy.readthedocs.io/en/latest/api.html#API.user_timeline

**Comment by tugayabdulla** [comment]
Is there any update on this topic?

**Comment by Harmon758** [comment]
Please don't necrobump old closed issues.
Feel free to create a new issue with the full traceback and the relevant code and/or a reproducible example (MCVE/SSCCE) if you're able to reproduce this.
