### ISSUE TITLE
Failed to send request : Err 111: Connection refused

### ISSUE THREAD

**Issue by irthomasthomas** [tweepy/tweepy#1216]
Hello,

I've installed tweepy for the first time and followed the instructions, but on running the script for the first time I get this error:

Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/update.json?status=Hello+World (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f173304c1d0>: Failed to establish a new connection: [Errno 111] Connection refused',))

I've been trying for a couple of days in case twitter was playing up but it's still the same today.

Regards
Thomas

**Comment by johnkw** [comment]
This is not a tweepy bug, as such. It's possible that you're firewalled or network blocked in some way.
