### ISSUE TITLE
NameError: name 'session' is not defined

### ISSUE THREAD

**Issue by eergenzinger** [tweepy/tweepy#1221]
In the authentication section of your tutorial, [https://tweepy.readthedocs.io/en/latest/auth_tutorial.html#oauth-authentication],
the "session" variable appears out of the blue in the pseudocode
`session.set('request_token', auth.request_token['oauth_token']`

this results of course in "NameError: name 'session' is not defined".
So how to define the session variable?

**Comment by johnkw** [comment]
You can't just copy paste and append those various lines together. That doc is a series of snippets - it could probably use some work though. See the Requests module Session object for info on sessions.

**Comment by casetofon** [comment]
@johnkw really? Your answer to this is "What you're doing is not ok" and "Go read the docs"?

**Comment by Harmon758** [comment]
I've rewritten the authentication documentation with https://github.com/tweepy/tweepy/commit/f9a722bae8cce368b9f8fd447c418e1034c32178, so this should be resolved now.
