### ISSUE TITLE
how to cite Tweepy

### ISSUE THREAD

**Issue by bfarzin** [tweepy/tweepy#1226]
Hi! 
I used Tweepy for a project and I would like to cite it in my list of references so others know about it.  Do you have a bibtex snippet I can use for that?  Best to just cite the GitHub page?

**Comment by Harmon758** [comment]
I think citing the GitHub repository, https://github.com/tweepy/tweepy, or alternatively the website, http://www.tweepy.org/, would be fine.
Thanks!

**Comment by Harmon758** [comment]
I've added a CITATION.cff file to the repository now, with https://github.com/tweepy/tweepy/commit/2547b44ac8ea1250b5eb6747db5bce7e425bc5ba.
