### ISSUE TITLE
How to filter multiple retweets AND links AND media from search query?

### ISSUE THREAD

**Issue by tinkermachine** [tweepy/tweepy#1230]
Struggling to construct a query that can filter out retweets, links AND media.

Filtering out just retweets seems to work, but once I add the other tags, none of it works.

I am structuring my query keyword as:

`query = query + "-filter:retweets" + "-filter:media"`

**Comment by Harmon758** [comment]
You need to include spaces between your operators, just like you would in a search on the website/app.
See https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators.html.
Note, you should also use the `+=` operator there.
