### ISSUE TITLE
The documentation for api.update_status() is incorrect for the media_ids parameter.

### ISSUE THREAD

**Issue by mattccrampton** [tweepy/tweepy#1235]
The documentation for ```api.update_status()``` is incorrect for the ```media_ids``` parameter...

http://docs.tweepy.org/en/latest/api.html#API.update_status

The documentation states...

```media_ids – A comma-delimited list of media_ids to associate with the Tweet```

But it should state...

```media_ids – A list of media_ids to associate with the Tweet```

The tweepy code is taking a native python list and converting it to a CSV string internally, and throws an error if it received a value that is not a list.

Doesn't work...
```
media = api.media_upload("william_gibson.jpg")
tweet = "Great scifi author or greatest scifi author? #williamgibson"
post_result = api.update_status(status=tweet, media_ids=media.media_id)
```
Does work...
```
media = api.media_upload("william_gibson.jpg")
tweet = "Great scifi author or greatest scifi author? #williamgibson"
post_result = api.update_status(status=tweet, media_ids=[media.media_id])
```

I can make a pull request to fix the issue if that's helpful.

**Comment by mattccrampton** [comment]
Thanks

**Comment by jonevanmoore** [comment]
Is there a way to make this work with posting videos?

**Comment by Harmon758** [comment]
@jonevanmoore See https://github.com/tweepy/tweepy/issues/640.
