### ISSUE TITLE
Tweepy not finding results that should be there

### ISSUE THREAD

**Issue by GameOver51** [tweepy/tweepy#1245]
Hi, I tested to query search api by some ' #keyword' and the the result is empty. But when I search the same '#keyword' in the twitter website, It display many of result. Did I do some thing wrong?

**Comment by Harmon758** [comment]
I'm unable to reproduce this. Using [`API.search`](https://tweepy.readthedocs.io/en/latest/api.html#API.search) with the query `"#keyword"` returns the expected results:
```py
>>> results = api.search("#keyword")
>>> len(results)
14
```
Can you show the relevant code?

**Comment by GameOver51** [comment]
No sorry. I mean searching '#\<some keyword>' for example : `'#coinmonks'`the api.search return empty result but in the twitter website the results are display.

**Comment by Harmon758** [comment]
From [Twitter's documentation for the standard search API](https://developer.twitter.com/en/docs/tweets/search/overview/standard):

> The Twitter Search API searches against a sampling of recent Tweets published in the past 7 days.
> 
> Before digging in, it’s important to know that the standard search API is focused on relevance _and not completeness_. This means that some Tweets and users may be missing from search results. If you want to match for completeness you should consider the [premium](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets) or [enterprise](https://developer.twitter.com/en/docs/tweets/search/api-reference/premium-search) search APIs.

The current most recent Tweet that matches that hashtag is from February, far outside the 7-day limit.

**Comment by GameOver51** [comment]
Oh understood. Is it only happen with some keyword because for in '#huaweimate20pro' retrieved post from 9 days ago.

**Comment by okomarov** [comment]
You can try to add a date condition e.g. `since:2018-01-01`

**Comment by Harmon758** [comment]
There might be some wiggle room on the limit.
From the [documentation for using the standard search API](https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators):
> The Search API is not complete index of all Tweets, but instead an index of recent Tweets. The index includes between 6-9 days of Tweets.

This isn't up to Tweepy and is off-topic here. For further questions about Twitter's API, you should use the [Twitter Developers Forums](https://twittercommunity.com/).

@okomarov Date operators do not affect the 7/6-9 day limit.

**Comment by GameOver51** [comment]
> There might be some wiggle room on the limit.
> From the [documentation for using the standard search API](https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators):
> 
> > The Search API is not complete index of all Tweets, but instead an index of recent Tweets. The index includes between 6-9 days of Tweets.
> 
> This isn't up to Tweepy and is off-topic here. For further questions about Twitter's API, you should use the [Twitter Developers Forums](https://twittercommunity.com/).
> 
> @okomarov Date operators do not affect the 7/6-9 day limit.

Ahh okay, understood. Thank you very much.
