### ISSUE TITLE
Accessibility Issue - alt text in images

### ISSUE THREAD

**Issue by edent** [tweepy/tweepy#1247]
Organisations which use Tweepy to post images *need* to be able to add alt text.

This is required under the USA's [Americans with Disabilities Act](https://adata.org/learn-about-ada) and the EU's [Accessibility Directive](https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32016L2102&from=en).

The Twitter API documentation is at: https://developer.twitter.com/en/docs/media/upload-media/api-reference/post-media-metadata-create

See #716 and  #727 for more discussion.

**Comment by radiocontrolled** [comment]
Hi @Harmon758, 
I'm using the latest version (3.8.0) and I'm wondering when you are planning to release 3.9. I would like to use the `create_media_metadata` feature, which is in the documentation. I'm prett
Thanks

**Comment by Harmon758** [comment]
@radiocontrolled There are [things I still want to add to 3.9.0](https://github.com/tweepy/tweepy/milestone/10) before it's released.
For now, you can simply install directly from the master branch.

**Comment by radiocontrolled** [comment]
Thank you @Harmon758 👍
