### ISSUE TITLE
Tweepy script stops for no reason

### ISSUE THREAD

**Issue by miguelwon** [tweepy/tweepy#1248]
I have a list of screen names (a few hundred) and their tweets (the ids). With that list, I'm using Tweepy to get the tweet status and the retweeters' ids. I'm using the code I show below that works fine.

The problem is that after a few screen names (10-15) from the initial list, the python script stops without printing any error. Initially, I was running the script with:

`python get_rt.py > log 2>&1 &`

which sometimes does not "catch" all the print errors. So I implemented a traceback with logging and there is no error in the traceback. The script justs stop for some reason.

Any idea why it stops or how should I do to catch the error?

```
import io,json,sys
import traceback
import logging

#Logging
LOG_FILENAME = 'log_exception.txt'
logging.basicConfig(filename=LOG_FILENAME, level=logging.DEBUG)


# Tweepy
import tweepy,time
consumer_key = 'XXX'
consumer_secret = 'XXX'
auth = tweepy.AppAuthHandler(consumer_key, consumer_secret)
api = tweepy.API(auth,wait_on_rate_limit=True, wait_on_rate_limit_notify=True, compression=True)

#MongoDB
from pymongo import MongoClient
client = MongoClient('localhost', 27018)
db = client['Twitter']
col_tweets = db['Tweets']
col_users = db['Users']

#Usefull function to save data to DB
def save_user(user_info):
    id_str = user_info['id_str']
    col_users.update({'id_str':id_str},user_info,upsert = True)
def save_tweet(tweet_info):
    id_str = tweet_info['id_str']
    col_tweets.update({'id_str':id_str},tweet_info,upsert = True)


screen_names = [...] #list of screen names
try:

    for sc_name in screen_names:
        print(sc_name)
        tweets_data = []
        with io.open('tweets_{}.json'.format(sc_name)) as f: #open the file containing the tweets from screen names X
            for line in f:
                tweet = json.loads(line)
                if tweet['retweets_count'] >= 1:
                    tweets_data.append(tweet)
        if not tweets_data:
            continue

        for i,tweet in enumerate(tweets_data):
            t_id = tweet['id']
            try:
                rts = api.retweets(id = t_id,count = 100,tweet_mode="extended")
                if rts:
                    retweeted_status = rts[0]._json['retweeted_status']
                    rts_u_ids = []
                    for rt in rts:
                        rt = rt._json
                        user_rt = rt['user']
                        save_user(user_rt)
                        rts_u_ids.append(user_rt['id_str'])
                    retweeted_status['retweeters_ids'] = rts_u_ids
                    save_tweet(retweeted_status)
            except tweepy.TweepError:
                time.sleep(60 * 15)
                print("Sleeping 60*15")
except Exception as e:
    logging.error(traceback.format_exc())
```

**Comment by okomarov** [comment]
You're manually sleeping when also `wait_on_rate_limit=True`:
```
except tweepy.TweepError:
    time.sleep(60 * 15)
    print("Sleeping 60*15")
```
You should use one or the other. You're probably hitting a rate limit and logging/printing that info in separate places, so you don't see it in your log.

**Comment by miguelwon** [comment]
That's why I have 900 seconds (the 15 min rate limit). The problem is that it never catch that exception. If so I should have seen it when running using

`python get_rt.py > log 2>&1 &`

But nothing...

**Comment by Harmon758** [comment]
Are you sure it hasn't simply reached the end of `screen_names`?

> If so I should have seen it when running using
> 
> `python get_rt.py > log 2>&1 &`

This will redirect both the stderr and stdout to a file called `log` while executing the script in the background. You're sure that the `log` file is empty and that the job/process completes instead of continuing to run in the background?

Instead of doing this and making it more difficult to debug, you could simply run the program normally and look at any errors or tracebacks in the console.

> That's why I have 900 seconds (the 15 min rate limit). The problem is that it never catch that exception.

This will catch all `TweepError`s, not just rate limits. In fact, a `RateLimitError` should never occur, since you have `wait_on_rate_limit` set to `True`.

**Comment by miguelwon** [comment]
> Are you sure it hasn't simply reached the end of screen_names?
For sure. I have more than 500 screen names and it will take a few days to get all the data. 

This will redirect both the stderr and stdout to a file called log while executing the script in the background. You're sure that the log file is empty and that the job/process completes instead of continuing to run in the background?

**Comment by miguelwon** [comment]
`Are you sure it hasn't simply reached the end of screen_names?`
Yes, I'm sure. I have more than 500 screen names. It will take days to get all the data


> This will redirect both the stderr and stdout to a file called log while executing the script in the background. You're sure that the log file is empty and that the job/process completes instead of continuing to run in the background?
Yes, I'm sure. I check with `top`

> This will catch all TweepErrors, not just rate limits. In fact, a RateLimitError should never occur, since you have wait_on_rate_limit set to True.
I know. Tha's why this is strange. Because this exception is never caught.

**Comment by Harmon758** [comment]
> Yes, I'm sure. I have more than 500 screen names. It will take days to get all the data

Are you sure each one has `tweets_data` though? How many `sc_name`s are being printed?

> Yes, I'm sure. I check with `top`

Again, instead of using indirect methods of logging and determining whether the script is still running, just run it directly in the console without pipes or other options.
As it is, this issue isn't actionable, and it's difficult to help you when there's no traceback or determinable issue.

> I know. Tha's why this is strange. Because this exception is never caught.

Why are you expecting a `TweepError`?

**Comment by miguelwon** [comment]
Not sure if you notice from my code but there is a traceback logging. The problem is precisely that from it no error is reached. 
I need to run the script for several days, more precisely about 15 days. Run it in the terminal is not a good approach. 
I'm not expecting a `TweepError`. I have it in case something wrong happen. For that scenario just sleep in continue to the next screen name.

**Comment by Harmon758** [comment]
> Not sure if you notice from my code but there is a traceback logging. The problem is precisely that from it no error is reached.

Right, which is why I'm asking if you're certain the script didn't just complete successfully.

> I need to run the script for several days, more precisely about 15 days. Run it in the terminal is not a good approach.

I don't really see the difference in keeping a terminal open. The process is going to be running and using resources either way.



> I'm not expecting a `TweepError`. I have it in case something wrong happen.

Then why is not encountering it strange?

**Comment by exp2Tapavicki** [comment]
I had similar issue. On 20000 twitter ids maybe 20 had this issue.

Payload:
{
    "request": "/1.1/friends/list.json",
    "error": "Not authorized."
}
``for i in range(3):
	try:
	    friends = self.api.GetFriends(
	        user_id=twitter_id,
	        screen_name=None,
	        cursor=None,
	        count=None,
	        total_count=total_count,
	        skip_status=True,
	        include_user_entities=False
	    )
	except Exception as e:
	    print(str(e))
	    time.sleep(10)
    if friends is not None:
          break``

**Comment by Harmon758** [comment]
This is a separate issue; you're encountering an exception.
However, it's also impossible to tell what your issue is without seeing the full traceback and/or the relevant code, i.e. `api_call`.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
