### ISSUE TITLE
How to get Poll options from a tweet

### ISSUE THREAD

**Issue by wtreston** [tweepy/tweepy#1249]
Hi,

I am trying to retrieve the options from a poll in a tweet, which should be possible according to Twitters Docs: [https://developer.twitter.com/en/docs/tweets/enrichments/overview/poll-metadata](here)

However when I get a tweet that has a poll in it, the poll attribute doesn't appear in the information returned. 

This is what I am currently using
`status = api.get_status(status_id)`

Any suggestions?

**Comment by Harmon758** [comment]
As that documentation says, it's:
> Available across all enterprise APIs

The [GET statuses/show/:id endpoint](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-statuses-show-id) that [`API.get_status`](https://tweepy.readthedocs.io/en/latest/api.html#API.get_status) uses is not an enterprise API.

For more information, see https://twittercommunity.com/t/idea-adding-polls-api-support-for-3rd-party-clients/127837, https://twittercommunity.com/t/poll-support/78235, and https://twittercommunity.com/t/poll-support-for-rest-api/54775.
