### ISSUE TITLE
stream.filter(track=list_of_keywords) not returning tweets with standard operators

### ISSUE THREAD

**Issue by sagar-raythatha** [tweepy/tweepy#1251]
Hi,

I am not receiving the tweets when I have build keywords using the [standard operators](https://developer.twitter.com/en/docs/tweets/rules-and-filtering/overview/standard-operators.html)

**Below keywords return the proper tweets:**
watching now
Boeing flight

**Whereas, the below keywords are not returning the matching tweets:**
"\""toms of maine\"""  _- (which should return tweet containing toms of maine together)_
love or hate _- (which should return tweets containing either love or hate)_
(hills%20OR%20hill%27s)%20advantage  _- (which should return hills advantage or hill's advantage)_

When I checked the [documentation](https://developer.twitter.com/en/docs/tweets/rules-and-filtering/overview/standard-operators.html) of standard [streaming](https://developer.twitter.com/en/docs/tweets/filter-realtime/overview) tweets, it supports all these operators. Whereas, when I pass into the list of keywords, it is unable to fetch the tweets.

Can you please guide if any solution available or suggest how should I get this?

Thanks

**Comment by Harmon758** [comment]
> """toms of maine""" _- (which should return tweet containing toms of maine together)_

I'm unable to reproduce this; using `stream.filter(track = ["""toms of maine"""])` works as intended.
There aren't many Tweets that match this though, so it could take a while to receive one.

> love or hate _- (which should return tweets containing either love or hate)_

The `OR` standard operator is case-sensitive, so this needs to be `love OR hate`.

> (hills%20OR%20hill%27s)%20advantage _- (which should return hills advantage or hill's advantage)_

You don't need to URL encode this. Tweepy should handle that for you.

Also:
> statuses/filter does not allow combining keywords using parentheses

https://twittercommunity.com/t/filter-realtime-problem/113061/2

and despite the documentation:
> You cannot use the search operators with statuses/filter

https://twittercommunity.com/t/statuses-filter-and-search-operators/115840/2

**Comment by sagar-raythatha** [comment]
Thank you Harmon for detailed answer.
