### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by Harmon758** [tweepy/tweepy#1253]
With [Python 2.7 reaching its EOL at the end of the year](https://www.python.org/dev/peps/pep-0373/), I'd like to start planning to drop support for it.
It would increase maintainability and reduce a lot of the overhead required for compatibility, as well as allowing improvements that would be difficult to implement while supporting Python 2.

Specifically, I want to look into adding asynchronous support with asyncio (#732), i.e. async/await syntax, and maybe with aiohttp (or requests 3 if that's released soon), especially to replace the current threading method for streams.

I think the current plan should be for Tweepy ~~v3.9~~ (v3.9 was released without noting that it would be the last version to support Python 2 in its changelog and release notes, so a v3.10 is planned) v3.10 to be the last version to support Python 2.7, and then for v4.0 to be Python ~~3.5+~~ (3.5 is also EOL now) 3.6+.

**Comment by hugovk** [comment]
The plan sounds good. Python 2.7 installs of Tweepy are relatively low for Tweepy.

Here's the pip installs for Tweepy from PyPI for July 2019:

| category | percent | downloads |
|----------|--------:|----------:|
| 3        |  73.34% |    83,887 |
| 2        |  25.93% |    29,655 |
| null     |   0.73% |       836 |
| Total    |         |   114,378 |

Source: `pip install -U pypistats && pypistats python_major tweepy --last-month`

| category | percent | downloads |
|----------|--------:|----------:|
| 3.6      |  37.23% |    42,582 |
| 2.7      |  25.89% |    29,611 |
| 3.7      |  18.38% |    21,022 |
| 3.5      |  15.50% |    17,734 |
| 3.4      |   2.08% |     2,381 |
| null     |   0.73% |       836 |
| 3.8      |   0.09% |        98 |
| 3.3      |   0.06% |        69 |
| 2.6      |   0.04% |        44 |
| 3.9      |   0.00% |         1 |
| Total    |         |   114,378 |

Source: `pip install -U pypistats && pypistats python_minor tweepy --last-month`

**Comment by hugovk** [comment]
Please see PR #1255.

**Comment by Harmon758** [comment]
Since Python 2 has been EOL for almost a year now and PyPI Stats shows Python 2 downloads averaging at about 5% or less, and with [Tweepy v3.10.0 released](https://github.com/tweepy/tweepy/releases/tag/v3.10.0) now, I've gone ahead and made a branch and PR #1482 to drop support for Python 2.

Note, Tweepy v3.10.0 will also be the last version to support Python 3.5, [since it's also EOL now](https://www.python.org/dev/peps/pep-0478/).
PyPI Stats shows downloads for it averaging at even less, about 2-4% or lower.
