### ISSUE TITLE
'tweepy.error.TweepError' status code 414 (URI too long) when getting an account's followers

### ISSUE THREAD

**Issue by mr-hydden** [tweepy/tweepy#1259]
I am doing some basic info gathering and when getting an account's followers I keep getting the following error:

```
 File "C:\PycharmProjects\Metrics\TwitterParsers.py", line 357, in _get_type_of_resource
    for follower in followers:
  File "C:\PycharmProjects\Metrics\venv\lib\site-packages\tweepy\cursor.py", line 47, in __next__
    return self.next()
  File "C:\PycharmProjects\Metrics\venv\lib\site-packages\tweepy\cursor.py", line 195, in next
    self.current_page = self.page_iterator.next()
  File "C:\PycharmProjects\Metrics\venv\lib\site-packages\tweepy\cursor.py", line 73, in next
    **self.kargs)
  File "C:\PycharmProjects\Metrics\venv\lib\site-packages\tweepy\binder.py", line 250, in _call
    return method.execute()
  File "C:\PycharmProjects\Metrics\venv\lib\site-packages\tweepy\binder.py", line 233, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: Twitter error response: status code = 414
```

I obtain the ```followers``` (a ```tweepy.cursor.ItemIterator```) using the following function:

```
def get_followers(user, item_limit = None):
    if item_limit is not None:
        return Cursor(api.followers, screen_name=user).items(item_limit)
    else:
        return Cursor(api.followers, screen_name=user).items()
```
At first I thought that the error might be due to some mistake in managing the rate limits (which I had nontheless activated when calling ```tweepy.API(auth, wait_on_rate_limit=True)```), but lowering the number of requested items to 1 or 2 makes no difference. Plus, I see that there is an if-else for ```RateLimitError``` and ```TweepError``` in the API's code.

I also have received a 431 (_Request Header Fields Too Large_) once when requesting data from a different account, but I haven't been able to reproduce it.

The problem is related to requesting followers, because I am also retrieving the user's account's description, ```created_at``` date, and tweets (_statuses_), and none of those produce any errors at all.

Any ideas? Thanks in advance.

**Comment by okomarov** [comment]
Check that you’re not passing the whole user object but just the screen name.

**Comment by mr-hydden** [comment]
God. That's it, thanks. I'm dumb.
