### ISSUE TITLE
Code 34: how to ? 

### ISSUE THREAD

**Issue by JocelynMunoz** [tweepy/tweepy#1264]
Hello,

I got an issue while trying to download tweets of a list thx to this code : 
`# Grap multiple user's user_timeline from twitter API and save to Excel
# Code will be save user's tweet ID, created Time, Coordinates-x, Coordinates-y, source, text. Can be modified at line 48 and so on
# Original code from https://gist.github.com/yanofsky/5436496  "A script to download all of a user's tweets into a csv"

import xlsxwriter
import tweepy

#https://github.com/tweepy/tweepy

consumer_key = "x"
consumer_secret = "x"
access_key = "x-x"
access_secret = "x"

def get_all_tweets(screen_name):

    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_key, access_secret)
    api = tweepy.API(auth)

    alltweets = []
    new_tweets = []
    outtweets = []

    new_tweets = api.user_timeline(screen_name = screen_name,count=200)

    alltweets.extend(new_tweets)

	#save the id of the oldest tweet less one
    oldest = alltweets[-1].id - 1

    #keep grabbing tweets until there are no tweets left to grab
    while len(new_tweets) > 0:
        print ("getting tweets before %s" % oldest)

        #all subsiquent requests use the max_id param to prevent duplicates
        new_tweets = api.user_timeline(screen_name = screen_name,count=200,max_id=oldest)

        #save most recent tweets
        alltweets.extend(new_tweets)

        #update the id of the oldest tweet less one
        oldest = alltweets[-1].id - 1

        print ("...%s tweets downloaded so far" % len(alltweets))

    #transform the tweepy tweets into a 2D array
    outtweets = [[tweet.id_str, tweet.created_at, tweet.coordinates,tweet.geo,tweet.source,tweet.text] for tweet in alltweets]

    return outtweets

def write_worksheet(twitter_name):

	#formating for excel
	format01 = workbook.add_format()
	format02 = workbook.add_format()
	format03 = workbook.add_format()
	format04 = workbook.add_format()
	format01.set_align('center')
	format01.set_align('vcenter')
	format02.set_align('center')
	format02.set_align('vcenter')
	format03.set_align('center')
	format03.set_align('vcenter')
	format03.set_bold()
	format04.set_align('vcenter')
	format04.set_text_wrap()

	out1 = []
	header = ["id","created_at","coordinates-x","coordinates-y","source","text"]

	worksheet = workbook.add_worksheet(twitter_name)

	out1 = get_all_tweets(twitter_name)
	row = 0
	col = 0

	worksheet.set_column('A:A', 20)
	worksheet.set_column('B:B', 18)
	worksheet.set_column('C:C', 13)
	worksheet.set_column('D:D', 13)
	worksheet.set_column('E:E', 20)
	worksheet.set_column('F:F', 120)

	for h_item in header:
		worksheet.write(row, col, h_item, format03)
		col = col + 1

	row += 1
	col = 0

	for o_item in out1:
		write = []
		cord1 = 0
		cord2 = 0

		write = [o_item[0], o_item[1], o_item[4], o_item[5]]

		if o_item[2]:
			cord1 = o_item[2]['coordinates'][0]
			cord2 = o_item[2]['coordinates'][1]
		else:
			cord1 = ""
			cord2 = ""

		format01.set_num_format('yyyy/mm/dd hh:mm:ss')
		worksheet.write(row, 0, write[0], format02)
		worksheet.write(row, 1, write[1], format01)
		worksheet.write(row, 2, cord1, format02)
		worksheet.write(row, 3, cord2, format02)
		worksheet.write(row, 4, write[2], format02)
		worksheet.write(row, 5, write[3], format04)
		row += 1
		col = 0

workbook = xlsxwriter.Workbook('Twitter_timeline7.xlsx')

write_worksheet('Drouky')
write_worksheet('DelphineArduini')
write_worksheet('PatVoyer')
write_worksheet('alfredlediabete‏')
write_worksheet('Pierroo64‏')
write_worksheet('LaurBeauvallet‏')
write_worksheet('AlainNanou50‏')

workbook.close()
`

When it comes to alfredlediabete‏, it tells me "Traceback (most recent call last):
  File "D:\Dropbox (Deep Opinion)\Dossier de l'équipe Deep Opinion\FFD\FFD.py", line 121, in <module>
    write_worksheet('alfredlediabete‏')
  File "D:\Dropbox (Deep Opinion)\Dossier de l'équipe Deep Opinion\FFD\FFD.py", line 74, in write_worksheet
    out1 = get_all_tweets(twitter_name)
  File "D:\Dropbox (Deep Opinion)\Dossier de l'équipe Deep Opinion\FFD\FFD.py", line 25, in get_all_tweets
    new_tweets = api.user_timeline(screen_name = screen_name,count=200)
  File "C:\Users\jmunoz\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tweepy\binder.py", line 250, in _call
    return method.execute()
  File "C:\Users\jmunoz\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tweepy\binder.py", line 233, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 34, 'message': 'Sorry, that page does not exist.'}]"

How to avoid that please ? I really need tweets to go in xlsx by the way.

**Comment by okomarov** [comment]
The account exists but might have protected mode on (https://help.twitter.com/en/safety-and-security/public-and-protected-tweets), so you can’t pull its tweets unless you’re following the account (which is subject to the account’s approval).

Code 34 also happens for deleted/banned accounts or for single deleted tweets.

So you should try catch that and continue with the other screen names.

**Comment by JocelynMunoz** [comment]
I think that it's not about protected since the script scrapped tweets from this account, from time to time. When i tryed with only alfredlediabete‏, it worked once... 

Same when i'm doing it with script getting tweets as CSV...

**Comment by okomarov** [comment]
The user exists: https://twitter.com/alfredlediabete?lang=en-gb

However it's not reachable by other services too, e.g. https://tweeterid.com/, which simply returns the user id for the given screen name:
<img width="754" alt="Screenshot 2019-09-03 at 09 38 09" src="https://user-images.githubusercontent.com/3731173/64157416-95e2d880-ce2e-11e9-8d81-87dd2824d64f.png">

So, this is not related to Tweepy. You can try to ask on https://twittercommunity.com/ to see what's the reason behind this unexpected behaviour. I still suspect some privacy setting by the user.

**Comment by JocelynMunoz** [comment]
Ok, you may be right .. Boring ! 
Strange because gettwitterid got it : 
![image](https://user-images.githubusercontent.com/26411554/64159603-ca5c9180-ce3a-11e9-835a-86b622e59d22.png)

**Comment by JocelynMunoz** [comment]
i tried again and it works : 
![image](https://user-images.githubusercontent.com/26411554/64161046-3e983480-ce3d-11e9-8956-c063e5e35003.png)
Really strange...

**Comment by Harmon758** [comment]
Error code 34 means the specified resource was not found. This is an error code form Twitter's API, not Tweepy. You can simply handle the exception.
See https://developer.twitter.com/en/docs/basics/response-codes.

I'm unable to reproduce this right now anyway, but one possibility is that they're changing their username back and forth. If an account with that username isn't found, you'll get error code 34.

It shouldn't be due to a protected account, as that should return a 401 HTTP status code corresponding to the reason "Not authorized." without an API error code.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by JocelynMunoz** [comment]
Thx a lot ! Does anyone have an idea about how to fix this please ?

**Comment by Harmon758** [comment]
You can simply catch the `TweepError` and handle the specific error code with the `api_code` attribute.
