### ISSUE TITLE
Replying to other tweets does not seem to work

### ISSUE THREAD

**Issue by FBosler** [tweepy/tweepy#1267]
Replying to Tweets that are not my own does not work.

It works perfectly when replying to my own tweets, but as of now, I've not managed to reply to somebody else's Tweets.
The tweet will be pushed out and be visible on my profile under "Tweets & replies" but It will not show up when actually checking the original tweet.

```
TWEET_ID = <<<INSERT ID>>>
tweet = api.get_status(TWEET_ID)
comment = f'@{tweet.author.screen_name} Test Reply'
res = api.update_status(comment, in_reply_to_status_id_str=tweet.id)
```

Checking the response is somewhat strange. As it makes apparent that it replies to the user but not the tweet.

```
'in_reply_to_screen_name': **<<<tweet.author.screen_name>>>**,
 'in_reply_to_status_id': None,
 'in_reply_to_status_id_str': None,
 'in_reply_to_user_id': **<<<tweet.author.id_str>>>**,
 'in_reply_to_user_id_str': **<<<tweet.author.id_str>>>**,
 'is_quote_status': False, 
```

Could you provide a minimal working example replying to a tweet, that you did not author?

**Comment by okomarov** [comment]
Does that solve `str(tweet.id)`?

**Comment by FBosler** [comment]
@okomarov  nope, str(tweet.id) == tweet.id_str , which I had also tried.

**Comment by FBosler** [comment]
Any news on this?

**Comment by arturocerna** [comment]
You need to also set auto_populate_reply_metadata=True in your call. Taking your example.
`res = api.update_status(comment, in_reply_to_status_id=tweet.id, auto_populate_reply_metadata=True)`

After this your tweet should look like a reply to another tweet.

**Comment by Harmon758** [comment]
`in_reply_to_status_id_str` is no longer a valid parameter for [the POST statuses/update endpoint](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update).
Instead, `in_reply_to_status_id` should be used instead.
`res = api.update_status(comment, in_reply_to_status_id=tweet.id)` should work (`tweet.id` will be an `int` anyway).

The allowed parameters for `API.update_status` and [the corresponding documentation](https://tweepy.readthedocs.io/en/latest/api.html#API.update_status) have already been updated to reflect this (https://github.com/tweepy/tweepy/commit/bffebd6e35d477532192adc47b804cc9c01d6df4).

@arturocerna That is not the issue, as `auto_populate_reply_metadata` is not necessary when the status text being passed is already prefixed with the necessary mention.

**Comment by migueloiro** [comment]
Same for me :/

**Comment by MathLanca** [comment]
Same problem here, 
I'm trying to use this:
api.update_status("Replying tweet", result.id)

But it's creates a new tweet instead of a reply from the result.id

**Comment by ndrezn** [comment]
There still seem to be issues with posting reply tweets to bot accounts, see #1057.
