### ISSUE TITLE
Including attachments in direct messages

### ISSUE THREAD

**Issue by secondscrgames** [tweepy/tweepy#1269]
Thank you for creating Tweepy, it has been a huge time saver! It took me a bit to figure out the two-step process for uploading and sending an image attachment in a direct message. Part of this request is for an update to the docs, and part is a possible update to the Tweepy code base.

For the code base update, sending direct messages with attachments actually does require that all five arguments are included. Even if you don't want to use Quick Reply Type, you have to insert something (e.g. None) to get the rest of the code to work. Best case, it would be great to update Tweepy so that won't error out.

In the interim, you could include a code snippet that shows the process for uploading and then attaching a file to the direct message. Here is an example:

    img = api.media_upload('filepath')
    api.send_direct_message(recipient_id, 'text', None, 'media', img.media_id)

(you have to specify None for the quick reply field, and 'media' for image/gif/video content)

**Comment by Harmon758** [comment]
You can pass the optional arguments (`quick_reply_type`, `attachment_type`, `attachment_media_id`) as keyword arguments, e.g.:
```py
img = api.media_upload('filepath')
api.send_direct_message(recipient_id, 'text', attachment_type='media', attachment_media_id=img.media_id)
```
This is the same as and compliant with the rest of Tweepy's API methods.

The optional parameters, as well as the acceptable arguments for `attachment_type`, are properly documented at https://tweepy.readthedocs.io/en/latest/api.html#API.send_direct_message and https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/api-reference/new-event.
