### ISSUE TITLE
Unable to capture retweets 

### ISSUE THREAD

**Issue by reyha** [tweepy/tweepy#1270]
Hi, I am using Tweepy to build a real-time twitter analyzer where I need to capture the retweets and label them separately. My code is as follows:

```
try:
    text = status.extended_tweet['full_text']
    except Exception as e:
        print("error is ", e)
            try:
                text = status.full_text
            except Exception as e:
                print("error: ", e)
                text = status.text
   
is_retweet = hasattr(status, 'retweeted_status') or text.startswith('RT @')
if is_retweet: post_type = 102
```

I have collected around 50k tweets where there are no retweets, which is highly unlikely. I am unable able to identify the problem although I checked the docs where I see you guys normalize retweets 
 -> function 'models.py' 
``` 
elif k == 'retweeted_status':
    setattr(status, k, Status.parse(api, v))
```

How can I possibly go about detecting retweets from other tweets then? Please help, thanks!

**Comment by reyha** [comment]
@gungorkdr Thanks for your reply! 
`status.quoted_status` field is for a quoted status. I don't understand how will it possibly capture a retweet?

**Comment by gungorkdr** [comment]
I think I misunderstood your issue.
When someone retweet a tweet with comment it becomes a quote not a retweet. With the code I've sent you can capture both, quotes and retweets.

**Comment by reyha** [comment]
Then what about the tweets that are directly retweeted with the retweet button? Those should be normal retweets, right! If I try to capture `status.retweeted_status`, I should get a few retweets at least, if not all! The issue is that I am unable to capture any retweets using tweepy's streaming API .

**Comment by gungorkdr** [comment]
I really don't know why but I can capture retweets without problem.
Hope you can solve your problem.

**Comment by Harmon758** [comment]
I'm unable to reproduce this.
Disregarding the indentation errors in your code snippet, `hasattr(status, 'retweeted_status') or text.startswith('RT @')` should work to capture Retweets in an `on_status` function.
Can you provide a reproducible example (MCVE/SSCCE) of what you're trying?

Also, note, if your code snippet is within an `on_status` function for a `StreamListener`, `status` will never have a `full_text` attribute.
See https://tweepy.readthedocs.io/en/latest/extended_tweets.html#streaming.
