### ISSUE TITLE
How do I upload video

### ISSUE THREAD

**Issue by downdawn** [tweepy/tweepy#1271]
I need to upload video to twitter now, can you tell me how to do it?I can't even get media_id, using the media_upload method.Thank you very much.

**Comment by fitnr** [comment]
Uploading video isn't currently possible with the Tweepy library. The plan is to introduce it shortly. In the mean time, there are forks with video capability. See https://github.com/tweepy/tweepy/pull/929

**Comment by Harmon758** [comment]
As explained, this is still in development. Also see #640.
