### ISSUE TITLE
Sending Image within Direct Message Issue (Bad Media)

### ISSUE THREAD

**Issue by enablex3** [tweepy/tweepy#1278]
Hello! So I am unable to send images that I'm uploading within direct messages. My code is as follows:
`  auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(accessKey, accessSecret)
    
    api = tweepy.API(auth)
    response = api.media_upload(media)
    media_id = response.media_id_string
    
    api.send_direct_message(recipient_id=friendID, text=message, attachment_type="media", attachment_media_id=media_id)`

My _media_ variable is a path to a .jpg file. This image is less than the maximum upload size (it uploads successfully). I get an ID associated with the image every time I attempt this process, but I always get the error: **[{'code': 151, 'message': 'There was an error sending your message: Bad Media, unable to process: Some(InvalidMedia).'}** when attaching the media to a direct message.

Any suggestions would be greatly appreciated. This API Wrapper is great! Thanks for your efforts!

**Comment by enablex3** [comment]
### Update to this. So when I include the .jpg in a status update it all works fine. I decided to try formatting the image files for direct messages. **Using _pillow_ module for python I converted the file format from JPEG to PNG**. The png file was sent successfully! Just in case anyone encounters this issue as well!

**Comment by ablkvo** [comment]
Hi enablex3,

what are the media and media_id here? where did you upload them?

**Comment by enablex3** [comment]
media is the local path to a .png image on your machine or server.
media_id is the id field from Twitter's response to their image upload API.

The way I got it working was using the image upload API for Twitter. The
image gets uploaded and Twitter responds with the media_id. I then used
that media_id and the path my local image for the media field to finally
send images via direct message.

**Comment by ablkvo** [comment]
> media is the local path to a .png image on your machine or server. media_id is the id field from Twitter's response to their image upload API. The way I got it working was using the image upload API for Twitter. The image gets uploaded and Twitter responds with the media_id. I then used that media_id and the path my local image for the media field to finally send images via direct message.
> […](#)
> On Thu, Feb 6, 2020 at 6:45 AM abolfazl komeazi ***@***.***> wrote: Hi enablex3, what are the media and media_id here? where did you upload them? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftweepy%2Ftweepy%2Fissues%2F1278%3Femail_source%3Dnotifications%26email_token%3DAJ73YHZGUPWDW2MJEZVXVTTRBPZ4TA5CNFSM4I3QRUG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEK65SWI%23issuecomment-582867289&data=02%7C01%7Cereyes%40mail.citadel.edu%7C91d3b936490a475cc62a08d7aafa0766%7C960c1081d06341f8844b41d738db04a3%7C0%7C0%7C637165863546388299&sdata=0nDYfNKYdcxs6rMR%2FKng%2F%2FNjFALedPyhKTWeT%2FQBp6Q%3D&reserved=0>, or unsubscribe <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJ73YH6ODOASQYB2ZOSNODLRBPZ4TANCNFSM4I3QRUGQ&data=02%7C01%7Cereyes%40mail.citadel.edu%7C91d3b936490a475cc62a08d7aafa0766%7C960c1081d06341f8844b41d738db04a3%7C0%7C0%7C637165863546388299&sdata=33Ax03gNvLT8cgE9VsLwWMTvvhdEAQ8LKFR5f9R%2FURY%3D&reserved=0> .

Thank you in advance. That works like a charm!

**Comment by enablex3** [comment]
I’m glad I could help!

**Comment by ablkvo** [comment]
> I’m glad I could help! On Thu, Feb 6, 2020 at 09:49 abolfazl komeazi <notifications@github.com> wrote:
> […](#)
> media is the local path to a .png image on your machine or server. media_id is the id field from Twitter's response to their image upload API. The way I got it working was using the image upload API for Twitter. The image gets uploaded and Twitter responds with the media_id. I then used that media_id and the path my local image for the media field to finally send images via direct message. … <#m_-6354165757792929527_> On Thu, Feb 6, 2020 at 6:45 AM abolfazl komeazi *@*.***> wrote: Hi enablex3, what are the media and media_id here? where did you upload them? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftweepy%2Ftweepy%2Fissues%2F1278%3Femail_source%3Dnotifications%26email_token%3DAJ73YHZGUPWDW2MJEZVXVTTRBPZ4TA5CNFSM4I3QRUG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEK65SWI%23issuecomment-582867289&data=02%7C01%7Cereyes%40mail.citadel.edu%7C91d3b936490a475cc62a08d7aafa0766%7C960c1081d06341f8844b41d738db04a3%7C0%7C0%7C637165863546388299&sdata=0nDYfNKYdcxs6rMR%2FKng%2F%2FNjFALedPyhKTWeT%2FQBp6Q%3D&reserved=0 <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftweepy%2Ftweepy%2Fissues%2F1278%3Femail_source%3Dnotifications%26email_token%3DAJ73YHZGUPWDW2MJEZVXVTTRBPZ4TA5CNFSM4I3QRUG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEK65SWI%23issuecomment-582867289&data=02%7C01%7Cereyes%40mail.citadel.edu%7Ca4abba05c24d406b367a08d7ab13d2e7%7C960c1081d06341f8844b41d738db04a3%7C0%7C0%7C637165973970075150&sdata=ivkFRKwJLF0EPJgY3mzAhXVeMrA9afMmKCXVsahpVIE%3D&reserved=0>, or unsubscribe https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJ73YH6ODOASQYB2ZOSNODLRBPZ4TANCNFSM4I3QRUGQ&data=02%7C01%7Cereyes%40mail.citadel.edu%7C91d3b936490a475cc62a08d7aafa0766%7C960c1081d06341f8844b41d738db04a3%7C0%7C0%7C637165863546388299&sdata=33Ax03gNvLT8cgE9VsLwWMTvvhdEAQ8LKFR5f9R%2FURY%3D&reserved=0 <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJ73YH6ODOASQYB2ZOSNODLRBPZ4TANCNFSM4I3QRUGQ&data=02%7C01%7Cereyes%40mail.citadel.edu%7Ca4abba05c24d406b367a08d7ab13d2e7%7C960c1081d06341f8844b41d738db04a3%7C0%7C0%7C637165973970085149&sdata=fIBrQ7HRoXtapns%2FW1TUi41evP5VC4%2FQAGiYdnifUkQ%3D&reserved=0> . Thank you in advance. That works like a charm! — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Ftweepy%2Ftweepy%2Fissues%2F1278%3Femail_source%3Dnotifications%26email_token%3DAJ73YH4JLIRX7KB73GLPPVTRBQPQ7A5CNFSM4I3QRUG2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEK7POVA%23issuecomment-582940500&data=02%7C01%7Cereyes%40mail.citadel.edu%7Ca4abba05c24d406b367a08d7ab13d2e7%7C960c1081d06341f8844b41d738db04a3%7C0%7C0%7C637165973970085149&sdata=2VCqxKUsVELGpKD5x%2BcJ6uKyqWT0W8oCjNMErhKmZ6w%3D&reserved=0>, or unsubscribe <https://nam01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAJ73YH3THJNO2IZI3ATIAELRBQPQ7ANCNFSM4I3QRUGQ&data=02%7C01%7Cereyes%40mail.citadel.edu%7Ca4abba05c24d406b367a08d7ab13d2e7%7C960c1081d06341f8844b41d738db04a3%7C0%7C0%7C637165973970095140&sdata=fPYcRQpEgSiFojb4DBGkBwAuwBsjYJDvC9xcUQfuuWs%3D&reserved=0> .

Yeah, Thanks. I used it for jpg files and also works by the way!

**Comment by enablex3** [comment]
Oh okay, interesting. I was having issues with jpeg and had to use a module
to convert jpeg to png.

**Comment by PvrpleBlvck** [comment]
Probably a little too late, but here's a function you use in your code to solve the issue


def send_direct_message_with_media(sender_id, text, attachment_media_id):
    get_api().send_direct_message(recipient_id=sender_id, text=text, attachment_type='media', attachment_media_id=attachment_media_id)

**Comment by PvrpleBlvck** [comment]
I find this to be a better way to solve this issue. But firstly just make sure your file images are within the max allowed size.

# upload media first we define the path to your image
media = api.media_upload(filename='/path/to/image/filename.jpg')

# send with media, now we call our api method for sendind the attachment. which takes a couple parameters as shown below
api.send_direct_message(recipient_id=recipient_id, text='Please find the attached png file! test', attachment_type='media', attachment_media_id=media.media_id)
![Screenshot (113)](https://user-images.githubusercontent.com/41530377/147391683-2c0d6acb-e480-4adf-8299-131806e24b85.png)
i did run into a few errors at first. One was because i used a bigger jpg file and the other was because i did not pass  string 'text'.

Goood Luck

**Comment by Harmon758** [comment]
This isn't reproducible without the image in question, but you likely need to specify the `media_category` paramter as `dm_image`.
You might also need to use chunked upload.
See the Twitter API documentation on [Media Best Practices](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/media-best-practices) and [Attaching media to Direct Messages](https://developer.twitter.com/en/docs/twitter-api/v1/direct-messages/message-attachments/guides/attaching-media).

For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.
