### ISSUE TITLE
Filtered Streams support - is it ready?

### ISSUE THREAD

**Issue by NetwarSystem** [tweepy/tweepy#1283]
I just noticed Andy Piper announcing the sunsetting of the current streaming methods:

https://twitter.com/andypiper/status/1186325788813119488

And I have not dug into this yet:

https://developer.twitter.com/en/docs/labs/filtered-stream/overview

Where does Tweepy development stand in terms of these upcoming changes?

**Comment by Harmon758** [comment]
Filtered Stream was only added to Labs a month ago, and there's no deprecation date for the statuses/filter and statuses/sample endpoints yet:

>With today’s announcement, we are also letting you know about the future deprecation of the current statuses/filter endpoint available through our current API. Once the filtered stream endpoints graduate out of Labs, they will replace the statuses/filter endpoint you use today. At that point, we will give 6 months’ notice to provide necessary time to transition. We plan to follow a similar pattern for our existing GET statuses/sample endpoint, as well.

See https://twittercommunity.com/t/new-filtered-stream-endpoints-available-in-labs-and-the-future-of-statuses-filter/129888.

I definitely plan on adding support for the filtered stream endpoints once they become part of the standard API. As of right now, I'm undecided on whether or not to support features in Labs, as it would require extra dev and maintenance work for features that aren't stable/generally released yet. Even if the decision was made to do so, it would likely come after [version 3.9](https://github.com/tweepy/tweepy/milestone/10) and [4.0](https://github.com/tweepy/tweepy/milestone/11), as those releases will likely include large features in the standard API that are currently unsupported (see the associated milestones; support for the Account Activity API might also be included in version 4.0).

**Comment by Harmon758** [comment]
Closing this in favor of #1472 now, since the Labs version of filtered stream has been graduated (and retired) into Twitter API v2 as the filtered stream endpoint group.
