### ISSUE TITLE
ModuleNotFoundError: No module named 'tweepy.auth' is happened

### ISSUE THREAD

**Issue by WebSamuraiDaisuke** [tweepy/tweepy#1287]
Hi, there

I got an issue happened on this code

```Python
import tweepy

consumer_key = "XXXXXXXXXXXXXX"
consumer_secret = "YYYYYYYYYYYYYYYYYY"
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)


```
And these errors have happened.
`Traceback (most recent call last):
File "test_tweepy.py", line 8, in <module>
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
AttributeError: module 'tweepy' has no attribute 'OAuthHandler'`

How can I solve this issue?

**Comment by Harmon758** [comment]
Your traceback does not correspond with the issue title.
Regardless, do you have a different file or module name `tweepy` in your path?

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by WebSamuraiDaisuke** [comment]
Thank you tell me how to use block usage.

>do you have a different file or module name tweepy in your path?
No

**Comment by Harmon758** [comment]
Tweepy 3.8.0 definitely does not have this issue.
You must have a file or module in your path or current directory that you're importing instead.
