### ISSUE TITLE
Rate limit reached keeps occurring, even after waiting 15 minutes

### ISSUE THREAD

**Issue by TomCasavant** [tweepy/tweepy#1292]
I'm trying to collect a couple thousand tweets from twitter for a data analysis project. I've got the api setup with the ```wait_on_rate_limit=True``` argument. The program tends to run through ~1000 tweets and then complains about the rate limit (which makes sense, because that would be about the limit twitter gives). However, after it waits for about 15 minutes it sends the rate_limit_error again. It keeps doing this forever as far as I can tell, if I end the program and start it again it has no problems for the first 15 minutes again. 

Let me know if you need any more information about the issue.

**Comment by Harmon758** [comment]
What method/endpoint are you using? Can you provide a reproducible example (MCVE/SSCCE) of what you're doing along with a full traceback?

**Comment by drandreaskrueger** [comment]
Perhaps this code snippet helps? 

```
from pprint import pformat 

def rate_limit_status(api, jsonpath=None, datetimeformat="%d %b %Y %H:%M:%S"):
    answer = api.rate_limit_status()
    if not jsonpath:
        answer = pformat(answer)
    else:
        for step in jsonpath:
            try:
                answer=answer[step]
            except Exception as e:
                print ("answer.keys()=%s" % answer.keys())
                raise e
        epoch = answer.get('reset', None)
        if epoch:
            answer['resetDatetime'] = time.strftime(datetimeformat, time.localtime(epoch)) 
    return answer

print (rate_limit_status(api, ['resources', 'statuses', '/statuses/user_timeline']))
print (rate_limit_status(api))
```


Before each possibly problematic call, it's simple to always query the rate limit endpoint, so that I can react accordingly.
