### ISSUE TITLE
Premium search support?

### ISSUE THREAD

**Issue by drandreaskrueger** [tweepy/tweepy#1293]
Hey, the tweepy function `api.search()` uses an endpoint at twitter which has an index of only 6-9 days (It's called "standard search"). Now, Twitter also has a "Premium search", which had to be enabled at https://developer.twitter.com/en/account/environments ...

Then in some "quick'n'dirty hack", I simply modified this tweepy code: https://github.com/tweepy/tweepy/blob/718e2de71ca545db3d3cd919fc96906ddde6f2a0/tweepy/api.py#L1274-L1281

to this:

    path='/tweets/search/fullarchive/dev.json',

which instead of the "Standard search" url

https://api.twitter.com/1.1/search/tweets.json

then creates the "Premium Search" url

https://api.twitter.com/1.1/tweets/search/fullarchive/dev.json

but then the twitter server answers with a 422

    tweepy.error.TweepError: Twitter error response: status code = 422

so I am doing something wrong here.

Please 

(a) help me how to get the "Premium search" going with some "quick'n'dirty hack", and   
(b) consider to later support it officially within tweepy. 

Thanks a lot! Great library, keep up the good work.

**Comment by Harmon758** [comment]
The premium search APIs are not in-place replacements for the current standard search API.
See https://developer.twitter.com/en/docs/tweets/search/overview/premium and https://developer.twitter.com/en/docs/tweets/search/api-reference/premium-search.
Closing this in favor of #1175.

**Comment by drandreaskrueger** [comment]
> not in-place replacements for the current standard search API

Yes. Would a mapping of the API results from the Premium format to the Standard format be impossibly difficult?

> Closing this in favor of #1175.

Yes, I understand that. I am subscribed to that issue now. Thanks.

**Comment by Harmon758** [comment]
Both the inputs and outputs for the endpoints are different.
I still want to try to get support for the premium search APIs into Tweepy v3.9. If that changes, I'll update the milestone for #1175.
