### ISSUE TITLE
Re-tweeter Cursor Always giving 0 as next cursor

### ISSUE THREAD

**Issue by nirav0999** [tweepy/tweepy#1295]
To collect more than the last 100 retweeters of a tweet. I used the below code
![Screenshot from 2019-11-15 16-40-21](https://user-images.githubusercontent.com/35040524/68939465-b3390900-07c6-11ea-872c-b0cdd75fcd2d.png)

 
Based on https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-statuses-retweeters-ids and the tweepy documentation of cursor
The function should return a next_cursor_value to get the next 100 retweeters of the tweet. I tested this on a tweet with 11k retweets , however it only returned 92 retweeter ID's and the cursor value 0.
![Screenshot from 2019-11-15 16-50-51](https://user-images.githubusercontent.com/35040524/68940046-23945a00-07c8-11ea-8322-bcda367c1f24.png)

I tried to pass 0 as cursor so as to get the next 100 retweeters when I called the function however I got the same 92 retweets and the same result as before. Has twitter API stopped Supporting Cursor iteration? Is there a workaround to get the full list of retweeters for a tweet?

PS.
I also tried the below code
![Screenshot from 2019-11-15 16-50-42](https://user-images.githubusercontent.com/35040524/68940068-3575fd00-07c8-11ea-9b07-9d7a620db4fd.png)

But got the same results.

**Comment by Harmon758** [comment]
As the Twitter API documentation you linked and [the documentation for API.retweeters](https://tweepy.readthedocs.io/en/latest/api.html#API.retweeters) say, that method/endpoint:
> Returns up to 100 user IDs belonging to users who have retweeted the Tweet specified by the id parameter.

This is an API limitation, and as the Twitter API documentation for the `cursor` parameter also says:
> Causes the list of IDs to be broken into pages of no more than 100 IDs at a time. The number of IDs returned is not guaranteed to be 100 as suspended users are filtered out after connections are queried.

and
> While this method supports the cursor parameter, the entire result set can be returned in a single cursored collection.
