### ISSUE TITLE
Exclude retweets from stream

### ISSUE THREAD

**Issue by s2t2** [tweepy/tweepy#1299]
I'm trying to exclude retweets from my stream.

I'm currently able to listen for all tweets matching a given topic:

```py
stream.filter(track=["mytopic"]) #> gets all tweets, which can later be filtered
```

However, I'd like to exclude retweets from the stream. The [Twitter API Streaming documentation](https://developer.twitter.com/en/docs/tweets/filter-realtime/overview) indicates it should be possible to exclude retweets using a filter like:

```py
stream.filter(track=["mytopic -filter:retweets"]) #> doesn't work
```

... however this doesn't work.

I thought maybe I'd need to activate the ["Filtered Stream" lab](https://developer.twitter.com/en/labs), but it still doesn't work.

Please advise.

**Comment by Harmon758** [comment]
Despite the documentation:
> You cannot use the search operators with statuses/filter

https://twittercommunity.com/t/statuses-filter-and-search-operators/115840/2

You can simply check for and filter them out yourself when handling the data/status stream.

**Comment by mansi-aggarwal-2504** [comment]
I'm using Premium Rest API (full archive) to get tweets but I don't want retweets (or replies).
However, -is:retweet is not working.

https://api.twitter.com/1.1/tweets/search/fullarchive/label.json?query=keyword -is:retweets

and I get this message 
{
    "error": {
        "message": "There were errors processing your request: Reference to invalid operator 'is:retweets'. Operator is not available in current product or product packaging. Please refer to complete available operator list at http://t.co/operators. (at position 28)",
        "sent": XXXXXXX,
        "transactionId": "XXXXXX"
    }
}
How to resolve this?
