### ISSUE TITLE
need media_tags param (feature) (improvement)

### ISSUE THREAD

**Issue by u11a0** [tweepy/tweepy#1300]
so users can be tagged in tweets with media using the api
i tried hacking into the scripts to allow the param but nothing happens
maybe something like media_tags=[userid1,userid2]

**Comment by Harmon758** [comment]
I'm not sure what "tagged" means in this context or what method this is about.

**Comment by u11a0** [comment]
tagging users
thought i included it in there

**Comment by u11a0** [comment]
![image](https://user-images.githubusercontent.com/45892778/69999278-4348b380-1526-11ea-8344-fb45fa7ee752.png)

![image](https://user-images.githubusercontent.com/45892778/69999300-5196cf80-1526-11ea-9425-d2bb658c082c.png)

**Comment by Harmon758** [comment]
This is not something Twitter's API supports, and I don't see `media_tags` as a parameter for any existing endpoint.

See https://twittercommunity.com/t/twitter-new-photo-tagging-feature/13023 and https://twittercommunity.com/t/twitter-photo-tagging-feature-api-support/81080.

**Comment by u11a0** [comment]
5 and a half fucking years lmao

also present in update.json using the web client (firefox>network>request>params):
`
media_ids | 1201627275348860928,
media_tags | {"1201627275348860928":[{"type":"user","user_id":"1046101058567778311"}]},
status | test
`

**Comment by u11a0** [comment]
fucking gotem
`api.update_status('test',media_ids=[1201629487735148544],media_tags='{"1201629487735148544":[{"type":"user","user_id":"1046101058567778311"}]}')`
(by adding media_tags as an allowed param)
https://twitter.com/U11a0/status/1201629793558642688
alright last time ill talk about this
i could make a gist that simplifies this process or whatever shit

**Comment by Harmon758** [comment]
Good to know that that's a possible workaround, though I don't think Tweepy should add support for an undocumented part of Twitter's API that's supposed to be unsupported and could break at any time.

**Comment by snowman** [comment]
That's annoying that Twitter API doesn't officially support it, but it's good to know it has a workaround 🎉🎉🎉

I tried to search Google and Twitter API, and come here finally. 

Twitter not mention doesn't support it, that's one part of why I don't like Twitter.
