### ISSUE TITLE
'code': 32, 'message': 'Could not authenticate you.'

### ISSUE THREAD

**Issue by heyJoshLee** [tweepy/tweepy#1302]
I'm getting the above error. My credentials are fine because I can authenticate with another API connected to Twitter. I heard this issue might be because I'm using Phyton 3.8.0. 

Will using a different version of Phyton help? If so, how do I change my Phyton version? (I'm a Ruby guy)

**Comment by AyoubKasmi** [comment]
Same Error

**Comment by Harmon758** [comment]
Double check that your credentials are correct and that your system clock is in sync with NTP.
For more information, see https://developer.twitter.com/en/docs/basics/authentication/guides/authorizing-a-request.

It's unlikely that it has anything to do with your Python (like the snake, not the plant part) version.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by jleewebdev** [comment]
This is the error I'm getting.

```
Traceback (most recent call last):
  File "bot-check.py", line 39, in <module>
    public_tweets = api.home_timeline()
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\binder.py", line 250, in _call
    return method.execute()
  File "C:\Users\Josh\AppData\Local\Programs\Python\Python38\lib\site-packages\tweepy\binder.py", line 233, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 32, 'message': 'Could not authenticate you.'}]
```

I have no problem authenticating using Ruby with the Twitter gem. 

Also, I checked out NTP issue, but I'm really not sure how to address that if that's the problem.

**Comment by Harmon758** [comment]
> Twitter will reject requests which were created too far in the past, so it is important to keep the clock of the computer generating requests in sync with NTP.

Again, double check that you're passing the credentials correctly and that your clock is in sync.

**Comment by SirDave001** [comment]
I also have this error thrown at me. How do fix this?
 File "C:\Users\Sir Dave\AppData\Local\Programs\Python\Python311\Lib\site-packages\tweepy\binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 32, 'message': 'Could not authenticate you.'}]

**Comment by Harmon758** [comment]
Please don't necrobump old closed issues.
This has been answered.
