### ISSUE TITLE
Issues with api.update_with_media

### ISSUE THREAD

**Issue by stanum235** [tweepy/tweepy#1305]
I'm trying to create a bot that copies and modifies text from tweets, and sends it as a reply to the original tweet with an image. 
`import random
import tweepy as tp

auth=tp.OAuthHandler("something", "something else", "http://")
auth.set_access_token("something", "something else" )
api=tp.API(auth)

def uwuify(text):
    new=[]
    r=random.randint(0,1)
    a=" (人◕ω◕)"
    b=" (ㆁᴗㆁ✿)"
    f="~~ "
    g=" uwu ~~"
    for c in text:
        if c=='r' or c=='l'or c=='L' or c=='R':
            new.append('w')
        else:
            new.append(c.lower())
    if r:
        return ''.join([f]+new+[g]+[a])
    else:
        return ''.join([f]+new+[g]+[b])

tweets1=api.user_timeline(screen_name="person")

for tweet in tweets1:
    imag=random.randint(1,4)
    if tweet.text[0:2]!="RT":
        if imag==1:
            api.update_with_media('1.jpg','@person {}'.format(uwuify(tweet.text)),tweet.id)
        elif imag==2:
            api.update_with_media('2.png', '@person {}'.format(uwuify(tweet.text)), tweet.id)
        elif imag==3:
            api.update_with_media('3.png', '@person {}'.format(uwuify(tweet.text)), tweet.id)
        elif imag==4:
            api.update_with_media('4.png', '@person {}'.format(uwuify(tweet.text)), tweet.id)
`
but I keep getting the following error when I run it:

> tweepy.error.TweepError: [{'code': 408, 'message': 'The given URL is invalid.'}]

I'm using PyCharm, and have the images saved in my project file's path. Can someone help solve this please?

**Comment by Harmon758** [comment]
I'm unable to reproduce this.
Can you provide a reproducible example (MCVE/SSCCE) as well as the full traceback?

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
