### ISSUE TITLE
Uploading videos

### ISSUE THREAD

**Issue by ders99** [tweepy/tweepy#1307]
Is there currently any way to upload videos?
I'm trying to upload an mp4 using the following code:

`upload_result = api.media_upload('clip.mp4')`
`api.update_status(status="test tweet", media_ids=[upload_result.media_id_string])`

and getting error:
`tweepy.error.TweepError: Invalid file type for image: video/mp4`

**Comment by Harmon758** [comment]
Duplicate of #640
