### ISSUE TITLE
'Status' object has no attribute 'Cursor'

### ISSUE THREAD

**Issue by KanduriR** [tweepy/tweepy#1308]
Hello, I am trying to read out 10 tweets with the Cursor using search api. But I'm getting an error as - Status object has no attribute 'Cursor':

Here's my code snapshot :

![Snip20191227_1](https://user-images.githubusercontent.com/7806480/71496299-b1269780-28a6-11ea-8463-dad36a6ef9ac.png)

**Comment by Harmon758** [comment]
What is `tw`?

**Comment by KanduriR** [comment]
tw is just a importing name for tweepy.

**Comment by Harmon758** [comment]
According to your traceback, it's a Status object instead.

**Comment by KanduriR** [comment]
So is there some wrong coding here on my part?

**Comment by Harmon758** [comment]
`tw` is a Status object, so yes. Somewhere along the way you must have set it to a Status object, likely through the result of an API method call. Without seeing all your code, it's impossible to determine what or where exactly.

**Comment by KanduriR** [comment]
ohh ok , thank you i needed to understand the error atleast. Its probably from some trials ive been doing that i might have reset it. Will check it thank you.
