### ISSUE TITLE
How to remove link title when post using post_with_media

### ISSUE THREAD

**Issue by c0delite** [tweepy/tweepy#1313]
when i get new DM, i have download and process the image then upload with twit using post_with_media. but after success upload i got a link after twit

here we go https://twitter.com/MenfessWhisper/status/1214579879343034368?s=20

![image](https://user-images.githubusercontent.com/15172470/72140172-bca7b180-33c2-11ea-89a4-6bcb6dc298fe.png)

**Comment by Harmon758** [comment]
Can you show the relevant code? Tweepy does not have a `post_with_media` method.
If you mean [`API.update_with_media`](https://tweepy.readthedocs.io/en/latest/api.html#API.update_with_media), this is likely something you're including in the status itself.

**Comment by c0delite** [comment]
> Can you show the relevant code? Tweepy does not have a `post_with_media` method.
> If you mean [`API.update_with_media`](https://tweepy.readthedocs.io/en/latest/api.html#API.update_with_media), this is likely something you're including in the status itself.

im sorry, my bad. i mean is API.update_with_media

`    def read_dm(self):
        print("Get direct messages...")
        dms = list()
        try:
            api = self.api
            dm = api.list_direct_messages()
            for x in range(len(dm)):
                sender_id = dm[x].message_create['sender_id']
                message = dm[x].message_create['message_data']['text']
                message_data = str(dm[x].message_create['message_data'])
                json_data = _json.encode_basestring(message_data)
                print("Getting message -> "+str(message)+" by sender id "+str(sender_id))

                if "attachment" not in json_data:
                    print("Dm does not have any media...")
                    d = dict(message=message, sender_id=sender_id, id=dm[x].id, media = None)
                    dms.append(d)
                    dms.reverse()

                else:
                    print("Dm have an attachment..")
                    attachment = dm[x].message_create['message_data']['attachment']
                    d = dict(message=message, sender_id=sender_id, id=dm[x].id, media = attachment['media']['media_url'])
                    dms.append(d)
                    dms.reverse()

            print(str(len(dms)) + " collected")
            time.sleep(60)
            return dms

        except Exception as ex:
            print(ex)
            time.sleep(60)
            pass

    def download_image(self,media_url):
        arr = str(media_url).split('\n', 1)
        auth = OAuth1(client_key=constant.CONSUMER_KEY,
                      client_secret=constant.CONSUMER_SECRET,
                      resource_owner_secret=constant.ACCESS_SECRET,
                      resource_owner_key=constant.ACCESS_KEY)
        r = requests.get(media_url, auth=auth)

        with open(arr[9], 'wb') as f:
            f.write(r.content)
        image = Image.open(arr[9])
        image.save("ready.png")
        print("Media downloaded successfully!")

    def post_tweet_with_media(self, message):
        print("Downloading media...")
        filename = 'ready.png'
        # tweet = tweet.replace("https://twitter.com/messages/media/1200393979625263109")
        self.api.update_with_media(filename, status = message )
        os.remove(filename)
        print("Upload with media success!")
`

**Comment by Harmon758** [comment]
Where do you use `post_tweet_with_media` and what is being passed as `message`?

**Comment by c0delite** [comment]
**post_tweet_with_media**
message is string of twit. 
```
from twitter import Twitter
import time

#test pancing ke heroku supaya keluar dyno
#test kedua pancing worker supaya muncul...

tw = Twitter()
def start():
    print("Starting program...")
    dms = list()
    while True:
        if len(dms) is not 0:
            for i in range(len(dms)):
                message = dms[i]['message']
                sender_id = dms[i]['sender_id']
                id = dms[i]['id']


                if len(message) is not 0 and len(message) < 280:
                    if "[whisp]" in message:
                        # message = message.replace("[whisp]", "")
                        if len(message) is not 0:
                            if dms[i]['media'] is None:
                                print("DM will be posted")
                                tw.post_tweet(message)
                                tw.delete_dm(id)
                            else:
                                print("DM will be posted with media")
                                tw.download_image(dms[i]['media'])
                                tw.post_tweet_with_media(message,dms[i]['media_ids'])
                                tw.delete_dm(id)

                        else:
                            print("DM deleted because its empty..")
                            tw.delete_dm(id)


                    else:
                        print("DM will be deleted because does not contains keyword..")
                        tw.delete_dm(id)

            dms = list()

        else:
            print("Direct message is empty...")
            dms = tw.read_dm()
            if len(dms) is 0:
                time.sleep(60)

if __name__ == "__main__":
    start()
```

**Comment by Harmon758** [comment]
You're passing in 2 arguments for `post_tweet_with_media` when only one parameter is expected?

**Comment by c0delite** [comment]
> You're passing in 2 arguments for `post_tweet_with_media` when only one parameter is expected?

sorry code is updated. my coding is fine i have already run but how i can delete link at the end

**Comment by Harmon758** [comment]
Ah, Twitter appends the media URL to the text of the DM object, similar to the way it does for Tweets.
You should be able to use the [entities object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object) in the `message_data`, which should contain the [URL object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object#urls) that has the relevant indices to handle it, in the same way as for Tweets.

**Comment by c0delite** [comment]
so how i can remove the link?

**Comment by Harmon758** [comment]
You can simply use the given indices to remove or replace that portion of the string.

**Comment by c0delite** [comment]
> You can simply use the given indices to remove or replace that portion of the string.

already did. thank you so much
re.sub(r"http\S+", "", str(tweet))
