### ISSUE TITLE
   tweets = api.get_tweets(query = 'Donald Trump', count = 200)  AttributeError: 'TwitterClient' object has no attribute 'get_tweets'

### ISSUE THREAD

**Issue by kumudanarayan** [tweepy/tweepy#1315]
can I get any help for this I have installed all libraries don't know what is  wrong help me if someone knew this

**Comment by kumudanarayan** [comment]
![image](https://user-images.githubusercontent.com/27479566/72305541-148a3500-36af-11ea-967c-2acda6ff333f.png)

**Comment by Harmon758** [comment]
You need to provide the full traceback and all the relevant code.
Neither `TwitterClient` nor a `get_tweets` method are part of Tweepy.
It's not even clear that you're using Tweepy.
For the little code that you have shown, it's not properly indented.
