### ISSUE TITLE
Is it possible to upload videos?

### ISSUE THREAD

**Issue by umar13893** [tweepy/tweepy#1322]
I have tried many methods to upload videos using Tweepy but nothing worked for me. I also looked at other issues.

I am getting this error: Invalid file type for image: video/mp4

**Comment by Harmon758** [comment]
Duplicate of #640

**Comment by MuhBayu** [comment]
Hi, I get the same error

> Invalid file type for image: video/mp4

I use version 3.8.0 of Tweepy
is there any solution?
