### ISSUE TITLE
TweepError.response.text doesn't work

### ISSUE THREAD

**Issue by flamionl** [tweepy/tweepy#1324]
Hi, I'm actually getting trouble to get the api error code , I have seen in the doc that we had to use TweepError.response.text but vscode tells me class TweepError has no 'response' class . I'have downloaded the latest version of tweepy on github
here is the code :
`except TweepError :` 
      `if TweepError.response.text == 326` :
                    `time.sleep(1250)`

**Comment by Harmon758** [comment]
`TweepError.response` is an instance attribute, not a class attribute.
When [handling exceptions](https://docs.python.org/3/tutorial/errors.html#handling-exceptions), you need to add an `as` clause for the instance of the exception.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
