### ISSUE TITLE
ALways the same Tweets

### ISSUE THREAD

**Issue by GGerProg** [tweepy/tweepy#1325]
Hi all, 
I'm trying to download a list of tweet using the standard API but what I get are always the same records.
i.e. this is my request:
"""
ApiSearch = api.search(q="#immigration", lang="en", result_type="mixed", count=100, until=untilDate, include_entities=False)
"""
but if I run it now and then between 1 hour the result I get is the same.

Is there something wrong in the settings of my api.search, or did I misunderstood the limits of the Twitter Standard API?

Thanks for your help,
Giuseppe

**Comment by Harmon758** [comment]
What is `untilDate`? If it's not `None`, it'll only return Tweets before the given date.
See [the documentation for `API.search`](https://tweepy.readthedocs.io/en/latest/api.html#API.search) and [the standard search API](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets).

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by GGerProg** [comment]
> What is `untilDate`? If it's not `None`, it'll only return Tweets before the given date.
> See [the documentation for `API.search`](https://tweepy.readthedocs.io/en/latest/api.html#API.search) and [the standard search API](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets).
> 
> For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

Hi Harmon and thanks for your answer.

I tried to modify the 'until' variable as you suggest but the result is the same. When I insert the result in a DB I get this message:
[23505] ERROR: duplicate key value violates unique constraint "pk_db_tweettable01";
The key is: pk_db_tweetTable01 PRIMARY KEY (tweet_id, user_id).

I don't understand what I'm doing wrong.

Above there is my code:

`conn_str = ("DRIVER={PostgreSQL Unicode};"
    "DATABASE=TwitterLCL;"
    "UID=postgres;"
    "PWD=pswd;"
    "SERVER=localhost;"
    "PORT=5432;")

consumer_key = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
consumer_secret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
access_token = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'
access_token_secret = 'xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx'

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth, wait_on_rate_limit=True)

col_db_tweetTable01 =  ['CREATED_AT', 'TWEET_ID', 'TEXT', 'USER_ID']

i = 0
while i <= 10000:
    time.sleep(2)
    i += 1
    ApiSearch = api.search(q="#immigration", lang="en", result_type="mixed", count=100, until=None, include_entities=False)
    time.sleep(2)
    for res in range(0, len(ApiSearch)):
        db_tweetTable01DB = pd.DataFrame(columns = col_db_tweetTable01) #creates a new dataframe that's empty
        TWEET = json.loads(json.dumps(ApiSearch[res]._json))
        Created_At = None
        Created_At = TWEET.get("created_at")
        print("Created_At : "+Created_At)
        Tweet_Id = None
        Tweet_Id = TWEET.get("id_str")
        Text = None
        Text = TWEET.get("text")
        User_Id = TWEET.get("user").get("id_str")
        db_tweetTable01DB = db_tweetTable01DB.append({'CREATED_AT' : Created_At, 'TWEET_ID' : Tweet_Id, 'TEXT' : Text, 'USER_ID' : User_Id}, ignore_index=True)
        try:
            connStr = pyodbc.connect(conn_str)
            cursor = connStr.cursor()
            for index, row in db_tweetTable01DB.iterrows():
                #print(row)
                cursor.execute("INSERT INTO public.db_tweettable01(CREATED_AT, TWEET_ID, TEXT, USER_ID) values (?, ?, ?, ?)", row['CREATED_AT'], row['TWEET_ID'], row['TEXT'], row['USER_ID'])
                connStr.commit()
            cursor.close()
            connStr.close()
        except pyodbc.Error as ex:
            sqlstate = ex.args[1]
            print(sqlstate)
            print("Tweet_Id : "+Tweet_Id)
            print("User_Id : "+User_Id)
`

**Comment by Harmon758** [comment]
As the documentation says, a "mixed" `result_type` includes both popular and recent results.
You'll want to specify "recent" if you only want the most recent results.
You should also look into using the `since_id` parameter to avoid getting duplicate Tweets.

Also, `Status._json` is already a dictionary representing the raw JSON. Using `json.dumps` and then `json.loads` just converts it to a string and then back and shouldn't have any effect.
You can also just directly use the attributes for the `Status` object as well, rather than the JSON.

**Comment by GGerProg** [comment]
Harmon thanks to your advices, but them don't help me to resolve my issue.
Always get '[23505] ERROR: duplicate key value violates unique constraint "pk_db_tweettable01"' after 100 tweets.

**Comment by Harmon758** [comment]
If you're not using `since_id` to avoid getting duplicate Tweets, then you'll need to perform a check to make sure you're not inserting a duplicate Tweet into your database, either with an upsert, or before the insert.

**Comment by GGerProg** [comment]
Harmon the point is another...what I gain from the request is always the same result, even if I set since_id = 9999999999999999999999.
I want to get different results for the same request made now and between 1 hour, but what I get it's always the same.

**Comment by Harmon758** [comment]
That's not a valid [Twitter ID](https://developer.twitter.com/en/docs/basics/twitter-ids), since it's greater than the range of that of a 64-bit unsigned integer, so Twitter's API likely just ignores the parameter since it's invalid.

**Comment by GGerProg** [comment]
the same is if I use an ID as 200000.
Can you please share with me a script where you use tweepy with standard API and the result you get are always different twitter?

**Comment by Harmon758** [comment]
That's less than any Tweet ID... so every Tweet will be since then.
You need to actually pass the ID that you want Tweets since. 
The purpose of GitHub issues is to report issues with the library, not request scripts as a service.

**Comment by GGerProg** [comment]
Ok, thank you a lot Harmon.
Have a nice day
