### ISSUE TITLE
Rate limit issue? Stops pulling tweets

### ISSUE THREAD

**Issue by aapeebles** [tweepy/tweepy#1326]
An hour and a half before I tried to run this code, I did the exact same thing for Boris Johnson's tweets going back to 2015.It worked fine. Got all 2 thousand tweets. But I run this and it stops at 115 tweets.

I'm not getting any flags about rate limit.
Is my code wrong or something else wrong?

```
import tweepy as tw

auth = tw.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tw.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify=True)

screen_name = "realDonaldTrump"
date_since = "2018-01-01"

donald_tweets = []
 
for tweet in tw.Cursor(api.user_timeline, id=screen_name, tweet_mode='extended', since_id=date_since).items():
    message = tweet.full_text
    if not message.startswith('RT'):
        donald_tweets.append([tweet.created_at, message])
```

**Comment by Harmon758** [comment]
I'm unable to reproduce this:
```py
>>> len(donald_tweets)
1579
```
This is almost certainly an issue with Twitter's API though, possibly relating to [issues with eventual consistency](https://twittercommunity.com/t/user-timeline-returning-unexpected-results/130885), rather than an issue with Tweepy.
