### ISSUE TITLE
Tweet from second account 

### ISSUE THREAD

**Issue by pawelkopka** [tweepy/tweepy#1327]
I can't find function that allow to tweet for another account that are connected to main account, like can be done by tweetdeck.

**Comment by Harmon758** [comment]
I'm not sure what you mean by "that are connected to main account", but you'll have to authenticate with OAuth 1.0a. See https://tweepy.readthedocs.io/en/latest/auth_tutorial.html and https://developer.twitter.com/en/docs/basics/authentication/oauth-1-0a.

**Comment by pawelkopka** [comment]
@Harmon758 I had been added to team account and I want to post on team account using my tweepy and my personal account app.

**Comment by Harmon758** [comment]
The authentication process for the Twitter account linked to the organization developer account should be the same.

**Comment by pawelkopka** [comment]
@Harmon758 yes, but we I update the status I can only this on my presonal account. I don't see any  option to choice on which account should be posted tweet.  Is there opction for that?

**Comment by Harmon758** [comment]
You would need to authenticate with the account that you want to use.
