### ISSUE TITLE
API.user_timeline sometimes returns an empty list

### ISSUE THREAD

**Issue by Nathan-Binkley** [tweepy/tweepy#1329]
I have a program pulling the most recent tweet from a specific user. 

I'm currently using the line 

> word.user_timeline(id = twitter_at , count = 1, tweet_mode='extended')[0]

in order to achieve this goal. I keep having the program crash because the index is out of bounds. This is especially strange because I had it run for a few hours and it worked fine but now (without changing any code), the system crashes with an IndexError after anywhere from 2-20 minutes.

**Comment by Harmon758** [comment]
Per [the documentation for the `count` parameter for the GET statuses/user_timeline endpoint](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline):
> Specifies the number of Tweets to try and retrieve, up to a maximum of 200 per distinct request. The value of *count* is best thought of as a limit to the number of Tweets to return because suspended or deleted content is removed after the count has been applied.

I can't reproduce this issue, but you're very likely encountering this API limitation rather than an issue with the library.

**Comment by Nathan-Binkley** [comment]
No. I'm not having a limitation. I'm only pinging once every 20 seconds for one account on a HIGHLY active twitter account.

**Comment by Harmon758** [comment]
This API limitation would manifest itself as exactly the issue you're describing.

**Comment by petervanness** [comment]
I'm having a similar issue, and it doesn't seem like it's an API limitation because when it throws an exception, my exception handling just continues the loop, and the next time through it runs fine.

**Comment by baylortweepy** [comment]
Has this issue been resolved?  I have the same problem.  I poll private and public twitter accounts.  I have one account that almost without exception returns a NULL object every 5 tries.  I can run it one request per second, per 5 seconds, 30 seconds, 5 minutes, same result.  

All other accounts I query for the last tweet (just requesting the latest tweet and only one tweet from using the tweepy request below:

api.user_timeline(user_id=clientID, count='1')

Any suggestions?  I have to test each response now for "is NULL" and retry when it randomly returns a null for this one single twitter account.

**Comment by baylortweepy** [comment]
does anyone check this board regularly?

**Comment by Harmon758** [comment]
Please don't necrobump old closed issues.
This issue isn't actionable without a reproducible example.
Additionally, the initial issue was likely an instance of #1550, involving eventual consistency issues with Twitter's API and "a HIGHLY active" account.

@petervanness @sgregg85 This issue doesn't involve any exceptions being raised.

@baylortweepy I'm not sure what you mean by "NULL object". The closest Python equivalent would be `None`, but that's not something `API.user_timeline` should be able to return. I'm also not sure what board you're referring to. I check the issues for this repository regularly, but I don't always have enough free time to volunteer to respond to each one immediately.
