### ISSUE TITLE
.xlsx or csv file line break

### ISSUE THREAD

**Issue by casoto62** [tweepy/tweepy#1331]
I get Tweepy to search for tweets and it gets me the result, but when I get the result file it has too many line breaks and blank lines in excel, and incomplete tweets.

How can I fix it?

Thanks,

**Comment by Harmon758** [comment]
I'm not sure what you mean by "result file" and "excel".
Tweets returned by the API are represented as Status objects.

**Comment by casoto62** [comment]
When I exporte tweets to an Excel file or csv file, it comes with too many blank lines.  It seems like certain caracters make the line to brake.  Like (., ´, #, etc)

**Comment by Harmon758** [comment]
That would be an issue with how you're exporting the Tweets rather than an issue with Tweepy.
