### ISSUE TITLE
Streaming: 'NoneType' object has no attribute 'filter' (similar to #1027)

### ISSUE THREAD

**Issue by jessesheidlower** [tweepy/tweepy#1332]
This seems similar to #1027, connected to #1026 and many previous issues, where the error was "'NoneType' object has no attribute 'strip'". I've been having this problem for some time, and my attempt to capture the exception also fail. This is with Tweepy v.3.8 running on Python 3.5. The current code unsuccessfully attempts to relaunch the stream, without a progressive delay for now; earlier versions didn't have the `start_stream` function or the try/except branch but I got the same error. Current code is more or less:

```
class MyStreamListener(tweepy.StreamListener):
   def on_data(self, data):
   # [etc.]

def run():
    # [stuff]
    auth = _get_auth(config)
    api = tweepy.API(auth)

    myListener = MyStreamListener(api)

    def start_stream(stream, **kwargs):
        try:
            stream.filter(**kwargs)
        except Exception:
            stream.disconnect()
            logger.error("Fatal exception")
            start_stream(stream, **kwargs) # TODO: add progressive backoff

    twitterStream = tweepy.Stream(auth=auth, listener=myListener)
    start_stream(twitterStream.sample(is_async=True))
```
After running for some random amount of time--could be hours, could be days--this eventually throws the error:

```
Traceback (most recent call last):
  File "my-bot.py", line 208, in start_stream
    stream.filter(**kwargs)
AttributeError: 'NoneType' object has no attribute 'filter'
```
(line 208 is the `stream.filter(**kwargs)` line in the `try` statement)

I then get the parallel error from the `except` branch `"AttributeError: 'NoneType' object has no attribute 'disconnect'`.

Happy to supply any additional information. Would be grateful for a solution.

**Comment by Harmon758** [comment]
This is not an issue with the library, but rather because the `stream` you define in your code is `None`.
Hence the error telling you that `None` doesn't have a `filter` or `disconnect` attribute.
`Stream.sample` doesn't return anything (i.e. returns `None`), so when you pass it to `start_stream`, you're passing `None` as `stream`.
