### ISSUE TITLE
tweepy.StreamListener on_status created_at field sometimes giving future date

### ISSUE THREAD

**Issue by manish-singh-accrete-ai** [tweepy/tweepy#1333]
Hi, 
I am using tweepy streaming service and have this code. Sometimes created_at field is giving future date. What could be issue!
------------------------------------------------------------------------------------------------------------

class TweetStreamHandler(tweepy.StreamListener):
	def on_status(self, status):
        #log = logging.getLogger("app." + __name__)
        if hasattr(status, "retweeted_status"):      # checking if tweet is retweet
            pass
        else:
            try:
                if hasattr(status, 'extended_tweet'):
                    text = status.extended_tweet["full_text"]  # if the tweet has extended text mode - get full tweet
                else:
                    text = status.text
                    **created_at = str(status.created_at)  #sometimes created_at is giving future date**
                    log.info('tweet time %s',created_at)
                    tweet_dt = datetime.strptime(created_at, '%Y-%m-%d %H:%M:%S')
                    current_dt = datetime.now()
                    if not (tweet_dt.year > current_dt.year or tweet_dt.month > current_dt.month
                            or tweet_dt.day > current_dt.day):
                        log.info('date condition fullfilled')
                        id_str = status.id_str
                        username = status.author.screen_name
                        followers_count = status.author.followers_count
                        link = 'https://twitter.com/' + username + '/status/' + id_str
                        article_source = 'https://twitter.com/' + username
                        api_data = {
                            "articleDate": created_at,
                            "title": text,
                            "scrapperDetails": {
                                "contents": text
                            },
                            "link": link,
                            "articleSource": article_source,
                            "appSource": "TWITTER_STREAM",
                            "followers": str(followers_count)
                        }

                        retval = ProcessCSV.call_api(api_data, config)
                        log.info(retval)
            except AttributeError:
                text = status.text                         # just take a normal text of the tweet
                print(text)                                # print the tweet
            return True

**Comment by Harmon758** [comment]
`created_at` is the:
> UTC time when this Tweet was created

https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object

If you're in a time zone with a negative UTC offset, then obviously, the UTC time will always be ahead of the time in your time zone and any recent Tweet might show a timestamp in UTC that your time zone hasn't reached yet.
