### ISSUE TITLE
Incorrect function documentation in streaming.py

### ISSUE THREAD

**Issue by khaleelsyed** [tweepy/tweepy#1337]
The Documentation page for Disconnect messages for the Streaming API has been changed to: https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/streaming-message-types

https://github.com/tweepy/tweepy/blob/78d2883a922fa5232e8cdfab0c272c24b8ce37c4/tweepy/streaming.py#L125-L131

**Comment by Harmon758** [comment]
This was already resolved with #1071 in v3.8.0.
The commit for the linked code is over five years old now.
In the future, please make sure you're looking at/using the latest development version when reporting issues.
