### ISSUE TITLE
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='formulae.brew.sh', port=443)

### ISSUE THREAD

**Issue by sivakris14** [tweepy/tweepy#1343]
hope help  some one could help here

**Comment by Harmon758** [comment]
This doesn't even seem to be related to Tweepy, as it's an error connecting to `formulae.brew.sh`.
Regardless, this doesn't provide any information beyond that it's a connection issue.
You'll need to provide the full traceback and any relevant code if you want anyone to be able to help you.
