### ISSUE TITLE
Developer Labs / next Twitter API

### ISSUE THREAD

**Issue by andypiper** [tweepy/tweepy#1345]
Hello from Twitter Developer Relations!

We really appreciate the Tweepy team and community for building on our API, and for supporting our developers! You, and many projects like this one, are among the reasons why Twitter data is much-appreciated by developers. We historically haven't built libraries and SDKs - the communities, YOU, have done so - and I'm here to tell you how much we appreciate that, and that we know you're around! Tweepy is hugely popular, and we recognise that history and background.

We're currently building a brand new API platform that (over time) will replace the current one. I would love to connect with you on any plans to add support for Twitter Developer Labs! We're looking to be much more focused on proper API versioning, and are basing our specification on OpenAPI.

As we hope you know, we do list tweepy on our developer libraries page https://developer.twitter.com/en/docs/developer-utilities/twitter-libraries and we would really love to continue to do so as you continue to help the Python community. Do you have any plans to support the latest Labs APIs as they will eventually replace the existing ones? 

Thank you, again!

**Comment by Harmon758** [comment]
I'm going to close this in favor of #1472, now that Twitter API v2 has been launched.
I greatly appreciate the support and encouragement, and I apologize for the delay in responding.
As for supporting any other current or future Labs endpoints, I've added that as an addendum to #1472 for now.
