### ISSUE TITLE
Tweepy documentation does not specify that OAuth 1a is required for Streaming

### ISSUE THREAD

**Issue by halmartin** [tweepy/tweepy#1346]
I have been reading the [Tweepy documentation](http://docs.tweepy.org/en/latest/index.html) as I try to use it for a new project.

As it wasn't clear to me what the difference between OAuth 1a and OAuth 2 authentication mechanisms is, I opted to use OAuth 2 as it involved fewer steps. Great success followed, I was able to search for users, hashtags, etc.

However, when trying to stream, I was consistently getting 401 errors from Twitter. There are existing issues surrounding Tweepy and 401 errors, such as #877.

Eventually I decided to try another python library for streaming, as I had already double checked that the system time was set to UTC and synced with NTP with a drift of <5 minutes. That's when I started reading [Twython's documentation](https://twython.readthedocs.io/en/latest/usage/streaming_api.html) and stumbled across this:

> The Streaming API requires that you have OAuth 1 authentication credentials.

I changed my Tweepy authentication to use OAuth 1a, and magically the Streaming API works.

I went back and reviewed Tweepy's [authentication documentation](http://docs.tweepy.org/en/latest/auth_tutorial.html) and [streaming documentation](http://docs.tweepy.org/en/latest/streaming_how_to.html), and nowhere do I see it mentioned that Streaming is only possible using OAuth 1a authentication.

It would be very nice to add this warning to your documentation, as Twython has done. Knowing this in advance would have saved me untold hours of debugging and hair pulling.

**Comment by philipthomasme** [comment]
Also took me way too long to figure this out. Thanks for the hint.

**Comment by Harmon758** [comment]
With https://github.com/tweepy/tweepy/commit/c9f59e680f17412522206d0999bf9f5ac7788f2f, this should no longer be necessary, with all the credentials being required arguments.

**Comment by Dounia-Khechab** [comment]
How can i now the version of OAuth streaming installed on my pc?

**Comment by Harmon758** [comment]
Please don't necrobump old closed issues.
I'm not sure what you mean by "the version of OAuth streaming installed".
You can check your version of Tweepy using [`pip show`](https://pip.pypa.io/en/stable/cli/pip_show/) or by checking `tweepy.__version__`.
