### ISSUE TITLE
search method is 2 hours late

### ISSUE THREAD

**Issue by mzalevski** [tweepy/tweepy#1355]
Hi, the `search` method is giving me 2 hours late results, e.g. at 19:00 -> search("xyz", result_type="recent") and the most recent result I am getting back is dated exactly at 17:00 (whereas the same query in the twitter UI returns tweets from 19:00, 18:59 and so on). I tried to change my OS timezone and twitter location settings. It didn't help. Any ideas how to fix this? :)

**Comment by MichaelCurrin** [comment]
All the times of tweets are at UTC ie GMT +0000. You can see this in the time string. So even if adjust your settings or someone posts from anywhere it will always be at that time zone.

If you turn that into a datetime object that is time zone aware, you can then do calculations (eg current day) or represent time using your local time.

**Comment by MichaelCurrin** [comment]
I cover how to parse it here

https://michaelcurrin.github.io/python-twitter-guide/#/code_snippets?id=handle-time-values

**Comment by mzalevski** [comment]
@MichaelCurrin thanks a lot! I've parsed the datetime object to string too soon and didn't see the timezone. The parsing function will help too :)

**Comment by Harmon758** [comment]
If the time in question was from the `created_at` attribute, see also [the documentation for Tweet objects](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object).
