### ISSUE TITLE
Tweepy module inactive during specific time gap

### ISSUE THREAD

**Issue by iammarco11** [tweepy/tweepy#1356]
Hello,

I have no clue why this issue is arising. My script does not run from 12:30 - 06:30 AM approx (IST). But the script works totally fine other time durations.

**Comment by MichaelCurrin** [comment]
What does your script do? If its reacting to people in your country, that sounds like a time for people to be asleep.
If it's running a task say hourly, it sounds like your machine if off/asleep at night especially if network gets turned of even though the machine is still on.
Get any script to run on the same cycle such as printing the current time and logging to a file and you might find that even that won't work when your machine is off.

**Comment by joshthecoder** [comment]
Would need to see some code that reproduces the issue to be of any help. Closing for now feel free to reopen if you can share code that shows a bug in Tweepy. If you are needing help with an issue unrelated to a bug in Tweepy please ask in our Discord server instead.
