### ISSUE TITLE
api.search()  ->Untill parameter is not giving the right output

### ISSUE THREAD

**Issue by vrawat1806** [tweepy/tweepy#1360]
Hey, in the below mentioned code, the "tweet_created_at" column, the output of the same (date duration) is not as per the command i have given to the search api. The output is of the most recent tweets.

%%Code%%
import pandas as pd
import tweepy 

consumer_key = r"XXXXXXXXXXXXXXXXXXXXXXXXX"
consumer_secret = r"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
access_token = r"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
access_token_secret = r"XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" 

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

hastag_phrase = "covid19"

all_tweets_info = tweepy.Cursor(api.search, q = hashtag_phrase, untill = "2020-05-07").items(100)

searched_tweets = [status for status in all_tweets_info]

df =  pd.DataFrame(columns = "tweet_created_at")

for tweet in searched_tweets: 
    df = df.append({ 'tweet_created_at' : tweet.created_at})

df.tweet_created_at

FYI 
I am using the free version of API. Please resolve the issue.

**Comment by MichaelCurrin** [comment]
`until` not `untill`

**Comment by Harmon758** [comment]
For code block usage, see https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks.
