### ISSUE TITLE
user_timeline() fails with @realDonaldTrump

### ISSUE THREAD

**Issue by JINHXu** [tweepy/tweepy#1361]
Hey there,

I was trying to download tweets from different users with user_time(). When I try with @realDonaldTrump, the number of tweets I was able to collect varies drastically every time the code was run.
While for any other accounts that also tweets frequently(probably not as frequently as Trump, but still, frequent), the numbers stay stable.  And this also happened to some other people I know.
I'm not sure if this is a technical issue. Does anyone have an idea why this abnormal behavior?

-------update---------------

**This issue is still unresolved**, the conversation below is **irrelevant** to the issue. Still looking forward to an idea. :D

Best,
Xu

**Comment by MichaelCurrin** [comment]
I haven't heard of that issue. 

Can you reproduce with text output or screenshot. E.g. run the script multiple times and get 10 tweets one time and 30 another and 15 another.

A code sample would help too, to see if you're paging, what your count is, if you're limiting by ID or date...

**Comment by JINHXu** [comment]
The code to download tweets(up to 3200 tweets ):

`def download_tweets(screen_name, keys, max_tweets=None):
    """Download all tweets of Twitter user with given screen_name.

    Parameters:
    -----------
    screen_name:  The screen name of the twitter user
    keys:         An object (or package) with four members,
                    consumer_key, consumer_secret,
                    access_token, access_secret
                  each holding respective OAuth authorization key.
    max_tweets:   Maximum number of tweets to download. If None, all
                  tweets (as much as Twitter allows) should be
                  downloaded.
    Returns:
    ----------
    tweets:       A list of dictionaries containing all the information
                  downloaded from Twitter for each tweet.
    """
    # list of dictionaries containing all the information downloaded from Twitter for each tweet to be returned
    dicts = []

    # tweepy initialization
    auth = tweepy.OAuthHandler(keys.consumer_key, keys.consumer_secret)
    auth.set_access_token(keys.access_token, keys.access_secret)

    try:
        api = tweepy.API(auth, wait_on_rate_limit=True)

        if max_tweets is None:
            max_tweets = float('inf')

        tweets = api.user_timeline(
            screen_name=screen_name, tweet_mode='extended', count=200)

        # temporary list of tweets(dictionaries) storing all tweets including retweets and replies, the id of the last element in this list will be used for while-loop control
        tmp = []

        for tweet in tweets:
            tmp.append(tweet._json)
            if accepted_tweet(tweet._json):
                dicts.append(tweet._json)
                if len(dicts) >= max_tweets:
                    return dicts

        # save the id of the oldest tweet less one
        oldest = tmp[-1]['id'] - 1

        # keep grabbing tweets until no more left to grab or reaching max_tweets set by user
        while len(tweets) > 0:
            tweets = api.user_timeline(
                screen_name=screen_name, tweet_mode='extended', count=200, max_id=oldest)
            for tweet in tweets:
                tmp.append(tweet._json)
                if accepted_tweet(tweet._json):
                    dicts.append(tweet._json)
                    if len(dicts) >= max_tweets:
                        return dicts

            # update oldest
            oldest = tmp[-1]['id'] - 1

        return dicts

    except RateLimitError:
        print("A rate limits error occured!")
`

With another function print statistics of the tweets downloaded and command line params setti.

Five continuous runs of the code(max_tweets set to None, passing user_name through commandline):
`python /Users/xujinghua/a1-birch-and-xu/a1.py 'realDonaldTrump' --stats True
The number of tweets is: 1186
The minimum number of tokens is: 3
The maximum number of tokens is: 76
The average number of tokens is: 31.741989881956155
Average number of menions is: 0.3650927487352445
Average number of hashtags is: 0.09949409780775717
Average number of retweets is: 23578.506745362563
Average number of times the tweets were favorited is: 109685.81281618887
The first tweet in the list was created at: Thu Jan 23 16:15:29 +0000 2020
The last tweet in the list was created at: Sat May 09 19:14:37 +0000 2020
python /Users/xujinghua/a1-birch-and-xu/a1.py 'realDonaldTrump' --stats True
The number of tweets is: 153
The minimum number of tokens is: 3
The maximum number of tokens is: 70
The average number of tokens is: 32.15686274509804
Average number of menions is: 0.35947712418300654
Average number of hashtags is: 0.058823529411764705
Average number of retweets is: 25362.830065359478
Average number of times the tweets were favorited is: 117902.4248366013
The first tweet in the list was created at: Fri Apr 24 14:59:05 +0000 2020
The last tweet in the list was created at: Sat May 09 19:14:37 +0000 2020
python /Users/xujinghua/a1-birch-and-xu/a1.py 'realDonaldTrump' --stats True
The number of tweets is: 1186
The minimum number of tokens is: 3
The maximum number of tokens is: 76
The average number of tokens is: 31.741989881956155
Average number of menions is: 0.3650927487352445
Average number of hashtags is: 0.09949409780775717
Average number of retweets is: 23578.631534569984
Average number of times the tweets were favorited is: 109682.69898819561
The first tweet in the list was created at: Thu Jan 23 16:15:29 +0000 2020
The last tweet in the list was created at: Sat May 09 19:14:37 +0000 2020
python /Users/xujinghua/a1-birch-and-xu/a1.py 'realDonaldTrump' --stats True
The number of tweets is: 1186
The minimum number of tokens is: 3
The maximum number of tokens is: 76
The average number of tokens is: 31.741989881956155
Average number of menions is: 0.3650927487352445
Average number of hashtags is: 0.09949409780775717
Average number of retweets is: 23578.697301854976
Average number of times the tweets were favorited is: 109686.54300168634
The first tweet in the list was created at: Thu Jan 23 16:15:29 +0000 2020
The last tweet in the list was created at: Sat May 09 19:14:37 +0000 2020
python /Users/xujinghua/a1-birch-and-xu/a1.py 'realDonaldTrump' --stats True
The number of tweets is: 1015
The minimum number of tokens is: 3
The maximum number of tokens is: 74
The average number of tokens is: 32.11724137931034
Average number of menions is: 0.37635467980295567
Average number of hashtags is: 0.10738916256157635
Average number of retweets is: 23949.189162561575
Average number of times the tweets were favorited is: 110903.39014778326
The first tweet in the list was created at: Fri Feb 07 12:47:41 +0000 2020
The last tweet in the list was created at: Sat May 09 19:14:37 +0000 2020
 `

**Comment by JINHXu** [comment]
in the case of a regular account:

`
python /Users/xujinghua/a1-birch-and-xu/a1.py 'Lagarde' --stats True
The number of tweets is: 1402
The minimum number of tokens is: 5
The maximum number of tokens is: 64
The average number of tokens is: 27.16690442225392
Average number of menions is: 0.35306704707560627
Average number of hashtags is: 0.6590584878744651
Average number of retweets is: 111.30456490727532
Average number of times the tweets were favorited is: 251.84165477888732
The first tweet in the list was created at: Wed May 25 09:43:09 +0000 2011
The last tweet in the list was created at: Sat May 09 10:00:00 +0000 2020

python /Users/xujinghua/a1-birch-and-xu/a1.py 'Lagarde' --stats True
The number of tweets is: 1402
The minimum number of tokens is: 5
The maximum number of tokens is: 64
The average number of tokens is: 27.16690442225392
Average number of menions is: 0.35306704707560627
Average number of hashtags is: 0.6590584878744651
Average number of retweets is: 111.30456490727532
Average number of times the tweets were favorited is: 251.84165477888732
The first tweet in the list was created at: Wed May 25 09:43:09 +0000 2011
The last tweet in the list was created at: Sat May 09 10:00:00 +0000 2020

python /Users/xujinghua/a1-birch-and-xu/a1.py 'Lagarde' --stats True
The number of tweets is: 1402
The minimum number of tokens is: 5
The maximum number of tokens is: 64
The average number of tokens is: 27.16690442225392
Average number of menions is: 0.35306704707560627
Average number of hashtags is: 0.6590584878744651
Average number of retweets is: 111.30456490727532
Average number of times the tweets were favorited is: 251.84165477888732
The first tweet in the list was created at: Wed May 25 09:43:09 +0000 2011
The last tweet in the list was created at: Sat May 09 10:00:00 +0000 2020

python /Users/xujinghua/a1-birch-and-xu/a1.py 'Lagarde' --stats True
The number of tweets is: 1402
The minimum number of tokens is: 5
The maximum number of tokens is: 64
The average number of tokens is: 27.16690442225392
Average number of menions is: 0.35306704707560627
Average number of hashtags is: 0.6590584878744651
Average number of retweets is: 111.30456490727532
Average number of times the tweets were favorited is: 251.84165477888732
The first tweet in the list was created at: Wed May 25 09:43:09 +0000 2011
The last tweet in the list was created at: Sat May 09 10:00:00 +0000 2020

python /Users/xujinghua/a1-birch-and-xu/a1.py 'Lagarde' --stats True
The number of tweets is: 1402
The minimum number of tokens is: 5
The maximum number of tokens is: 64
The average number of tokens is: 27.16690442225392
Average number of menions is: 0.35306704707560627
Average number of hashtags is: 0.6590584878744651
Average number of retweets is: 111.30456490727532
Average number of times the tweets were favorited is: 251.84165477888732
The first tweet in the list was created at: Wed May 25 09:43:09 +0000 2011
The last tweet in the list was created at: Sat May 09 10:00:00 +0000 2020`

**Comment by MichaelCurrin** [comment]
I was able to reproduce your issue. I don't have a solution.

I ran for `realDonaldTrump` and got close to 2000 tweets, then again 1595 tweets. I ran for `Lagarde` and got 1815 tweets twice in a row.

**Comment by MichaelCurrin** [comment]
A side note - your Tweepy logic is not typical and ends up being long and complicated. 

Avoid using `tweet._json` as then you have to deal with the JSON structure. Tweepy makes attributes available to you - see [attributes](https://michaelcurrin.github.io/python-twitter-guide/#/models?id=status).

You can save yourself handling IDs and a max by using Cursor - my [guide](https://michaelcurrin.github.io/python-twitter-guide/#/code_snippets?id=paging) and follow the link through to Tweepy docs Cursor tutorial.
And my [Get tweets](https://michaelcurrin.github.io/python-twitter-guide/#/code_snippets?id=get-tweets) guide specifically for getting tweets for a user. 

Here is a sample for you, based on what testing I did. Note I left `.items()` empty but could have set `.items(300)` to restrict it.

```python
    screen_name = "realDonaldTrump"

    cursor = tweepy.Cursor(
        api.user_timeline,
        screen_name=screen_name,
        user_id=user_id,
        count=200,
        tweet_mode="extended",
    )

    for i, tweet in enumerate(cursor.items()):
        print(i + 1, tweet.full_text)
```

You can also avoid catching the Rate limit error by using [waiting](https://michaelcurrin.github.io/python-twitter-guide/#/auth?id=add-waiting) params.

**Comment by MichaelCurrin** [comment]
Also lookup markdown cheatsheet

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

Your single backticks can be replaced with triple


    `
    This will not work
    `

    ```
    This is the way
    ```

    ```python
    Customize the language!
    ```

**Comment by JINHXu** [comment]
> Avoid using `tweet._json` as then you have to deal with the JSON structure. Tweepy makes attributes available to you - see [attributes](https://michaelcurrin.github.io/python-twitter-guide/#/models?id=status).
> 

My task was to save the tweets to a JSON file, so I kinda have to deal with JSON. 😅
But the Python Twitter Guide is great! Thanks!



> You can save yourself handling IDs and a max ID by using Cursor in Tweepy - see my [Paging guide](https://michaelcurrin.github.io/python-twitter-guide/#/code_snippets?id=paging) and follow the link through to Tweepy doc's Cursor tutorial.
> And my [Get tweets](https://michaelcurrin.github.io/python-twitter-guide/#/code_snippets?id=get-tweets) guide specifically for getting tweets for a user, with increasing levels of compleity.
> 
> Here is a sample for you, based on what testing I did. Note I left `.items()` empty but could have set `.items(300)` to restrict it.
> 
> ```python
>     screen_name = "realDonaldTrump"
> 
>     cursor = tweepy.Cursor(
>         api.user_timeline,
>         screen_name=screen_name,
>         user_id=user_id,
>         count=200,
>         tweet_mode="extended",
>     )
> 
>     for i, tweet in enumerate(cursor.items()):
>         print(i + 1, tweet.full_text)
> ```
> 

cursor object is cool, thanks for the heads up!

> You can also avoid catching the Rate limit error by using [waiting](https://michaelcurrin.github.io/python-twitter-guide/#/auth?id=add-waiting) params.

I have the waiting parameter😅, but again, thanks for sharing the documentation, it's great!

**Comment by MichaelCurrin** [comment]
You're welcome.

The extra waiting parameter I suggested is specifically to _notify_ you on the console rather than wait silently.

**Comment by JINHXu** [comment]
Ah, thanks!

**Comment by francis-de-ladu** [comment]
I'm also experiencing this issue, getting a different number of tweets when repeatedly making the same request with user realDonaldTrump.

**Comment by Harmon758** [comment]
The number of results per page/request to [GET statuses/user_timeline](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline) is not guaranteed to be consistent and in fact, [possibly subject to issues with eventual consistency](https://twittercommunity.com/t/user-timeline-returning-unexpected-results/130885). This is likely causing you to have retrieved a different number of Tweets when you hit the rate limit or even possibly retrieved a page with no results prior to that happening. I'd recommend that you use a cursor instead.
See https://tweepy.readthedocs.io/en/latest/cursor_tutorial.html.

For code block usage, see https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks.

**Comment by francis-de-ladu** [comment]
> I'm also experiencing this issue, getting a different number of tweets when repeatedly making the same request with user realDonaldTrump.

I'm actually using a cursor to send the requests, with 100 tweets per page. Also, the problem randomly happens (more than half the time) even if no requests have been sent before.

**Comment by Harmon758** [comment]
This is almost certainly an issue with Twitter's API rather than Tweepy. You could make a forum post about it, but it's more than likely an eventual consistency issue.

**Comment by keikoang** [comment]
I also have the same issue even with the use of Cursor. Is there a fix yet? Thank you.

**Comment by JINHXu** [comment]
> I also have the same issue even with the use of Cursor. Is there a fix yet? Thank you.

not yet, but as discussed above, this is most likely an issue with Twitter's API rather than Tweepy.
