### ISSUE TITLE
on_delete events not triggered

### ISSUE THREAD

**Issue by pellski** [tweepy/tweepy#1363]
The on_delete event is not triggered upon deleting a tweet.

The on_event function inside should call on_delete, however, debugging this showed that on_event was also not triggered.
https://github.com/tweepy/tweepy/blob/b8871487f3060c0225a9dfd1098bbeaff8dfcd06/tweepy/streaming.py#L58

The severity of this is quite high, as users utilizing the on_delete event are not aware of this issue, and are therefore failing GDPR and twitter's own terms of service.

**Comment by pellski** [comment]
It looks as though this may be an API issue. I will contact the Twitter Developer community for a response.

https://twittercommunity.com/t/not-receiving-delete-events-on-filter-stream-is-there-any-alternate-way-to-consume-delete-events/82415/2

**Comment by Harmon758** [comment]
Twitter's API stopped delivering compliance events for the statuses/filter and statuses/sample endpoints last year.
See https://twittercommunity.com/t/removing-compliance-events-from-statuses-filter-and-statuses-sample-endpoints/131946.
