### ISSUE TITLE
Stop retweeting blocked acccounts.

### ISSUE THREAD

**Issue by humblelad** [tweepy/tweepy#1365]
Is there a way to stop retweeting blocked accounts(which was done manually). In the sense, it should not retweet if the user id is in the block list. Any help appreciated. .: :)

**Comment by humblelad** [comment]
@MichaelCurrin Can you help with the query?

**Comment by MichaelCurrin** [comment]
@humblelad Is your blocked list stored in your application or in Twitter?

For the latter try

```python
blocked_users = api.blocks()
```

Then you can get `user.id` or `user.screen_name` on the result. 

You might want to get the blocked list at application start (to save regularly checking) and then reuse it for your retweeting.

http://docs.tweepy.org/en/latest/api.html#API.blocks

**Comment by humblelad** [comment]
@MichaelCurrin https://github.com/humblelad/HashTagger-Twitter-Bot/blob/master/hashtagger.py Here is the sample code. I want to stop retweeting accounts which I blocked manually via twitter to stop spams.

**Comment by Harmon758** [comment]
As explained, you can use [`API.blocks`](https://tweepy.readthedocs.io/en/latest/api.html#API.blocks) or [`API.blocks_ids`](https://tweepy.readthedocs.io/en/latest/api.html#API.blocks_ids) and check against the IDs of the users you have blocked, using the `user` attribute of the Status/[Tweet object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object) and the `id` attribute of the [User object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/user-object).
