### ISSUE TITLE
DM's not working

### ISSUE THREAD

**Issue by SortOfThePythonRuler** [tweepy/tweepy#1366]
Hi, I'm pretty new to the tweepy library so and my journey to find the answer online wasn't that successful so I would be very thankful if anyone here could help me:
I want to see the DM's that people sent me but it gives me a weird error I could not solve
(the keys are in the code and they work with update status)

```
# import library
import tweepy

# login details
CONSUMER_KEY = ""
CONSUMER_SECRET = ""
ACCESS_KEY = ""
ACCESS_SECRET = ""

# login twitter
auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_KEY, ACCESS_SECRET)

# auth
api = tweepy.API(auth)

# get and print the messages
content = api.direct_messages()
print(content)
```

and this is the error:

`tweepy.error.TweepError: [{'code': 34, 'message': 'Sorry, that page does not exist.'}]`

**Comment by bpluly** [comment]
You need to use list_direct_messages() which gets all DMs for the last 30 days.
To get them as events you have to use the AccountActivity api.

**Comment by RasPiPkr** [comment]
Hi,

I'm having problems with list_direct_messages() function and I'm using the standard account for twitter api.

I'm using version 3.8.0 and I've tested by logging into twitter to see and reply to DM's but can not get it through using tweepy.

I get this error:
tweepy.error.TweepError: [{'code': 93, 'message': 'This application is not allowed to access or delete your direct messages.'}]

**Comment by AFirouzi** [comment]
Hi @RasPiPkr 

I am not quite sure that your problem is related to tweepy. so let's do it step by step. in app permissions on your developer account, could you please check that your permissions have been set like this:
![image](https://user-images.githubusercontent.com/5881793/82740948-cc121080-9d4d-11ea-94e3-8a38df02ed55.png)

**Comment by RasPiPkr** [comment]
I will admit at first it was set to read and write but I changed it earlier just after I had posted my issue. It's still the same as below:
>>> spuggie_API.list_direct_messages()
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    spuggie_API.list_direct_messages()
  File "C:\Program Files\Python38\lib\site-packages\tweepy\binder.py", line 250, in _call
    return method.execute()
  File "C:\Program Files\Python38\lib\site-packages\tweepy\binder.py", line 233, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 93, 'message': 'This application is not allowed to access or delete your direct messages.'}]

**Comment by RasPiPkr** [comment]
Exception in Tkinter callback
Traceback (most recent call last):
  File "C:\Program Files\Python38\lib\tkinter\__init__.py", line 1883, in __call__
    return self.func(*args)
  File "C:\Users\Owner\Desktop\Spuggie\SpuggieApp.py", line 238, in showMessage
    messagePull = spuggie_API.get_direct_message(idNum)
  File "C:\Program Files\Python38\lib\site-packages\tweepy\binder.py", line 250, in _call
    return method.execute()
  File "C:\Program Files\Python38\lib\site-packages\tweepy\binder.py", line 233, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 34, 'message': 'Sorry, that page does not exist.'}]

That is my current fault code I'm getting as it only happens when I'm trying to do get or list direct messages

**Comment by AFirouzi** [comment]
@RasPiPkr Could you please share your code here? or email me? I'm using the same methods and I don't have any problem.

**Comment by RasPiPkr** [comment]
I’ve figured it out, the documents refer to get_direct_message(id)
I thought it was after the user id of messages from or to
It’s after the message id

**Comment by RasPiPkr** [comment]
I can't see anywhere to close my issue, many thanks for the help and replies.

**Comment by Harmon758** [comment]
@SortOfThePythonRuler You're using an outdated version of Tweepy.
`API.direct_messages` was replaced with [`API.list_direct_messages`](https://tweepy.readthedocs.io/en/latest/api.html#API.list_direct_messages) in #1228 with Tweepy v3.8.0.

@RasPiPkr None of your issues are related to this issue.
See [Twitter's API documentation for app permissions](https://developer.twitter.com/en/docs/basics/apps/guides/app-permissions).
As it says:
> If a permission level is changed, any user tokens already issued to that Twitter app must be discarded and users must re-authorize the app in order for the token to inherit the updated permissions.

See also [the documentation for `API.get_direct_message`](https://tweepy.readthedocs.io/en/latest/api.html#API.get_direct_message).

This isn't your issue, so you're unable to close it.

For code block usage, see https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks.

**Comment by SortOfThePythonRuler** [comment]
who are you?

בתאריך יום ה׳, 2 ביולי 2020, 6:27, מאת Harmon ‏<notifications@github.com>:

**Comment by Harmon758** [comment]
I am a member of [Tweepy](https://github.com/tweepy) and the one who primarily maintains the library these days.
I'm not sure why you're asking this though.
