### ISSUE TITLE
Exclude certified accounts from api.search ?

### ISSUE THREAD

**Issue by Underbrine** [tweepy/tweepy#1367]
Hello there,
I want to know if there is a way to exclude the certified accounts from the search method.
Thanks for the replies !

**Comment by MichaelCurrin** [comment]
First search result for "Twitter search verified"

https://stackoverflow.com/questions/4268193/how-do-i-search-twitter-for-posts-by-verified-accounts-only

You can use `filter:verified #python`

Or on a fetched tweet `tweet.author.verified is True`

**Comment by Harmon758** [comment]
`filter:verified` is undocumented outside of [some documentation for TweetDeck](https://help.twitter.com/en/using-twitter/advanced-tweetdeck-features), but it does work.
As for the negation operator, see [the documentation for standard search operators](https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators).
