### ISSUE TITLE
Blocking when searching with a "too old" max_id

### ISSUE THREAD

**Issue by Sailoriae** [tweepy/tweepy#1370]
Hello,
First of all, sorry if my english is a bit weird.

I have the following code : 
```
for tweet in tweepy.Cursor( api.search,
                            q = "#Minecraft",
                            tweet_mode = "extended",
                            max_id = 1257574945175080965 ).items( 20 ) :
    print( tweet.id )
```
When `max_id` is set with a recent tweet, I get 20 tweets older than this one. Fine.
But when this `max_id` is too old, like in my example code, I get nothing.

And I don't understand why.
Is it a bug ? Or is there somthing I didn't read ?
In the second case : How to get older tweets ?

In advance, thank you for an answer, and have a nice day ! ^^

PS : I'm using Tweepy 3.8.0 with Python 3.7.4.

**Comment by MichaelCurrin** [comment]
Hi. Twitter search API only gives tweets back a week ("6 to 9 days" according to doc). Regardless of setting a date range or max ID.

You need to use a browser-based scraping approach for historical data 

https://michaelcurrin.github.io/python-twitter-guide/#/browser_scraping?id=browser-scraping-tools

Or get on the premium plan for Twitter API

**Comment by MichaelCurrin** [comment]
For tweets in the past week set `count=100` and `.items()` without an argument. Then you can get all available and using max tweets allowed per page. Default is 20

**Comment by Sailoriae** [comment]
Okaaay, I understand now. Thank you very much @MichaelCurrin for your answer.
Have a nice day ! ^^

**Comment by Harmon758** [comment]
The [standard search API](https://developer.twitter.com/en/docs/tweets/search/overview/standard)
> searches against a sampling of recent Tweets published in the past 7 days.

Scraping Twitter itself outside of the API is against its [Terms of Service](https://twitter.com/en/tos) and [Automation Rules](https://help.twitter.com/en/rules-and-policies/twitter-automation).

You'll have to use a premium or enterprise API if you want access to older Tweets.
