### ISSUE TITLE
Update with media alternative way

### ISSUE THREAD

**Issue by oGabrielArruda** [tweepy/tweepy#1372]
Hey! Does `API.Update_with_media() ` works? I'm trying to reply tweets that have mentioned my profile, but isn't work. My profile send the tweet with image, but not as a reply and just as a normal tweet.

If the method is deprecated, is there another way to reply tweets with a image?

```
def reply_tweet(tweet, message, img):
    api.update_with_media(img, message, in_reply_to_status_id = tweet.id)
    store_last_seen(FILE_NAME, tweet.id)
```

```
def main():
    tweets = api.mentions_timeline(read_last_seen(FILE_NAME), tweet_mode='extended')
    for tweet in reversed(tweets):
        message = generate_message()
        img = select_image_path()
        reply_tweet(tweet, message, img)
```

**Comment by MichaelCurrin** [comment]
Yes the deprecated method does work, as you've said it posts images and since my own app uses it 

If you read the Tweepy docs you'll see a note that it is deprecated and what the recommended alternative is. 

The preferred approach is to use api.upload_media and then attach the returned ID as part of the media_ids list parameter on the api.update_status method 

Here are my noted about that

https://michaelcurrin.github.io/python-twitter-guide/#/code_snippets?id=tweet-a-message-with-media

**Comment by MichaelCurrin** [comment]
If you try posting a reply without an image you'll notice you're still not making a reply. You need to follow tweepy docs for adding reply target ID and twitter docs which say you must also include a handle for it to become a reply

Example 

https://michaelcurrin.github.io/python-twitter-guide/#/code_snippets?id=create-a-reply

**Comment by oGabrielArruda** [comment]
> Yes the deprecated method does work, as you've said it posts images and since my own app uses it
> 
> If you read the Tweepy docs you'll see a note that it is deprecated and what the recommended alternative is.
> 
> The preferred approach is to use api.upload_media and then attach the returned ID as part of the media_ids list parameter on the api.update_status method
> 
> Here are my noted about that
> 
> https://michaelcurrin.github.io/python-twitter-guide/#/code_snippets?id=tweet-a-message-with-media

Thanks man! That works!

For those who have opened this issue for the solution properly, follow the code now:

```
 # note that message has already a space (" ") before message really starts
def reply_tweet(tweet, message, img):
    status = '@' + tweet.user.screen_name + message
    api.update_with_media(img, status, in_reply_to_status_id = tweet.id)
    store_last_seen(FILE_NAME, tweet.id)
```

**Comment by MichaelCurrin** [comment]
Great to hear.

**Comment by Harmon758** [comment]
The method is [`API.update_with_media`](https://tweepy.readthedocs.io/en/latest/api.html#API.update_with_media), not `API.Update_with_media`, but yes, it should still work even though the endpoint that it uses, [POST statuses/update_with_media](https://web.archive.org/web/20190809210259/https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-update_with_media), has been deprecated and is no longer documented now. You should use [`API.media_upload`](https://tweepy.readthedocs.io/en/latest/api.html#API.media_upload) with [`API.update_status`](https://tweepy.readthedocs.io/en/latest/api.html#API.update_status) instead. See [Twitter's API documentation for uploading media](https://developer.twitter.com/en/docs/media/upload-media/overview).

See also the documentation for the `in_reply_to_status_id` parameter of `API.update_with_media` and `API.update_status`.
