### ISSUE TITLE
Write a User Guide for implementing AccountActivity in a Client Application.

### ISSUE THREAD

**Issue by bpluly** [tweepy/tweepy#1380]
The AccountActivity API https://github.com/tweepy/tweepy/issues/1075 is implemented but the way to use it is quite obscure, especially if the developer doesn't have experience of webhooks. In the same way as the Authentication Tutorial helps with that the Account Activity Tutorial should give a clear example for implementing its use in a client application.

**Comment by Harmon758** [comment]
This is stale now that [the Premium v1.1 Account Activity API has been deprecated](https://twittercommunity.com/t/deprecating-the-premium-v1-1-api/191092).
