### ISSUE TITLE
Streaming API can't find my account

### ISSUE THREAD

**Issue by Nathan-Binkley** [tweepy/tweepy#1382]
I have a list of accounts I'm following.

I'm using the same method for each account (ie, pulling 1 tweet from each, then getting the ['user']['id'] json object). The system can find every other account and get their tweets but they can't find mine.

**Comment by Nathan-Binkley** [comment]
Code looks like this:

`myStreamListener = MyStreamListener() 
 myStream = tweepy.Stream(auth = word.auth, listener=myStreamListener)
 myStream.filter(follow=people_id, is_async=False)`

where people_id is a list generated from the following:

`for i in listOfPeopleAts:
 response = word.user_timeline(id=i, count=1)
 people_id.append(str(response[0]._json['user']['id']))
 print(people_at)
 print(people_id)`

It gets me the correct user ID ('1235370767048740864') but it does not stream correctly. It works properly for other IDs ('25073877', '939091', '432895323') but not mine. seems kind of weird.

**Comment by Nathan-Binkley** [comment]
NVM, I just have a bug somewhere.

**Comment by Harmon758** [comment]
For code block usage, see https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks.
