### ISSUE TITLE
'&' is represented as '&amp;'

### ISSUE THREAD

**Issue by Nathan-Binkley** [tweepy/tweepy#1383]
When I tweet from my app, all & characters get represented as &amp;

Is there any way to actually tweet & instead of &amp;? The &amps; get pulled, I change them via regex to &, I try and push them back up and they get changed back to &amp;. I want to actually tweet & instead of &amp;. Is this possible or is Twitter's API just weird.

**Comment by Harmon758** [comment]
I'm not sure I understand exactly what the issue is.
Can you more clearly explain the difference between your expected and actual results and/or provide what you're trying?
