### ISSUE TITLE
How to get live tweets only from a set of users?

### ISSUE THREAD

**Issue by fahadshery** [tweepy/tweepy#1388]
Hi,

I have tried this:

```python
users_to_follow = ['twitterid_1', 'twitterid_2', 'twitterid_3']

mystream = tweepy.Stream(self.auth, self.listener)
        try:
            mystream.filter(follow=users_to_follow)
        except:
            print("error!")
            mystream.disconnect()
```
But it's not pulling `live` tweets but first or second tweet from the user profile. How can I just `track` certain users for `live` tweets only?

thanks

**Comment by Harmon758** [comment]
I'm unable to reproduce this, and I'm not sure how this is possible. The [POST statuses/filter endpoint](https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter) that `Stream.filter` uses is used to filter realtime Tweets. Can you provide a reproducible example (MCVE/SSCCE)?
