### ISSUE TITLE
Filter API suddenly stopped working

### ISSUE THREAD

**Issue by TheVidoja** [tweepy/tweepy#1390]
Hello,

I have a Python script that constantly feeds from the filter API. 

The thing is that last night it stopped receiving any data, around 23:00 GMT+2 (I'm in Spain).

I don't know if the issue is related with Tweepy or not, but I haven't changed absolutely anything, and still it stopped working. It worked until it suddenly didn't

Maybe this can be related to an update in the Twitter API or something similar, I don't know. Ot maybe there's a much more obscure reason within my system/script.

I hope we can fix this, it's really important.

Thank you!

PS: I know that it isn't receiving anything because I added a print inside "on_status" listener code. 
If you need more data/information about the script or my system, just ask me for it, I haven't posted anything yet because I don't know what information could be relevant.

**Comment by TheVidoja** [comment]
I found the issue.

Apparently Windows decided to change the computer time to a time that was wrong and didn't synchronize with online servers.

And when I noticed that the time was wrong and set it correctly, the script started working again.

Apparently Tweepy doesn't like it when the system tyme is not correctly set, at least on Windows.

In conclusion, the issue wasn't related to the Twitter API or anything external, in fact the culprit ended up being the system time, which I would have never thought of it, but luckily noticed relatively early in the process.

Thank you anyways!

**Comment by Harmon758** [comment]
This is actually a documented aspect of Twitter's API and not an issue with Tweepy.
You were likely receiving a 401 error from Twitter's API indicating an
> Out-of-sync timestamp in your OAuth request (the response body will indicate this).

https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/connecting

In the future, you should use the `on_error` method of the `StreamListener` to determine what errors you're encountering.
