### ISSUE TITLE
Stream isn't returning anything

### ISSUE THREAD

**Issue by gabrielsandrade** [tweepy/tweepy#1392]
`class newTT(tweepy.StreamListener):
    def __init__(self, api):
        self.api = api
        self.me = api.me()
        logger.info("StreamListener Inicializado")

    def on_status(self, tweet):
        print (tweet.text)

def main():

    api = create_api()
    tweets_listener = newTT(api)
    stream = tweepy.Stream(auth=api.auth, listener=tweets_listener, tweet_mode="extended")
    
    stream.filter(track=['python'])

if __name__ == "__main__":
    main()`
Tweepy was working fine but suddenly the stream isn't returning anymore.
I've tried with different Authentications but nothing worked.

**Comment by AFirouzi** [comment]
I ran your code and it seems fine. could you send a screenshot of the error you get?

**Comment by Harmon758** [comment]
I'm also unable to reproduce this issue.
In the future, you should use the `on_error` method of the `StreamListener` to determine what errors you're encountering.

For code block usage, see https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks.

**Comment by rae89** [comment]
I am having the same issue. Running python 3.7.5

**Comment by sharockys** [comment]
I maybe the limit reached. 
I had error code 420. 
`Returned when an app is being rate limited for making too many requests.`
