### ISSUE TITLE
problem with id parameter into statuses_lookup

### ISSUE THREAD

**Issue by thekillgfx** [tweepy/tweepy#1395]
**Code**
`for tweet in twitter.statuses_lookup(ids, tweet_mode='extended'):`

**Traceback**
```
File "tester.py", line 85, in getTweetMedia
    for tweet in twitter.statuses_lookup(ids, tweet_mode='extended'):
File "/usr/local/lib/python3.6/dist-packages/tweepy/api.py", line 97, in statuses_lookup
    trim_user, map_, tweet_mode)
File "/usr/local/lib/python3.6/dist-packages/tweepy/binder.py", line 250, in _call
    return method.execute()
File "/usr/local/lib/python3.6/dist-packages/tweepy/binder.py", line 233, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 38, 'message': 'id parameter is missing.'}]
```

**Code 2**
`for tweet in twitter.statuses_lookup(id=ids, tweet_mode='extended'):`

**Traceback 2**
```
File "tester.py", line 85, in getTweetMedia
    for tweet in twitter.statuses_lookup(id=ids, tweet_mode='extended'):
TypeError: statuses_lookup() got an unexpected keyword argument 'id'
```

- Code 1 work fine but the error show up, Code 2 doesn't work at all.

- Looking through the code [here](https://github.com/tweepy/tweepy/blob/master/tweepy/api.py#L102) in Github seems like the `id` should be accepted but it's not actually.

**Comment by Harmon758** [comment]
I'm unable to reproduce the first traceback when passing a list of IDs as `ids`.
The traceback actually shows an error from Twitter. Are you passing `None` or an empty list as `ids`?

As for the second traceback, the reasoning behind not accepting `id` as a keyword argument is that [`id` is a built-in function in Python](https://docs.python.org/3/library/functions.html#id), and it would be bad practice to override it.
