### ISSUE TITLE
Support for next Twitter API version :-)

### ISSUE THREAD

**Issue by andypiper** [tweepy/tweepy#1396]
Hi friends! Andy here, from Twitter Developer Relations :-)

Tweepy is one of the most popular libraries for the Twitter API, and we would love to be able to list you as supporting the newest version of the API when it comes out in the coming weeks.

Do you all have any plans to support the [Twitter Developer Labs](https://developer.twitter.com/en/labs) endpoints and fields? Although the paths may change at release, you can expect the overall pattern to be very similar, since we've been in pilot with this new version for some time.

Feel free to Tweet me @andypiper, or chat with us on the [developer forums](https://twittercommunity.com/c/labs/57) if you'd like to learn more. Not long now! We will not be replacing everything you're familiar with at launch, but we think a lot of developers will be interested in the new features (topic context annotations, pinned Tweets, poll data, etc etc).

**Comment by senic35** [comment]
@andypiper What is the exact reason you guys removed support for your legacy version? This broke so many libraries depending on some functions of it. Is there any way to fix some of the issues which https://github.com/twintproject/twint or https://github.com/ciderpunx/twitrssme are having?

**Comment by andypiper** [comment]
Which legacy version are you referring to? We haven't announced plans to retire v1.1 as yet.

**Comment by senic35** [comment]
> Which legacy version are you referring to? We haven't announced plans to retire v1.1 as yet.
Here are some of the issues that occurred: https://github.com/ciderpunx/twitrssme/issues/92

**Comment by andypiper** [comment]
This is off-topic for the tweepy library / the issue that I originally opened.

The Twitter website is not an API so there should be no expectation that it will remain the same. If you're relying on undocumented internal behaviours then unfortunately things may break. It will be down to the developers of those web scraping tools to adapt themselves.

**Comment by fitnr** [comment]
@andypiper I'm sure that the maintainers of the library would appreciate a pull request. After all, open source only works if people (and enormous public corporations) pitch in!

**Comment by andypiper** [comment]
I hear you - I can’t promise a specific PR for Tweepy, but I’m working with as many of the community libraries as I can (and there’s a lot of languages and ground to cover!). More news coming soon.

**Comment by joshthecoder** [comment]
@andypiper Yes it would be great to keep Tweepy up to date with the latest API changes. I'll take a look at Labs today and also review where we can start updating Tweepy to support API changes. I've gone ahead and also applied for a developer account for the Tweepy organization so we can access Labs.

I'll be sure to reach out if I have any questions. Thanks for reaching out!

**Comment by andypiper** [comment]
Hey @joshthecoder I followed you on Twitter so feel free to DM if you need support. Thanks!

**Comment by tdstarkisoc** [comment]
Does anyone know if there has been any progress on this?

**Comment by tdstarkisoc** [comment]
> Does anyone know if there has been any progress on this?

@joshthecoder any thoughts on a rough timeline?

**Comment by dnpthree** [comment]
Bump - would love to know if this has started yet?

**Comment by andypiper** [comment]
When @Harmon758 was on the TwitterDev Twitch chat yesterday I think it was mentioned that this is being looked into for after the next mainline release (i.e. early 2021). There are some basic (non-Tweepy) Python samples at https://github.com/twitterdev/Twitter-API-v2-sample-code but nothing in Tweepy yet.

**Comment by Harmon758** [comment]
I'm going to close this in favor of #1472, now that Twitter API v2 has been launched.
I greatly appreciate the support and encouragement, and I apologize for the delay in responding.
As for supporting any other current or future Labs endpoints, I've added that as an addendum to #1472 for now.
My Twitter account is an active developer account, so access to Labs shouldn't be an issue.

**Comment by samuelmaker** [comment]
hey @andypiper do you know if the destroy tweet endpoint is being retired in v2?

**Comment by andypiper** [comment]
The current v1.1 `statuses/destroy` will go away in the future, but not before the v2 replacement is ready. So far as I know there are no plans to *not* have the ability to delete Tweets in the API, but I cannot describe what this will look like or when it will be available in v2 at this time.
