### ISSUE TITLE
Read the docs in website not opening

### ISSUE THREAD

**Issue by wahidGulzar** [tweepy/tweepy#1406]

**Comment by Harmon758** [comment]
I'm unable to reproduce this.
Both https://tweepy.readthedocs.io/en/latest/ and http://docs.tweepy.org/en/latest/ work for me, in multiple different browsers and on multiple different devices.
You'll need to be more specific as to the issue and your browser, platform, etc., but it's highly unlikely that this is an issue specific to Tweepy's documentation, as all [the recent builds](https://readthedocs.org/projects/tweepy/builds/) have passed.
