### ISSUE TITLE
Add support for "trim_user" and "exclude_replies" to home_timeline

### ISSUE THREAD

**Issue by changwally** [tweepy/tweepy#1410]
"trim_user" and "exclude_replies" are supported by the twitter API as per [documentation](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-home_timeline).

The same is already supported for user_timeline (at least in the code, the tweepy api documentation seems not up to date?)

**Comment by Harmon758** [comment]
Resolved by #1458
