### ISSUE TITLE
"tweepy.error.TweepError: Could not determine file type" error when trying to upload jpg image.

### ISSUE THREAD

**Issue by AlbertCoolGuy** [tweepy/tweepy#1411]
I'm trying to upload a image using this code:
```python
media = api.media_upload('quote.jpg', f)
api.update_status(status="foo", media_ids=[media.media_id_string])
```

**Expected Results**

Tweepy uploads the image with the message "foo".

**Actual Results**

Tweepy fails to upload the image because it can't guess the filetype using imghdr.what().

**Possible Solution**

Use mimetypes and/or magic as a fallback if imghdr fails.

**Traceback**

```
Traceback (most recent call last):
  File "planetexpressbot.py", line 30, in <module>
    media = api.media_upload('quote.jpg', f)
  File "/usr/local/lib/python3.8/site-packages/tweepy/api.py", line 229, in media_upload
    headers, post_data = API._pack_image(filename, max_size,
  File "/usr/local/lib/python3.8/site-packages/tweepy/api.py", line 1392, in _pack_image
    raise TweepError('Could not determine file type')
tweepy.error.TweepError: Could not determine file type
```

**Comment by Harmon758** [comment]
Would you be able to provide the image in question?

**Comment by AlbertCoolGuy** [comment]
Here it is.
![quote](https://user-images.githubusercontent.com/39652844/89123953-96b73b00-d4d3-11ea-9a30-3ceb15a63743.jpg)

**Comment by Harmon758** [comment]
Thanks, re-uploaded to GitHub for posterity:
https://user-images.githubusercontent.com/9403740/89124007-43c09200-d499-11ea-9a83-fd1aa48b21d8.png
