### ISSUE TITLE
Retweet a tweet which quotes a tweet isn't retweeted correctly

### ISSUE THREAD

**Issue by Forium777** [tweepy/tweepy#1417]
Doing :
```python
API.retweet(id=1294582972704796672)
```
appear like :
![image](https://user-images.githubusercontent.com/69720050/90526524-c8393300-e170-11ea-9767-ef074caece9f.png)

whereas it should appear like :
![image](https://user-images.githubusercontent.com/69720050/90525517-a68b7c00-e16f-11ea-8a7a-90304ce33d52.png)

Notice that when we try to retweet a tweet which **doesn't** contains a quoted tweet, it's retweeting well.

**Comment by Harmon758** [comment]
I'm unable to reproduce this. Both `api.retweet(1294582972704796672)` and `api.retweet(id=1294582972704796672)` appear as:
![image](https://user-images.githubusercontent.com/9403740/90528298-13831f80-e138-11ea-98c7-a87d44fb6af8.png)
How are you viewing the Tweet?

**Comment by Forium777** [comment]
I was viewing the retweet as the first image in my issue, can't reproduce it though... Might be a bug in my code (low chance but still) I'm closing the issue.

**Comment by Harmon758** [comment]
Odd, it's almost certainly not an issue with Tweepy if that was the only line of code in question.
I suppose it could also have been a transient issue with Twitter's API.
