### ISSUE TITLE
trends_place returning wrong top trends

### ISSUE THREAD

**Issue by yunusemrecatalcam** [tweepy/tweepy#1421]
using this function for fetching trends in my country (Turkey)
```python
country_trends = api.trends_place(country_woeid)
```
It returns 
`#KathrynForLazada
#OycEledumareChallenge
#JOLLIFootballWeekend
#InfinixZero8VisionMaster
#TRODTheLivinGrinEP
BDAY LOUD WILL
Gary Rohan
RizzleApp Rocks
Thrilled For Sadak2
Opebi, Lagos
Alternative Plans
Space Sonic
GALANTIS
MAGANDANG GABI JADINES
JUNG HOSEOK WORLD DOMINATION
LAZADA QUEEN
Salvation Road
1.9% in July
PARK JIMIN WORLD DOMINATION
#MankathaCDPBlast
#ChineseButcher
#TheRebirthofJoeEP
#FreeBetFriday
#BETWAYFRIDAY
#DynamitePHarty
#IDreamALotAbout
#cizaseason
#MSSAcrossTheUniverseByNISSIN
#NoMoreHateChaDen
#夜見3D
#KeerthyBdayBashIn50D
#கர்ணன்
#FoundInPandorasBox
#SouthAfricaRemix
#initials
#매순간이_소중했던_우리의3년
#Fatalis
#BoiledMovies
#jajanbighitopfoll
#ShowMeTheMWM_ONEUS
#opebi
#เอ้พีท2020
#큥이버블
#MULTOWishClusive
#KCPHGA
#BillyNaMbaruk
#Majorxพร้อมเบนซ์` 

And none of them is a top trend in Turkey and they are not even in Turkish, So I guess there is something wrong with the twitter api.

I already checked the woeid and it is correct;
My tweepy version is 3.9.0 which is the latest release.

Thanks

**Comment by Harmon758** [comment]
I'm unable to reproduce this.
```py
country_woeid = 23424969
country_trends = api.trends_place(country_woeid)
' '.join(trend["name"] for trend in country_trends[0]["trends"])
```
produces:

`#LisansGelisimOrgunde İlveİlçeEmri Verilmelidir #AkşenerHalkTVde Kurtuluş Gemisi #tekçözümtekkalemzamlımaaş #BayrağıDevral yusufunkuyuda olmasıgibi #TransferSihirbazıEmreBello istanbulmaltepe alevaltında Hüseyin Atakan Üner yenyespor bayilikbaşvuru Orkun Kökçü maç sonucu Gökhan Akkan #AytaçÜnsalaSahipÇık #SevrUşağıHDP #BabadanMiras #spormerkezi #GücümüzSizsiniz #FenomenOlmaYöneticiOl #EnnerValencia #Görmekİsterim #ForeverWithBaekhyun #UnilerUzaktanEgitimİstemiyor #DorukhanKırmızıÇizgimizdir #MeüYüzyüzeİstiyor #FBvAAL`

for me right now, which seems to be mainly in Turkish.

Can you provide a reproducible example (MCVE/SSCCE) or at least the WOEID you're using?

**Comment by yunusemrecatalcam** [comment]
I see that its resolved in a few hours after I opened this issue. I guess it was a temporary error on api.

**Comment by yunusemrecatalcam** [comment]
I see that its resolved in a few hours after I opened this issue. I guess it was a temporary error on api.
