### ISSUE TITLE
Tweet reply seems to work only one way

### ISSUE THREAD

**Issue by Nemotaku** [tweepy/tweepy#1422]
I use tweepy 3.9.0 to create a bot that reply when notified. 

I use the function "update_status" this way :  

`api.update_status(
                status = at + " " + reponse,
                in_reply_to_status_id=tweet.id
            )
`The reply tweet work fine for the bot (https://twitter.com/StivouLaposte/status/1299394023938023425) but the user who sent the first tweet has no notification and can't see the reply tweet (https://twitter.com/Nemotaku/status/1299390109381427200).

**Comment by Harmon758** [comment]
I'm unable to reproduce this, but this seems like an issue on Twitter's end.
There are various other similar reports of this:
https://twittercommunity.com/t/tweets-sent-through-api-showing-up-as-unavailable/141639
https://twittercommunity.com/t/only-me-can-see-my-replies-to-tweets/140052
https://twittercommunity.com/t/replying-to-tweets-that-are-not-my-own-does-not-work/139901
https://twittercommunity.com/t/bot-tweets-not-showing-up-to-users-other-than-me/140345

It could also be something specific to the account that Twitter is limiting. I would recommend following the suggestions in https://twittercommunity.com/t/replies-posted-are-being-hidden-below-show-additional-replies/140364/2.

This is unlikely to be an issue with Tweepy, so I'd recommend making a post on the Twitter Developers Forums as well.

**Comment by Harmon758** [comment]
This seems to have been an intermittent issue or an issue that was resolved on Twitter's end, as the Tweet in question now shows up properly as a reply.
