### ISSUE TITLE
Twitter V2

### ISSUE THREAD

**Issue by Ces-D** [tweepy/tweepy#1423]
There wouldn't happen to be any support for Twitter developer api v2. It is still in testing, but if your trying to get metrics it is very useful.

**Comment by NicholasMamo** [comment]
Bumping this to ask: since v2 is out in early-access and seems stable, does tweepy have plans to support the new version in the near future?

**Comment by lucasrangit** [comment]
Duplicate of #1396

**Comment by Harmon758** [comment]
I'm going to close this in favor of #1472. Apologies for the delay in responding.
