### ISSUE TITLE
Premium search not in pip install

### ISSUE THREAD

**Issue by xiaolin-TL** [tweepy/tweepy#1425]
I run my python scripts with bazel and use `pip install` for python libraries. Can you update the version of tweepy in pip install ? Right now tweepy from pip install does not have premium search features like `search_30_day`.

**Comment by Harmon758** [comment]
Support for premium search has already been merged into the master branch and will be released with v3.10.0.
See https://github.com/tweepy/tweepy/issues/1175#issuecomment-659173030.

There is no "version of tweepy in pip install". [pip](https://pip.pypa.io/en/stable/) itself is a package installer and does not host any libraries/packages. You're likely installing from [PyPI](https://pypi.org/), the Python Package Index. The latest version of Tweepy that has been released and is on PyPI is v3.9.0. Until v3.10.0 is released, you can use pip to install from the master branch.

As for the release of v3.10.0, I will probably try to actualize it fairly soon. Besides what's already in [the corresponding milestone](https://github.com/tweepy/tweepy/milestone/12), there's probably only one or two other issues that need to be addressed prior to release.
