### ISSUE TITLE
Status doesn't include proper URLS

### ISSUE THREAD

**Issue by officiallymarky** [tweepy/tweepy#1426]
I am streaming looking for specific domain names in tweets.  I have this working and I am properly finding tweets that mention a specific set of domain names.  The problem is the status.entities['urls'] does not always include these urls.  90-95% of the time it includes the urls, that 5-10% of the time it only includes a twitter link to the tweet.  If I manually verify the tweet, it includes one of the URLs I am looking for and doesn't not include any links to the tweet itself or any other tweet.

For example, if someone mentions a link to example.com/greatpost, I will find the tweet when streaming for example.com links, but the urls will only show a link to the tweet itself.  Manually pulling up the tweet on Twitter.com I can see the link to example.com/greatpost only.

**Comment by Harmon758** [comment]
Are you sure these Tweets aren't extended Tweets? If they are (> 280 characters), you'll have to use the `extended_tweet` attribute of the Tweet/Status object and its corresponding `entities` sub-field/key instead.
See https://tweepy.readthedocs.io/en/latest/extended_tweets.html#streaming.

Otherwise, can you provide a reproducible example (MCVE/SSCCE) or at least an example of such a Tweet?

**Comment by officiallymarky** [comment]
I am checking for extended tweets.
Here is an example:

https://twitter.com/splinterlands/status/1308047715490725890

You can see there is a link in the tweet to https://t.co/gOmwmbwHnS which goes to https://peakd.com/hive-13323/@marianaemilia/splinterlands-basic-battle-tips-the-taunt-strategy.

But in the status, the only link is to the tweet itself.

```
   'urls': [
      {
        'url': 'https://t.co/tgCAhMVXsg',
        'expanded_url': 'https://twitter.com/i/web/status/1308047715490725890',
        'display_url': 'twitter.com/i/web/status/1…',
        'indices': [
          117,
          140
        ]
```

This tweet has no extended_tweet attribute, but even on tweets that did, I didn't see the URL.  This seems to happen to a decent portion of tweets I have observed (20%+) which makes this method of getting the URL unusable and I had to resort to regex of the actual tweet for reliable way of obtaining urls being tweeted.

**Comment by Harmon758** [comment]
> This tweet has no extended_tweet attribute, but even on tweets that did, I didn't see the URL.

That shouldn't be the case. Can you provide the code you're using to test this?

**Comment by officiallymarky** [comment]
I am streaming, but just using `api.get_status(1308047715490725890)` will return a status object where you can see the same problem I'm seeing.  It happens frequently to the point where I can't use entities for urls and have to manually strip them from the tweet text.

**Comment by Harmon758** [comment]
Since that Tweet is > 140 characters, you need to use extended mode when retrieving it, and when doing so, I'm unable to reproduce the issue:
```py
>>> status = api.get_status(1308047715490725890, tweet_mode = "extended")
>>> status.entities
{'hashtags': [{'text': 'Splinterlands', 'indices': [28, 42]}], 'symbols': [], 'user_mentions': [], 'urls': [{'url': 'https://t.co/gOmwmbwHnS', 'expanded_url': 'https://peakd.com/hive-13323/@marianaemilia/splinterlands-basic-battle-tips-the-taunt-strategy?fbclid=iwar1d66ibsyzqub9rwfzwsmxtcrkbokdu8buxvzved2qckekppyxronmuote', 'display_url': 'peakd.com/hive-13323/@ma…', 'indices': [234, 257]}]}
```

**Comment by officiallymarky** [comment]
Ahh, sorry forgot to use extended mode, I don't usually use get_status and I usually stream but it does happen, I just need to find another tweet as an example.  In my streaming code I do check for both extended and regular text and in the cases where it happens, they both show a link to the tweet itself instead of the links in the tweet.

Will take a bit to find another example but I will dig one up or just add some logging to my streaming code as it finds them all the time when using entities.

**Comment by Harmon758** [comment]
It would be helpful if you could provide the relevant portions of your code or a separate reproducible example. Otherwise, there's not really a way for me to attempt to reproduce what you're encountering, and another example Tweet doesn't really provide any additional information.

**Comment by officiallymarky** [comment]
Will do
