### ISSUE TITLE
error in statuses_lookup

### ISSUE THREAD

**Issue by awurman** [tweepy/tweepy#1428]
Hi! i tried with different codes and always get:
api         | tweepy.error.TweepError: [{'code': 34, 'message': 'Sorry, that page does not exist.'}]

Any clue?
Last test:
    api = tweepy.API(auth)

    # list of status IDs to be fetched  
    id_ = [1266978261701210112, 1266735261012111360, 1266342841648898049] 
    
    # fetching the statuses 
    statuses = api.statuses_lookup(id_) 

Thnaks!

**Comment by Harmon758** [comment]
I'm unable to reproduce this:
```py
>>> id_ = [1266978261701210112, 1266735261012111360, 1266342841648898049]
>>> statuses = api.statuses_lookup(id_)
>>> len(statuses)
3
```
Are you sure you're properly authenticated? Can you provide a full traceback and reproducible example (MCVE/SSCCE)?
