### ISSUE TITLE
Not matching results: api.get_user('Any id')  versus tweepy.Cursor(api.followers, screen_name = user.screen_name, count = 1, skip_status=False, include_user_entities=True).pages()

### ISSUE THREAD

**Issue by jcuadrag** [tweepy/tweepy#1429]
Hi there!

I am having different results depending on how I query followers' data.

These are the methods that I am using to query those data:

1. tweepy.Cursor(api.followers, screen_name = user.screen_name, count = 1, skip_status=False, include_user_entities=True).pages()

2. api.get_user('Any id')

By doing 2 I get 'profile_location' among the gotten results. This field is missing in my results when I do 1.

Is this the expected behavior? Do I need to take into consideration which method is needed to be used in order to get specific results?

Thanks in advance!

**Comment by Harmon758** [comment]
[`profile_location` is a deprecated attribute of the user object that is no longer supported](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/overview/user-object), and will always be set to null/`None`, so it should have no bearing on the actual data. This is just Twitter's API continuing to provide the deprecated attribute (probably for consistency and/or back-end reasons) and Tweepy passing that along.
