### ISSUE TITLE
Trying to download the members of a list. Problem: I always get 'Sorry, that page does not exist.'-error

### ISSUE THREAD

**Issue by danielp3011** [tweepy/tweepy#1430]
I tried downloading all the members of this page: https://twitter.com/i/lists/912241909002833921
using the following code:

```
api = tweepy.API(auth)

# which Twitter list and who owns it
slug = '912241909002833921'
owner = 'wahl_beobachter'

def get_list_members(api, owner, slug):
    members = []
    # without this you only get the first 20 list members
    for page in tweepy.Cursor(api.list_members, owner, slug).items():
        members.append(page) # create a list containing all usernames
    for m in members:
        print(m)
    return [ m.screen_name for m in members ]
    
get_list_members(api, owner, slug)
```
However, I always get the following error:
tweepy.error.TweepError: [{'code': 34, 'message': 'Sorry, that page does not exist.'}]

Can somebody give me a hint what I did wrong? Or is there something wrong with the tweepy library?

**Comment by Harmon758** [comment]
`912241909002833921` is the list ID, not the slug. The slug is based on the name of the list, `MdB (Bundestag)`. Parentheses are removed and spaces are replaced with dashes, and it's not case sensitive, so in this case, the slug is `mdb-bundestag`:
```py
>>> twitter_list = api.get_list(list_id = 912241909002833921)
>>> twitter_list.slug
'mdb-bundestag'
```
You can simply set `slug = 'mdb-bundestag'` instead.

Alternatively, you can just provide the list ID:
```py
>>> members = []
>>> for page in tweepy.Cursor(api.list_members, list_id = 912241909002833921).items():
...     members.append(page)
...
>>> len(members)
533
```
