### ISSUE TITLE
Bot doesn't reply to specific status id 

### ISSUE THREAD

**Issue by NizWasTaken** [tweepy/tweepy#1440]
When using `in_reply_to_status_id=mention.id`, the script records the tweet id, saves it to last seen id file but doesn't reply to that specific id, it makes a whole new status for some reason.

**Comment by Harmon758** [comment]
Are you mentioning the author of the Tweet you're attempting to reply to or using `auto_populate_reply_metadata`?
If so, can you provide a reproducible example (MCVE/SSCCE) of this?

**Comment by NizWasTaken** [comment]
adding `auto_populate_reply_metadata` fixed the problem, thanks a lot.
