### ISSUE TITLE
Streaming is broken

### ISSUE THREAD

**Issue by Nathan-Binkley** [tweepy/tweepy#1441]
Not sure what the issue really _is_ here. I can't stream, returns a 403. Keys are valid as I can pull most recent tweets from followers. Happened sometime in the last 7 hours (the last streamed/repeated tweet I sent out).

**Comment by Nathan-Binkley** [comment]
Found out my issue is on Twitter's end.

They, for whatever reason, revoked my streaming + write access. Not sure why. Trying to get with Twitter Support now.

Here's a link incase anyone stumbles across this later

**Comment by Harmon758** [comment]
This makes sense, as a [403](https://en.wikipedia.org/wiki/HTTP_403) [HTTP status code](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes) is defined as Forbidden:
> The request is understood, but it has been refused or access is not allowed.

https://developer.twitter.com/en/support/twitter-api/error-troubleshooting#http-status-codes
