### ISSUE TITLE
Cant retrieve full_text of tweets even after setting tweet_mode to 'extended' and assigning tweet.full_text 

### ISSUE THREAD

**Issue by akhilkapil** [tweepy/tweepy#1449]
Hi, i know  this issue has been raised before as well plenty  of times but I have tried all the solutions I an find online and it doesn't seem to work.The output I am getting is incomplete text. As I am new to this, let me know if I am wrong somewhere. 

tweets = tp.Cursor(api.search,
                   q=search_words,
                   lang='en', since = date_since, tweet_mode='extended', count=300).items(2000)

**Comment by MaxSaakyan** [comment]
Did you find a solution for this in the end?

**Comment by akhilkapil** [comment]
Yes bro I did. I changed my whole code and did it some other way. If u r still facing this issue let me know, I will post the solution

**Comment by Harmon758** [comment]
From [the documentation on extended Tweets](https://tweepy.readthedocs.io/en/latest/extended_tweets.html):
> When using extended mode with a Retweet, the `full_text` attribute of the Status object may be truncated with an ellipsis character instead of containing the full text of the Retweet. However, since the `retweeted_status` attribute (of a Status object that is a Retweet) is itself a Status object, the` full_text` attribute of the Retweeted Status object can be used instead.

If you're encountering this with Tweets that aren't Retweets, you'll need to provide a reproducible example (MCVE/SSCCE) for this to be actionable in any way.
