### ISSUE TITLE
Error while extracting hashtags from tweets

### ISSUE THREAD

**Issue by ekdnam** [tweepy/tweepy#1451]
The code is like this

```
text = []
id_str = []
entities_hashtags = []
entities_symbols = []
entities = []
user_id = []
entities_hashtags = []
entitites_symbols = []
user_location = []
time_zone = []
lang = []
created_at = []

cnt = 0

for tweet_id in ids:
    
    print("\nCurrent indx: " + str(indx))
    print("Tweets to be processed: " + str(900-cnt))
    cnt += 1 
    indx += 1
    
    try:
        print("Processing tweet. ID = " + str(tweet_id))
        
        tweet = api.get_status(tweet_id, tweet_mode = 'extended', include_entities = True)
        
        text.append(tweet.full_text)
        created_at.append(tweet.created_at)
        id_str.append(tweet.id_str)
        entities.append(tweet.entities)
        user_id.append(tweet.user.id)
        lang.append(tweet.lang)
        time_zone.append(tweet.user.time_zone)
        user_location.append(tweet.user.location)
        entities_hashtags.append(tweet.entities.hashtags)
        entities_symbols.append(tweet.entities.symbols)
        
        if(cnt%100 == 0):
            print("Text: " + str(tweet.full_text))
    except tw.error.TweepError:
      print("ERROR WHILE ACCESSING TWEET. ID: " + str(tweet_id))
      pass
```

The code was running perfectly before. But while trying to get hashtags and symbols I added

```
        entities_hashtags.append(tweet.entities.hashtags)
        entities_symbols.append(tweet.entities.symbols)
```

And now the resulting error is
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-07cbe3581438> in <module>
     21         time_zone.append(tweet.user.time_zone)
     22         user_location.append(tweet.user.location)
---> 23         entities_hashtags.append(tweet.entities.hashtags[0])
     24         entities_symbols.append(tweet.entities.symbols)
     25 

AttributeError: 'dict' object has no attribute 'hashtags'
```

What can be done to resolve this issue?

**Comment by sumit-jaswal** [comment]
This should work
`tweet.entities['hashtags']`

**Comment by sumit-jaswal** [comment]
> This should work
> `tweet.entities['hashtags']`
> 
> Similarly, for symbols
> `tweet.entities['symbols']`

The way you are trying to access is not working because Python is considering hashtags as a method (some built in function) for dictionary but instead it is a key of dictionary entities.

**Comment by sumit-jaswal** [comment]
> The code is like this
> 
> ```
> text = []
> id_str = []
> entities_hashtags = []
> entities_symbols = []
> entities = []
> user_id = []
> entities_hashtags = []
> entitites_symbols = []
> user_location = []
> time_zone = []
> lang = []
> created_at = []
> 
> cnt = 0
> 
> for tweet_id in ids:
>     
>     print("\nCurrent indx: " + str(indx))
>     print("Tweets to be processed: " + str(900-cnt))
>     cnt += 1 
>     indx += 1
>     
>     try:
>         print("Processing tweet. ID = " + str(tweet_id))
>         
>         tweet = api.get_status(tweet_id, tweet_mode = 'extended', include_entities = True)
>         
>         text.append(tweet.full_text)
>         created_at.append(tweet.created_at)
>         id_str.append(tweet.id_str)
>         entities.append(tweet.entities)
>         user_id.append(tweet.user.id)
>         lang.append(tweet.lang)
>         time_zone.append(tweet.user.time_zone)
>         user_location.append(tweet.user.location)
>         entities_hashtags.append(tweet.entities.hashtags)
>         entities_symbols.append(tweet.entities.symbols)
>         
>         if(cnt%100 == 0):
>             print("Text: " + str(tweet.full_text))
>     except tw.error.TweepError:
>       print("ERROR WHILE ACCESSING TWEET. ID: " + str(tweet_id))
>       pass
> ```
> 
> The code was running perfectly before. But while trying to get hashtags and symbols I added
> 
> ```
>         entities_hashtags.append(tweet.entities.hashtags)
>         entities_symbols.append(tweet.entities.symbols)
> ```
> 
> And now the resulting error is
> ```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-13-07cbe3581438> in <module>
>      21         time_zone.append(tweet.user.time_zone)
>      22         user_location.append(tweet.user.location)
> ---> 23         entities_hashtags.append(tweet.entities.hashtags[0])
>      24         entities_symbols.append(tweet.entities.symbols)
>      25 
> 
> AttributeError: 'dict' object has no attribute 'hashtags'
> ```
> 
> What can be done to resolve this issue?

The way you are trying to access is not working because Python is considering hashtags as a method (some built in function) for dictionary but instead it is a key of dictionary entities.

**Comment by ekdnam** [comment]
>This should work
tweet.entities['hashtags']

Thanks a lot! The issue got resolved.

> The way you are trying to access is not working because Python is considering hashtags as a method (some built in function) for dictionary but instead it is a key of dictionary entities.

Oh okay got it.
