### ISSUE TITLE
Tweepy error: 'API' object has no attribute 'search_full_archive'

### ISSUE THREAD

**Issue by hamelena** [tweepy/tweepy#1452]
Hi!
I have a problem testing access to older tweets according to documentation in http://docs.tweepy.org/en/latest/api.html#API.search_full_archive

The ordinary search works fine, but trying to change to full archive search I get: 
'API' object has no attribute 'search_full_archive'

I've already set the environment on Twitter to get the sandbox access and try following code(my original environment name is deleted for safety reasons:

```
search_words ='Russia'
date_since = "201403010000"
date_to = "201405010000"
numTweets = 100

tweets=tweepy.Cursor(api.search_full_archive (environment_name='MY_ENV_NAME', query=search_words, fromDate=date_since, toDate=date_to)).items(numTweets)
```

Do you have any idea or examples of a working code? Thank you in advance!

**Comment by ChristophBr** [comment]
Hello!
Did you find a solution? I habe the same issue! 
Best 
Christoph

**Comment by dplefevre** [comment]
It seems that the version on PyPi has not been updated. The following worked for me:
$ pip uninstall tweepy
$ pip install git+https://github.com/tweepy/tweepy.git

**Comment by Harmon758** [comment]
`API.search_full_archive` is currently only in the development version on the master branch.
In the future, please make sure you're using the latest development version when reporting issues.

See [the installation instructions in the documentation](https://tweepy.readthedocs.io/en/latest/install.html) for how to install from the repository.

> The following worked for me:
> $ pip uninstall tweepy
> $ pip install git+https://github.com/tweepy/tweepy.git

Uninstalling to reinstall shouldn't be necessary; using the `--upgrade` flag should work fine.

**Comment by Victor-Ikechukwu** [comment]
Hey, it might be a late response but can be of help to someone.

Replace "search" with "search_tweets" 
For example: API.search_tweets(q, *, geocode, lang, locale, result_type, count, until, since_id, max_id, include_entities)

Hope that works.

**Comment by Harmon758** [comment]
Please don't necrobump old closed issues.

That's also not relevant to this issue at all.
