### ISSUE TITLE
TWEEPY API RETURNS NULL LIST OF DIRECT MESSAGES WHEN THERE ARE DIRECT MESSAGES IN THE TWITTER.

### ISSUE THREAD

**Issue by SulavSapkota2060** [tweepy/tweepy#1454]
` api = tweepy.API(auth)`

`messages = api.list_direct_messages()`

`print(messages)`

Previously it was working fine and I tried removing all direct messages by the `destroy_direct_message()` method but It didn't remove the messages and is now returning null to all when I call `list_direct_messages()`

What is the fix?

**Comment by andypiper** [comment]
How recent are the Direct Messages? The API only provides access to Direct Messages within the past 30 days - see the Twitter API documentation.

**Comment by lxlGhostlylxl** [comment]
I also have this problem.  My messages are also not past 30 days old

**Comment by Harmon758** [comment]
Assuming you mean an empty list, I'm unable to reproduce this.

Note:
> The authenticating user must be the recipient of the specified direct message. Direct Messages are only removed from the interface of the user context provided. Other members of the conversation can still access the Direct Messages.

https://tweepy.readthedocs.io/en/latest/api.html#API.destroy_direct_message
https://developer.twitter.com/en/docs/twitter-api/v1/direct-messages/sending-and-receiving/api-reference/delete-message-event

Are you deleting messages visible to the authenticating user? and are you viewing them while logged in as that user?
If so, can you provide a reproducible example (MCVE/SSCCE)?
