### ISSUE TITLE
api.update_status returns None

### ISSUE THREAD

**Issue by Slagt** [tweepy/tweepy#1459]
According to the documentation, the method `api.update_status` is expected to return a Status object.

### Expectation:
A call to `api.update_status` returns a Status object referring to the newly updated status.

### Reality:
A call to `api.update_status` always returns a None object.

### Link to the documentation:
http://docs.tweepy.org/en/latest/api.html?highlight=followers_ids#API.update_status

**Comment by Harmon758** [comment]
I'm unable to reproduce this:
```py
>>> status = api.update_status("testing")
>>> type(status)
<class 'tweepy.models.Status'>
```

What version of Tweepy are you using?
Can you provide a reproducible example (MCVE/SSCCE)?
