### ISSUE TITLE
Extended tweet_mode not available in search_30_day and search_full_archive

### ISSUE THREAD

**Issue by MartinBeckUT** [tweepy/tweepy#1461]
I currently have a problem where I'm using both the 30 day search and full archive search APIs however all tweets coming back are truncated. I tried to use tweet_mode='extended' to get the full 280 characters available in tweets, like in the normal search method however it comes back with an error saying the tweet_mode parameter is unknown. 

Based on the documentation about extended tweets it says any API method should have this parameter available however appears it's not available for these two methods. http://docs.tweepy.org/en/latest/extended_tweets.html

Example code snippets for both:
```
tweets = tweepy.Cursor(api.search_30_day, environment_name='example, query='coronavirus', tweet_mode='extended').items(count)

tweets = tweepy.Cursor(api.search_full_archive, environment_name='example, query='coronavirus', tweet_mode='extended').items(count)
```

The error that comes back for both is: 
TweepError: {'message': "There were errors processing your request: Unknown parameter:'tweet_mode'", 'sent': '2020-11-26T05:00:55+00:00', 'transactionId': '009e7f0700aee9ea'}

Whereas if I use the tweet_mode parameter for the api.search method this error is not returned.

**Comment by MartinBeckUT** [comment]
While the search methods don't allow you to send the tweet_mode parameter, when you use the search methods and tweets are truncated, the data response still contains the extended_tweet.full_text attributes.

When I pulled data from the list of tweet objects I checked if it was truncated and pulled out full_text through indexing.

`for i, tweet in enumerate(tweets):
    print(i)
    if tweet.truncated:
        print(tweet.extended_tweet['full_text'])
    else:
        print(tweet.text)`

**Comment by andypiper** [comment]
This is expected behaviour - the premium API doesn't need the `tweet_mode` parameter, as the extended object is served by default. Equally, in the new v2 API, there's also no concept of an extended Tweet any more, as all Tweets contain the full text by default. The `tweet_mode` option was only added to the legacy 1.1 API in order to maintain backward compatibility for apps that were never updated to deal with more than 140 characters of text.
