### ISSUE TITLE
AttributeError: 'API' object has no attribute 'search_full_archive'

### ISSUE THREAD

**Issue by ajc356** [tweepy/tweepy#1462]
I'm having problems accessing historical content using both of the new search_full_archive and search_30_day features. I've updated tweepy to Version: 3.9.0, yet still when I try to run either `api.search_full_archive `or `api.search_30_day` I get AttributeError: 'API' object has no attribute 'search_full_archive'... however when I do the equivalent search using regular `api.search` I get results as expected. 

I will note that I am using the free sandbox versions and do have different environment names for my 30-days sandbox and my full-history sandbox.

Any thoughts?
```

api = tweepy.API(auth, parser=tweepy.parsers.JSONParser(), wait_on_rate_limit=True, wait_on_rate_limit_notify=True)

test = api.search_30_day(environment_name='30daycerb', q = '#cerb')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-73-0b2b236c134b> in <module>
----> 1 test = api.search_30_day(environment_name='30daycerb',
      2                                             q = '#cerb')

AttributeError: 'API' object has no attribute 'search_30_day'

```

```
my_new_tweets = api.search_full_archive(environment_name='cerbhistory', query='#CERB')

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-74-c8e25af8d1ef> in <module>
----> 1 my_new_tweets = api.search_full_archive(environment_name='cerbhistory', query='#CERB')

AttributeError: 'API' object has no attribute 'search_full_archive'
```

**Comment by sdelgadoc** [comment]
For some reason, the latest tweepy package doesn't ship with the latest version of the api.py file, which includes the search_30_day, and search_full_archive methods.

However, the latest version of the code on GitHub does include these methods.

To solve your issue try uninstalling tweepy:

`pip uninstall tweepy`

and then install it directly from GitHub:

`pip install git+https://github.com/tweepy/tweepy.git`


This fixed the issue for me, and I hope it does for you too.

**Comment by AndChen153** [comment]
> For some reason, the latest tweepy package doesn't ship with the latest version of the api.py file, which includes the search_30_day, and search_full_archive methods.
> 
> However, the latest version of the code on GitHub does include these methods.
> 
> To solve your issue try uninstalling tweepy:
> 
> `pip uninstall tweepy`
> 
> and then install it directly from GitHub:
> 
> `pip install git+https://github.com/tweepy/tweepy.git`
> 
> This fixed the issue for me, and I hope it does for you too.

I had the same issue with the search methods and this solved it for me too thanks for the help!

**Comment by Harmon758** [comment]
`API.search_full_archive` and `API.search_30_day` are currently only in the development version on the master branch.
In the future, please make sure you're using the latest development version when reporting issues.

See [the installation instructions in the documentation](https://tweepy.readthedocs.io/en/latest/install.html) for how to install from the repository.

> To solve your issue try uninstalling tweepy:
> 
> `pip uninstall tweepy`
> 
> and then install it directly from GitHub:
> 
> `pip install git+https://github.com/tweepy/tweepy.git`

Uninstalling to reinstall shouldn't be necessary; using the `--upgrade` flag should work fine.

**Comment by SlyTheFloof** [comment]
broke again lol

**Comment by Cody-coder017** [comment]
Uninstall the present version go for previous versions,might be the present version is a bit unstable
>>  !pip install tweepy==4.0.1

**Comment by Harmon758** [comment]
Please don't necrobump old closed issues.
The latest release of Tweepy, v4.4.0, should be fully stable.
