### ISSUE TITLE
api.list_direct_message() Updates slow?

### ISSUE THREAD

**Issue by lxlGhostlylxl** [tweepy/tweepy#1468]
I think there is some form of lag when trying to use the api.list_direct_message()  method.  When I run this code the ID doesn't change for about 2 or 3 minutes even though there has been a reply.

```
auth = tweepy.OAuthHandler(token[0], token[1])
auth.set_access_token(token[2], token[3])
api = tweepy.API(auth, wait_on_rate_limit=True, wait_on_rate_limit_notify= True)


last_dm = api.list_direct_messages(1)

for messages in last_dm:
    print(messages.message_create['sender_id'])
    if not (messages.message_create['sender_id'] == my_id):
          send_message() 
```
I don't think I did anything wrong.

**Comment by Harmon758** [comment]
This seems to be [a limitation with Twitter's API](https://twittercommunity.com/t/new-direct-message-api-delayed/102122/4) rather than an issue with Tweepy.
