### ISSUE TITLE
cannot query by emoji using search_user

### ISSUE THREAD

**Issue by rbroc** [tweepy/tweepy#1471]
Hi, I'm trying to query users based on the presence of a flag (🇩🇰) emoji in their screen name or description.
I'm using `search_user` to do that, setting `q='🇩🇰'`. 
However, this kind of query returns nothing, nor does the utf encoding obtained via `'🇩🇰'.encode()`, i.e. `b'\xf0\x9f\x87\xa9\xf0\x9f\x87\xb0'`. 
I'm probably missing something obvious here, but what is the correct way of querying this kind of information? I have no issue retrieving result when I run a search on the Twitter website using 🇩🇰 as input. Thanks!

**Comment by Harmon758** [comment]
As far as I can tell, this seems to be an issue with Twitter's API itself not returning any results, rather than an issue with Tweepy.
It might be worth making a forum post at https://twittercommunity.com/c/twitter-api/64 about this.

**Comment by rbroc** [comment]
thanks - seems like user query by regex match in general is a no go, am I right? 
Is there any workaround to get a list of users that match certain regular expressions or search criteria (given that this is possible on web search)?

**Comment by Harmon758** [comment]
> thanks - seems like user query by regex match in general is a no go, am I right?

Yeah, I don't think it's possible at the moment.

> Is there any workaround to get a list of users that match certain regular expressions or search criteria (given that this is possible on web search)?

I don't think there's any good way to do this right now.

I'm going to close this for now, as it does seem to be an issue with Twitter's API:
https://twittercommunity.com/t/cannot-query-by-emoji-using-search-user-through-tweepy/147103
https://twitterdevfeedback.uservoice.com/forums/930250-twitter-api/suggestions/42235918-enable-emoji-based-query-for-user-search
