### ISSUE TITLE
Twitter stream will randomly hang 

### ISSUE THREAD

**Issue by JustinHenderson98** [tweepy/tweepy#1477]
I have been having an issue with the Twitter stream in my script hanging every few hours to months. The stream does not end, does not raise an exception, new tweets just don't come in.  I am running in async mode if that is important.  If there is a way to setup a watchdog timer in the meantime that would be great. I'm tired of getting emails that my website went down and needing to manually restart my script.

**Comment by Harmon758** [comment]
Are you [handling errors](https://tweepy.readthedocs.io/en/latest/streaming_how_to.html#handling-errors) from the Stream Listener?

**Comment by JustinHenderson98** [comment]
I am.  I have
 ```
    def on_error(self, status_code):
        print(status_code)
        if status_code == 420:
            # returning False in on_error disconnects the stream
            return False
```

No status code is printed.

**Comment by Harmon758** [comment]
Are you able to provide a reproducible example (MCVE/SSCCE)?
This issue isn't actionable right now, as I'm unable to reproduce this, and there isn't enough information to determine what the issue might be.
