### ISSUE TITLE
tweets created_at time is off

### ISSUE THREAD

**Issue by asafal172** [tweepy/tweepy#1492]
hi

run this code:

```
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_secret)
api = tweepy.API(auth)

tweet = api.home_timeline()[0]
print(tweet.created_at)

```
the datetime I get is off by 2 hours (tweet was made at 23:00, `created_at` is at 21:00)
I thought the timezone is off, but when i checked it, it was ok
(meaning, when I run `tweet.created_at.astimezone()`
I get "Jerusalem Standard Time", which is currect in my case.)

not sure if thats a real issue or just a confusion of mine.
anyways, I thought I'd better report it.

thanks!

**Comment by Harmon758** [comment]
The `created_at` attribute of a Status/[Tweet object](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/tweet) is the time in UTC when the Tweet was created.
When you printed it, you should have seen that Tweepy returns this as a naive datetime object.
When [`datetime.datetime.astimezone`](https://docs.python.org/3/library/datetime.html#datetime.datetime.astimezone) is used with a naive datetime object, it is presumed to represent time in the system time zone.
