### ISSUE TITLE
Support for Twitter Polls

### ISSUE THREAD

**Issue by PavanaU** [tweepy/tweepy#1497]
Hi Tweepy devs,

Will the Support to create Twitter poll be added?

**Comment by Harmon758** [comment]
This isn't supported by Twitter's API (outside of the Ads API) yet.
See https://twittercommunity.com/t/how-to-create-twitter-poll-card/38368, https://twittercommunity.com/t/polls/75456, and https://twittercommunity.com/t/designing-the-new-engage-endpoints/142766,
