### ISSUE TITLE
odd user_timeline behavior 

### ISSUE THREAD

**Issue by zacharskim** [tweepy/tweepy#1499]
Hi Tweepy Devs!

I've been using the user_timeline method to grab 200 recent tweets from various twitter users. Most of the time it works great! However, I've notice that for some users, it does not work as expected.

`new_tweets = api.user_timeline(screen_name = 'phoebe_bridgers',count=200)
`
The above line of code results in an empty list for some reason. (No errors thrown) 

`new_tweets = api.user_timeline(screen_name = 'elonmusk',count=200)
`
This line of code results in list of with a length of 200.

Using the following twurl command, I'm able to get a json response for the user @phoebe_bridgers so I'm not sure why the method is behaving in this way. 

`twurl /1.1/statuses/user_timeline.json?screen_name=phoebe_bridgers`

Thanks!
Matt

**Comment by Harmon758** [comment]
What is `phoebe_bridgers` set to?

**Comment by zacharskim** [comment]
> What is `phoebe_bridgers` set to?

Ops  edited it to make it clear that both 'phoebe_bridgers' and 'elonmusk' are strings.

**Comment by Harmon758** [comment]
I can't reproduce this:
```py
>>> new_tweets = api.user_timeline(screen_name = 'phoebe_bridgers',count=200)
>>> len(new_tweets)
199
```

**Comment by zacharskim** [comment]
Hmm. I guess it is an issue within the script that I call that line of code in that causes it to act that way? Because when I run it by itself it works just as you showed but when I run it in my overall program it produces an empty list. 

Not sure what the discrepancy is but I'm convinced it's somewhere in my code now. Thanks
