### ISSUE TITLE
API.media_upload still doesn't allow uploading animated GIFs > 5 MB in size.

### ISSUE THREAD

**Issue by tanjyeyee** [tweepy/tweepy#1501]
I've updated my Tweepy to the latest version (3.10.0).

When I try to upload an animated GIF that's larger than 5 MB, I get the following error:

`TweepError([{'code': 324, 'message': 'Image file size must be <= 5242880 bytes'}])`

Which is super-strange, because I dove into `api.py` and confirmed that it should allow animated GIFs up to 15 MB in size.

My files are definitely GIF mimetype, file extension .gif.

I also did this:

```
import imghdr

print(imghdr.what('<path to my GIF file>')
```

It spit out 'gif' and so should allow a higher file size limit in both `media_upload()` and also `_pack_image()` in api.py.

Am I missing something here?

**Comment by tanjyeyee** [comment]
Nevermind, I resolved it.

I should have used:

```
python -m pip install --upgrade tweepy
```

I had 2 versions of Python installed.

My Python was importing modules from a different site-packages path.

**Comment by tanjyeyee** [comment]
Actually, I discovered that the error occurred because Tweepy uses the wrong endpoint to try to upload GIFs >5 MB in size.

According to the Twitter API documentation, you have to use chunked media upload to upload larger GIFs, instead of the regular media upload endpoint: https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/api-reference/post-media-upload

("Please note that to upload videos or GIFs (tweet_video, amplify_video, and tweet_gif), you need to use the chunked upload end-point.")

Can someone fix this bug?

**Comment by Harmon758** [comment]
The video-upload branch / pull request #1486 should resolve this and should be complete now.
Any feedback or review would be appreciated.

**Comment by Harmon758** [comment]
That is an error from Twitter and is different from this issue involving chunked media upload.

From the Animated GIF recommendations section of the [Twitter API documentation's Media Best Practices guide for uploading media](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/media-best-practices):
> In order to process larger GIFs, use the [chunked upload endpoint](https://developer.twitter.com/en/docs/media/upload-media/api-reference/post-media-upload-init.html) with the `media_category` parameter. This allows the server to process the GIF file asynchronously, which is a requirement for processing larger files. Pass `media_category=tweet_gif` to enable async upload behavior for Tweets with an animated GIF.

For more information, see that section and the Media Categories section of that documentation.
