### ISSUE TITLE
Pin message 

### ISSUE THREAD

**Issue by vsnz** [tweepy/tweepy#1502]
Hi,

I was wondering if I am able to also Pin a message via the API?

Thanks for your help.

**Comment by Harmon758** [comment]
No, this isn't possible with Twitter's API.
See https://twittercommunity.com/t/pin-a-tweet-with-the-twitter-api/13048 and https://twitterdevfeedback.uservoice.com/forums/930250-twitter-api/suggestions/41253373-pin-unpin-tweets.

**Comment by vsnz** [comment]
Ok. Thanks for the quick response.
