### ISSUE TITLE
How would you be able to extract the link embedded into the tweet?

### ISSUE THREAD

**Issue by jonathanlin-github** [tweepy/tweepy#1514]
Like if I wanted to get the link of a Wired article that the official Wired Twitter account tweeted out of an article, how would I do that?

**Comment by Harmon758** [comment]
If you have the `Status`/[Tweet object](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/tweet), you can use its `entities` attribute to retrieve the [entities object](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/entities#entitiesobject) that contains a `urls` field with [URL objects](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/entities#urls) representing URLs included in the text of a Tweet.
