### ISSUE TITLE
Support for undocumented Bookmark API

### ISSUE THREAD

**Issue by lcheylus** [tweepy/tweepy#1521]
Twitter launched its "Bookmarks" feature in 2018 (tweets saved privately for a user). Get/save/remove bookmark is undocumented in Twitter API but via Web browser debug, we can found some API endpoints for it => see https://gist.github.com/stepney141/c161a83f02c42e161c905249733b9225

In the same way as for favorites, please add methods to get / save / delete bookmark via API endpoints.

**Comment by Harmon758** [comment]
Tweepy won't be implementing any undocumented/unsupported/unofficial parts of the Twitter API, as using these endpoints violates Twitter's [Terms of Service](https://twitter.com/en/tos) and [Developer Policy](https://developer.twitter.com/en/developer-terms/policy).

As for bookmarks specifically, Twitter plans on implementing endpoints to enable creation and consumption of bookmarks, as part of the new v2 API (for support for that, see #1472).

See:
https://twitterdevfeedback.uservoice.com/forums/930250-twitter-api/suggestions/39678766-api-endpoint-for-getting-bookmarks
https://trello.com/c/qztXMWCK/76-bookmarks-v2-twitter-api
https://twittercommunity.com/t/add-api-to-retrieve-and-delete-twitter-bookmark/142091
https://twittercommunity.com/t/bookmarks-api-updates/140498
