### ISSUE TITLE
HTTPConnectionPool and OSErrors. How to handle?

### ISSUE THREAD

**Issue by trevtravtrev** [tweepy/tweepy#1528]
I've gotten 2 strange errors below that I've never seen before when running my tweepy driven programs. They are being caught as a tweepy.TweepError exception. The except block should catch and ignore these 2 following errors yet they still cause the program to crash. It seems strange to me that they are a tweepy.TweepError exception and not a broad exception and I fear it could be hidden under the tweepy hood. Is there a way to specifically catch and handle each of the following errors?

Error 1:
`_tweepy_error_handler caught Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/friends/ids.json?cursor=-1&screen_name=blahblahblah&count=5000 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xb570c0b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
`

Error 2:
`_tweepy_error_handler caught Failed to send request: ('Connection aborted.', OSError(0, 'Error'))`

**Comment by Harmon758** [comment]
Closing this in favor of #1606
