### ISSUE TITLE
AttributeError: module 'tweepy' has no attribute 'StreamListener'

### ISSUE THREAD

**Issue by jauntyd** [tweepy/tweepy#1531]
Hello:

**AttributeError: module 'tweepy' has no attribute 'StreamListener'**

Here is my relevant code, which is from the example on the tweepy docs page.

import tweepy

class MyStreamListener(tweepy.StreamListener):
        myStreamListener = MyStreamListener()
        myStream = tweepy.Stream(auth = api.auth, listener=myStreamListener)
        myStream.filter(track=['python'])

FreeBSD 12.2-RELEASE/Django 3.1.6/Tweepy 3.10

Let me know if I can help myself help myself by answering any questions!

John

**Comment by Harmon758** [comment]
Are you using v3.10 installed from the latest version on PyPI or the development version from the master branch?

**Comment by jauntyd** [comment]
Master branch

**Comment by Harmon758** [comment]
I've refactored the code for streaming in the master branch.
`StreamListener` has been merged into `Stream` with https://github.com/tweepy/tweepy/commit/39abff4520e291180425ac2219d1d8597ac5da96, so you can simply subclass `Stream` instead.
There's other simplifications and improvements I've made as well.
I haven't updated the documentation yet, but I'll be doing so prior to v4.0 being released.
For now, you can refer to https://github.com/tweepy/tweepy/blob/master/tweepy/streaming.py and its docstrings.

**Comment by jauntyd** [comment]
Thank ya.

**Comment by Harmon758** [comment]
No problem. I'm going to leave this open to track the documentation update.

**Comment by Harmon758** [comment]
I've added documentation for `API.stream` with https://github.com/tweepy/tweepy/commit/18a6059e7980de7759be126ffe39836494cc4f23 and rewritten the guide to streaming with https://github.com/tweepy/tweepy/commit/bf641965278d2486cebef45bb940e2d2e691d420.
