### ISSUE TITLE
setting include_rts arg as "True" in API.user_timeline method causes no tweets to appear when using Cursor

### ISSUE THREAD

**Issue by ancientjpeg** [tweepy/tweepy#1532]
Issue is as described in title. Expected function to work normally, but when include_rts argument is passed as True, iterating through the Cursor for user_timeline will show no tweets. 

**NOTE**: this issue only arises when a since_id argument is passed as well. issue began only recently, without any change to the installed version of tweepy.

relevent code is as follows (from a member function of a class):
```python
import tweepy

def get_all_target_statuses(self, exRep = True, incRT = False):
        allID = []
        if self.debug: print('looking for target user tweets')
        #checks for since_id
        if self.__since_id:
            if self.debug: print(f'using a since_id: {self.__since_id}')
            cursor = tweepy.Cursor(self.__api.user_timeline, screen_name = 'traceybrakes', exclude_replies = exRep, since_id = self.__since_id).items()
        else: 
            cursor = tweepy.Cursor(self.__api.user_timeline, user_id = self.__targetID, exclude_replies = exRep).items()
        if self.debug: print( f"beginning target user tweet find loop" )
        for status in cursor:
            if self.debug: print( f"Found tweet from target user, text = {status.text}" )
            allID.append( status.id )
        return allID
```

when self.__since_id is not None, cursor will not contain any statuses. Temporary fix is possible by replacing the code within the for-loop iterating through the Cursor with the following:

```python
if status.text[:2] != 'RT': #this is a hotfix to deal with some broken functionality in the 'include_rts' field in tweepy
    if self.debug: print( f"Found tweet from target user, text = {status.text}" )
    allID.append( status.id )
```

Apologies if my code is sloppy, I'm new to Python!

**Comment by Harmon758** [comment]
I'm unable to reproduce this.
Can you provide a reproducible example (MCVE/SSCCE)?
Your code doesn't seem to use `include_rts` at all.

Setting `include_rts` as both boolean `True` and `"True"` as a string for `API.user_timeline` with a `Cursor` works as expected:
```py
>>> tweets = []
>>> for tweet in tweepy.Cursor(api.user_timeline, screen_name="Twitter", include_rts="True").items(100):
...     tweets.append(tweet)
...
>>> len(tweets)
100
>>> tweets = []
>>> for tweet in tweepy.Cursor(api.user_timeline, screen_name="Twitter", include_rts=True).items(100):
...     tweets.append(tweet)
...
>>> len(tweets)
100
```
Doing so while also passing `since_id` and using the screen name in your code also works as expected:
```py
>>> tweets = []
>>> for tweet in tweepy.Cursor(api.user_timeline, screen_name="traceybrakes", include_rts=True).items(101):
...     tweets.append(tweet)
...
>>> tweets[100].id
1362659339723563008
>>> tweets = []
>>> for tweet in tweepy.Cursor(api.user_timeline, screen_name="traceybrakes", include_rts=True, since_id=1362659339723563008).items(100):
...     tweets.append(tweet)
...
>>> len(tweets)
100
>>> tweets = []
>>> for tweet in tweepy.Cursor(api.user_timeline, screen_name="traceybrakes", include_rts="True", since_id=1362659339723563008).items(100):
...     tweets.append(tweet)
...
>>> len(tweets)
100
```
Additionally, even your code that uses `exclude_replies` rather than `include_rts` works as expected:
```py
>>> tweets = []
>>> for tweet in tweepy.Cursor(api.user_timeline, screen_name="traceybrakes", exclude_replies=True, since_id=1362659339723563008).items(100):
...     tweets.append(tweet)
...
>>> len(tweets)
20
```

**Comment by ancientjpeg** [comment]
Hi,

I've actually found in testing that the issue arises from two issues that aren't from the include_rts field, but a combination of two things:

1. applying a since_id 
2. using my friend's twitter ID

I have tested using IDs from multiple other accounts, and it works as expected. Addtionally, if I forgo using a since_id, it works as expected. I have a feeling that I've hit some sort of rate limit issue. Here's the simplified code I used to test the issue:

```python
target = #some user id
since = #some status id

cursor_with_since = tweepy.Cursor(api.user_timeline, 
    user_id = target, 
    exclude_replies = True,
    include_rts = False, 
    since_id = since).items() 

cursor_without_since = tweepy.Cursor(api.user_timeline, 
    user_id = target, 
    exclude_replies = True,
    include_rts = False).items()


print('starting first loop')
for status in cursor_with_since:
        print( f"Found tweet from target user (with since_id), text = {status.text}" )

print('starting second loop')
for status in cursor_without_since:
        print( f"Found tweet from target user (without since_id), text = {status.text} id = {status.id}" )
```

I'm going to close this issue and do some more thorough testing on my end, if at all possible I'd kindly ask if you could delete/edit your response to remove the username that was present from my code for privacy reasons! I posted this a bit too hastily and realized I didn't ask my friend if I could post her username in this issue. Thank you so much for your help!

**Comment by Harmon758** [comment]
This is still not a reproducible example without the IDs that you're using.

> I have a feeling that I've hit some sort of rate limit issue.

It's more likely that there's simply no Tweets since that ID by that user.

> I'd kindly ask if you could delete/edit your response to remove the username that was present from my code for privacy reasons

I've done so, but note, it's still in your original issue comment.
