### ISSUE TITLE
Ignore user replies in streaming?

### ISSUE THREAD

**Issue by flower-pixel** [tweepy/tweepy#1541]
edit:  nm  I'll just ignore status that starts with '@'

**Comment by ThomasH-Dev** [comment]
Could I ask how you specifically filter out certain words?

**Comment by Harmon758** [comment]
You can check the `in_reply_to_status_id`, `in_reply_to_status_id_str`, `in_reply_to_user_id`, `in_reply_to_user_id_str`, or `in_reply_to_screen_name` attribute of the Status/[Tweet object](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/tweet) to determine if it's a reply or not.
