### ISSUE TITLE
"TweepError: media type unrecognized" when trying to upload WebP file

### ISSUE THREAD

**Issue by damien-devpy** [tweepy/tweepy#1542]
Hello,

I'm encountering the above error trying to upload WebP file with this simple code : (Work just fine with a jpeg file)

```python
>>> with open('output.webp', 'rb') as f:
...     api.media_upload('output.webp', file=f)
```
The full traceback is below : 

```python
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/.../lib/python3.8/site-packages/tweepy/api.py", line 242, in media_upload
    return bind_api(
  File "/.../lib/python3.8/site-packages/tweepy/binder.py", line 253, in _call
    return method.execute()
  File "/.../lib/python3.8/site-packages/tweepy/binder.py", line 234, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: media type unrecognized.
```
I've already search through other issues, the best that i've found is that WebP file are now supported by Tweepy since December 2020.
This might be important, but the webp file is an output of the pillow library (fork from PIL)

The install version of Tweepy is 3.10.0

Thank you for your help.

Best regards.

**Comment by Harmon758** [comment]
This is an error from Twitter's API rather than Tweepy, and I'm unable to reproduce this with https://www.gstatic.com/webp/gallery/1.webp (from https://developers.google.com/speed/webp/gallery1).
Are you sure the issue isn't with the image itself?

**Comment by damien-devpy** [comment]
I'm trying ASAP with your file. Thanks for your response.

**Comment by damien-devpy** [comment]
It work like a charm with some random webp file. The problem is probably the way pillow output webp images. Sorry for bothering you ! And thanks for your response.
