### ISSUE TITLE
API.update_status() endpoint producing 404 errors very frequently.

### ISSUE THREAD

**Issue by tanjyeyee** [tweepy/tweepy#1547]
I use Celery to send out tweets for my scheduling app.

This has been getting worse lately, but it's probably because Celery is attempting to send out too many tweets at once?

I don't know.

The returned error is:

"Twitter error response: status code = 404"

It makes no sense to get that error; each time I retry it, it works.
My scheduler has retry mechanisms, but I'd like to prevent this in the first place if possible.
I don't think I'm hitting any rate limits yet.

Anyone else experiencing the same issue?

**Comment by Harmon758** [comment]
I'm unable to reproduce this. 
Can you provide a reproducible example (MCVE/SSCCE)?
It might also be helpful if you can catch the exception and use it to determine the text of the response.

**Comment by tanjyeyee** [comment]
> I'm unable to reproduce this.
> Can you provide a reproducible example (MCVE/SSCCE)?
> It might also be helpful if you can catch the exception and use it to determine the text of the response.

Honestly, it's sporadic and right now I can't reproduce it either.

I'll let you know if I catch it again.
