### ISSUE TITLE
user_timeline [0] returning random tweets ! 

### ISSUE THREAD

**Issue by Hamze24w** [tweepy/tweepy#1548]
my code sends me tweets from the people that I add their username to it . 
this piece of code is what I use to get the last tweet :
`user = api.get_user("elonmusk")
twit = api.user_timeline(id=user.id, count=1, tweet_mode="extended")[0]
temp = twit.retweeted_status.full_text if twit.full_text.startswith("RT @") else twit.full_text`

the issue is that for some people (ex: Elon Musk, Trump). it sends random tweets from long ago instead of the last one on some runs. the code keeps running with multithread.  
for others is okay but it's stuck for Elon I keep getting repeat tweets. I looked around and could not found a similiar issue or solution on the web.

**Comment by Harmon758** [comment]
I'm unable to reproduce this:
```py
>>> user = api.get_user("elonmusk")
>>> twit = api.user_timeline(id=user.id, count=1, tweet_mode="extended")[0]
>>> temp = twit.retweeted_status.full_text if twit.full_text.startswith("RT @") else twit.full_text
>>> temp
'The simulation really struggled to make this look real haha https://t.co/t8zvFTRUHU'
```

Can you provide a reproducible example (MCVE/SSCCE) of what you're encountering?

Additionally, if you're only retrieving the user object for its ID, that shouldn't be necessary, as you can pass the screen name directly to [`API.user_timeline`](https://tweepy.readthedocs.io/en/latest/api.html#API.user_timeline).

Also, it would probably be safer to simply check for the existence of the `retweeted_status` attribute rather than using `startswith` with the text of the Tweet.

For code block usage, see https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks.

**Comment by Hamze24w** [comment]
ok so I made this little piece of code so you can reproduce the issue 

```python

last = ""
while True:
    time.sleep(0.5)
    user = api.get_user('elonmusk')
    twit = api.user_timeline(id=user.id, count=1, tweet_mode="extended")
    if len(twit) > 0:
        twit = twit[0]
    else: continue
    temp = twit.retweeted_status.full_text if twit.full_text.startswith("RT @") else twit.full_text
    if temp != last:
        print(temp)
        last = temp

```

now I realise this could take a while, but in my runs, it started happening in a few minutes.
in my program I have a 30s timer, and I have a loop to go over the people in the list, something like this:

```python

last = ""
while True:
    time.sleep(30)
    for person in people:
        user = api.get_user('elonmusk')
        twit = api.user_timeline(id=user.id, count=1, tweet_mode="extended")
        if len(twit) > 0:
            twit = twit[0]
        else: continue
        temp = twit.retweeted_status.full_text if twit.full_text.startswith("RT @") else twit.full_text
        if temp != (this person's)last:
             print(temp)
             last = temp

```

**Comment by Hamze24w** [comment]
the interesting thing is that for all the people I have in my list, this only happens with Elon Musk (and it used to happen with Trump but I removed him)

**Comment by Harmon758** [comment]
This seems to be an eventual consistency issue with Twitter's API rather than an issue with Tweepy.
See https://twittercommunity.com/t/inconsistent-tweet-retrieval/150635.
