### ISSUE TITLE
How do I handle these 2 tweepy errors causing my script to crash?

### ISSUE THREAD

**Issue by trevtravtrev** [tweepy/tweepy#1555]
These 2 errors occasionally cause my script to crash. These are being caught as tweep errors, I'm not sure how to handle them or keep them from causing my script to crash.  Ideally I'd like my script too ignore them and try again. Has anyone encountered these before?

P.S. My script already ignores ALL tweep errors it catches except a couple specific ones such as api code '63'. These should be ignored by my script since they are not one of these specific codes I am looking for yet they are still causing the script to crash.

Error 1:
`Failed to send request: ('Connection aborted.', OSError(0, 'Error'))`

Error 2:
`Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/friends/ids.json?cursor=-1&screen_name=helloworld&count=5000 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0xb570c0b0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution'))
`

**Comment by Harmon758** [comment]
Closing this in favor of #1606
