### ISSUE TITLE
The function tweet_mode = 'extended' does not work

### ISSUE THREAD

**Issue by AvidCoder08** [tweepy/tweepy#1562]
The `tweet_mode = 'extended'` function does not work when used with the tweepy.Cursor function. The extended tweet when downloaded shows only 140 characters
<img width="960" alt="Screenshot 2021-04-03 165714" src="https://user-images.githubusercontent.com/68290597/113477164-b1e0ad00-949d-11eb-9503-7491f365b318.png">

**Comment by Harmon758** [comment]
> When using extended mode with a Retweet, the `full_text` attribute of the Status object may be truncated with an ellipsis character instead of containing the full text of the Retweet. However, since the `retweeted_status` attribute (of a Status object that is a Retweet) is itself a Status object, the `full_text` attribute of the Retweeted Status object can be used instead.

https://tweepy.readthedocs.io/en/latest/extended_tweets.html#handling-retweets
