### ISSUE TITLE
Unable to upload video in Tweepy

### ISSUE THREAD

**Issue by layilpaht** [tweepy/tweepy#1564]
Hi,
I am new to twitter.I was experimenting with api but I faced a wall
Exception has occurred: TweepError
Invalid file type for image: video/mp4

Why I am unable to upload video? Image is working just fine.

**Comment by layilpaht** [comment]
tweepy==3.10.0

Version.If it is old then please guide me in installing the latest one. I tried through pip but it is already updated

**Comment by Harmon758** [comment]
Video upload support was only just added with #1486.
The PR was only just merged into the master branch today, and there hasn't been a release yet.
