### ISSUE TITLE
alt_text missing

### ISSUE THREAD

**Issue by rola93** [tweepy/tweepy#1570]
Hello, I'm using tweepy 3.10 and I need to check whether a tweet contains images or not, and in case that images are included, if alt_text is given too.

However, I found some tweets does contain image and alt_text but doesn't I can't get it with the API.

[Consider this twet](https://twitter.com/IDATHAuy/status/1383120257565474816): I get it with the following line:

```python
status = api.get_status(tweet_id, include_ext_alt_text=True, include_entities=True)
```

But `status` object does not contain `extended_entities` attribute, so I can't go to `status.extended_entities['media'][0]['ext_alt_text']` to get alt_text. Notice that this work for some other cases like [this](https://twitter.com/amendaroUY/status/1382138812571193345).

Any ideas? my full code is [here](https://github.com/rola93/altBot/blob/1b44ae424a952c75e8ba29ad98e2f2d8d306f9fc/altBot_main.py#L271) if you want to check it, any help is appreciated.

thanks!

**Comment by Harmon758** [comment]
You'll want to use extended `tweet_mode`.
See [the section in the documentation about extended Tweets](https://tweepy.readthedocs.io/en/latest/extended_tweets.html).
