### ISSUE TITLE
Rate limits remaining of Twitter API v2

### ISSUE THREAD

**Issue by rnakashiro** [tweepy/tweepy#1580]
Hi, using Twitter API v2, 
I found that we couldn't confirm remaining of rate limits by each response with `tweepy/client.py`.

Rate limits doc:
https://developer.twitter.com/en/docs/twitter-api/rate-limits

So, I'd like to propose to extend `tweepy/client.py` a little below.

```python
# before
Response = namedtuple("Response", ("data", "includes", "errors", "meta"))

# after
Response = namedtuple("Response", ("data", "includes", "headers", "errors", "meta"))
```

And just add the `headers` of `requests.response` into `Response` in `Client._make_request` method.

Then, we can check the remaining of rate limits for each endpoint's return value, such as `response.headers['x-rate-limit-remaining']`.
I'd be grateful if you could look into that 😄

**Comment by Harmon758** [comment]
What's your use case for this?
I'm considering instead adding a Client parameter/attribute that allows setting the response type, so that it can be a `requests.Response`.

**Comment by rnakashiro** [comment]
Thank you for reply.

The use cases are, to show rate-limits for users, to prevent 429 response before API call when remaining are 0, and so on.

Official Twitter API provides a way to check rate-limits for every response, so this lib is ideal to inherit the Twitter's feature 😄

**Comment by Harmon758** [comment]
That's not really related to this issue, but support for API v2 is only in the development version on the master branch right now, yes.

**Comment by rnakashiro** [comment]
Oh, sorry.
I'm using with commit-hash `git+https://github.com/tweepy/tweepy.git@9a28e0eaa7329918bfbf19e08afccb473210a2d1` in requirements.txt, and reviewed this lib's code on Github.

I'm interested in Twitter API v2's arrival and this lib's support.
So, I proposed  a little change. 😄
