### ISSUE TITLE
can you help me about fleet api?

### ISSUE THREAD

**Issue by rhatami7495** [tweepy/tweepy#1589]

**Comment by Harmon758** [comment]
If you're referring to Twitter Fleets, that's not something Twitter's API supports.
See:
https://twittercommunity.com/t/will-twitter-api-support-fleets/145710
https://twittercommunity.com/t/failed-to-request-fleets/146278
https://twitterdevfeedback.uservoice.com/forums/930250-twitter-api/suggestions/41994790-fleets
