### ISSUE TITLE
Documentation site is ahead of current PyPI version

### ISSUE THREAD

**Issue by hkennyv** [tweepy/tweepy#1596]
I'm not sure if this is intended, but the link to the tweepy docs from <https://www.tweepy.org/> link to docs that are up-to-date with the latest commit on the `master` branch.

This is slightly confusing for people who are installing from PyPI: <https://pypi.org/project/tweepy/> since it looks like the package is in the middle of a major version bump so the docs have some API breaking differences (`tweepy.Stream` was the one I ran into).

Ultimately, I was able to find the docs for v3.10.0 here: <https://docs.tweepy.org/en/v3.10.0/> and that's been working for me. Just thought I'd give a heads up to any other people who may run across this.

**Comment by Harmon758** [comment]
I've changed the default Read the Docs version to `stable`.

**Comment by hkennyv** [comment]
@Harmon758 thanks! awesome job on the docs btw, definitely a huge improvement IMO.
