### ISSUE TITLE
Reply_count documentation update 

### ISSUE THREAD

**Issue by Gaurav7888** [tweepy/tweepy#1598]
Reply_count 
print(status.reply_count)
AttributeError: 'Status' object has no attribute 'reply_count'

**Comment by Harmon758** [comment]
As [Twitter's API documentation for Tweet objects](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/tweet) says about the `reply_count` attribute:
> Note: This object is only available with the Premium and Enterprise tier products.
