### ISSUE TITLE
New at Python - downloading a list of friends from a list of accounts

### ISSUE THREAD

**Issue by DV777** [tweepy/tweepy#1599]
Hello, as mentioned in the title I am entirely new at Python, basically know how to adapt scripts, create loops and using pandas... 

I am trying to obtain the complete list of friends and followers from a specific set of accounts as part of my research project (I am a PhD student). Is it possible with Tweepy ? I really don't get how to do it from the documentation and feel quite dumb each time I look at it.

I have my tokens (I generated a standalone app) but apart from authenticating myself, I cannot do anything with Tweepy...

Thanks in advance to the (very) patient person who will manage to help me.
```
access_token='*'
access_token_secret='*'
consumer_key='*'
consumer_secret='*'
bearer_token='*'
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth, wait_on_rate_limit=True)
try:
    redirect_url = auth.get_authorization_url()
except tweepy.TweepError:
    print('Error! Failed to get request token.')
api.update_status('tweepy + oauth!')

def limit_handled(cursor):
    while True:
        try:
            yield cursor.next()
        except tweepy.RateLimitError:
            time.sleep(15 * 60)

for friend in tweepy.Cursor(api.friends).items():
    # Process the friend here
    process_friend(friend)   

for follower in limit_handled(tweepy.Cursor(api.followers).items()):
    print(follower.screen_name)

**Comment by Harmon758** [comment]
> Is it possible with Tweepy ?

Yes

Is there a specific issue you're encountering? What is `process_friend`?

**Comment by DV777** [comment]
> > Is it possible with Tweepy ?
> 
> Yes
> 
> Is there a specific issue you're encountering? What is `process_friend`?

Actually I cannot manage to write a script to scrap all these friends and followers. "process_friend" was in the original example provided in the doc, I thought it was mandatory to include it smh but it's actually just an undefined variable 👍

**Comment by Harmon758** [comment]
From this, `process_friend` is an undefined function, yes.
Otherwise, this is fine for iterating through friends and followers.
Feel free to ask about any specific issues you have.
