### ISSUE TITLE
API.get_direct_messages() not working

### ISSUE THREAD

**Issue by jaimindp** [tweepy/tweepy#1601]
I would like to read my direct messages however the call API.get_direct_messages() returns:

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-c391746a4afb> in <module>
----> 2 API.get_direct_messages()

AttributeError: 'API' object has no attribute 'get_direct_messages'

My permissions are correct as I can send messages to other users. Any ideas of why this might be?

Thanks in advance

**Comment by jaimindp** [comment]
My bad, I was looking at old documentation. API.list_direct_messages() is working

**Comment by Harmon758** [comment]
`API.list_direct_messages` was actually renamed to `API.get_direct_messages` with https://github.com/tweepy/tweepy/commit/ff1186f80b2dbb7f5e4ed3669d90db300e8de36d, and the latest documentation is up to date with that change. `API.get_direct_messages` should work with the development version on the master branch, and any documentation with `API.list_direct_messages` would be the "old documentation".
