### ISSUE TITLE
tweepy.errors.Forbidden when using Client.follow()

### ISSUE THREAD

**Issue by euglevi** [tweepy/tweepy#1612]
First of all, thank you for the amazing library.

When using the Client.follow(target_user_id) method for following someone, I get the following error:

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    client.follow(outcome.data.id)
  File "/home/eugenio/Dropbox/narratives_immigration/twitter/code/venv/lib/python3.9/site-packages/tweep
y/client.py", line 958, in follow
    return self._make_request(
  File "/home/eugenio/Dropbox/narratives_immigration/twitter/code/venv/lib/python3.9/site-packages/tweep
y/client.py", line 144, in _make_request
    response = self.request(method, route, params=request_params,
  File "/home/eugenio/Dropbox/narratives_immigration/twitter/code/venv/lib/python3.9/site-packages/tweep
y/client.py", line 105, in request
    raise Forbidden(response)
```
My code is simply:

```
client = tweepy.Client(bearer_token, consumer_key, consumer_secret, key, secret)
client.follow(******)
```
If I got this correctly, the error here does not relate to the authentication procedure but to specific authorizations of the app. Is there a possibility to get a more specific error message from Twitter? Does Tweepy allow for retrieving it? I could not find any reference in the documentation while finding on the Twitter website that usually this error comes with an explanation.

**Comment by Harmon758** [comment]
If the API provides an error code and/or message, it should be included in the string representation, but I don't think it does in this case. You can handle the `Forbidden` error and access the `requests.Response` with its `response` attribute, and that does still need to be documented, but in this case, the body of the response isn't very helpful:
```py
>>> try:
...     client.follow(user_id)
... except tweepy.Forbidden as e:
...     print(e.response.json())
...
{'title': 'Forbidden', 'type': 'about:blank', 'status': 403, 'detail': 'Client Error'}
```

**Comment by euglevi** [comment]
Thank you very much. Your answer was very helpful. I got exactly that type of response which made me realize that something with the app authorizations was wrong.

**Comment by grass-shack-studio** [comment]
how do you take an "Error 139" and use it to skip that account and move to the next account without breaking? I have a bot that is going through looking for certain hashtags and when it finds them it follows the account and favorites the tweet. when it come across tweets that it has already liked it totally breaks. i want it to skip that account and move on. any help or insight is greatly appreciated.

**Comment by grass-shack-studio** [comment]
figured it out. nevermind
`import tweepy
from time import sleep
from credentials import *
from config import QUERY, FOLLOW, LIKE, SLEEP_TIME

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

print("Twitter bot which retweets,like tweets and follow users")
print("Bot Settings")
print("Like Tweets :", LIKE)
print("Follow users :", FOLLOW)



for tweet in api.search_tweets(q=QUERY):
    try:
        print('\nTweet by: @' + tweet.user.screen_name)

        # Favorite the tweet
        # check that bot has not already favorited the tweet
        if LIKE:
            if not tweet.favorite:
                tweet.favorite()
                print('Favorited the tweet')

        # Follow the user who tweeted
        # check that bot is not already following the user
        if FOLLOW:
            if not tweet.user.following:
                tweet.user.follow()
                print('Followed the user')

        sleep(SLEEP_TIME)

    except tweepy.TweepError as e:
        print(e.reason)

    except StopIteration:
        break
`

**Comment by grass-shack-studio** [comment]
https://github.com/grass-shack-studio/twitter-bot

**Comment by Harmon758** [comment]
Documentation for `HTTPException`'s attributes have been added with https://github.com/tweepy/tweepy/commit/c62c31a0f3574e04b6e2f5996b90b5c1b5917485.
