### ISSUE TITLE
Calling API.Configuration() Causes a 410 Error Response

### ISSUE THREAD

**Issue by Dev1082** [tweepy/tweepy#1614]
Calling API.Configuration() to get the current Twitter configuration returns a 410 Error.
 
`tweepy.error.TweepError: Twitter error response: status code = 410`

**Comment by Harmon758** [comment]
The Twitter API endpoint it uses was retired recently.
I was waiting until it was to remove it for v4.0.
See https://twittercommunity.com/t/retiring-the-1-1-configuration-endpoint/153319 and https://twittercommunity.com/t/is-the-1-1-configuration-endpoint-retired/155211.
