### ISSUE TITLE
AttributeError: 'API' object has no attribute 'lookup_statuses'

### ISSUE THREAD

**Issue by Cmastris** [tweepy/tweepy#1615]
Hi there,

I've been trying to use the `API.lookup_statuses()` method, as documented here: https://docs.tweepy.org/en/latest/api.html#tweepy.API.lookup_statuses

However, I'm encountering the following error:

`AttributeError: 'API' object has no attribute 'lookup_statuses'`

This is my code:

```
def tweepy_auth():
    """Return an authenticated Tweepy API object."""
    auth = tweepy.OAuthHandler(config.CONSUMER_KEY, config.CONSUMER_SECRET)
    auth.set_access_token(config.ACCESS_TOKEN, config.ACCESS_TOKEN_SECRET)
    return tweepy.API(auth, retry_count=10, retry_delay=30)


API = tweepy_auth()
```
`test_tweets = twitter_auth.API.lookup_statuses([1405193581556637698])`

Other `API` methods seem to be working so I think it's a bug and/or possibly related to the Twitter API migration.

The Twitter docs note that the endpoint has been replaced by V2, but I've seen this notice for other V1 endpoints while the Tweepy method still seems to work: https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/get-statuses-lookup.

Thanks!

**Comment by Harmon758** [comment]
That documentation is for the latest development version on the master branch, where that method was renamed.
See https://github.com/tweepy/tweepy/commit/b442920ea3a19fc91820f43652f03a57c7727224 and #477.

For v3.10.0, the method is `API.statuses_lookup`, the documentation for which can be found at https://docs.tweepy.org/en/v3.10.0/api.html#API.statuses_lookup.

**Comment by Cmastris** [comment]
Ah my bad, thanks!
