### ISSUE TITLE
Chunked media upload not working for GIFs larger than 5.2 MBs

### ISSUE THREAD

**Issue by carlosgnet** [tweepy/tweepy#1624]
I attach two GIF files (9 MBs, and 2 MBs) for testing purposes.

### Discussed in https://github.com/tweepy/tweepy/discussions/1622

<div type='discussions-op-text'>

<sup>Originally posted by **carlosgnet** July 17, 2021</sup>
Hey, I need to use the chunked media upload so I'm using the latest development version:

`tweepy                   4.0.0a0`

But when I try to upload a 9 Mb GIF file (as per Twitter docs: _Image size <= 5 MB, animated GIF size <= 15 MB_) a 400 Bad Request is returned with no additional info:

```
>>>response_media_upload = api.media_upload(filename = "/home/carlos/repos/oneclout/gif_small.gif", chunked = True)
>>>response_media_upload = api.media_upload(filename = "/home/carlos/repos/oneclout/gif_big.gif", chunked = True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/carlos/.local/lib/python3.6/site-packages/tweepy/api.py", line 3403, in media_upload
    additional_owners=additional_owners, **kwargs
  File "/home/carlos/.local/lib/python3.6/site-packages/tweepy/api.py", line 3502, in chunked_upload
    additional_owners=additional_owners, **kwargs
  File "/home/carlos/.local/lib/python3.6/site-packages/tweepy/api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "/home/carlos/.local/lib/python3.6/site-packages/tweepy/api.py", line 3639, in chunked_upload_init
    upload_api=True, **kwargs
  File "/home/carlos/.local/lib/python3.6/site-packages/tweepy/api.py", line 255, in request
    raise BadRequest(resp)
tweepy.errors.BadRequest: 400 Bad Request
```

As you can see, GIFs smaller than 5 Mb are uploaded correctly. Any help would be much appreciated.</div>
![gif_big](https://user-images.githubusercontent.com/18427657/126207674-9b815ea3-3881-45b3-9a66-34a1b4f23c41.gif)
![gif_small](https://user-images.githubusercontent.com/18427657/126207687-16717d25-987f-41b1-be7c-574edbfc6b26.gif)

**Comment by Harmon758** [comment]
You need to pass `media_category`, e.g.:
```py
response_media_upload = api.media_upload(
    filename = "/home/carlos/repos/oneclout/gif_big.gif", chunked = True,
    media_category = "tweet_gif"
)
```

See https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/media-best-practices.
