### ISSUE TITLE
Authentication problem with api.followers_ids

### ISSUE THREAD

**Issue by davera-017** [tweepy/tweepy#1633]
I'm having a problem when using `api.followers_ids`. The code is quite simple:

```python
user_id = 1037141442
followers = api.followers_ids(user_id)
```

I have already test my authentication with:

```python
# test authentication
try:
    api.verify_credentials()
    print("Authentication OK")
except:
    print("Error during authentication")
```

Which prints: `Authentication OK`. 

But still I'm getting this error:
```python
[{'message': 'Your credentials do not allow access to this resource', 'code': 220}]
```

Does somebody knows what I'm doing wrong?

**Comment by Harmon758** [comment]
I'm able to reproduce this. It seems to be an issue with Twitter's API:
https://twittercommunity.com/t/multiple-endpoints-are-failing-across-the-api/157534

**Comment by Harmon758** [comment]
This seems to be resolved now.
