### ISSUE TITLE
Your credentials do not allow access to this resource

### ISSUE THREAD

**Issue by Arshit007** [tweepy/tweepy#1635]

**Comment by Harmon758** [comment]
There is not any information here at all for this issue to be actionable or reproducible.

This is simply the Twitter API error text for code 220, which can be encountered when appropriate, without there being anything amiss with Tweepy or Twitter's API. You probably want to check that your app has the necessary permissions and that you're using the right authentication method.

See https://developer.twitter.com/en/support/twitter-api/error-troubleshooting.
