### ISSUE TITLE
Add support for media_upload for bytes in memory

### ISSUE THREAD

**Issue by pedrohml** [tweepy/tweepy#1645]
### Context

Nowadays the current implementation only supports `media_upload` method for filename / file objects.
To avoid IO latency when posting in memory generated images, it would be good to support byte arrays as input for `media_upload`

Current signature:
```python
def media_upload(self, filename, *args, **kwargs):
  ...
```

Possible signature:
```python
def media_bytes_upload(self, blob: bytes, *args, **kwargs):
  ...
```

**Comment by Harmon758** [comment]
This should already be possible with the `file` parameter of [`API.media_upload`](https://tweepy.readthedocs.io/en/v3.10.0/api.html#API.media_upload) using [`io.BytesIO`](https://docs.python.org/3/library/io.html#io.BytesIO).
