### ISSUE TITLE
full_text parameter does not return the full status

### ISSUE THREAD

**Issue by SimonStaehli** [tweepy/tweepy#1652]
In a personal project I am witnessing following problem:

Minimal Example:
`api = tweepy.API(auth_handler=auth)`
`status = api.get_status(id=1432709418735611912, tweet_mode='extended')`
`print(status.full_text)`

This is what I get as output:
'RT @Dollarcurrency1: SUMMARY OF TODAY SHOW 2021-08-31\nSHARE AND RETWEET\nWATCH THE SHOW: \nhttps://t.co/6brPFX0YDN\n\nGOOGLE DRIVE:\nhttps://t.c…'

Compared to the real tweet:
![image](https://user-images.githubusercontent.com/55585561/131520723-04c21c66-2eb9-4db1-9edd-2cb0802a8e09.png)

This does not return the full status unfortunately, although I put the param tweet_mode='extended'. If I investigate the the attribtue status.truncated, it returns False, which actually is incorrect...

**Comment by Harmon758** [comment]
This is how Twitter's API provides the data and is not an issue with Tweepy.
You can use `status.retweeted_status.full_text` instead.
See the [Handling Retweets section of Tweepy's documentation on extended Tweets](https://tweepy.readthedocs.io/en/v3.10.0/extended_tweets.html#handling-retweets).
