### ISSUE TITLE
Optimizations for Large Video Upload in v4

### ISSUE THREAD

**Issue by ghadlich** [tweepy/tweepy#1658]
When uploading large videos (>15 MB?), I ran into a couple issues:

1) If a video file is big enough, the **media_category** should default to **"tweet_video"** otherwise the finalize will fail (as per https://github.com/twitterdev/large-video-upload-python/blob/master/async-upload.py#L49)
2) Would be nice to default the chunk size to 5 MB if file size is big enough
3) When setting the chunk size from upload_media, it hits a **Unexpected parameter: chunk_size** in https://github.com/tweepy/tweepy/blob/master/tweepy/api.py#L3500 before it is popped in https://github.com/tweepy/tweepy/blob/master/tweepy/api.py#L3509 - maybe those lines can be flipped?

Example mp4 to test on: https://sdo.gsfc.nasa.gov/assets/img/latest/mpeg/latest_1024_0094.mp4

```api.media_upload(image_path, chunk_size=5*1024*1024, media_category="tweet_video")``` seems to work but emits the warning about chunk_size.

**Comment by Harmon758** [comment]
Thanks for the feedback / report.

> 1. If a video file is big enough, the **media_category** should default to **"tweet_video"** otherwise the finalize will fail (as per https://github.com/twitterdev/large-video-upload-python/blob/master/async-upload.py#L49)

Tweepy purposefully does not set a `media_category` by default. There's no way for Tweepy to determine the proper `media_category` for the user without knowing the user's intention for the media in question. For videos, `tweet_video`, `dm_video`, and `amplify_video` are all valid `media_category` values. Twitter's API documentation on this could be better, but I don't think there's anything to be changed about this on Tweepy's end. I might write up some documentation on it for Tweepy at some point, but feel free to PR that if you'd like.

> 2. Would be nice to default the chunk size to 5 MB if file size is big enough

I'm not set on not doing this, but this is probably not going to happen. There are pros and cons to smaller and larger chunk sizes, and it's really up to the user and what they would prefer depending on their situation. Even the current default of 1 MiB is a bit arbitrary, but it's mentioned as an example chunk size in [the Twitter API documentation for the POST media/upload (APPEND endpoint)](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/api-reference/post-media-upload-append) and it seems like a good balance. Having the chunk size be dependent on different ranges of file sizes would make the default even more arbitrary. What file size would be "big enough"? Without any specific and consistent guidelines or recommendations from Twitter API documentation (e.g. https://github.com/twitterdev/large-video-upload-python seems to use a chunk size of 4 MiB for some reason), any answer or range chosen would probably be pretty much completely arbitrary. I think leaving it up to the user to choose the chunk size they'd like to use is probably the best option.

I think `chunk_size` is an undocumented parameter at the moment though, so feel free to PR that if you'd like.

> 3. When setting the chunk size from upload_media, it hits a **Unexpected parameter: chunk_size** in https://github.com/tweepy/tweepy/blob/master/tweepy/api.py#L3500 before it is popped in https://github.com/tweepy/tweepy/blob/master/tweepy/api.py#L3509 - maybe those lines can be flipped?

This is indeed a bug. I'll fix this before v4.0 is released. For now, you can simply ignore the warning.

**Comment by Harmon758** [comment]
#​3 should now be resolved with https://github.com/tweepy/tweepy/commit/e4a588eb3fc5733fca81f67b01eb64e288cb887b.

**Comment by ghadlich** [comment]
Great, thank you! I’ll pull down the changes.

Makes sense on the chunk size, would be nice to have it default internally but might be nice to have. Can always reopen this issue - thanks!
