### ISSUE TITLE
Twitter sunsets V1.1 rate limit reporting?

### ISSUE THREAD

**Issue by NetwarSystem** [tweepy/tweepy#1661]
This snippet of code walks the results of api.rate_limit_status() and prints the ones where the remaining is less than the limit. I use similar constructs to wait for token reloads on large tasks, like getting followers for a popular account.

`zod = api.rate_limit_status()
for zoop in zod['resources']:
    for zord in zod['resources'][zoop]:
        if(zod['resources'][zoop][zord]['remaining'] < zod['resources'][zoop][zord]['limit']):
            print(zord + " " + str(zod['resources'][zoop][zord]['remaining']) + "/" + str(zod['resources'][zoop][zord]['limit']) + " " + str(zod['resources'][zoop][zord]['reset'] - int(time.time())))
`

This code has been stable for several years but overnight it just stopped working. The code runs but it always shows remaining equal to limit. After much frustration, I got the idea it was the API response rather than my code. A quick check of the api.py file from Tweepy shows this:

 `   def __init__(self, auth_handler=None,
                 host='api.twitter.com', search_host='search.twitter.com',
                 upload_host='upload.twitter.com', cache=None, api_root='/1.1',
                 search_root='', upload_root='/1.1', retry_count=0,
                 retry_delay=0, retry_errors=None, timeout=60, parser=None,
                 compression=False, wait_on_rate_limit=False,
                 wait_on_rate_limit_notify=False, proxy=''):
`

I went through api.py, replacing "1.1" with both "2" and "2.0", wiped __pycache__ for the package, the ran the rate check script again. This recompiles the bytecode, repopulating __pycache__, but it generates errors - so not a workable fix.

I was not aware of the wait_on_rate_limit option when creating an API connection, but I'm not at all sure that solves for running out of API tokens in a particular area, and even if it did I still want to be able to quickly determine what resources have been used and how long it will be before they are refilled.

Is there anything I can do to help nail this down?

**Comment by Harmon758** [comment]
Like you imply, this seems to be an issue with Twitter's API rather than Tweepy:
https://twittercommunity.com/t/rate-limit-status-returns-wrong-results/159687
https://twittercommunity.com/t/api-rate-limit-status-is-not-working-tweepy/159688

For code block usage, see https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks.

**Comment by Harmon758** [comment]
This seems to be resolved now.
