### ISSUE TITLE
tweepy.error.TweepError: [{'message': 'Application cannot perform write actions. Contact Twitter Platform Operations through https://help.twitter.com/forms/platform.', 'code': 261}]

### ISSUE THREAD

**Issue by steevenakintilo** [tweepy/tweepy#1663]
I've made a bot who is working well but after a certain amount of time I keep getting this error and I don't know why:

tweepy.error.TweepError: [{'message': 'Application cannot perform write actions. Contact Twitter Platform Operations through https://help.twitter.com/forms/platform.', 'code': 261}]

My code: [https://pastebin.com/XtmEHPFZ](url)

**Comment by Harmon758** [comment]
The most likely cause of Code 261 is:
> The App that you are using with the API does not have the proper [permission level](https://developer.twitter.com/en/docs/apps/app-permissions) set for its access token and access token secret. Please navigate to the 'Keys and tokens' tab on the [Twitter Apps](https://developer.twitter.com/en/docs/apps) dashboard and check the permission levels assigned to your access token and access token secret. If it is set to anything other than 'Read, write and Direct Messages,' then you are going to have to adjust the settings under the 'Permission' tab and regenerate your access token and access token secret to apply the new settings.

https://developer.twitter.com/en/support/twitter-api/error-troubleshooting

This is likely happening when you try to update you status.

**Comment by steevenakintilo** [comment]
Ok I will try thanks for the answer

**Comment by steevenakintilo** [comment]
> The most likely cause of Code 261 is:
> 
> > The App that you are using with the API does not have the proper [permission level](https://developer.twitter.com/en/docs/apps/app-permissions) set for its access token and access token secret. Please navigate to the 'Keys and tokens' tab on the [Twitter Apps](https://developer.twitter.com/en/docs/apps) dashboard and check the permission levels assigned to your access token and access token secret. If it is set to anything other than 'Read, write and Direct Messages,' then you are going to have to adjust the settings under the 'Permission' tab and regenerate your access token and access token secret to apply the new settings.
> 
> https://developer.twitter.com/en/support/twitter-api/error-troubleshooting
> 
> This is likely happening when you try to update your status.

I just what you send so if I understand well I need to pay to have a better api?

**Comment by Harmon758** [comment]
Like it says, you simply need to use the proper permission level. It has nothing to do with paying.

**Comment by steevenakintilo** [comment]
> Like it says, you simply need to use the proper permission level. It has nothing to do with paying.

Ok thanks and I have another question what is the difference between standard app and standalone app?

**Comment by Harmon758** [comment]
That's not relevant to this issue, but see https://developer.twitter.com/en/docs/apps/overview.
