### ISSUE TITLE
On Direct Message not working 

### ISSUE THREAD

**Issue by krisnantobi** [tweepy/tweepy#1671]
Hi As we can see this tweepy update to v4.
and when I look at the method inside the Stream class is no  on_direct_message method like in V3. Is it tweepy v4.0.0 still possible to stream direct message and if not how to approach this  ?

Thank you.

**Comment by generousjj** [comment]
I believe it’s been deprecated, see [https://github.com/tweepy/tweepy/commit/ab2479b15da04c28144c3f4384b7aac71eaa0250](https://github.com/tweepy/tweepy/commit/ab2479b15da04c28144c3f4384b7aac71eaa0250)

**Comment by krisnantobi** [comment]
Yap, but is any alternative for get realtime recieve get direct message in v4 ?

Or we must use the webhook with premiun plan?

**Comment by Harmon758** [comment]
`on_direct_message` was for user streams, the endpoint for which has been deprecated and retired for years now, in favor of the new Account Activity API. The method no longer served a purpose and just hadn't been removed until now.
For Account Activity API support, see #1075.
It is indeed a premium / enterprise API.

**Comment by krisnantobi** [comment]
Ok thanks @Harmon758 , @generousjj .
