### ISSUE TITLE
Stream Listener

### ISSUE THREAD

**Issue by rwanjohi** [tweepy/tweepy#1678]
Can't load StreamListener anymore.Any updates? new location?
 
ImportError: cannot import name 'StreamListener' from 'tweepy.streaming'

**Comment by Harmon758** [comment]
`StreamListener` has been merged with [`Stream`](https://tweepy.readthedocs.io/en/v4.0.1/stream.html#tweepy.Stream) in [Tweepy v4.0.0](https://github.com/tweepy/tweepy/releases/tag/v4.0.0).
