### ISSUE TITLE
Is it possible to support images in jfif format?

### ISSUE THREAD

**Issue by star005** [tweepy/tweepy#1685]
Hello.

This is my first time asking a question, so I apologize if this is weird.
I hired another engineer to use tweepy, and he had a problem where he couldn't download some images.
The reason seems to be that it doesn't support jfif, is it possible to fix it?

Sorry. I'm not an engineer, so I don't know the details.
It would be very helpful if you could help.

**Comment by gregyjames** [comment]
What exactly is the issue that he has with downloading the images? If they are showing in the entities object of the status, he could try downloading those images from those URL directly

**Comment by Harmon758** [comment]
I'm not sure what support for JFIF images means here.
I don't think the Twitter API uses JFIF images anywhere, Tweepy itself does not provide a specific means of downloading images (you can do so using the URLs provided by the Twitter API / Tweepy), and generally, there doesn't need to be "support" for specific file formats when downloading them.
