### ISSUE TITLE
get authenticated user raises NotImplementedError

### ISSUE THREAD

**Issue by moyid** [tweepy/tweepy#1703]
`api.me().screen_name` no longer works, it returns a NotImplementedError. I'm using tweepy 3.10.0

**Comment by Harmon758** [comment]
I'm unable to reproduce this, and it's not possible to determine what's going on without a full traceback and/or the relevant code. Also, Tweepy v3 is no longer supported. You should look into using Tweepy v4.

**Comment by moyid** [comment]
I upgraded to 4.3.0, the API object has no attribute 'me' - Here is the full code and traceback:

```
[in]
import tweepy

read_twitter_api_key = API_KEY
read_twitter_api_secret = API_SECRET

auth = tweepy.AppAuthHandler(read_twitter_api_key, read_twitter_api_secret)
read_api = tweepy.API(auth, wait_on_rate_limit = True)
read_api.me()
```
```
[out]
AttributeError                            Traceback (most recent call last)
<ipython-input-64-9421ad920711> in <module>
----> 1 read_api.me()

AttributeError: 'API' object has no attribute 'me'
```

**Comment by Harmon758** [comment]
[Tweepy v4.0.0](https://github.com/tweepy/tweepy/releases/tag/v4.0.0) removed `API.me`. You can use [`API.verify_credentials`](https://tweepy.readthedocs.io/en/v4.3.0/api.html#tweepy.API.verify_credentials) instead.

See the [relevant section of the FAQ in the documentation](https://tweepy.readthedocs.io/en/v4.3.0/faq.html#where-did-api-me-go).

**Comment by moyid** [comment]
@Harmon758 - I tried this but I get :

```
Forbidden: 403 Forbidden
37 - Your credentials do not allow access to this resource
```

can you tell me what permissions I need to change for this to work?

**Comment by Harmon758** [comment]
You're using app authentication, which doesn't have any user information associated with it.
You need to authenticate as a user to get information about the authenticating user.
