### ISSUE TITLE
Tweets returned from get_users_mentions are out of order

### ISSUE THREAD

**Issue by cj-l** [tweepy/tweepy#1704]
Every time I reinstantiate a Tweepy client and call `client.get_users_mentions(user_id)`, the returned list of 10 tweets is in a different order. (If I call it multiple times from the same instantiated client, the list is identical).

Is this intended?

If so, is there a way to return an ordered list each time?

Thanks!

**Comment by Harmon758** [comment]
I'm unable to reproduce this. Can you provide a reproducible example (MCVE/SSCCE)?
