### ISSUE TITLE
get_users not working

### ISSUE THREAD

**Issue by Wittline** [tweepy/tweepy#1713]
The below line is throwing an error:

users = api.get_users(ids = ['11111010109','193764933'])

error:

**users = api.get_users(ids = ['11111010109','193764933'])
AttributeError: 'API' object has no attribute 'get_users'**

Is anyone else facing the same error?

**Comment by Harmon758** [comment]
Like the error says, [`API`](https://tweepy.readthedocs.io/en/v4.4.0/api.html#tweepy.API) doesn't have a `get_users` attribute/method.
You probably want to use [`API.lookup_users`](https://tweepy.readthedocs.io/en/v4.4.0/api.html#tweepy.API.lookup_users).

For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.
