### ISSUE TITLE
access to /search/:product/:label/counts endpoint (v1.1 api)

### ISSUE THREAD

**Issue by Schulzjo** [tweepy/tweepy#1721]
Hey,

is there a already an implementation to get the number of tweets for a given search query in search_full_archive with tweepy?
I am using the full archiv enpoint with a premium account and it would be great to evaluate number of tweets before query them all and use the paid contingent.

endpoint docs: https://developer.twitter.com/en/docs/twitter-api/premium/search-api/api-reference/premium-search 

Thx in advance

**Comment by Harmon758** [comment]
This is stale now that [the Premium v1.1 API has been deprecated](https://twittercommunity.com/t/deprecating-the-premium-v1-1-api/191092).
