### ISSUE TITLE
Getting a null value returned frequently from user_timeline

### ISSUE THREAD

**Issue by baylortweepy** [tweepy/tweepy#1727]
Has this issue been resolved? I have the same problem. I poll private and public twitter accounts. I have one twitter account that I query that almost without exception returns a NULL object every 5 tries. I can run it one request per second, per 5 seconds, 30 seconds, 5 minutes, same result.

All other accounts I query for the last tweet (just requesting the latest tweet and only one tweet from using the tweepy request below:

api.user_timeline(user_id=clientID, count='1')

Any suggestions? I have to test each response now for "is NULL" and retry when it randomly returns a null for this one single twitter account.

**Comment by baylortweepy** [comment]
does anyone check these questions?

**Comment by baylortweepy** [comment]
13 days and no response.  i wonder how i can get someone in the know to help with this.  it's a very frustrating failure of the API.  1 in every 4 requests returns a null causing me to have to retry to deal with the exception.

**Comment by Harmon758** [comment]
I'm not sure what you mean by "null value" / "NULL object". The closest Python equivalent would be `None`, but that's not something `API.user_timeline` should be able to return. Can you provide a reproducible example (MCVE/SSCCE) of what you're encountering?

I check the issues for this repository regularly, but I don't always have enough free time to volunteer to respond to each one immediately.

**Comment by baylortweepy** [comment]
> I'm not sure what you mean by "null value" / "NULL object". The closest Python equivalent would be `None`, but that's not something `API.user_timeline` should be able to return. Can you provide a reproducible example (MCVE/SSCCE) of what you're encountering?
> 
> I check the issues for this repository regularly, but I don't always have enough free time to volunteer to respond to each one immediately.

Absolutely and thank you for responding.  I've never posted here so didnt know if it was an orphaned board or if someone would see it eventually lol

yes it's None

Basically i call this with tweepy and then have to check for None to prevent crashing my program

lastTweetObject = get_last_tweet(api, userID)

    if lastTweetObject is None:
        print("object is None")

i "listen" to several twitter accounts calling a function i wrote called get_last_tweet which basically does the following:

timeline = client.user_timeline(user_id=clientID, count='1')
    
        for status in timeline:
            tweetObject = status
            if lastTweetID == "":
                lastTweetID = status.id_str)

            return tweetObject

on this one particular private twitter account (which i pay to have access to and i monitor several paid access "private" twitter accounts), about 1 in 4 times this method returns an object of type None after calling  

timeline = client.user_timeline(user_id=clientID, count='1')

**Comment by baylortweepy** [comment]
I'm running the code right now and every 200 tries i log how many out of the 200 did i get a None object returned in my python code from Tweepy.  here's the latest stat:

monitor_tweet() total / null =  200 / 36

so 36 out of 200 or 18% (so on a sunday night it appears to happen less frequently than 1 in 5 but more like 1 in 4)

**Comment by Harmon758** [comment]
This isn't a reproducible example.

However, you would encounter a `TypeError: 'NoneType' object is not iterable` if `API.user_timeline` actually returned `None` there and you attempted to iterate over it.

Instead, you're likely encountering instances where `API.user_timeline` is returning an empty list. Your function then doesn't have anything to iterate through and returns `None` at the end, after the `for` loop.

The `count` parameter doesn't guarantee the number of Tweets returned:
> Specifies the number of Tweets to try and retrieve, up to a maximum of 200 per distinct request. The value of *count* is best thought of as a limit to the number of Tweets to return because suspended or deleted content is removed after the count has been applied. We include retweets in the count, even if i*nclude_rts* is not supplied. It is recommended you always send *include_rts=1* when using this API method.

per [the Twitter API documentation of the GET statuses/user_timeline endpoint](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-user_timeline) that `API.user_timeline` uses.

For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.

**Comment by baylortweepy** [comment]
ok thanks for this information.  let me ponder it and see if i can somehow test it.  

is there an issue with how many times i may be calling twitter through tweepy?  whats odd is sometimes when i start up my code, it gives me a None object on the initial call and i have to keep retrying it to get it to not get a None from the "timeline" which is bizarre because the timeline obviously has something as it's a longstanding account and I'm just trying to get the current tweet

**Comment by Harmon758** [comment]
I've already explained to you what's going on.
`API.user_timeline` is not returning `None`, and the `count` parameter is a limit, not a guarantee of the number of Tweets returned.

**Comment by baylortweepy** [comment]
is there a better way to "get the last tweet"?  im basically priming my algo with the last tweet and then checking every second for a new tweet

> I've already explained to you what's going on. `API.user_timeline` is not returning `None`, and the `count` parameter is a limit, not a guarantee of the number of Tweets returned.

**Comment by Harmon758** [comment]
You can likely just use a higher `count`, but you should probably use streaming if you're doing something realtime.

**Comment by baylortweepy** [comment]
> 

Thanks.  Yes what i'm doing is sitting and listening to a twitter account (basically chceking each second if something new has been tweeted) and then processing  the "new" tweet if there is one.  If the tweet ID hasnt changed, i do nothing, wait a second and check for a new tweet again ad infinitum.

let me check into the streaming you recommended this weekend and see if that improves things.

**Comment by baylortweepy** [comment]
> This isn't a reproducible example.
> 
> However, you would encounter a `TypeError: 'NoneType' object is not iterable` if `API.user_timeline` actually returned `None` there and you attempted to iterate over it.
> 
> Instead, you're likely encountering instances where `API.user_timeline` is returning an empty list. Your function then doesn't have anything to iterate through and returns `None` at the end, after the `for` loop.
> 
> The `count` parameter doesn't guarantee the number of Tweets returned:
> 
> > Specifies the number of Tweets to try and retrieve, up to a maximum of 200 per distinct request. The value of _count_ is best thought of as a limit to the number of Tweets to return because suspended or deleted content is removed after the count has been applied. We include retweets in the count, even if i_nclude_rts_ is not supplied. It is recommended you always send _include_rts=1_ when using this API method.
> 
> per [the Twitter API documentation of the GET statuses/user_timeline endpoint](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/timelines/api-reference/get-statuses-user_timeline) that `API.user_timeline` uses.
> 
> For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.

I did some further investigation on this and as you say when the length of the ResultSet returned from calling user_timeline() is 0, I get the NoneType situation.  

What i cant understand is how i can call the user_timeline() function 1 second and get a nontype (from a ResultSet that is len of 0) and then the next second get a ResultSet that has multiple objects in it when nothing has change in that twitter users timeline. 

Is there a logical explanation for that?

**Comment by baylortweepy** [comment]
also, when i note this issue is marked "closed" so do i need to open a new one with these questions?  dont want to clutter the database.  thanks
