### ISSUE TITLE
Is there major compatitbility issues?  Repeated Errors

### ISSUE THREAD

**Issue by Negaunee0024** [tweepy/tweepy#1747]
I have spent over 10 hours trying to set up a bot simply to like tweets based on keywords.  I keep getting invalid syntax "<stdin>" line 1.  I was only able to setup something that retweeted tweets from certain users.  What am I doing wrong?  About to throw my PC out the window and not retrieve it

**Comment by PvrpleBlvck** [comment]
Do you have a sample code

**Comment by Harmon758** [comment]
What's the full traceback?

**Comment by ByBilal** [comment]
@Negaunee0024  how did u get around the 401 errors with authenticating to use POST endpoints such as retweeting? I keep getting 401 errors on my oauth1a authentication 

thanks

**Comment by Harmon758** [comment]
That's not related to this issue.
See [the FAQ section about this in the documentation](https://tweepy.readthedocs.io/en/v4.4.0/faq.html#why-am-i-encountering-a-401-unauthorized-error).

**Comment by ByBilal** [comment]
heres my codebase homies, and my traceback is:

`
Traceback (most recent call last):
  File "/Users/flakibaby/PROJECTS/peyote-sentiment-twitterbot/like.py", line 23, in <module>
    user = getUserInfo()
  File "/Users/flakibaby/PROJECTS/peyote-sentiment-twitterbot/like.py", line 20, in getUserInfo
    user = y.get_user(username='im_rickjamez')
  File "/usr/local/lib/python3.9/site-packages/tweepy/client.py", line 1660, in get_user
    return self._make_request(
  File "/usr/local/lib/python3.9/site-packages/tweepy/client.py", line 166, in _make_request
    response = self.request(method, route, params=request_params,
  File "/usr/local/lib/python3.9/site-packages/tweepy/client.py", line 122, in request
    raise Unauthorized(response)
tweepy.errors.Unauthorized: 401 Unauthorized

'



`
import tweepy
import config
import time

# creating client returning client
def getClient():
    x = tweepy.Client(
                        # bearer_token=config.bearer_token,

                       consumer_key=config.consumer_key,
                       consumer_secret=config.consumer_secret,
                       access_token=config.access_token,
                       access_token_secret=config.access_token_secret
                       ) 
    return x

# testing if i can get full user info
def getUserInfo():
    y = getClient()
    user = y.get_user(username='jack')
    return user.data

user = getUserInfo()


print(user)
`

**Comment by Harmon758** [comment]
Again, that's not related to this issue.
