### ISSUE TITLE
Trouble getting anything besides text when using V2 and get_users_tweets() method

### ISSUE THREAD

**Issue by andycccccccc** [tweepy/tweepy#1755]
Hello,

Currently trying to migrate over to API v2, but I'm having difficulty getting the usual extras when querying user timelines. API v1.1 automatically returns fields such as "created_at", and retweet/reply/quote statuses, but apparently V2 needs to be told explicitly to return those items. The issue I'm running into is that the procedures for returning that data as outlined in official documentation do not seem to be working for Tweepy.

Here is my code, attempting to get both "created_at" and "public_metrics" in addition to the tweet text:

```
import Tweepy
TOKEN = '12345678912345678912345567889etc'
id = '1234567890'

tweepy_client = authorize_twitter_oauth2(TOKEN) #just a custom login function
tweets = tweepy_client.get_users_tweets(id=id, tweet_fields=['created_at,public_metrics']).data
```

The above code just returns the tweet id and the tweet text, ignoring my requests for "created_at" and "public_metrics". I've also tried formatting the "tweet_fields" argument like this, but still to no avail:
```
tweet_fields=['created_at' ,'public_metrics']
```

Am I doing something wrong or is this a current limitation of Tweepy?

Thanks for any support.

**Comment by Harmon758** [comment]
https://tweepy.readthedocs.io/en/latest/faq.html#why-am-i-not-getting-expansions-or-fields-data-with-api-v2-using-client
