### ISSUE TITLE
api.search_30_day doesn't return next token

### ISSUE THREAD

**Issue by omnisat** [tweepy/tweepy#1757]
Hello

Next token is missing from the ResultSet object in the search_30_day method, although it's present in the resp from twitter.
I find it hard to modify the parser in order to include it because everything is so intricate.

the way to get the token is to add (temporary fix) : 

```python
import json
try:
    next_token = json.loads(resp.content)['next']
except KeyError:
    next_token = None
```

in the `request` method of the API class and to return it alongside the result object. 

https://github.com/tweepy/tweepy/blob/bbdbb7bbd7f3eb0d3c46d970aa14098d37857053/tweepy/api.py#L271-L275

So... Could the parser be fixed ? Thanks.

**Comment by Harmon758** [comment]
What's the use case for this?

**Comment by omnisat** [comment]
> What's the use case for this?

how could I fill the `next` parameter of the `api.search_30_day` method if it doesn't return the next_token in the first call (ie when `next` is not filled) ? 

The `Client.search_recent_tweets` returns a next token for example. 
Would be nice to include next token as an attribute of a `ResultSet`.

**Comment by Harmon758** [comment]
Tweepy handles pagination for you with [`Cursor`](https://tweepy.readthedocs.io/en/v4.4.0/pagination.html#tweepy.Cursor). If you still need the `next` token, you can access it with the `next_token` attribute of `NextIterator`, the iterator `Cursor.pages` returns.

Parsing is not broken, and your initial proposal of returning the `next` token along with the results is a breaking change that will not be implemented. I also don't really see a reason to add an attribute for it to `ResultSet` without a conceivable use case for needing access to it outside of pagination.

**Comment by omnisat** [comment]
> Tweepy handles pagination for you with [`Cursor`](https://tweepy.readthedocs.io/en/v4.4.0/pagination.html#tweepy.Cursor). If you still need the `next` token, you can access it with the `next_token` attribute of `NextIterator`, the iterator `Cursor.pages` returns.
> 
> Parsing is not broken, and your initial proposal of returning the `next` token along with the results is a breaking change that will not be implemented. I also don't really see a reason to add an attribute for it to `ResultSet` without a conceivable use case for needing access to it outside of pagination.

Hey, Sorry I didn't realize we could paginate using Cursor. I was too focused on the Twitter API v1.1 Reference and this `next, parameter.` and comparing my usage of search_recent_tweets with v2 (that returns the next_token in its response), I thought something was missing. I agree on what you say. 

Sorry for wasting your time and have a great day  :)
