### ISSUE TITLE
Create an easy way to return name values from  tweet.context_annotations

### ISSUE THREAD

**Issue by PoliTwit1984** [tweepy/tweepy#1772]
currently when you try to get data back from tweet.context.annotations it returns a string with nested json. It is difficult to parse through that data to get entity name and id . tweet_context_annotations returns this -

[{'domain': {'id': '10', 'name': 'Person', 'description': 'Named people in the world like Nelson Mandela'}, 'entity': {'id': '10040395078', 'name': 'Joe Biden', 'description': 'US President Joe Biden'}}, {'domain': {'id': '10', 'name': 'Person', 'description': 'Named people in the world like Nelson Mandela'}, 'entity': {'id': '880137300021137408', 'name': 'Sarah Huckabee Sanders', 'description': 'White House Press Secretary Sarah Huckabee Sanders'}}, {'domain': {'id': '35', 'name': 'Politician', 'description': 'Politicians in the world, like Joe Biden'}, 'entity': {'id': '10040395078', 'name': 'Joe Biden', 'description': 'US President Joe Biden'}}, {'domain': {'id': '35', 'name': 'Politician', 'description': 'Politicians in the world, like Joe Biden'}, 'entity': {'id': '880137300021137408', 'name': 'Sarah Huckabee Sanders', 'description': 'White House Press Secretary Sarah Huckabee Sanders'}}]

it would be nice if there was a function that could return the name values of domains and entities. Twitter does not keep their domain id and entity id lists  up to date so parsing the id's does not help.

**Comment by Harmon758** [comment]
`Tweet.context_annotations` should be that as a list, not a string, so you can parse this pretty simply yourself, e.g. with list comprehensions, so this won't be implemented within Tweepy.
