### ISSUE TITLE
login question chnage by alice blue 

### ISSUE THREAD

**Issue by dhanu0013** [tweepy/tweepy#1773]
dear sir 
alice blue change login format in 2 Question  TO 1 question but my alogo doen't work so how can i update this error....
i m not correct this code in my algo so how can i correct it i m share error [scren](url) shot
![image](https://user-images.githubusercontent.com/36652792/150623262-8697810e-41e8-40f7-bb92-9934ef1ea6e3.png)

alice blue login 2FA change to DOB question means .....2 question cancel and only one question in login service but i m not update it on my alogo so How can i change this ,

**Comment by Harmon758** [comment]
This doesn't seem to have anything to do with Tweepy.
