### ISSUE TITLE
Access to has_nft_avatar flag 

### ISSUE THREAD

**Issue by scooterrr** [tweepy/tweepy#1775]
Would be great if it were possible to gain access to the new `has_nft_avatar` attribute as part of the `User` class.

**Comment by Harmon758** [comment]
Where are you seeing the existence of such an attribute?

**Comment by scooterrr** [comment]
I believe this is still a beta feature so it may not actually be exposed by the API yet, but you can see it listed with the other user attributes in the main script on profile pages. 

<img width="959" alt="has_nft_avatar" src="https://user-images.githubusercontent.com/26532086/151071229-2b2f9565-d894-4aa9-8dd0-7262a3808c5a.png">

**Comment by Harmon758** [comment]
This is not something that's exposed through the Twitter API's [User object](https://developer.twitter.com/en/docs/twitter-api/data-dictionary/object-model/user).
You should request it for the API through the [Twitter Developers Forums](https://twittercommunity.com/) or [Twitter Developer Feedback site](https://twitterdevfeedback.uservoice.com/forums/930250-twitter-api) instead.
