### ISSUE TITLE
Pagination parameter for liking users and retweeters

### ISSUE THREAD

**Issue by yitopeligo** [tweepy/tweepy#1803]
A feature requests, as headline suggests, it's a need for the liking users and retweeters to be able to paginate through next token... Many thanks !

**Comment by Harmon758** [comment]
This was added recently to the API with https://twittercommunity.com/t/updates-to-retweets-lookup-and-likes-lookup-endpoints/165327, and support for this is already being tracked in #1472 and is expected in v4.6.
For now, you can still pass `pagination_token` (and use `Paginator`). It'll just give you a warning that the parameter is unexpected.

**Comment by Harmon758** [comment]
This should be resolved with https://github.com/tweepy/tweepy/commit/3479e56a0fff02594ab6e77ca8227e65b51b46f7 and https://github.com/tweepy/tweepy/commit/bdd6b55d7cb075fc2e4c7cb56a061c552ca106fe now.
