### ISSUE TITLE
Discrepancy between the Getting Started page and Authentication page in Documentation

### ISSUE THREAD

**Issue by ravi-maithrey** [tweepy/tweepy#1809]
Hi,

Sorry if this has been brought up already, I did a brief search and did not find anything relevant.

In the[ Getting Started](https://docs.tweepy.org/en/stable/getting_started.html) page, the very first example asks to use `OAuthHandler` in the Hello Tweepy code snippet. However, in the [Authentication](https://docs.tweepy.org/en/stable/authentication.html#authentication) page, in the reference section, it says, `OAuthHandler` is depricated and to use `OAuth1UserHandler` instead, esp. as `OAuthHandler` is getting deprecated from version 4.5, which is the current release. 

Am I to assume that the Authentication page is right and the Getting Started page simply hasn't been updated and proceed with `OAuth1UserHandler`?

Thanks

**Comment by Harmon758** [comment]
Yes, `OAuthHandler` was renamed to `OAuth1UserHandler` in v4.5.0, with `OAuthHandler` kept as a deprecated alias.
https://github.com/tweepy/tweepy/commit/12822795fac8eceea6a0c1260a38b304a34ffd13 should resolve any inconsistencies within the library regarding this usage.
