### ISSUE TITLE
This App has violated Twitter Rules and policies, while i use filter.

### ISSUE THREAD

**Issue by yangzh9106** [tweepy/tweepy#1813]
`
class IDPrinter(tweepy.Stream):

    def on_status(self, status):
       print(status)      
    def on_request_error(self, status_code): 
        print(status_code)
        if status_code == 420: 
            print(status_code)
            return False        
    def on_connection_error (self, status_code):
        print(status_code)
        if status_code == 420: 
            print(status_code)
            return False        
def main():

    printer = IDPrinter(
            consumer_key, consumer_secret,
            access_token, access_token_secret
            )
    while True:
        try:
            printer.filter(follow=following_id_list, stall_warnings=True)
            time.sleep(5)
        except Exception as e:
            print(e)
            time.sleep(60)
if __name__ == '__main__':

    main()

`
after i run this code for about an hour, i get 403 error and twitter send me an email said 'This App has violated Twitter Rules and policies. As a result, certain functions will be limited'. 

![image](https://user-images.githubusercontent.com/52728728/154609171-90ee9c6f-70d6-4056-a52c-5e0807dd455e.png)

![image](https://user-images.githubusercontent.com/52728728/154609324-48450795-ee82-4a13-b01c-36a9b8769759.png)

I don't know how to solve it. Can anyone help?

**Comment by yangzh9106** [comment]
I am trying to regenerate the token info and see what happens.
![image](https://user-images.githubusercontent.com/52728728/154610556-ddf0a215-255c-4507-9185-099af55e59a7.png)

**Comment by Harmon758** [comment]
This isn't an issue with Tweepy. You should contact [Twitter API Policy Support](https://help.twitter.com/en/forms/platform) instead.

For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.
