### ISSUE TITLE
TAKES 1 POSITIONAL ARGUMENT BUT TWO WERE GIVEN

### ISSUE THREAD

**Issue by saheedniyi02** [tweepy/tweepy#1826]
Using tweepy version 4.6.0

`access_token = "######"
access_token_secret = "######"
API_KEY = "#######"
API_SECRET_KEY = "######"
bearer_token = "#######"

import tweepy

client = tweepy.Client(
    bearer_token=bearer_token,
    consumer_key=API_KEY,
    consumer_secret=API_SECRET_KEY,
    access_token=access_token,
    access_token_secret=access_token_secret,
)

client.create_tweet("testing")`

There seem to be an issue with the create_tweet() function, it returns 
`TypeError:  get_users() ` takes 1 positional argument but 2 were given`.
The ` get_user() `  function returns same too

**Comment by Harmon758** [comment]
[`Client.create_tweet`](https://tweepy.readthedocs.io/en/v4.6.0/client.html#tweepy.Client.create_tweet), [`Client.get_users`](https://tweepy.readthedocs.io/en/v4.6.0/client.html#tweepy.Client.get_users), and [`Client.get_user`](https://tweepy.readthedocs.io/en/v4.6.0/client.html#tweepy.Client.get_user) do not accept any positional arguments. The 1 positional argument being referred to in the error is `self`.

You likely want to pass `"testing"` as the `text` kwarg instead.

For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.
