### ISSUE TITLE
V2 API - 401 Unauthorized when using search 

### ISSUE THREAD

**Issue by miiguelkf** [tweepy/tweepy#1827]
I am trying to do a simple tweets search using the v2 api, but it gives me an 401 Unauthorized error. 
The weird part is that I can create a tweet - gives me no error.

obs: I already have Read and Write permission on my project.

```
import tweepy
import keys
import time, datetime

client = tweepy.Client(
    consumer_key=keys.API_KEY,
    consumer_secret=keys.API_SECRET_KEY,
    access_token=keys.ACCESS_TOKEN,
    access_token_secret=keys.SECRET_ACCESS_TOKEN
)

client.search_recent_tweets(query='test')
```

changing the last line to 
`client.create_tweet(text='Teste')`
works fine

**Comment by Harmon758** [comment]
By default, [`Client.search_recent_tweets`](https://tweepy.readthedocs.io/en/v4.6.0/client.html#tweepy.Client.search_recent_tweets) does not use OAuth 1.0a User Context to authenticate. You need to pass `user_auth=True`.
