### ISSUE TITLE
Issue Authenticating with Twitter using GitHub Actions

### ISSUE THREAD

**Issue by Nick-Rimmer2016** [tweepy/tweepy#1838]
Hi,
I am new to using Github Actions, but I have set up repository secrets for use with my script, but I can't pass the secrets to the script. This is an excerpt from my GitHub Action:

`- name: execute Random-YouTube script    
        env:   
            ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}   
            ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}   
            API_KEY_TWITTER: ${{ secrets.API_KEY_TWITTER }}   
            API_KEY_TWITTER_SECRET: ${{ secrets.API_KEY_TWITTER_SECRET }}   
            API_KEY: ${{ secrets.API_KEY}}   
        run: python Random-YouTube.py       `

This is how I am calling it in Python.

`CONSUMER_KEY = os.environ.get('API_KEY_TWITTER')
CONSUMER_SECRET = os.environ.get('API_KEY_TWITTER_SECRET')
ACCESS_TOKEN = os.environ.get('ACCESS_TOKEN')
ACCESS_TOKEN_SECRET = os.environ.get('ACCESS_TOKEN_SECRET')
auth = tweepy.OAuthHandler("CONSUMER_KEY","CONSUMER_SECRET")
auth.set_access_token("ACCESS_TOKEN","ACCESS_TOKEN_SECRET")
api = tweepy.API(auth)`

This is the error I get:
`Traceback (most recent call last):
  File "Random-YouTube.py", line 68, in <module>
    publictweet()
  File "Random-YouTube.py", line 65, in publictweet
    api.update_status(tweettopublish)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/tweepy/api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/tweepy/api.py", line 1128, in update_status
    ), status=status, **kwargs
  File "/opt/hostedtoolcache/Python/3.7.5/x64/lib/python3.7/site-packages/tweepy/api.py", line [25](https://github.com/Nick-Rimmer2016/Python-Tweepy/runs/5439415341?check_suite_focus=true#step:5:25)7, in request
    raise Unauthorized(resp)
tweepy.errors.Unauthorized: 401 Unauthorized
89 - Invalid or expired token.
Error: Process completed with exit code 1.`

**Comment by Nick-Rimmer2016** [comment]
I should add that the tokens etc. work when I use them directly in a Python script.

**Comment by Harmon758** [comment]
You're passing the strings, "CONSUMER_KEY","CONSUMER_SECRET", "ACCESS_TOKEN", and "ACCESS_TOKEN_SECRET", as credentials. You need to use the variables you're defining instead.

For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.
