### ISSUE TITLE
KeyError:"urls" when flatten limit is increased above 8. 

### ISSUE THREAD

**Issue by Smyja** [tweepy/tweepy#1842]
I am trying to get the expanded_urls for tweets, i get KeyError: "urls" randomly when the flatten limit is above 8. Sometimes it works,sometimes it doesn't but so far it hasn't gone past 10 urls. I only get this problem with the urls. 

This is my code to reproduce it. 
```
for tweet in tweepy.Paginator(client.search_recent_tweets, "test  -is:retweet", max_results=100,tweet_fields=["entities","created_at","text"]).flatten(limit=10):
    urls.append(tweet.data["entities"]["urls"][0]["expanded_url"])
    tweets.append(tweet.text)
    date.append(tweet.data["created_at"])
  
print(date)
print(len(urls))
print(tweets)
```
I've tried using time.sleep and wait_on_rate_limit with a flatten limit of 30 and the error still persists.

**Comment by Smyja** [comment]
I tried time.sleep(5) and time.sleep(30) and I still got the key error. I noticed that if I try a limit of 20 and it fails and I try it again in 15-20 minutes, it will work. I'm confused because this doesn't look like a rate limit problem.

**Comment by Harmon758** [comment]
`"urls"` is not a guaranteed field for entities objects. If the Tweet doesn't contain a URL, it will not be there.
In fact, `"entities"` is not a guaranteed field for Tweet objects. If the Tweet doesn't contain any entities, you'll encounter a `KeyError: 'entities'` error.
