### ISSUE TITLE
Pagination is not working with return_type = dict or return_type = requests.Response

### ISSUE THREAD

**Issue by Teyfice** [tweepy/tweepy#1843]
Dear tweepy developer,

when i set the return_type to either dict or  requests.Response, pagination is not working anymore.

That likely has to with the fact that the function seems to "assume" that a Tweepy.Response is chosen as return_type:

response = self.method(*self.args, **self.kwargs)

self.previous_token = response.meta.get("previous_token")
self.next_token = response.meta.get("next_token")

However, when I chose "dict" as return_type, response.meta throws an error, while response['meta'] probably works. I fixed it rudimentarily to work at least for dict:

        response = self.method(*self.args, **self.kwargs)

        try:
            self.previous_token = response.meta.get("previous_token")
        except Exception:
            self.previous_token = response['meta'].get("previous_token")
        
        try:
            self.next_token = response.meta.get("next_token")
        except Exception:
            self.next_token = response['meta'].get("next_token")

It would be very nice if you could provide a more sophisticated solution to this issue. Thank you very much!

**Comment by lqhuang** [comment]
Any update? No one responses to my PR, too. Sad 😢
