### ISSUE TITLE
streamingClient.filter() hangs 

### ISSUE THREAD

**Issue by salahaz** [tweepy/tweepy#1854]
Hello, I have the following sample code, where I try using the streamingClient for Twitter's API v2, however, when running the filter() function it just keeps hanging without returning anything. I have tested it on multiple basic rules.

Note: I have tested the streamingClient with the sample() function and it works, however the filter() doesn't

Here is the code:
<img width="598" alt="Screen Shot 2022-03-31 at 9 02 04 AM" src="https://user-images.githubusercontent.com/41476094/161018668-cb9c09df-ac33-4145-89e5-420db3d29c32.png">

Any fix?

**Comment by Harmon758** [comment]
I'm unable to reproduce this issue.
Are you getting a successful response from `add_rules`?
Is there any relevant information when you enable [logging](https://tweepy.readthedocs.io/en/v4.8.0/logging.html)?

**Comment by salahaz** [comment]
@Harmon758 The following is the response I get for adding a rule. Afterwards, as you can see running the filter() just stays hanging.

I'm using tweepy 4.8.0 btw

<img width="927" alt="Screen Shot 2022-03-31 at 9 47 35 AM" src="https://user-images.githubusercontent.com/41476094/161027916-49c9967e-39e2-454a-9ec1-43c0c0c9beda.png">

**Comment by salahaz** [comment]
@Harmon758 And this is the logger's output

<img width="927" alt="Screen Shot 2022-03-31 at 9 55 16 AM" src="https://user-images.githubusercontent.com/41476094/161030008-da3cda1b-497b-47ac-a955-085c9595dcb5.png">

Any idea ?

**Comment by Harmon758** [comment]
Can you paste the relevant code here?
What response do you get from calling `get_rules` after you add the rule?

**Comment by salahaz** [comment]
@Harmon758 Here is the response of `get_rules` :

<img width="914" alt="Screen Shot 2022-03-31 at 11 30 25 AM" src="https://user-images.githubusercontent.com/41476094/161045566-f618a1ad-22dd-4dca-b9e0-e2bfae9f6f6d.png">

**Comment by Harmon758** [comment]
Ah, it seems like this is an issue on Twitter's end rather than an issue with Tweepy.

**Comment by Harmon758** [comment]
https://twittercommunity.com/t/stream-stopped-getting-updates/169105 might also be relevant.

**Comment by Harmon758** [comment]
I believe this is resolved now on Twitter's end.
