### ISSUE TITLE
module 'tweepy' has no attribute 'Client'

### ISSUE THREAD

**Issue by luckyonetwo** [tweepy/tweepy#1862]
how to deal with the problem of module 'tweepy' has no attribute 'Client'

**Comment by Harmon758** [comment]
You're probably either using an older version of Tweepy (`tweepy.Client` was added with support for Twitter API v2 in Tweepy v4.0.0) or have another file or folder in your path named "tweepy".

Regardless, this is not a reproducible issue with Tweepy and there's nothing actionable here.
