### ISSUE TITLE
API.request return None

### ISSUE THREAD

**Issue by KohnoseLami** [tweepy/tweepy#1873]
I use a custom endpoint to implement the welcome message
Since bind_api was deleted and API.request was added, I tried to use it, but the data did not come back.

```
res = api.request("GET", "account/verify_credentials")
print(res)
>>> None
```

**Comment by Harmon758** [comment]
That is expected behavior when `payload_type` isn't passed, as it defaults to `None`.
Note, [`API.verify_credentials`](https://tweepy.readthedocs.io/en/v4.8.0/api.html#tweepy.API.verify_credentials) exists.

**Comment by KohnoseLami** [comment]
Thank you.
I confirmed that the value returned normally by specifying json for payload_type.
