### ISSUE TITLE
Media_url is not retrieved

### ISSUE THREAD

**Issue by reejit** [tweepy/tweepy#1875]
My code is 
```
id = 1518542738307829760

  
# fetching the status 
api = tweepy.API(auth) 
status = api.get_status(id) 
time.sleep(5)
  
# fetching the text attribute 
print(status.text)
print(status.author.screen_name)
print(status.author)
print(status.entities)
if 'media' in status.entities:
     for image in status.entities['media']:
        print(image['media_url'])

else:
  print ('false')
```

The output received is ```The full details here. Given Russia's track record with humanitarian corridors, and incendiary rhetoric from Russia… https://t.co/XEmMbOpiLE
SamRamani2
User(_api=<tweepy.api.API object at 0x7f4cdabe4fd0>, _json={'id': 1957610664, 'id_str': '1957610664', 'name': 'Samuel Ramani', 'screen_name': 'SamRamani2', 'location': 'Oxford, England', 'description': 'DPhil/PhD Intl Relations @UniofOxford Assoc Fellow @RUSI_org Bylines @ForeignPolicy, WaPo etc 3 forthcoming books @HurstPublishers Email samuel.ramani@gmail.com', 'url': None, 'entities': {'description': {'urls': []}}, 'protected': False, 'followers_count': 137631, 'friends_count': 3685, 'listed_count': 2066, 'created_at': 'Sat Oct 12 23:22:53 +0000 2013', 'favourites_count': 9102, 'utc_offset': None, 'time_zone': None, 'geo_enabled': False, 'verified': True, 'statuses_count': 17528, 'lang': None, 'contributors_enabled': False, 'is_translator': False, 'is_translation_enabled': False, 'profile_background_color': 'C0DEED', 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png', 'profile_background_tile': False, 'profile_image_url': 'http://pbs.twimg.com/profile_images/1082550331114954752/Pg1pRVnh_normal.jpg', 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1082550331114954752/Pg1pRVnh_normal.jpg', 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1957610664/1634503725', 'profile_link_color': '1DA1F2', 'profile_sidebar_border_color': 'C0DEED', 'profile_sidebar_fill_color': 'DDEEF6', 'profile_text_color': '333333', 'profile_use_background_image': True, 'has_extended_profile': False, 'default_profile': True, 'default_profile_image': False, 'following': False, 'follow_request_sent': False, 'notifications': False, 'translator_type': 'none', 'withheld_in_countries': []}, id=1957610664, id_str='1957610664', name='Samuel Ramani', screen_name='SamRamani2', location='Oxford, England', description='DPhil/PhD Intl Relations @UniofOxford Assoc Fellow @RUSI_org Bylines @ForeignPolicy, WaPo etc 3 forthcoming books @HurstPublishers Email samuel.ramani@gmail.com', url=None, entities={'description': {'urls': []}}, protected=False, followers_count=137631, friends_count=3685, listed_count=2066, created_at=datetime.datetime(2013, 10, 12, 23, 22, 53), favourites_count=9102, utc_offset=None, time_zone=None, geo_enabled=False, verified=True, statuses_count=17528, lang=None, contributors_enabled=False, is_translator=False, is_translation_enabled=False, profile_background_color='C0DEED', profile_background_image_url='http://abs.twimg.com/images/themes/theme1/bg.png', profile_background_image_url_https='https://abs.twimg.com/images/themes/theme1/bg.png', profile_background_tile=False, profile_image_url='http://pbs.twimg.com/profile_images/1082550331114954752/Pg1pRVnh_normal.jpg', profile_image_url_https='https://pbs.twimg.com/profile_images/1082550331114954752/Pg1pRVnh_normal.jpg', profile_banner_url='https://pbs.twimg.com/profile_banners/1957610664/1634503725', profile_link_color='1DA1F2', profile_sidebar_border_color='C0DEED', profile_sidebar_fill_color='DDEEF6', profile_text_color='333333', profile_use_background_image=True, has_extended_profile=False, default_profile=True, default_profile_image=False, following=False, follow_request_sent=False, notifications=False, translator_type='none', withheld_in_countries=[])
{'hashtags': [], 'symbols': [], 'user_mentions': [], 'urls': [{'url': 'https://t.co/XEmMbOpiLE', 'expanded_url': 'https://twitter.com/i/web/status/1518542738307829760', 'display_url': 'twitter.com/i/web/status/1…', 'indices': [117, 140]}]}
false```

But the media_url isn't received but the tweet has a media
```https://mobile.twitter.com/SamRamani2/status/1518542738307829760```

**Comment by reejit** [comment]
The problem is solved by using
```
status = api.get_status(id, tweet_mode="extended")
```

**Comment by Harmon758** [comment]
For posterity, https://tweepy.readthedocs.io/en/v4.8.0/extended_tweets.html.
