### ISSUE TITLE
Stream encountered HTTP error: 403

### ISSUE THREAD

**Issue by kenxdrgn** [tweepy/tweepy#1877]
```
class Listener(tweepy.Stream):
    def on_status(self, status):
        print(status.user.screen_name + ": " + status.text)


stream_tweet = Listener(api_key, api_key_secret, access_token, access_token_secret)

keywords = ["2002", "#python"]

stream_tweet.sample()
```
I am getting "**Stream encountered HTTP error: 403**" when using the above code.
Other method such as **_home_timeline_** etc is working fine.

I am using tweepy 4.8.0 and python 3.9.10 on Mac OS.
I have **Elavated Access** of twitter developers api.

Is anyone experiencing the same errors or have any ideas for making the stream work?

**Comment by Indominus-Rexian** [comment]
I was also getting the same error.
I was also using `tweepy.Streams` but it has been deprecated if your App is new. After I changed to `tweepy.StreamingClient` and it was working well.

**Comment by Harmon758** [comment]
Are you using a Twitter Developer App created on or after last Friday (2022-04-29)?

**Comment by kenxdrgn** [comment]
> Are you using a Twitter Developer App created on or after last Friday (2022-04-29)?

Yes! I just created the app yesterday!

**Comment by kenxdrgn** [comment]
> I was also getting the same error while using `tweepy.Streams` but it has been deprecated if your App is new. After I changed to `tweepy.StreamingClient` and it was working well.

Could you share some of your code? 
And are you enabling both OAuth 2.0 and OAuth 1.0a for your app?

**Comment by elon2022** [comment]
兄弟你是中国人吗，如果是一起交流一下啊。我的微信：    Cc18991001        我跟你遇到了一模一样的问题

**Comment by elon2022** [comment]
兄弟你是中国人吗？我跟你遇到一模一样的问题，我也是申请好了高级权限，然后使用此功能的，同样的是403. 加个微信啊： Cc18991001

**Comment by elon2022** [comment]
Brother, are you Chinese? I have the exact same problem as you, I also applied for advanced permissions, and then used this function, the same is 403. Add a WeChat: Cc18991001

**Comment by elon2022** [comment]
Brother, I have been working on this problem for a long time, and I haven't solved it yet. Can you add a WeChat or a telegram: @musk1992 Let's solve this problem together

**Comment by Harmon758** [comment]
New Apps:
> will not be able to gain access to v1.1 statuses/sample and v1.1 statuses/filter

https://twittercommunity.com/t/deprecation-announcement-removing-compliance-messages-from-statuses-filter-and-retiring-statuses-sample-from-the-twitter-api-v1-1/170500

You'll have to use Twitter API v2.
