### ISSUE TITLE
simple_upload/media_upload Error

### ISSUE THREAD

**Issue by RenFinkle** [tweepy/tweepy#1905]
Expected behavior: Image posts to Twitter
Actual behavior: Receive this error message `Failed to send request: Failed to parse: https://upload.twitter.com/1.1/media/upload.json`
Relevant code:
`auth = tweepy.OAuth1UserHandler(xx, xx, xx, xx)`
`api = tweepy.API(auth)`
`api.simple_upload("xx")
`
Possibly relevant: in my developer dashboard it says I'm using V2 of the API, if this is the problem how can I switch to v1.1?

**Comment by RenFinkle** [comment]
Updated urllib3 and now I'm just getting a 403 error

**Comment by RenFinkle** [comment]
This was due to a permissions configuration issue, lastly it seems like it's working but it's not actually posting

**Comment by RenFinkle** [comment]
This was due to a permissions configuration issue, resolved.

**Comment by Harmon758** [comment]
In the future, you need to provide the full traceback(s) and relevant code for someone to be able to determine what's going on and help you.
