### ISSUE TITLE
show_friendship() raise TweepError

### ISSUE THREAD

**Issue by alexeyproskuryakov** [tweepy/tweepy#191]
I use this:

> > api.show_friendship('navalny','linoleum2k12')

And after it get me:

  File "D:\develop\twitter_searcher\search_engine\engines.py", line 263, in <module>
    print engine_.api.show_friendship('navalny','linoleum2k12')
  File "D:\Python\lib\site-packages\tweepy\binder.py", line 185, in _call
    return method.execute()
  File "D:\Python\lib\site-packages\tweepy\binder.py", line 168, in execute
    raise TweepError(error_msg, resp)
tweepy.error.TweepError: [{u'message': u'Sorry, that page does not exist', u'code': 34}]

But if I request this: 

> > https://api.twitter.com/1/friendships/show.json?source_screen_name=navalny&target_screen_name=linoleum2k12

i have some responce not equals "Sorry, that page does not exist"
Maybe i do not know how to do it?

**Comment by DarkRedman** [comment]
I've the same error and even if I I precise the source and target I get this error with two specific values source_id=437398082 and target_id=942376476292403205 but If I use one of them with another it works, so I check thoses ids correspond to existing users, the error is not really verbose, it doesn't explain why it can't.
`[{'code': 163, 'message': 'Could not determine source user.'}]`
