### ISSUE TITLE
Error Dates in Germany tweets not correct

### ISSUE THREAD

**Issue by Skarali1** [tweepy/tweepy#1919]
Hello, I have a full archive access in twitter and i am using paginator to scrape 500 tweets per request so when i am done scraping and trying to see the dates all the dates are the same never changed the only changes i see is the minuets that in "German languages" The query i used is: 
query = "keywords lang:de" 
start-time = "2021-01-01T00:00:00Z"
end-time = "2021-05-01T00:00:00Z"
But when i try to scrape English tweet it is working perfect so i am not sure where is the issue!!  

The script seems to work in other languages perfect so the issue is not the script i believe and is not twitter so it might be a bug or something could you help out please!!

**Comment by Skarali1** [comment]
Not an issue

**Comment by Harmon758** [comment]
In your second `for` loop, you're only iterating over the (up to 500) Tweets in the last `response`.
It's plausible for all of those to have been Tweeted on the same date, depending on your keyword.
