### ISSUE TITLE
Not able to get the conversation id/replied to tweet using filtered stream

### ISSUE THREAD

**Issue by 4RCAN3** [tweepy/tweepy#1924]
I'm trying to get the tweet to which someone's mentioned my bot, but I'm unable to get the conversation id for it. This is the response I'm getting:
![image](https://user-images.githubusercontent.com/69053040/180244474-8f6c86ae-2c55-45a9-b0ff-1b3005ef43fb.png)
Also referencing the "reply":
![image](https://user-images.githubusercontent.com/69053040/180244556-ba7fbf55-fbaa-4e12-95b5-145af0538761.png)
Is it possible I might be doing something wrong?

**Comment by luizoti** [comment]
Same here, conversation id is None with get_users_tweets.

**Comment by luizoti** [comment]
I don't know if it's a limitation of the api or something similar, but from what I analyze the lib is making the request and passing the parameters that, but the result is always the same, the id and text, strange.

**Comment by luizoti** [comment]
After re-reading the documentation I noticed that I was using the wrong parameter, instead of tweet_fields I was using media_fields, now it seems to be returning everything correctly.

**Comment by 4RCAN3** [comment]
> After re-reading the documentation I noticed that I was using the wrong parameter, instead of tweet_fields I was using media_fields, now it seems to be returning everything correctly.

Hi, can you send me the code snippet for that? Is there something I may be doing wrong. The on_tweet function returns the tweet object so I was using the attributes for that. I also tried fetching the tweet using client.get_tweet but I stil wasn't able to get the conversation ID.

**Comment by luizoti** [comment]
I believe there should be no problems.

**Comment by Harmon758** [comment]
Are you requesting the `conversation_id` [Tweet field](https://tweepy.readthedocs.io/en/v4.10.0/expansions_and_fields.html#tweet-fields)?
If so, you'll need to provide all of the relevant code for further help.
