### ISSUE TITLE
unexpected parameter wait_on_rate_limit  

### ISSUE THREAD

**Issue by renjiege** [tweepy/tweepy#1925]
Code: 
```
for follower in tweepy.Cursor(api.get_followers, id=tid, wait_on_rate_limit=True).items(10):
            print(follower.description)
```

I got the following warnings:
```
Unexpected parameter: id
Unexpected parameter: wait_on_rate_limit
```

Tweepy version = 4.10.0

**Comment by renjiege** [comment]
wait_on_rate_limit is now a parameter in tweepy.api
id should be should be changed to user_id

**Comment by Harmon758** [comment]
`id` was removed as a parameter for [`API.get_followers`](https://tweepy.readthedocs.io/en/v4.10.0/api.html#tweepy.API.get_followers) in [Tweepy v4.0.0](https://github.com/tweepy/tweepy/releases/tag/v4.0.0), as it's no longer a documented parameter for the Twitter API endpoint that method uses.
`user_id` was and continues to be a documented and supported parameter.

`wait_on_rate_limit` was removed as an API method parameter in [v4.0.0](https://github.com/tweepy/tweepy/releases/tag/v4.0.0).
It previously existed and still exists as an API parameter on initialization.
