### ISSUE TITLE
I get the error message: tweepy.errors.Forbidden: 403 Forbidden, 453 - You currently have Essential access which includes access to Twitter API v2 endpoints only. However I have elevated access so why it is telling me otherwise? 

### ISSUE THREAD

**Issue by nospmis27** [tweepy/tweepy#1927]
from textblob import TextBlob
import tweepy
import pandas as pd
import numpy as np
import sys

api_key = XX
api_key_secret = XX
bearer_token = XX
access_token = XX"
access_token_secret = XX

auth_handler = tweepy.OAuthHandler(consumer_key=api_key, consumer_secret=api_key_secret)
auth_handler.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth_handler)

search_term = "bitcoin"
tweet_amount = 1000

tweets = tweepy.Cursor(api.search_tweets, q=search_term, lang="en").items(tweet_amount)

for tweet in tweets:
    print(tweet.text)

**Comment by Harmon758** [comment]
Have you regenerated your credentials after gaining Elevated access?

For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.

**Comment by NovemberFalls** [comment]
> Have you regenerated your credentials after gaining Elevated access?
> 
> For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.

was going to say this. Every time you make a change to your "app" you will need to regenerate keys.
