### ISSUE TITLE
module 'tweepy' has no attribute 'Client'

### ISSUE THREAD

**Issue by ablil** [tweepy/tweepy#1936]
from the docs [here](https://docs.tweepy.org/en/stable/authentication.html#twitter-api-v2) it says we we can authenticate with v2 using only the bearer token, but it fails with the following error:

```
Traceback (most recent call last):
  File "/home/ablil/projects/twitter-scripts/tweepy.py", line 10, in <module>
    auth = tweepy.Client(os.environ['TWITTER_API_BEARER_TOKEN'])
AttributeError: module 'tweepy' has no attribute 'Client'
```

I've ried that as well from the python interpreter but it didn't work as exptected.

Python version: 3..913
Tweepy version: 4.10.0

**Comment by 4RCAN3** [comment]
You seem to have named your python file as "tweepy", hence the error. Just change the name of your file and that should fix it.

**Comment by Harmon758** [comment]
As noted, make sure you don't have a file or folder in your path or current working directory named "tweepy" or "tweepy.py", so that you import the Tweepy library rather than your file or folder.
