### ISSUE TITLE
Documentation error under StreamingClient.delete_rules

### ISSUE THREAD

**Issue by Dipankar-Medhi** [tweepy/tweepy#1937]
There's an error in the documentation under **StreamingClient.delete_rules** section. 

> "dry_run ([bool](https://docs.python.org/3/library/functions.html#bool)) – Set to true to test a the syntax of your rule without submitting it. This is useful if you want to check the syntax of a rule before removing one or more of your existing rules." 

Refer to [link](https://docs.tweepy.org/en/stable/streamingclient.html#tweepy.StreamingClient.delete_rules)

**Comment by Harmon758** [comment]
Thanks! This was actually a typo copied and pasted from the Twitter API documentation on https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/api-reference/post-tweets-search-stream-rules.
