### ISSUE TITLE
503 when starting stream with basic filter

### ISSUE THREAD

**Issue by zevaryx** [tweepy/tweepy#1938]
I'm getting a strange error while trying to move to v2 async streaming. I have a basic rule filtering tweets from 3 users:

`from:14075928 OR from:1479926388173930497 OR from:32771325`

My code is as follows:
```py
class Stream(AsyncStreamingClient):
    async def on_tweet(self, status):
        print(f"Got tweet from {status.author.id}")

stream = Stream(bearer_token=TOKEN)
await stream.filter()
````

I get a 503 error on the last line every time, but have no issues with anything else. Is there something I'm missing?

**Comment by Harmon758** [comment]
A 503 HTTP error code indicates Service Unavailable, a (likely transient) issue on Twitter's end.
Are you still encountering this?

**Comment by zevaryx** [comment]
I'd been getting issues with this for the last week every time I tried it out, and then you reply and of course it works. Might have been something weird on my end, or with my project on Twitter. Thank you for responding!
