### ISSUE TITLE
v2 response.includes not containing media_fields nor poll_fields when expanded 

### ISSUE THREAD

**Issue by nickohnickohni** [tweepy/tweepy#1941]
I used v2 API but it seems that .includes does not have field values other than the default values: For media_fields, it has media_key and type but no other values; Similarly, for poll_fields, it has poll_id and options but no others. 

This is consistent with both 'Client.search_recent_tweets( )' and 'StreamingClient'. 

For example, in the case of StreamingCleint, I used the code as below: 
 
```
class stream(tweepy.StreamingClient):
    
    def on_connect(self): 
        print("Twitter API Connnected")
        
    def on_response(self, response):
        print(response.includes)

streamer = stream(bearer_token=bearerToken, wait_on_rate_limit=True)
streamer.add_rules(tweepy.StreamRule(query))
streamer.filter(expansions=["attachments.poll_ids", "attachments.media_keys"],
                tweet_fields=["author_id","conversation_id","context_annotations","created_at","attachments","entities","possibly_sensitive","public_metrics","referenced_tweets"],
                media_fields=["duration_ms", "preview_image_url", "type", "url", "alt_text", "public_metrics"],
                poll_fields=["duration_minutes", "end_datetime", "options", "voting_status"])
```

Despite using 'expansions' and 'media_fields', response.includes only outputs the default field values. For example, if the 'includes' includes media, it only returns {'media': [ < Media media_key=3_********** type=photo > ]}. As mentioned eariler, this is consistent with 'Client.search_recent_tweets'.

Please help me!!

**Comment by Harmon758** [comment]
Those fields should be populated and just not included in the string representation of the object itself.
See the [FAQ section in the documentation about this](https://tweepy.readthedocs.io/en/v4.10.0/faq.html#why-am-i-not-getting-expansions-or-fields-data-with-api-v2-using-client).
