### ISSUE TITLE
AsyncStreamingClient.delete_rules raises tweepy.errors.BadRequest, when called with a list of StreamRule.

### ISSUE THREAD

**Issue by breuxi** [tweepy/tweepy#1942]
Greetings!

While developing a project I came across a strange error:
`tweepy.errors.BadRequest: 400 Bad Request '_tuplegetter(2, 'Alias for field number 2')' is not a valid Long`

Investigating with my debugger, I found out this happens because the StreamRule class is used instead of the current StreamRule Tuple Object.

This is the exact place in the code, which should be `json["delete"]["ids"].append(str(id.id))` to function properly.
https://github.com/tweepy/tweepy/blob/598ea64d68ab3c27861e0f6dcf9bbce864dc3748/tweepy/asynchronous/streaming.py#L682

Should I open a PR for that, or do you want to do this?

Have a nice day everyone, and don't forget to drink enough! 🥤

**Comment by Harmon758** [comment]
Thanks for the bug report! This should be fixed now.
