### ISSUE TITLE
Underlying dependency `yarl` not accepting NoneType parameter values?

### ISSUE THREAD

**Issue by mijolabs** [tweepy/tweepy#1944]
`AsyncClient.search_recent_tweets()` (and probably Tweepy's other methods using `yarl`) does not accept `NoneType` values for certain parameters, despite [Tweepy documentation](https://docs.tweepy.org/en/stable/asyncclient.html#tweepy.asynchronous.AsyncClient.search_recent_tweets) listing them as an acceptable.

I have a class method calling `search_recent_tweets` with `since_id` and `next_token` parameter values set to `None` by default.

```python
async def search_recent(
    self,
    search_query: str,
    since_id: str = None,
    next_token: str = None,
    ) -> dict:
```

The method later calls `search_recent_tweets()` with the provided parameters, like
```python
return await self.search_recent_tweets(search_query, since_id=since_id, next_token=next_token, ...)
```

Which results in `yarl` throwing a `TypeError` (unless a valid value has been provided to `since_id` and `next_token`).
```python
r = await twitter.search_recent("tweepy")


Traceback (most recent call last):
...
File ".../lib/python3.9/site-packages/yarl/_url.py", line 916, in _query_var
    raise TypeError(
TypeError: Invalid variable type: value should be str, int or float, got None of type <class 'NoneType'>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x104992880>
```

Could this have something to do with `yarl` [not supporting boolean values](https://github.com/aio-libs/yarl#why-isnt-boolean-supported-by-the-url-query-api), and that includes NoneTypes too?

My current workaround is to create a dict inside the method with the func params and only add `since_id`/`next_token` if they're not None, then pass the **params to `search_recent_tweets()` that way. It's not pretty, but works.

**Comment by Harmon758** [comment]
Thanks for the bug report! This should be fixed now.
