### ISSUE TITLE
 unicode char problem

### ISSUE THREAD

**Issue by savataqe1** [tweepy/tweepy#1948]
In the dataset I've drawn, some letters seem corrupted. for example ü,ı,ö,ç,ş .
Is there any solution to this or do I have to continue with this dataset?
example data: 
\ud83d\udcccCHP'li Seyit Torun'un, \u0130\u00e7i\u015fleri Bakan\u0131 S\u00fcleyman Soylu'ya y\u00f6nelik \"\u0130BB\u2019de 557 ter\u00f6rist var demi\u015ftin ama 8 ayd\u0131r g\u0131k\u0131n \u00e7\u0131\u2026

**Comment by Harmon758** [comment]
There's no "corruption" there. That's just UTF-16 encoding.
This isn't an issue with Tweepy.
