### ISSUE TITLE
'Media' object is not iterable when attempting to post a media tweet Twitter API V2

### ISSUE THREAD

**Issue by iiSuperior** [tweepy/tweepy#1958]
Here's the relevant block of code:

```
media_id = api.media_upload(filename, chunked=True, media_category="tweet_video")
client.create_tweet(text='test', media_ids=[media_id])
```

Attempting to run this stalls for a while, as I assume the video is being uploaded. I then get the error mentioned in the post title.

For posterity, I have also attempted:

```
media_id = api.media_upload(filename, chunked=True, media_category="tweet_video")
client.create_tweet(text='test', media_ids=media_id)
```

I get the same error.

**Comment by Harmon758** [comment]
[`API.media_upload`](https://tweepy.readthedocs.io/en/v4.10.1/api.html#tweepy.API.media_upload) returns a [Media object](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/entities#media), not just an ID.

**Comment by iiSuperior** [comment]
I'm not sure what you mean. I hate to ask, but can you explain how to do this properly?

**Comment by Harmon758** [comment]
[`Client.create_tweet`](https://tweepy.readthedocs.io/en/v4.10.1/client.html#tweepy.Client.create_tweet) expects `media_ids` to be a list of integers or strings (or `None`), not a Media object or list of Media objects.
You need to use the `id` (or `id_str`) attribute  of the Media object returned by `API.media_upload` and pass it to `Client.create_tweet` in a list.
