### ISSUE TITLE
List support is buggy

### ISSUE THREAD

**Issue by CatoLynx** [tweepy/tweepy#196]
I'm working on a twitter client and noticed that Tweepy's methods for list handling (especially adding and removing members to / from a list) do not work and return an API error saying that the page doesn't exist.
I think someone should look into this and adapt the code to the current API methods for list handling.

Besides, sometimes when I get an API error, I get just the error description (as expected) but sometimes I get a dictionary with an error code and the error description.

**Comment by Harmon758** [comment]
This should have been fixed with https://github.com/tweepy/tweepy/commit/b144a8e617525f7a6896b68270fcf5bb437e02a9 and https://github.com/tweepy/tweepy/commit/5be123101fc5f8959bb5bed64095ce45f8828b38 in Tweepy 2.0.
