### ISSUE TITLE
API v2 StreamingClient: Stream encountered HTTP error: 429 "This stream is currently at the maximum allowed connection limit"

### ISSUE THREAD

**Issue by johnedstone** [tweepy/tweepy#1962]
Using the tweepy.StreamingClient (for the Twitter API v2), I am getting this error about every 7-20 min.
```
Stream encountered HTTP error: 429
HTTP error response text: {"title":"ConnectionException","detail":"This stream is currently at the maximum allowed connection limit.","connection_issue":"TooManyConnections","type":"https://api.twitter.com/2/problems/streaming-connection"}```
```
Should I be concerned?  The streaming client seems to be working, even with this error.

**Comment by Harmon758** [comment]
As the error indicates, you're encountering a [rate limit](https://developer.twitter.com/en/docs/twitter-api/rate-limits).
Tweepy handles the rate limit by backing off exponentially, [as it's supposed to](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/integrate/handling-disconnections), before attempting to reconnect.
If you're attempting to use [redundant connections](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/integrate/recovery-and-redundancy-features), you'll need Academic Research or Enterprise access to do so.
