### ISSUE TITLE
Client and AsyncClient do not return media url in get_tweet()

### ISSUE THREAD

**Issue by StephanAkkerman** [tweepy/tweepy#1964]
I am trying to get the media url of certain tweets, however the tweepy Client and AsynClient does not return the same information as a normal get request would do.

```
client = tweepy.Client(bearer_token=bearer_token)
print(client.get_tweet(id=1573660149146861569,expansions="attachments.media_keys",media_fields="url"))
```
Gives as output
```
Response(data=<Tweet id=1573660149146861569 text='$PYR 📌 https://t.co/krCPyiJ0nS'>, includes={'media': [<Media media_key=3_1573660144281571328 type=photo>]}, errors=[], meta={})
```

Using the requests library I managed to get the information manually, like so
```
id=1573660149146861569
print(requests.get(
    f"https://api.twitter.com/2/tweets/{id}?expansions=attachments.media_keys&media.fields=url",
    headers={"Authorization": f"Bearer {bearer_token}"},
))
```
This results in the following output
```
{'data': {'attachments': {'media_keys': ['3_1573660144281571328']}, 'id': '1573660149146861569', 'text': '$PYR 📌 https://t.co/krCPyiJ0nS'}, 'includes': {'media': [{'media_key': '3_1573660144281571328', 'type': 'photo', 'url': 'https://pbs.twimg.com/media/FdbDkEkX0AAi41A.jpg'}]}}
```

As you can see this does include the image url, which is never returned when using the Client or AsyncClient.

**Comment by Harmon758** [comment]
> If you are simply printing the objects and looking at that output, the string representations of API v2 models/objects only include the default fields that are guaranteed to exist.
> 
> The objects themselves still include the relevant data, which you can access as attributes or by subscription.

https://tweepy.readthedocs.io/en/v4.10.1/faq.html#why-am-i-not-getting-expansions-or-fields-data-with-api-v2-using-client
