### ISSUE TITLE
Seeking code example: using Tweepy & GET search API pagination?

### ISSUE THREAD

**Issue by inactivist** [tweepy/tweepy#197]
Is there a code example (or documentation) showing proper use of Twitter's GET search API pagination in Tweepy?

**Comment by lucabenato** [comment]
Hi, thanks for the previous comment were very useful for me, but the output for 
<code>for: tweet in tweepy.Cursor(api.search,
                           q="google",
                           rpp=100,
                           result_type="recent",
                           include_entities=True,
                           lang="en").items(): 
                           print tweet</code>
give me too much properties that i don't need. How is possible to have only the tweet text in the output?thanks to all

**Comment by RuoxiLu** [comment]
@lucabenato You can use
```
print tweet.text
```

**Comment by osisieke** [comment]
Hello how an i specify a time frame for a search.
E.g:
for: tweet in tweepy.Cursor(api.search, q="google", rpp=100, timeframe  = 10/10/2016: 10/11/2016).items()
??

**Comment by NandeeshHD** [comment]
@osisieke 
superhero since:2015-12-21	containing “superhero” and sent since date “2015-12-21” (year-month-day).
puppy until:2015-12-21	containing “puppy” and sent before the date “2015-12-21”.

so query string would be q="google since:2016-10-10 until:2016-10-11" 

Ref: https://dev.twitter.com/rest/public/search

**Comment by davidfa94** [comment]
@inactivist 
I am using version 3.5.0 and that piece of code raises an exception:
`TweepError: Failed to send request: local variable "auth" referenced before assignment`.
I guess that changed since 1.10 ?

**Comment by PookieDaCat** [comment]
I was looking for the tweepy cursor doc and tried the link "Cursor Docs", but thanks for the code, seriously, the tweepy pdf doesn't cover passing args to the query as well as your code does.  

-Thanks
