### ISSUE TITLE
AsyncStreamingClient does not respect exponential backoff ratelimit for 429

### ISSUE THREAD

**Issue by TrustyJAID** [tweepy/tweepy#1982]
After setting up the AsyncStreamingClient for v2 I noticed a massive number of 429 error codes, thousands within 24 hours. I did some digging to figure out what is going on and haven't been able to spot the exact cause. What I did notice though is that twitters documentation says that you must use exponential backoff if the error code is 429 starting at 60 seconds but the code only does exponential backoff starting at the minimum 60 seconds when the error code is 420 which I have yet to see. This inevitably leads to the stream constantly attempting to reconnect too early increasing the time before it can reconnect the stream again due to too many connections leading to downtime on the stream.

**Comment by deboomce** [comment]
This relates to issue #1986

**Comment by Harmon758** [comment]
Thanks for the report.
I noticed this recently, but I hadn't gotten around to committing a fix for it yet.
