### ISSUE TITLE
StreamingClient: rate limit implementation incorrect

### ISSUE THREAD

**Issue by deboomce** [tweepy/tweepy#1986]
The `BaseStream` class checks the 420 HTTP error code, while it should be 429.
https://github.com/tweepy/tweepy/blob/33e444a9d13d53ea024ddb3c9da30158a39ea4f6/tweepy/streaming.py#L113

Also: the `wait_on_rate_limit` argument of `StreamingClient` is misleading, because it only impacts the `add_rules` and `delete_rules` methods. It has no impact on the `filter` or `sample` methods.

Related to this: how does a rate limit exactly work for a stream? Apparently you can make 50 requests per 15 minutes to the stream endpoint, but what does this mean exactly in the context of a stream?

**Comment by TrustyJAID** [comment]
It's probably worth mentioning that in twitter's v1.1 streaming API the rate limit error code was 420. The v2 Streaming API the rate limit code changed to 429.

**Comment by Harmon758** [comment]
This is partially a duplicate of #1982.

> It's probably worth mentioning that in twitter's v1.1 streaming API the rate limit error code was [420](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/filter-realtime/guides/connecting). In the v2 Streaming API the rate limit code changed to [429](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/integrate/handling-disconnections).

Correct, I must have missed the change/difference when I implemented streaming for Twitter API v2.

> Also: the `wait_on_rate_limit` argument of `StreamingClient` is misleading, because it only impacts the `add_rules` and `delete_rules` methods. It has no impact on the `filter` or `sample` methods.

This is a separate documentation issue arising from the fact that `StreamingClient` also subclasses `BaseClient`.
I'll work on improving that documentation presently.

> Related to this: how does a rate limit exactly work for a stream? Apparently you can make 50 requests per 15 minutes to the stream endpoint, but what does this mean exactly in the context of a stream?

Each time you connect to the stream is a request being made to the endpoint.
There's also a limit in terms of [the number of active (redundant/simultaneous) connections](https://developer.twitter.com/en/docs/twitter-api/tweets/filtered-stream/integrate/recovery-and-redundancy-features).

> Edit: After some more digging the socket read timeout has changed as well. v1.1 suggests using a 90 second read timeout while v2 suggests a 20 seconds read timeout. Currently the code uses the 90 second read timeout for all streaming endpoints.

Good catch. I hadn't noticed that yet.
I'll work on a fix for that presently.

**Comment by Harmon758** [comment]
> > Edit: After some more digging the socket read timeout has changed as well. v1.1 suggests using a 90 second read timeout while v2 suggests a 20 seconds read timeout. Currently the code uses the 90 second read timeout for all streaming endpoints.
> 
> Good catch. I hadn't noticed that yet. I'll work on a fix for that presently.

This should be resolved with https://github.com/tweepy/tweepy/commit/3a71c9e42ae9bcda479905def0f41b656d2dab5a now.

**Comment by Harmon758** [comment]
> > Also: the `wait_on_rate_limit` argument of `StreamingClient` is misleading, because it only impacts the `add_rules` and `delete_rules` methods. It has no impact on the `filter` or `sample` methods.
> 
> This is a separate documentation issue arising from the fact that `StreamingClient` also subclasses `BaseClient`.
> I'll work on improving that documentation presently.

This should be resolved with https://github.com/tweepy/tweepy/commit/7f0d5871bf4afd4bbe0a5b4a47f62e298d2caa7e (Tweepy's 3000th commit 🎉) now.
