### ISSUE TITLE
StreamRule broken?

### ISSUE THREAD

**Issue by krrishdholakia** [tweepy/tweepy#1988]
Hi, 

I'm using streamrule to filter tweets for a given stream: 

Here's my code: 

`class MyStream(tweepy.StreamingClient):
    # This function gets called when the stream is working
    def on_connect(self):
        print("Connected")

    def on_tweet(self, tweet):
       print(tweet.data) 
       return

stream = MyStream(bearer_token=bearer_token)
stream.add_rules(tweepy.StreamRule("#Bitcoin")) #adding the rules
stream.filter() #runs the stream`

And here's the output: 
<img width="775" alt="Screen Shot 2022-10-21 at 10 51 59 PM" src="https://user-images.githubusercontent.com/17561003/197322835-748eb9d0-54d7-435e-bfd9-e05fccffd002.png">

None of it is relevant to the hashtag. Unsure what's happening here. Any help?

**Comment by Harmon758** [comment]
What existing rules do you have?

For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.

**Comment by krrishdholakia** [comment]
`stream = MyStream(bearer_token=bearer_token)
stream.add_rules(tweepy.StreamRule("#Bitcoin")) #adding the rules
stream.filter() #runs the stream`


@Harmon758

**Comment by Harmon758** [comment]
Again, what existing rules do you have?

And again, for code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.

**Comment by krrishdholakia** [comment]
The rule is to only look for tweets with the #Bitcoin (as an example): 

```
stream = MyStream(bearer_token=bearer_token)
stream.add_rules(tweepy.StreamRule("#Bitcoin")) #adding the rules
stream.filter() #runs the stream

```

**Comment by Harmon758** [comment]
Showing the same code for the third time does not answer the question.

**Comment by krrishdholakia** [comment]
There is no other rule beyond this one. I am unsure what additional information is required here.

**Comment by Harmon758** [comment]
Have you checked?

**Comment by Harmon758** [comment]
Yes, you need to provide a reproducible example (MCVE/SSCCE), along with what existing rules you have.
This issue is not reproducible or actionable as is.

**Comment by Bhb-1** [comment]
Hi, is this problem solved? I am now also encountering the same problem that the filtering rules do not take effect, and I have checked that the code logic is basically consistent with yours.

**Comment by Harmon758** [comment]
> You need to provide a reproducible example (MCVE/SSCCE), along with what existing rules you have.
> This issue is not reproducible or actionable as is.

**Comment by Bhb-1** [comment]
my code like that:

`import tweepy
from tweepy import StreamingClient, StreamRule

bearer_token = "***************"

class TweetPrinterV2(tweepy.StreamingClient):

    def on_tweet(self, tweet):
        print(f"{tweet.id} {tweet.created_at} ({tweet.author_id}): {tweet.text}")
        print("-" * 50)

printer = TweetPrinterV2(bearer_token)

# add new rules
rule = StreamRule(value="Python")
printer.add_rules(rule)

printer.filter()`

**Comment by Harmon758** [comment]
Again, you need to provide more information. What is your expected and actual behavior? What existing rules do you have?

For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.

**Comment by Bhb-1** [comment]
```python

import tweepy
from tweepy import StreamingClient, StreamRule

bearer_token = "***************"

class TweetPrinterV2(tweepy.StreamingClient):

    def on_tweet(self, tweet):
        print(f"{tweet.id} {tweet.created_at} ({tweet.author_id}): {tweet.text}")
        print("-" * 50)

printer = TweetPrinterV2(bearer_token)

# add new rules
rule = StreamRule(value="Python")
printer.add_rules(rule)

printer.filter()

```

**Comment by Bhb-1** [comment]
> Again, you need to provide more information. What is your expected and actual behavior? What existing rules do you have?
> 
> For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.

And judging from the results of my code running, this rule does not take effect, and the tweets I get do not contain python. I don’t know where the problem is

> ```python
> import tweepy
> from tweepy import StreamingClient, StreamRule
> 
> bearer_token = "***************"
> 
> class TweetPrinterV2(tweepy.StreamingClient):
> 
>     def on_tweet(self, tweet):
>         print(f"{tweet.id} {tweet.created_at} ({tweet.author_id}): {tweet.text}")
>         print("-" * 50)
> 
> printer = TweetPrinterV2(bearer_token)
> 
> # add new rules
> rule = StreamRule(value="Python")
> printer.add_rules(rule)
> 
> printer.filter()
> ```
> 
> My code is like this, I want to get the output of the tweets containing the hashtag #Python

And judging from the results of my code running, this rule does not take effect, and the tweets I get do not contain python. I don’t know where the problem is

**Comment by Harmon758** [comment]
Again, what existing rules do you have?

**Comment by Bhb-1** [comment]
> Again, what existing rules do you have?

Sorry I'm a new learner on this.
I think in my code
```python
rule = StreamRule(value="Python")
printer. add_rules(rule)
```
That is my rule and there are no other rules
I want to run the code and return the result of #Python

**Comment by Harmon758** [comment]
Have you checked what other existing rules you have?

**Comment by Bhb-1** [comment]
> Have you checked what other existing rules you have?

There is nothing else, my code is just these, and I re-created the project and re-run the code, the result is that I did not get tweets containing python

**Comment by Harmon758** [comment]
Have you checked?..

**Comment by Bhb-1** [comment]
> Have you checked?..

I promise I checked.the code logic is all there , I still don't know why I don't get the result I want

**Comment by Harmon758** [comment]
What was the response when you checked?

**Comment by Bhb-1** [comment]
> What was the response when you checked?

The result of the code running looks like some real-time tweets, without any rules

**Comment by Bhb-1** [comment]
> What was the response when you checked?

Is there something wrong with my code?

**Comment by Bhb-1** [comment]
> What was the response when you checked?

Thank you very much, now I understand what you mean. When I checked my filtering rules with the get_rules().data method, I found that there were some filtering rules in my previous code in StreamRule. After I deleted the rules one by one with delete_rules() and re-run my original code, I Get tweets with python characters. Thank you very much! !
