### ISSUE TITLE
api.user_timeline() produces error

### ISSUE THREAD

**Issue by virajp1110** [tweepy/tweepy#1999]
Code: api.user_timeline(screen_name = user_name, count=200,tweet_mode="extended")

tweepy version: 4.8.0
Error: user_timeline() takes 1 positional argument but 2 were given

**Comment by Harmon758** [comment]
> Why am I getting a [`TypeError`](https://docs.python.org/3/library/exceptions.html#TypeError) about an [`API`](https://docs.tweepy.org/en/stable/api.html#tweepy.API) method taking 1 positional argument but given 2?
> 
> This and other similar errors are due to [Tweepy v4.0.0](https://docs.tweepy.org/en/stable/changelog.html#version-4-0-0-2021-09-25) changing [`API`](https://docs.tweepy.org/en/stable/api.html#tweepy.API) methods to no longer accept arbitrary positional arguments. The 1 positional argument being referred to in the error is `self`.
> 
> These parameters can be passed as keyword arguments instead.
> 
> Refer to the documentation for the [`API`](https://docs.tweepy.org/en/stable/api.html#tweepy.API) method being used.

https://tweepy.readthedocs.io/en/v4.12.0/faq.html#why-am-i-getting-a-typeerror-about-an-api-method-taking-1-positional-argument-but-given-2
