### ISSUE TITLE
 Is there a way to get all the videos and gifs of the tweets?

### ISSUE THREAD

**Issue by takuya01251** [tweepy/tweepy#2011]
Multiple videos can now be attached to a single tweet on Twitter.
However, tweepy can only retrieve the first video.
Is there a way to get all the videos and gifs?

**Comment by Harmon758** [comment]
I'm not sure why you're saying Tweepy can only retrieve the first video and then proceeding to contradictorily ask for a way to retrieve all the videos, but that's incorrect anyway. Tweepy fully supports mixed media, with no changes to the library even necessary for its release.
