### ISSUE TITLE
Oauth2 authentication problems

### ISSUE THREAD

**Issue by chromafunk** [tweepy/tweepy#2014]
following the suggested code in the docs for Oauth2 flow, I do this:

```
oauth2_user_handler = tweepy.OAuth2UserHandler(
    client_id="xxxxx",
    redirect_uri="http://127.0.0.1:8080",
    scope=["tweet.read", "tweet.write", "tweet.moderate.write", "users.read", "follows.read", "follows.write", "offline.access", "space.read",
           "mute.read", "mute.write", "like.read", "like.write", "list.read", "list.write", "block.read", "block.write", "bookmark.read", "bookmark.write"],
    # Client Secret is only necessary if using a confidential client
    client_secret="xxxxxxx"
)
```

`print(oauth2_user_handler.get_authorization_url())`

when I get the URL I authorize my user with the app, then I get redirected to the callback URL

then when I do this, by pasting the resulting URL, I get the following error : 
`access_token = oauth2_user_handler.fetch_token(xxxxxxx)`

```
    raise cls(**kwargs)
oauthlib.oauth2.rfc6749.errors.InvalidClientIdError: (invalid_request) Missing required parameter [code_verifier].
```

what I'm missing ? do I need to format the resulting url after auth on a specific way before passing it to `fetch_token() `?

my needs are just to have my own user ( the account owner ) to use all these scopes defined. I don't need to have any other user using the app

 thanks

**Comment by chromafunk** [comment]
just realized that this can be done just with the tokens and api keys provided by tweeter without the need to Oauth

**Comment by Harmon758** [comment]
I'm unable to reproduce this.
You'll have to provide how exactly you're passing the URL to `fetch_token` if you need further help with this.

> do I need to format the resulting url after auth on a specific way before passing it to `fetch_token() `?

No, it should be the full un-modified URL.

> just realized that this can be done just with the tokens and api keys provided by tweeter without the need to Oauth

You need to use OAuth to authenticate. There is no way around that.
If you're referring to the OAuth 1.0a User Context credentials that you can generate through the Twitter Developer Portal, that is still OAuth.
