### ISSUE TITLE
Your media ID's are invalid

### ISSUE THREAD

**Issue by chromafunk** [tweepy/tweepy#2016]
```
        self.media_filename = media_filename
        self.media = self.twitter.api.media_upload(self.media_filename, chunked=True, media_category="tweet_video")
        self.twitter.client.create_tweet(text='test', media_ids=[self.media.media_id])
```
I am getting the ID correctly after uploading which is an long int, but when creating the tweet it fails with : 

```
tweepy.errors.BadRequest: 400 Bad Request
Your media IDs are invalid.
```

what is the correct way to do this ? 

Thanks !

**Comment by Harmon758** [comment]
Does your video meet the required and recommended specifications?
https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/uploading-media/media-best-practices

**Comment by chromafunk** [comment]
thanks, for some reason twitter doesn't like the videos when I encode them with the nvidia h264 codec, but it does when I do it with the regular h264 lib

cheers
