### ISSUE TITLE
HTTP  406 error when using stream to follow a user_id

### ISSUE THREAD

**Issue by Kousaka-Honoka** [tweepy/tweepy#2023]
tweepy_version=4.0.0

Code be like
`
myStream = Stream(consumer_key,consumer_secret,access_token,access_token_secret)
`
`myStream.filter(follow=['@_zongxiong_'])`
or 
`myStream.filter(follow=['_zongxiong_'])`
Both raise HTTP 406 erorr.
However the ` myStream.filter(track=['python'])` works
![image](https://user-images.githubusercontent.com/36869676/203773095-f1a3c8f5-bf58-4780-b40a-c855d01e364a.png)

**Comment by Harmon758** [comment]
[`Stream.filter`](https://tweepy.readthedocs.io/en/v4.0.0/stream.html#tweepy.Stream.filter) accepts user IDs for the `follow` parameter, not handles/usernames.
