### ISSUE TITLE
Can someone confirm this image url can be downloaded in Python or curl? 

### ISSUE THREAD

**Issue by davidbernat** [tweepy/tweepy#2030]
Often the embedded image will be hosted internally to Twitter, with a `expanded_url` such as:

`https://twitter.com/POTUS/status/1610721959330840578/photo/1`

Can someone confirm for me this image can be downloaded using Python `requests` or command line `curl` and post their code in the reply?

Thank you 🙏

**Comment by Harmon758** [comment]
That's simply the display page for the media.
You'll want to use the media URL instead.
