### ISSUE TITLE
Feature Request: view count info in `API.get_status()`

### ISSUE THREAD

**Issue by yyzz1010** [tweepy/tweepy#2032]
as there is new `impression_count` info in `public_metrics`, would be nice to have this info added for easy access, thx!

**Comment by Harmon758** [comment]
[`API.get_status`](https://tweepy.readthedocs.io/en/v4.12.1/api.html#tweepy.API.get_status) returns the data directly from the Twitter API's [GET statuses/show/:id endpoint](https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/get-statuses-show-id), and that's not something that that endpoint supports.
