### ISSUE TITLE
support for use of premium educational access for accessing full achieve data of past 6 months

### ISSUE THREAD

**Issue by prathamesh168** [tweepy/tweepy#2049]
- we want to use tweepy for educational use.

- for that we need tweet data of past 6 months

- we have access for educational access for tweeter api.

**Comment by prathamesh168** [comment]
- we want to use tweepy for educational use. 
- for that we need tweet data of past 6 months 
- we have access for educational  access for tweeter api.

**Comment by Harmon758** [comment]
Tweepy already supports the Premium v1.1 Search APIs, as well as Academic Research access.
Otherwise, I'm not sure what "full achieve data" or "tweeter api" is referring to.
