### ISSUE TITLE
cursor can not use but other functions can

### ISSUE THREAD

**Issue by Changanyuexia** [tweepy/tweepy#2052]
I have the v2 access to api. And 2 days ago, I could use cursor to get data, but now I cannot. My account email is qm17509@my.bristol.ac.uk, please help me with the issue.

I need to use cursor to get text data.

**Comment by Harmon758** [comment]
This isn't actionable at all, as there is no information here.
You need to provide the relevant code and/or full traceback, with the expected and actual behavior, for anyone to be able to help you.

**Comment by Changanyuexia** [comment]
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth)

# Create API object
api = tweepy.API(auth)

hashtag = "chatgpt"
start_date = "2022-12-30"
end_date = "2023-01-01"

# Authenticate to Twitter
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
for tweet in tweepy.Cursor(api.search_tweets, q=hashtag, until=end_date, locale="en", lang ="en").items(10):


here is my code. cursor does not work, also api.search_tweets, only api.home_timeline works
