### ISSUE TITLE
Paginator Not Working With My Twitter Account

### ISSUE THREAD

**Issue by SakiSakiSakiSakiSaki** [tweepy/tweepy#2055]
Hi,

I am attempting to get my liked tweets from my profile, however my profile is locked/privated. I have some working code that only returns 20 liked tweets from my profile.

```
import tweepy
import configparser
import pandas as pd
import json, requests, re, os

#Credentials
config = configparser.ConfigParser(interpolation=None)
config.read('config.ini')
api_key = config['twitter']['api_key']
api_key_secret = config['twitter']['api_key_secret']
access_token = config['twitter']['access_token']
access_token_secret = config['twitter']['access_token_secret']
twitter_id = config['twitter']['twitter_id']

bearer_token = config['twitter']['bearer_token']

# Auth
auth = tweepy.OAuthHandler(api_key, api_key_secret)
auth.set_access_token(access_token, access_token_secret)


#Calling API
api = tweepy.API(auth, parser=tweepy.parsers.JSONParser())
client = tweepy.Client(bearer_token)
grabbed_tweets = api.get_favorites(user_id = twitter_id)

#-----------------------------
tweet_id_list = []

for tweet in grabbed_tweets:
    tweet_id_list.append(tweet['extended_entities']['media'][0]['id'])
print(len(tweet_id_list), "Tweets") #20 Tweets
```

I'd like all of my liked tweets, so I tried using paginator, however it returns nothing for me, while returning 250 tweets for other public Twitter profiles.

This is NASA's account, returning 250 tweets.
```
tweet_id_list = []
nasa_twitter_id = 11348282
for tweet in tweepy.Paginator(client.get_liked_tweets, id = nasa_twitter_id, max_results = 100).flatten(limit = 250):
    tweet_id_list.append(tweet.id)
print(len(tweet_id_list), "Tweets") #250 Tweets
```
This is my account, returning 0 tweets.
```
tweet_id_list = []
for tweet in tweepy.Paginator(client.get_liked_tweets, id = twitter_id, max_results = 100).flatten(limit = 250):
    tweet_id_list.append(tweet.id)
print(len(tweet_id_list), "Tweets") #0 Tweets
```

Am I doing something wrong? How can I fix this? Thanks.

**Comment by Harmon758** [comment]
Is `bearer_token` from OAuth 2.0 Authorization Code Flow with PKCE?

**Comment by Harmon758** [comment]
Since the account in question is private, you need to authenticate as that user with [OAuth 2.0 Authorization Code Flow with PKCE](https://tweepy.readthedocs.io/en/v4.12.1/authentication.html#oauth-2-0-authorization-code-flow-with-pkce-user-context) if you want to use an OAuth 2.0 access token. Otherwise, an app-only bearer token will not have access to the account.

Alternatively, you can just use your OAuth 1.0a User Context credentials or `Cursor` with `API` (and that endpoint/method's `count` parameter).
