### ISSUE TITLE
Twitter API No longer free.

### ISSUE THREAD

**Issue by Commander-Crash** [tweepy/tweepy#2057]
I don't know if there is somehow around this. On feb 9th elon will decide to monetize it.
https://twitter.com/TwitterDev/status/1621026986784337922

**Comment by Harmon758** [comment]
More accurately:
> Starting February 9, we will no longer support free access to the Twitter API, both v2 and v1.1. A paid basic tier will be available instead
> 
> We’ll be back with more details on what you can expect next week.

There is no further information about this right now, so there's nothing to be done about it yet.

Personally, I am highly opposed to this change though.
