### ISSUE TITLE
[docs] Expansion and Fields `owner_id` instead of `author_id`

### ISSUE THREAD

**Issue by ranggakd** [tweepy/tweepy#2064]
as a [Expansions and Fields - tweepy 4.12.1 documentation](https://github.com/tweepy/tweepy/blob/cc8dd493b1ed04b48a6dd4e47eeb9a9064f83024/docs/expansions_and_fields.rst#expansions) it says:

> At this time, the only expansion available to endpoints that primarily return List objects is `expansions=owner_id`. You will find the expanded user data object living in the `includes` response object.

But when I tried to code this example below

```python
tr = client.get_liked_tweets(id_dict['Indonesia'],max_results=5,tweet_fields=['created_at'],expansions=['owner_id'])
```

it threw this error
```
BadRequest: 400 Bad Request
The `expansions` query parameter value [owner_id] is not one of [author_id,referenced_tweets.id,referenced_tweets.id.author_id,entities.mentions.username,attachments.poll_ids,attachments.media_keys,in_reply_to_user_id,geo.place_id,edit_history_tweet_ids]
```

I think it supposed to be `author_id` instead of `owner_id`. If that so, I will request PR right away. Thanks

**Comment by Harmon758** [comment]
[`Client.get_liked_tweets`](https://tweepy.readthedocs.io/en/v4.12.1/client.html#tweepy.Client.get_liked_tweets) returns Tweet objects, not List objects.

**Comment by ranggakd** [comment]
I don't think you get my point. Still `owner_id` is not one of those `expansions` parameters I find based on that error. I suggest updating the docs immediately.

**Comment by Harmon758** [comment]
As that documentation says, `owner_id` is the only available expansion for methods (that use endpoints) that return List objects.
`Client.get_liked_tweets` is not one of those methods.
This documentation is correct.

**Comment by ranggakd** [comment]
I don't quite catch that in the first viewing. It would be better if it provides one example function to the context i.e. [Client.get_followed_list](https://docs.tweepy.org/en/stable/client.html#tweepy.Client.get_followed_lists).

```diff
- At this time, the only expansion available to endpoints that primarily return List objects is expansions=owner_id.
+ At this time, the only expansion available to endpoints (i.e. Client.get_followed_list) that primarily return List objects is expansions=owner_id. 
```
Now I agree, sorry for the inconvenience.
