### ISSUE TITLE
[feature request] `Paginator.flatten()` return tuple of `data, includes, errors, meta`

### ISSUE THREAD

**Issue by ranggakd** [tweepy/tweepy#2065]
Could we enable this feature on flatten method? I think it is pretty beneficial to include more information when necessary (trigger by parameter) i.e. `includes`

> `response` may do not have `.data` attribute when `response` isn't the default return type. Here, the returned data structure also lost other information (meta, includes, error) except `data` attr.

> And no unit tests for both sync/async Paginator for now.

> _Originally posted by @lqhuang in https://github.com/tweepy/tweepy/issues/1933#issuecomment-1292918797_

**Comment by lqhuang** [comment]
It's probably difficult IMHO, because the API is required to re-design under this situation? And this depends on the owner/maintainer of tweepy.

My simplest approach to solve this is I don't use `flatten()` further, but manually iterate `Paginator` directly.

Do you have other advices?

**Comment by Harmon758** [comment]
This doesn't make sense. The purpose of `Paginator.flatten` is to flatten the data.
If you want the `Response` objects, then just use the `Response` objects from iterating over the `Paginator` instance itself.
