### ISSUE TITLE
Client.get_user_tweets() fails to retrieve protected tweets, even when authenticated user account has been allowed to view these tweets

### ISSUE THREAD

**Issue by peterdh** [tweepy/tweepy#2070]
Running the code below where `user_id` is that of a Twitter account with protected tweets that has allowed user whose authentication gives us `access_token` and `access_token_secret` below returns a "Not authorized for resource error":

`Response(data=None, includes={}, errors=[{'resource_id': 'XXXXXXXXXXXXXXXXX, 'parameter': 'id', 'resource_type': 'user', 'section': 'data', 'title': 'Authorization Error', 'value': 'XXXXXXXXXXXXXXXXX', 'detail': 'Sorry, you are not authorized to see the user with id: [XXXXXXXXXXXXXXXX].', 'type': 'https://api.twitter.com/2/problems/not-authorized-for-resource'}], meta={})`

Raising the issue because I was not experiencing the problem about ~2 months ago & wondering if recent changes to API have affected some tweepy functionality. Any thoughts? Thanks--

`

```
def get_tweets(user_id):
    
    auth = tweepy.OAuth1UserHandler(api_key, api_key_secret, access_token, access_token_secret)
    api = tweepy.API(auth, wait_on_rate_limit=True)

    client = tweepy.Client(
        bearer_token=bearer_token, 
        consumer_key=api_key, 
        consumer_secret=api_key_secret, 
        access_token=access_token, 
        access_token_secret=access_token_secret)


    start_time = "2022-12-29T10:00:01Z". # this is an arbitrary start date

    for tweet in tweepy.Paginator(client.get_users_tweets, user_id, start_time=start_time):
        print(tweet)
````

**Comment by Harmon758** [comment]
By default, [`Client.get_users_tweets`](https://tweepy.readthedocs.io/en/v4.12.1/client.html#tweepy.Client.get_users_tweets) does not use OAuth 1.0a User Context to authenticate, so if you're passing an app-only bearer token, it's attempting to use that.

You need to pass `False` for `user_auth` or use an OAuth 2.0 Authorization Code Flow with PKCE access token.

For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.
