### ISSUE TITLE
client.get home_timeline() only returns RTs from accounts I don't follow

### ISSUE THREAD

**Issue by MatthieuDurand08** [tweepy/tweepy#2076]
Hello guys, 

I have a really weird problem happening to me. When I use client.get home_timeline()

```
response = client.get_home_timeline(
                expansions=[
                    "author_id",
                    "in_reply_to_user_id",
                    "referenced_tweets.id",
                    "referenced_tweets.id.author_id",
                ],
                user_fields=["id"],
                tweet_fields=[
                    "public_metrics",
                    "created_at",
                    "in_reply_to_user_id",
                    "referenced_tweets",
                ],
                start_time=last_24_hour,
            )

```

RTs from accounts I don't follow are sent back to me. But if I follow the account in the meantime and I relaunch the request, the same RT disappears. On the other hand, the QRTs are always displayed. Do you have any idea what's going on?

**Comment by IParraMartin** [comment]
I used to have this same issue some time ago, but I can't remember how I solved it...

**Comment by Harmon758** [comment]
Do you have a reproducible example of this?

@IParraMartin Please don't unnecessarily bump issues with non-constructive comments, especially if they're not even applicable or relevant to you anymore.
