### ISSUE TITLE
Twitter error: Invalid file type for image: video/mp4

### ISSUE THREAD

**Issue by carelesswhisp** [tweepy/tweepy#2077]
I keep getting this error, I have it set so that when it sees a new video in a folder, it takes it resizes it with ffmpeg then applies the hashtags and tweets it. however, the error persists, whether it's 30 seconds or 1 minute. uploading both the resized and original directly to Twitter both work and play.  

*SOLVED VIA UPDATE OF TWEEPY*

**Comment by carelesswhisp** [comment]
> What's the full traceback?

Thats all the erorrs i could get out of it. Everything else fires perfectly without a hitch. No matter the media category i choose same issue.

**Comment by Harmon758** [comment]
You need to provide the full traceback.

**Comment by carelesswhisp** [comment]
> You need to provide the full traceback.

i don't know what you want there are no failure points, the API just returns that not fail state that stops the code 
Video resized: Z:\name_resized.mp4 
Twitter error: Invalid file type for image: video/mp4

which at first I just thought it was due to the original way the type was set but changing it still produces the same issue.

**Comment by Harmon758** [comment]
I'm not sure what you mean by "there are no failure points".
If you're getting an error like you say, then tautologically, there's an error.
I have no idea what you mean by "the API just returns that not fail state that stops the code" either.
Regardless, a full traceback would clarify exactly what you're encountering, and this isn't actionable without one.

**Comment by carelesswhisp** [comment]
> 

can you explain simply what you want? I've tried to get the trace back by running it in interactive mode, I see no issues. in the debug console and terminal nothing. the only message is coming back that the file type is invalid

**Comment by carelesswhisp** [comment]
never mind i need to go to bed, tweepy was not updated on this computer. therefore it wasn't working right

**Comment by Harmon758** [comment]
https://docs.python.org/3/tutorial/errors.html#exceptions
https://en.wikipedia.org/wiki/Stack_trace
