### ISSUE TITLE
Attribute error no matter what you do to fix it.

### ISSUE THREAD

**Issue by bentosilva** [tweepy/tweepy#2079]
AttributeError: module 'tweepy' has no attribute 'Client'

**Comment by Harmon758** [comment]
What version of Tweepy are you using?
Do you have a another file or folder in your path called "tweepy"?

**Comment by bentosilva** [comment]
I'm using the latest version 
4.13.0

**Comment by bentosilva** [comment]
Two folders:
1) ~\Anaconda3\Lib\site-packages\tweepy\__pycache__
2) ~\Anaconda3\Lib\site-packages\tweepy\asynchronous
And many files such as:
__init__.py
api.py
...
client.py
...
sítios.py

**Comment by Harmon758** [comment]
If you have v4 installed and you see client.py in your installation, then you're almost certainly importing another file or folder in your path named "tweepy".

**Comment by IParraMartin** [comment]
I used to have the same issue a while ago. I think it had to do with some kind of API permission or a Tweepy update. Can't really remember but you could try doing some research on those aspects!

**Comment by Harmon758** [comment]
This has nothing to do with Twitter API permissions, and if they're using Tweepy v4, it has nothing to do with any update to Tweepy either.

Please don't unnecessarily add to an already answered issue.
