### ISSUE TITLE
"user_fields" and "expansions" does not work in client.get_user() final response

### ISSUE THREAD

**Issue by 0xXtro** [tweepy/tweepy#2082]
for the request 
`user = client.get_user(id=user_id,user_fields="description,profile_image_url",expansions="pinned_tweet_id")
`
tweepy.client._make_request gets the data correct `{'data': {'profile_image_url': 'https://pbs.twimg.com/profile_images/1628443532582338562/S2GGDtdw_normal.jpg', 'username': '0xXtro', 'description': 'do no harm. don’t take shit.', 'id': '1616063322725679104', 'name': 'xtro'}}`

but since the response is not a list, somehow client._process_includes looses the data `Response(data=<User id=1616063322725679104 name=xtro username=0xXtro>, includes={}, errors=[], meta={})`

**Comment by Harmon758** [comment]
Regarding the user fields, I'm unable to reproduce this:
```pycon
>>> response = client.get_user(
...     id=1616063322725679104,
...     expansions="pinned_tweet_id",
...     user_fields="description,profile_image_url"
... )
>>> user = response.data
>>> user.description
'do no harm. don’t take shit.'
>>> user.profile_image_url
'https://pbs.twimg.com/profile_images/1628443532582338562/S2GGDtdw_normal.jpg'
```

If you're referring to the string representation of the `Response` object, that is as intended:
https://tweepy.readthedocs.io/en/v4.13.0/faq.html#why-am-i-not-getting-expansions-or-fields-data-with-api-v2-using-client

As for the `pinned_tweet_id` expansion, that user does not have a pinned Tweet, so there is no Tweet to be returned in `includes`.
