### ISSUE TITLE
Tweepy exception hierarchy

### ISSUE THREAD

**Issue by beaumartinez** [tweepy/tweepy#209]
Tweepy uses `TweepError` for all errors—whether they be network errors, authentication errors, or any other flavour.

This makes handling the different underlying reasons difficult—I don't know if the error was because Twitter is down, or because the user revoked my app.

I'd love it if Tweepy had an exception hierarchy—overloading Python's own. `TweepError` would still be the base class—maintaining backwards compatibility—but we'd also have other well-defined exception types. `TweepNetworkError`, inheriting from both `TweepError` and `IOError`, for example.
#16 (from three years ago, wow) touches on this issue—and to fix it, you added the HTTP response to the exception. However, that isn't available everywhere, nor is it always possible—[OAuthHandler. get_username](https://github.com/tweepy/tweepy/blob/master/tweepy/auth.py#L161) throws a `TweepError` without the HTTP response, for example. #58 is similar as well.

Let me know what you think. I don't mind adding the code myself, and I'm sure it'd be a welcome change. It'd make buiding robust apps on top of Tweepy easier—and make making them more user friendly easier as well.

Keep up the awesome work!

**Comment by Araib93** [comment]
This has been driving me crazy for days now... I keep getting different errors but all get caught in a single exception... makes it super hard to code right, can this be reopened?

**Comment by 1029338** [comment]
Guys any update on this issue?
