### ISSUE TITLE
Unexpected parameter: contributor_details Unexpected parameter: inlclude_entities

### ISSUE THREAD

**Issue by vardhans07** [tweepy/tweepy#2091]
when i try use tweepy using api-key but this error occured .how tackle this problem.

**Comment by vardhans07** [comment]
Unexpected parameter: contributor_details
Unexpected parameter: inlclude_entities

**Comment by Harmon758** [comment]
Like it says, whatever method/endpoint you're using doesn't expect those parameters that you're passing.

If you need further help, you'll need to provide the relevant code and what exactly you're trying to do.
