### ISSUE TITLE
[bug] Threads are not working

### ISSUE THREAD

**Issue by giacomov** [tweepy/tweepy#2094]
I am seeing a strange behavior that looks like a bug.

I am trying to create a thread, so I post a tweet and then I post other tweets in reply to the first one.

This is my code

```
response = client.create_tweet(
            text="testing"
        )
client.create_tweet(
            text="testing reply", in_reply_to_tweet_id=response.data['id']
        )
```
After this, if I log to the user sending the tweet, the threads is there and works as expected.

However, a user that is following the user who posted the thread cannot see the thread. Clicking on the second message takes that user to a thread, but instead of showing also the previous message, this user sees "This tweet is unavailable". Clicking on the first message shows as if there was a thread, but the second message is NOT displayed (there's a small gray dot instead). It looks like only the poster account can see that the two things are connected.

Am I doing something wrong? Is this a Twitter bug? It is a really weird behavior.

**Comment by giacomov** [comment]
I am on the latest version of tweepy (4.13.0)

**Comment by Harmon758** [comment]
I'm unable to reproduce this, as this is on Twitter's end and not an issue with Tweepy.
This could be due to spam detection or some other reason: https://help.twitter.com/en/rules-and-policies/notices-on-twitter
