### ISSUE TITLE
 Forbidden(response) tweepy.errors.Forbidden: 403 Forbidden When authenticating requests to the Twitter API v2 endpoints

### ISSUE THREAD

**Issue by vardhans07** [tweepy/tweepy#2098]
line 100, in request
    raise Forbidden(response)
tweepy.errors.Forbidden: 403 Forbidden
When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.

**Comment by vardhans07** [comment]
import tweepy
import config

client = tweepy.Client(bearer_token='XXXXXXXXXX')
query = 'from:suhemparack -is:retweet'

start_time = '2020-01-01T00:00:00Z'

# Replace with time period of your choice
end_time = '2020-08-01T00:00:00Z'

tweets = client.search_all_tweets(query=query, tweet_fields=['context_annotations', 'created_at'],
                                  start_time=start_time,
                                  end_time=end_time, max_results=5)
for tweet in tweets.data:
    print(tweet.text)
    print(tweet.created_at)




this is my code 


#config.py
API_KEY='xxxxxxxxxxxxxxxxxxx'
API_SECRET='xxxxxxxxxxxxxxxxxxxxx'
Bearer_TOKEN='xxxxxxxxxxxxxxxxx'
ACCESS_TOKEN='xxxxxxxxxxxxxxxxxxxxxxx'
ACCESS_TOKEN_SECRET='xxxxxxxxxxxxxxxxxxxxxxx'


everything was right but 403forbidden error occured.

**Comment by vardhans07** [comment]
![run on postman](https://user-images.githubusercontent.com/95933896/235137868-33dc3758-befe-4a99-b460-fef5fb4ab517.png)
![run on postman](https://user-images.githubusercontent.com/95933896/235137875-82d4ae72-edaa-4dbc-bee2-c4ed437e8dd3.png)


even try to check quick access from postman but  still not working

**Comment by vardhans07** [comment]
![error](https://user-images.githubusercontent.com/95933896/235138958-4d463228-b142-4e95-92e7-844dedb086b1.png)

**Comment by Harmon758** [comment]
Read the error.

For code block usage, see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.

**Comment by vardhans07** [comment]
But even not working on postman website .

**Comment by ChankitSaini** [comment]
I have same issue.

> line 100, in request raise Forbidden(response) tweepy.errors.Forbidden: 403 Forbidden When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.

**Comment by Harmon758** [comment]
Please don't bump old closed issues.
You should start a new discussion with what exactly you're trying and encountering.
