### ISSUE TITLE
posting tweets or retweets no longer wirk with tweept due to changes in api 

### ISSUE THREAD

**Issue by MistyIce672** [tweepy/tweepy#2101]
changes should be made to the endpoints i believe 
tweepy response : 403 Forbidden
453 - You currently have Essential access which includes access to Twitter API v2 endpoints only. If you need access to this endpoint, you’ll need to apply for Elevated access via the Developer Portal. You can learn more here: https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api#v2-access-leve

**Comment by MistyIce672** [comment]
my current work around for this to make the request using python requests

**Comment by HogenYuan** [comment]
same

**Comment by Harmon758** [comment]
Please read the error and https://twittercommunity.com/t/announcing-new-access-tiers-for-the-twitter-api/188728.
Tweepy is not affiliated with Twitter, so changing API endpoints themselves is not an option, nor is this a new error related to any recent changes. It's impossible to tell without the full traceback and/or what exactly you're trying, but you're likely attempting to use Twitter API v1.1, which has never been possible with Essential access.
