### ISSUE TITLE
genuine plea for help

### ISSUE THREAD

**Issue by davidulu25** [tweepy/tweepy#2103]
please I'm a new beginner and still figuring out how to send out tweets with my automated twitter account. It seems twitter is asking me to apply for elevated access. Is there any way I can access endpoints that allow me to tweet without applying for elevated access?

**Comment by Harmon758** [comment]
Yes, you can just use Free access.
https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api
https://twittercommunity.com/t/announcing-new-access-tiers-for-the-twitter-api/188728
