### ISSUE TITLE
get_list_tweets() returns a 401 Unauthorized error

### ISSUE THREAD

**Issue by bigsky77** [tweepy/tweepy#2107]
When I call get_list_tweets() via the Tweepy v2 API,  I am getting a 401 error.  I am a subscriber to Basic and according to the docs this endpoint is included in that tier.  

Everything else works fine and I am able to retrieve timeline tweets and post tweets via the api.

**Comment by Harmon758** [comment]
There's no information here with which to help you.
You need to provide what exactly you're trying and encountering, e.g. the relevant code or a reproducible example (MCVE/SSCCE) and the full traceback.

**Comment by bigsky77** [comment]
This issue arises when using an OATH v1 tweepy client for retrieving list tweets.  The issue is resolved by using OATH v2 client with the Bearer Token.

**Comment by Harmon758** [comment]
If by "OATH v1" and "OATH v2" you mean OAuth 1.0a and OAuth 2.0, that method should work with both.
