### ISSUE TITLE
Tweepy wont display full tweet even after using extend mode

### ISSUE THREAD

**Issue by panchaliDM** [tweepy/tweepy#2113]
Hi, I am trying to extract Tweets and I am in the first few stages of my code. But i have included the following to get the extended tweet but i still get the below

code:
tweets = api.search_tweets(q="colombo", lang="en", tweet_mode='extended', count=2)
for tw in tweets:
    print(tw.full_text)

Returned Tweet: RT @rothbourne: Just another day in the streets of Colombo...

**Comment by Harmon758** [comment]
> When using extended mode with a Retweet, the `full_text` attribute of the Status object may be truncated with an ellipsis character instead of containing the full text of the Retweet. However, since the `retweeted_status` attribute (of a Status object that is a Retweet) is itself a Status object, the `full_text` attribute of the Retweeted Status object can be used instead.

https://tweepy.readthedocs.io/en/v4.14.0/extended_tweets.html#handling-retweets

This is a limitation with Twitter's API, not an issue with Tweepy.

For code block usage, see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.
