### ISSUE TITLE
OAuth 2.0 Authorization Code Flow with PKCE uses OAuth1UserHandler

### ISSUE THREAD

**Issue by marbella-web** [tweepy/tweepy#2122]
Using your method outlined in the docs 
import tweepy

oauth2_user_handler = tweepy.OAuth2UserHandler(
    client_id="Client ID here",
    redirect_uri="Callback / Redirect URI / URL here",
    scope=["Scope here", "Scope here"],
    # Client Secret is only necessary if using a confidential client
    client_secret="Client Secret here"
)

For a list of scopes, see the Scopes section of Twitter’s [OAuth 2.0 Authorization Code Flow with PKCE documentation](https://developer.twitter.com/en/docs/authentication/oauth-2-0/authorization-code).

Then, you can get the authorization URL:

print(oauth2_user_handler.get_authorization_url())

This can be used to have a user authenticate your app. Once they’ve done so, they’ll be redirected to the Callback / Redirect URI / URL you provided. You’ll need to pass that authorization response URL to fetch the access token:

access_token = oauth2_user_handler.fetch_token(
    "Authorization Response URL here"
)

You can then pass the access token to [Client](https://docs.tweepy.org/en/stable/client.html#tweepy.Client) when initializing it:

client = tweepy.Client("Access Token here")

The above statement used in code outputs as a OAuth1UserHandler File "/app/.heroku/python/lib/python3.11/site-packages/tweepy/client.py", line 129, in _make_request
2023-05-30T21:25:32.965968+00:00 app[web.1]: response = self.request(method, route, params=request_params,
2023-05-30T21:25:32.965968+00:00 app[web.1]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-05-30T21:25:32.965969+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.11/site-packages/tweepy/client.py", line 69, in request
2023-05-30T21:25:32.965969+00:00 app[web.1]: auth = OAuth1UserHandler(

**Comment by Harmon758** [comment]
You're specifying the `user_auth` parameter as `True` or using a method where it defaults to `True`, so it's using OAuth 1.0a User Context to authenticate.

In the future, please provide the full traceback and the relevant code or a reproducible example (MCVE/SSCCE).

For code block usage, see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.
