### ISSUE TITLE
V2 Api no Tweet POST interactions

### ISSUE THREAD

**Issue by marbella-web** [tweepy/tweepy#2123]
I cant seem to find anywhere in your docs a create_tweet() option. 
No way to post a reply although Ive heard its create_tweet(), I cant see any info on this in the docs.

**Comment by Harmon758** [comment]
https://tweepy.readthedocs.io/en/v4.14.0/search.html?q=create_tweet

https://tweepy.readthedocs.io/en/v4.14.0/client.html#tweepy.Client.create_tweet
https://tweepy.readthedocs.io/en/v4.14.0/asyncclient.html#tweepy.asynchronous.AsyncClient.create_tweet
