### ISSUE TITLE
You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product

### ISSUE THREAD

**Issue by cwnmedia** [tweepy/tweepy#2137]
Manage Tweets returns "You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product"

**Comment by crer** [comment]
I get the same, trying to figure out if free access is still available.

**Comment by Harmon758** [comment]
This is an error from Twitter's API, not an issue with Tweepy.
If you need further help, you need to provide what exactly you're trying and encountering, as well as what Twitter API access plan you have.

**Comment by 0xgokuz** [comment]
How do you resolve this? @Harmon758 I'm getting the same issue
