### ISSUE TITLE
Sorry, that page does not exist, 404 on user_timeline

### ISSUE THREAD

**Issue by DimaDDM** [tweepy/tweepy#2139]
### Summary

Can't get news feed from tomorrow

### Reproduction Steps

When i'm trying call `self.twitter_api.user_timeline` i got this error. It's starting tomorrow after new twitter limit announced

`Traceback (most recent call last):
  File "twitter_news.py", line 121, in get_tweets
    tweets = self.twitter_api.user_timeline(screen_name=source,
  File "parser/venv/lib/python3.10/site-packages/tweepy/api.py", line 33, in wrapper
    return method(*args, **kwargs)
  File "parser/venv/lib/python3.10/site-packages/tweepy/api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "parser/venv/lib/python3.10/site-packages/tweepy/api.py", line 415, in user_timeline
    return self.request(
  File "parser/venv/lib/python3.10/site-packages/tweepy/api.py", line 274, in request
    raise NotFound(resp)
tweepy.errors.NotFound: 404 Not Found
34 - Sorry, that page does not exist`

### Expected Results

Get tweets from my feed

### Actual Results

404 on this url https://api.twitter.com/1.1/statuses/user_timeline.json

### Twitter API Access Plan

free

### Tweepy Version

4.14

### Checklist

- [X] I have searched for duplicate issues.
- [X] If applicable, I have shown the entire traceback.
- [X] If applicable, I have removed any visible credentials from my code and/or screenshots.

**Comment by Harmon758** [comment]
Twitter API v1.1 isn't available with Free access.
https://twittercommunity.com/t/announcing-new-access-tiers-for-the-twitter-api/188728
https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api
https://developer.twitter.com/en

For code block usage, see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.
