### ISSUE TITLE
Use cookies instead of application for authentication 

### ISSUE THREAD

**Issue by kairusds** [tweepy/tweepy#2147]
### Summary

Add a parameter that allows you to use cookies for authenticated requests.

### The Problem

Developer applications have rate limits.

### The Ideal Solution

Use authenticated cookies to bypass the rate limit.

**Comment by Harmon758** [comment]
This is not something Twitter's API supports and would violate Twitter's [Terms of Service](https://twitter.com/en/tos) and [Developer Policy](https://developer.twitter.com/en/developer-terms/policy).
