### ISSUE TITLE
Sudden error today on posting?

### ISSUE THREAD

**Issue by mypolopony** [tweepy/tweepy#2148]
### Summary

Now incompatible with 4.14.0?

### Reproduction Steps

I've used **4.14.0** for a long time. I post about one tweet per day. A la:

```python
auth = OAuthHandler(credentials.consumer_key, credentials.consumer_key_secret,
                    credentials.access_token, credentials.access_token_secret)
api = API(auth)
text = "hello"
api.update_status(text)
```

This has been working for years. I know there are lots of changes recently, i.e. to 2.0, but this _just_ stopped working **today**, with:

```
tweepy.errors.Forbidden: 403 Forbidden
453 - You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product
```

What changed today!?

### Expected Results

Successful post to Twitter

### Actual Results

Failure:

```
tweepy.errors.Forbidden: 403 Forbidden
453 - You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product
```

### Twitter API Access Plan

Free

### Tweepy Version

4.14.0

### Checklist

- [X] I have searched for duplicate issues.
- [X] If applicable, I have shown the entire traceback.
- [X] If applicable, I have removed any visible credentials from my code and/or screenshots.

### Additional Context

```
Traceback (most recent call last):
  File "/Users/mypolopony/Projects/streamer/purepost.py", line 310, in <module>
    run_task(sys.argv[1])
  File "/Users/mypolopony/Projects/streamer/purepost.py", line 234, in run_task
    post_loop()
  File "/Users/mypolopony/Projects/streamer/purepost.py", line 290, in post_loop
    _ = api.update_status(post['text'])
  File "/Users/mypolopony/Projects/streamer/env/lib/python3.9/site-packages/tweepy/api.py", line 46, in wrapper
    return method(*args, **kwargs)
  File "/Users/mypolopony/Projects/streamer/env/lib/python3.9/site-packages/tweepy/api.py", line 979, in update_status
    return self.request(
  File "/Users/mypolopony/Projects/streamer/env/lib/python3.9/site-packages/tweepy/api.py", line 271, in request
    raise Forbidden(resp)
tweepy.errors.Forbidden: 403 Forbidden
453 - You currently have access to a subset of Twitter API v2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.twitter.com/en/portal/product
```

**Comment by Harmon758** [comment]
As the error indicates, the Twitter API v1.1 endpoint that method uses is not available with Free access.
https://twittercommunity.com/t/announcing-new-access-tiers-for-the-twitter-api/188728
https://developer.twitter.com/en/docs/twitter-api/getting-started/about-twitter-api
https://developer.twitter.com/en
https://twittercommunity.com/t/understanding-the-error-453-you-currently-have-access-to-a-subset-of-twitter-api-v2-endpoints/200361

In the future, please make sure to fill out the issue form correctly.

**Comment by mypolopony** [comment]
Sorry :/ this error just appeared for me today. I'll be more careful to fill out the form and I'll adjust my access. Thanks so much
