### ISSUE TITLE
All POST requests fail due to Twitter now will return empty content if request is with ssl.OP_NO_TICKET context

### ISSUE THREAD

**Issue by fireattack** [tweepy/tweepy#2152]
### Summary

When making post request to Twitter, if SSL context has ssl.OP_NO_TICKET option (urllib3 default), the server will always return HTTP 200 with empty content.

### Reproduction Steps

1. do any post request to Twitter end points. I test with V1.1's `simple_upload()`.

### Minimal Reproducible Example

```python
keys = ["key", "secret", "access_token", "access_token_secret"]
file = "path/to/file.jpg"
tweepy_auth = tweepy.OAuth1UserHandler(*keys)
tweepy_api = tweepy.API(tweepy_auth)
media = tweepy_api.simple_upload(file)
```

### Expected Results

File upload success. 

### Actual Results

```
Exception has occurred: TweepyException
Failed to parse JSON payload: Expecting value: line 1 column 1 (char 0)
StopIteration: 0

During handling of the above exception, another exception occurred:

json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

  File "D:\!lastfm\lastfm-collage-generator\lastfm_collage_generator.py", line 134, in tweet
    media = tweepy_api.simple_upload(file)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\!lastfm\lastfm-collage-generator\lastfm_collage_generator.py", line 160, in main
    tweet(text, output)
  File "D:\!lastfm\lastfm-collage-generator\lastfm_collage_generator.py", line 163, in <module>
    main()
tweepy.errors.TweepyException: Failed to parse JSON payload: Expecting value: line 1 column 1 (char 0)
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

### Twitter API Access Plan

Free

### Tweepy Version

4.14.0

### Checklist

- [X] I have searched for duplicate issues.
- [X] If applicable, I have shown the entire traceback.
- [X] If applicable, I have removed any visible credentials from my code and/or screenshots.

### Additional Context

It takes me admittedly very long time to figure out why, since I cannot reproduce the bug with either curl or Postman.

Apparently, requests/urllib3 by default includes an SSL option called [OP_NO_TICKET](https://docs.python.org/3/library/ssl.html#ssl.OP_NO_TICKET): 

https://github.com/urllib3/urllib3/blob/5325c2b179945a9931662412b3bc9a428ab16af3/src/urllib3/util/ssl_.py#L314-L318

And this flag now causes Twitter server to always return empty content (together with code 200) since yesterday (or a few days ago).

You can test it simply with:

```python
import requests

r = requests.post('https://upload.twitter.com/1.1/media/upload.json')
print(r.status_code)
print(r.content)
```

With curl, it returns error message normally:

```
>curl -X POST https://upload.twitter.com/1.1/media/upload.json
{"errors":[{"code":215,"message":"Bad Authentication data."}]}
```

To fix the issue, one has to manually modify the HTTPAdapter:

```python
import requests
from requests.adapters import HTTPAdapter
from urllib3.util.ssl_ import create_urllib3_context
import ssl

class AdapterFix(HTTPAdapter):
    def __init__(self):
        self.ssl_context = create_urllib3_context()
        self.ssl_context.options &= ~ssl.OP_NO_TICKET
        super().__init__()

    def init_poolmanager(self, *args, **kwargs):
        kwargs["ssl_context"] = self.ssl_context
        super().init_poolmanager(*args, **kwargs)

    def proxy_manager_for(self, *args, **kwargs):
        kwargs["ssl_context"] = self.ssl_context
        return super().proxy_manager_for(*args, **kwargs)

adapter = AdapterFix()

s = requests.Session()
s.mount('https://', adapter)
s.mount('http://', adapter)

r = s.post("https://upload.twitter.com/1.1/media/upload.json")
print(r.status_code)
print(r.content)
```

(You can also just use `ssl.create_default_context()`, which does NOT have `ssl.OP_NO_TICKET` set.)

**Comment by c4talyst** [comment]
Similar, but on `client.search_recent_tweets()`. 

Started 04:00 UTC (06:00 GMT+02:00) from Google Cloud Function. The same code works from my local (a different network)

Debug logging returns empty content, but HTTP 200
```
Received API response: 200 OK
Headers: {'date': 'Fri, 04 Aug 2023 07:50:00 UTC', 'perf': '<redacted>', 'server': 'tsa_b', 'cache-control': 'no-cache, no-store, max-age=0', 'backoff-policy': 'backoff=1234;serial-duration=30000;serial-delay=500;no-retry=true', 'content-length': '0', 'x-transaction-id': '<redacted>', 'x-rate-limit-limit': '40000', 'x-rate-limit-reset': '<redacted>', 'x-rate-limit-remaining': '39993', 'strict-transport-security': 'max-age=<redacted>', 'x-response-time': '5', 'x-connection-hash': '<redacted>'}
Content: b''
```

Tweepy exception
```File "/layers/google.python.pip/pip/lib/python3.7/site-packages/tweepy/client.py", line 1273, in search_recent_tweets
    ), data_type=Tweet, user_auth=user_auth
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/tweepy/client.py", line 135, in _make_request
    response = response.json()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)"```

**Comment by glebret** [comment]
Same problem with create_tweet (V2) : json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by fireattack** [comment]
> Same problem with create_tweet (V2) : json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

You can right, the issue actually affects v2 too.

I only tested with `requests.post("https://api.twitter.com/2/tweets")` which can return proper http 401 and proper content, but after another test with a valid data upload, it fails too. I modified my title to reflect this.

**Comment by Harmon758** [comment]
Thanks for the detailed bug report.
I'm no longer able to reproduce this.
This seems to have been an issue on Twitter's end that's resolved now?

**Comment by alanhamlett** [comment]
> I'm no longer able to reproduce this.

Same here... I was seeing the error but then 42 mins ago the same code started working again.

**Comment by pluckhuang** [comment]
twitter fix this
