### ISSUE TITLE
When using the api version one to upload an image it returns none

### ISSUE THREAD

**Issue by yaronelh** [tweepy/tweepy#2153]
### Summary

When using the api version one to upload an image it returns none

### Reproduction Steps

After validation

```
consumer_key = ''
consumer_secret = ''
access_token = ''
access_token_secret = ''

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api_v1 = tweepy.API(auth)


....

try:
    media = api_v1.media_upload(image_path)   <---------------------  this line
    media_id = re.search("media_id=(.+?),", str(media)).group(1)
except Exception as e:
    print(f"Error uploading media: {e}")

```

### Expected Results

Image to upload successfully

### Actual Results

Error uploading media: 'NoneType' object has no attribute 'items'

### Twitter API Access Plan

free

### Tweepy Version

Version: 4.14.0

### Checklist

- [X] I have searched for duplicate issues.
- [ ] If applicable, I have shown the entire traceback.
- [ ] If applicable, I have removed any visible credentials from my code and/or screenshots.

**Comment by Harmon758** [comment]
I'm unable to reproduce this.
It's likely this was due to the issue in #2152.
You'll need to provide the full traceback if this is still occurring.

**Comment by LeifHenriksen** [comment]
Just letting you know that I had the same issue this morning, but it seems to be fixed now. 
Sadly I lost the stack trace, but if it happens again I will post it here.

**Comment by yaronelh** [comment]
@LeifHenriksen Same, It was Twitter, a few hours later same code, no changes, working (checked a few minutes ago)
@Harmon758 I dont know if its related to https://github.com/tweepy/tweepy/issues/2152 , But the current status is that it's working, I think we can close it as something that happened on Twitter's end.

**Comment by Harmon758** [comment]
The library returning `None` for a response from the API with no content is not unexpected, so it was likely due to #2152.
