### ISSUE TITLE
I can't import tweepy!

### ISSUE THREAD

**Issue by mohammedouahman** [tweepy/tweepy#2170]
### Summary

I installed tweepy, but can not import it, i don't know if it's a bug

### Reproduction Steps

However, I don't know if it's a bug or not, but here is the output of `>> import tweepy` command:
`Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import tweepy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\mohammed\tweepy\tweepy\__init__.py", line 12, in <module>
    from tweepy.api import API
  File "C:\Users\mohammed\tweepy\tweepy\api.py", line 15, in <module>
    import requests
  File "C:\Users\mohammed\.pyenv\pyenv-win\versions\3.7.0\lib\site-packages\requests\__init__.py", line 43, in <module>
    import urllib3
  File "C:\Users\mohammed\.pyenv\pyenv-win\versions\3.7.0\lib\site-packages\urllib3\__init__.py", line 42, in <module>
    "urllib3 v2.0 only supports OpenSSL 1.1.1+, currently "
ImportError: urllib3 v2.0 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'OpenSSL 1.1.0h  27 Mar 2018'. See: https://github.com/urllib3/urllib3/issues/2168`

### Expected Results

I expected an empty output as well as the next process will successfully work

### Actual Results

nothing

### Twitter API Access Plan

twitter API v2

### Tweepy Version

3.3.0

### Checklist

- [X] I have searched for duplicate issues.
- [ ] If applicable, I have shown the entire traceback.
- [ ] If applicable, I have removed any visible credentials from my code and/or screenshots.

**Comment by Harmon758** [comment]
As the error indicates, this is an issue with your version of OpenSSL not being supported by urllib3, not an issue with Tweepy.

Also, [Tweepy v3.3.0](https://tweepy.readthedocs.io/en/v4.14.0/changelog.html#version-3-3-0-2015-02-21) is almost 9 years old now, and does not support Twitter API v2, which is not in and of itself an access plan.

For code block usage, see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.
