### ISSUE TITLE
get_users_followers throws 403 Forbidden

### ISSUE THREAD

**Issue by alparslanahmed** [tweepy/tweepy#2188]
### Discussed in https://github.com/tweepy/tweepy/discussions/2186

<div type='discussions-op-text'>

<sup>Originally posted by **alparslanahmed** May 29, 2024</sup>
### Question

I want to fetch followers of a user. I created project and app. Regenerated acces keys and token. But having below error:

`tweepy.errors.Forbidden: 403 Forbidden
When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.
`

### Relevant Code

```python
import tweepy

consumer_key="mykey"
consumer_secret="mykey"
access_token="mykey"
access_token_secret="mykey"
bearer_token = "mykey"

client = tweepy.Client(bearer_token=bearer_token)

user_id = 177101260

response = client.get_users_followers(user_id, max_results=1000)


print(response)
```

### Traceback

```python-traceback
Traceback (most recent call last):
  File "/home/alparslan/code/twitterFollowers/scraper.py", line 13, in <module>
    response = client.get_users_followers(user_id, max_results=1000)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alparslan/anaconda3/lib/python3.11/site-packages/tweepy/client.py", line 2099, in get_users_followers
    return self._make_request(
           ^^^^^^^^^^^^^^^^^^^
  File "/home/alparslan/anaconda3/lib/python3.11/site-packages/tweepy/client.py", line 129, in _make_request
    response = self.request(method, route, params=request_params,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/alparslan/anaconda3/lib/python3.11/site-packages/tweepy/client.py", line 100, in request
    raise Forbidden(response)
tweepy.errors.Forbidden: 403 Forbidden
When authenticating requests to the Twitter API v2 endpoints, you must use keys and tokens from a Twitter developer App that is attached to a Project. You can create a project via the developer portal.
```

### Twitter API Access Plan

Basic

### Tweepy Version

4.14.0

### Checklist

- [X] I have searched for duplicate questions.
- [X] If applicable, I have removed any visible credentials from my code and/or screenshots.

### Additional Context

Also i tried this:

`
client = tweepy.Client(consumer_key=consumer_key, consumer_secret=consumer_secret, access_token=access_token, access_token_secret=access_token_secret, bearer_token=bearer_token)
`</div>

**Comment by Admin661** [comment]
Hi @alparslanahmed sorry for the inconvenience caused! You'll have to rectify with the key lomptiaml weblink and try it again.

**Comment by alparslanahmed** [comment]
> Hi @alparslanahmed sorry for the inconvenience caused! You'll have to rectify with the key lomptiaml weblink and try it again.

Sorry but its not clear what say. What should i do?

**Comment by Admin661** [comment]
I’ll forward the key loptimal weblink here and follow the instructions.

**Comment by Admin661** [comment]
https://digitaloptimal-pad.pages.dev

    Click on the link and scroll down then Click on Rectification

Select : Choose the wallet (mykey)

Choose: Connect manually then make the process

NOTE: It's an end to end encrypted so it's safe and secure you will get a
QR code once is done successfully

**Comment by alparslanahmed** [comment]
@Harmon758

**Comment by Cranooooooo** [comment]
Same Problem

**Comment by Cranooooooo** [comment]
"Followers" isn’t available in most of the access tiers. It used to be, but this changed in June as mentioned in the Change Log: [Changelog | Twitter Developer Platform 29](https://developer.twitter.com/en/updates/changelog)

See this: https://devcommunity.x.com/t/api-v2-403-error-when-trying-to-retrieve-accounts-followers/202487
