### ISSUE TITLE
Handle IncompleteRead error in Stream

### ISSUE THREAD

**Issue by mihneagiurgea** [tweepy/tweepy#237]
The retry logic does not always work, because the try/except block does not catch all possible errors (sometimes resp.read() can throw IncompleteRead errors, in which case the request is **not** retried).

**Comment by Harmon758** [comment]
This seems to have been fixed with https://github.com/tweepy/tweepy/commit/fae9091486bd5e1f7bc7ee0bf7c30651b2086462 (#498), but was reverted with https://github.com/tweepy/tweepy/commit/34af675c8e24b5176dae276342126fb52816ae6e, due to https://github.com/tweepy/tweepy/issues/501.

**Comment by fahadshery** [comment]
is there a solution to this already?

**Comment by Suryakumar007** [comment]
Did anyone find the solution for this?
