### ISSUE TITLE
Newly added local trends are not returned in the array

### ISSUE THREAD

**Issue by Menelion** [tweepy/tweepy#281]
Hello Josh,  
I need your help. This is I was asking about in the mailing list: the returned array of local trends doesn't return neither Ukraine nor Poland.  
I've started a discussion [here](https://dev.twitter.com/discussions/16789). Please have a look at it. They say it's OK on their part. As you know this much better, I would like to have your suggestion.  
Thanks!

**Comment by Harmon758** [comment]
Your discussion link is now dead, and I'm unable to reproduce this.
`API.trends_available` includes Ukraine and Poland, something like `api.trends_closest(48.3794, 31.1656)` returns Ukraine, something like `api.trends_closest(51.9194, 19.1451)` returns Poland, and something like `api.trends_place(23424976)` for Ukraine and `api.trends_place(23424923)` for Poland both seem to work.
