### ISSUE TITLE
406 error in Streaming API when filtering on language

### ISSUE THREAD

**Issue by magsol** [tweepy/tweepy#291]
I invoke the streaming API:

``` python
stream.filter(languages = ["en"])
```

I get 406 errors. However, if I simply emulate the OAuth streaming example:

``` python
stream.filter(track = ["basketball"])
```

it works fine. I noticed that even though Twitter supposedly [implemented language support](https://dev.twitter.com/calendar) on March 26, it hasn't shown up on their official documentation for the [filter streaming API](https://dev.twitter.com/docs/api/1.1/post/statuses/filter), so I can't tell which side the problem is on. Any suggestions?

It should be noted: I'm using the most current version of tweepy from github, specifically so I can use the language filter.

**Comment by saifmahamood** [comment]
Hi, I'm still supposedly getting 406 errors after I do stream.filter(languages = ["en"]). 

Any help?

**Comment by FredZHENG** [comment]
I guess you need to pass on the "track" parameter as well. 

twitterStream.filter(track = ["car"], languages=["en"]) works for me,

but twitterStream.filter(languages=["en"]) does not.
