### ISSUE TITLE
Geo Enabled tweets return Coordinates value "False"

### ISSUE THREAD

**Issue by swirlanalytics** [tweepy/tweepy#295]
Hello,
I am using Tweepy to access the streaming API. I am able to get results with the code below but for tweets where the Geo Enabled value is "True" I am getting a Coordinates returned value of "False". How can this be? Do I need to decode the JSON object being returned for status.coordinates?

from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream
import random
import time
import MySQLdb
import json

consumer_key="XXX"
consumer_secret="XXX"

access_token="XXX"
access_token_secret="XXX"

db=MySQLdb.connect(host='localhost', user='XXX', passwd='XXX', db='twitter') 
db.set_character_set('utf8')

Coords = dict()
Place = dict()
PlaceCoords = dict()
XY = []
curr=db.cursor()

class StdOutListener(StreamListener):
                """ A listener handles tweets that are the received from the stream. 
                This is a basic listener that inserts tweets into MySQLdb.
                """
                def on_status(self, status):
                                print "Tweet Text: ",status.text
                                text = status.text
                                print "Time Stamp: ",status.created_at
                                print "Time Stamp: ",status.created_at
                                print "Source: ",status.source
                                source = status.source
                                print "Author: ",status.user.screen_name
                                author = status.user.screen_name
                                print "Name: ",status.user.name
                                name = status.user.name
                                print "Time Zone: ",status.user.time_zone
                                time_zone = status.user.time_zone
                                print "User Language: ",status.user.lang
                                user_language = status.user.lang
                                print "Followers: ",status.user.followers_count
                                followers = status.user.followers_count
                                print "User Description: ",status.user.description
                                user_description = status.user.description
                                print "Geo Enabled: ",status.user.geo_enabled
                                geo_enabled = status.user.geo_enabled
                                print "Friends: ",status.user.friends_count
                                friends = status.user.friends_count
                                print "Retweets: ",status.retweet_count
                                retweets = status.retweet_count
                                print "Location: ",status.user.location
                                location = status.user.location
                                print "ID: ",status.user.id_str
                                user_id = status.user.id_str
                                #Coords.update(status.coordinates)
                                #XY = (Coords.get('coordinates'))
                                print "Coordinates: ",status.coordinates
                                coordinates = status.coordinates
                                print "Place: ",status.place
                                place = status.place

Here is a sample result output:

Tweet Text:  @aranone aran tu eres el mejor  soy tu fanatico 1 me gusta tu musica.hey pana sique asi q vay bn te deseo lo mejor bro)
Time Stamp:  2013-05-30 23:36:38
Time Stamp:  2013-05-30 23:36:38
Source:  web
Author:  juandvd_96
Name:  juan David Romero
Time Zone:  Atlantic Time (Canada)
User Language:  es
Followers:  365
User Description:  hola soy juan david... soy una chico muy enamorado... y soy muy fekiz...
Geo Enabled:  True
Friends:  1857
Retweets:  0
Location:  veezuela maracaibo
ID:  481513551
Coordinates:  None
Place:  None

cheers,
BD

**Comment by thehodapp** [comment]
It's deprecated. See here: https://groups.google.com/forum/#!topic/twitter-api-announce/5_wG5KjLcVA

**Comment by mateuspgx5** [comment]
news features ?

**Comment by Harmon758** [comment]
This issue is now stale, since the `geo_enabled` attribute no longer exists and the `geo` attribute is also deprecated. Simply use the `coordinates` or `place` attributes instead.
For more information, see https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object.html and https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/geo-objects.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
