### ISSUE TITLE
OAuthHandler' object has no attribute 'set_request_token'

### ISSUE THREAD

**Issue by pranny** [tweepy/tweepy#3]
On trying the GAE code sample, after the authorization happens, the error is produced. It goes like
"OAuthHandler' object has no attribute 'set_request_token'"

A detailed Server Log is provided herewith

WARNING  2009-09-30 15:04:51,874 urlfetch_stub.py:269] Stripped prohibited headers from URLFetch request: ['Host']
INFO     2009-09-30 15:04:52,836 dev_appserver.py:3034] "GET /oauth/ HTTP/1.1" 200 -
ERROR    2009-09-30 15:05:00,280 **init**.py:388] 'OAuthHandler' object has no attribute 'set_request_token'
Traceback (most recent call last):
  File "/home/pranny/appengine/google/appengine/ext/webapp/**init**.py", line 507, in **call**
    handler.get(*groups)
  File "/home/pranny/appengine/projects/mbl2/oauth_example/handlers.py", line 58, in get
    auth.set_request_token(request_token.token_key, request_token.token_secret)
AttributeError: 'OAuthHandler' object has no attribute 'set_request_token'
INFO     2009-09-30 15:05:00,307 dev_appserver.py:3034] "GET /oauth/callback?oauth_token=cbmnHe4Urqwdd3Le1l4rrFhap3nxKKYUu1cfhnJo8g&oauth_verifier=MTeAGy6NNYjaGjicbFKVjz9QJ63tEgtAAFmKuN8tXH0 HTTP/1.1" 200 -
INFO     2009-09-30 15:05:00,341 dev_appserver_index.py:212] Updating /home/pranny/appengine/projects/mbl2/index.yaml

**Comment by gustavoaires** [comment]
In my case, it worked just setting the variables with the values of my access token and my secret token. So instead of using the method to set the values you can just use the variables.

Ps: I am using the latest version of tweepy at this time and python 2.7.
