### ISSUE TITLE
Search complication with since_id and max_id

### ISSUE THREAD

**Issue by basti2342** [tweepy/tweepy#303]
I just noticed a problem occuring since the change of the API.search() endpoint to v1.1.

I use tweepy.Cursor with the `since_id` parameter to retrieve multiple pages of search results.

The corresponding request(s) looks like this:
`GET /1.1/search/tweets.json?lang=de&q=SEARCH_TERM&since_id=344796632681967616`
So far so good, but the last request fails:
`GET /1.1/search/tweets.json?lang=de&q=SEARCH_TERM&max_id=344796632681967615&since_id=344796632681967616`
.. resulting in:
`tweepy.error.TweepError: [{'message': 'Missing or invalid url parameter', 'code': 195}]`

I noticed that the failing request contains both `since_id` and `max_id`. Their values seem to be mutually exclusive:

> **since_id**: Returns results with an ID greater than (that is, more recent than) the specified ID.
> **max_id**: Returns results with an ID less than (that is, older than) or equal to the specified ID.
> Source: https://dev.twitter.com/docs/api/1.1/get/search/tweets

So I think Twitter is right, this seems to be a tweepy bug.

I think this might be linked to drevicko's comment https://github.com/tweepy/tweepy/pull/296#commitcomment-3404913.

Thanks.

**Comment by Pardeep-007** [comment]
i can't get these two term 'max_id' and 'since_id' .
