### ISSUE TITLE
question: does tweepy support application-only auth?

### ISSUE THREAD

**Issue by maraoz** [tweepy/tweepy#318]
Does tweepy support it? I coudn't find it in the docs. More info here:
https://dev.twitter.com/docs/auth/application-only-auth

**Comment by a5m0** [comment]
Hi, I just wanted to ask if application-only auth has support for multiple authentication handlers like here http://www.nirg.net/using-tweepy.html, I'm trying it but it doesn't seem to work. No auth errors but when I try to use cursor it just completes without returning anything.

**Comment by Aaron1011** [comment]
@a5m0: Tweepy currently only supports using one authentication instance. However, I can definitely look into getting that added. Could you open a separate issue for it?

**Comment by a5m0** [comment]
@Aaron1011 are you talking about adding multiple auths? If so I'll add an issue, that would be great, that fork I'm using is kind of broken.

**Comment by Aaron1011** [comment]
@a5m0: Yes, I mean multiple auth support. Additionally, feel free to open issues for any other features you'd like to see added.

**Comment by a5m0** [comment]
@Aaron1011 thanks opened in https://github.com/tweepy/tweepy/issues/808

**Comment by saitam1** [comment]
@Aaron1011 I am also trying to get multiple auth handlers working with the forked version, but facing errors when trying to switch to the next key. Here is my SO post: http://stackoverflow.com/questions/42059191/tweepy-multiple-auth-handler Any idea what I am doing wrong?
