### ISSUE TITLE
Asynchronous handling via StreamListener?

### ISSUE THREAD

**Issue by dorvak** [tweepy/tweepy#332]
Is it possible to handle the results inside the StreamListener asynchronously or concurrently? For example, patch "on_data" or  "on_status" with gevent and consume the incoming data with a pooling-pattern? (Or with generators?)

**Comment by alexjacquot** [comment]
Yes. For instance you can add the org.springframework.scheduling.annotation.Async annotation.

@Async
@StreamListener(Sink.INPUT) {
public void handle(MyMessage msg) {
}

But note that in case of failure the processing won't be retried automatically.
