### ISSUE TITLE
send_direct_message results in tweepy Error: Invalid Request

### ISSUE THREAD

**Issue by lifewithryan** [tweepy/tweepy#36]
I'm using the tweepy library, 1.7 in a django project.  I can retrieve mentions, send tweets, etc but I cannot seem to send a DM t anyone.

Trying it from the shell:
auth = tweepy.BasicAuthHanlder(username, pw)
api = tweepy.API(auth)
api.send_direct_message(targetusername, mesg)

results in the following:
    177 
    178         method = APIMethod(api, args, kargs)
--> 179         return method.execute()
    180 
    181 

```
160                 except Exception:
161                     error_msg = "Twitter error response: status code = %s" % resp.status
```

--> 162                 raise TweepError(error_msg, resp)
    163 
    164             # Parse the response payload

tweepError: Invalid Request

Am I missing something?

**Comment by andjelx** [comment]
Much appreciated

**Comment by toadlyBroodle** [comment]
Thanks also :)
