### ISSUE TITLE
streaming.py doesn't accept unless 4 locations or multiples

### ISSUE THREAD

**Issue by hadyelsahar** [tweepy/tweepy#395]
this line 
https://github.com/tweepy/tweepy/blob/master/tweepy/streaming.py#L303
always gives  `AssertionError` unless four locations are specified

also and line below 
https://github.com/tweepy/tweepy/blob/master/tweepy/streaming.py#L304
shows error % operation on String  '%.4f' 

i doubt if i'm using it in the correct way 

```
locs = ["Egypt","cairo","kuwait","riadh"]
stream.filter(track=keywords,locations=locs)
```

**Comment by nobodykid** [comment]
I tried using this too (tried to encapsulate Jakarta, ID) but it seems I always getting 406

Is there a specific way in putting the coordinates?
