### ISSUE TITLE
Setup and test out Discourse forum

### ISSUE THREAD

**Issue by joshthecoder** [tweepy/tweepy#398]
I have spun up a Discourse instance for us to try out. Looking to replace
Google Groups mainly due to the high span we have to moderate out.

It's currently live at http://discuss.tweepy.org

Feel free to try it out and if it looks good I'll start retiring the Google Group.

@Aaron1011 I can add you as a moderator once you sign up.

**Comment by Harmon758** [comment]
Note, as of right now, this has been replaced with a [Discord server](https://discord.gg/bJvqnhg).
See #1025.
