### ISSUE TITLE
Remove  API.friends_timeline from tweepy/docs/api.rst

### ISSUE THREAD

**Issue by yskmt** [tweepy/tweepy#439]
`API.friends_timeline` was removed in [Version 2.0](https://github.com/tweepy/tweepy/blob/master/CHANGELOG.md#version-20).

**Comment by githublr** [comment]
in the docs of v3.6.0 —> [Code Snippets]—>[Pagination]:
for status in tweepy.Cursor(api.friends_timeline).items(200)
``````
Look, there is still 'api.friends_timeline' exist.
