### ISSUE TITLE
When trying pip install from github, dependencies are not installed

### ISSUE THREAD

**Issue by unohoo** [tweepy/tweepy#441]
When I try to do a pip install for git+git://git+git://github.com/tweepy/tweepy.git the install fails saying it cant find requests_oauthlib (mentioned in the requirements.txt). I see that you do have the 'install_reqs' in the setup.py -- so I'm not sure what and why this is happening. Any ideas ?

**Comment by davissolutions** [comment]
Where to I "create the directory pip/" ?

**Comment by jbabbin** [comment]
The "pip/" directory can be anywhere but for testing try in your tweepy directory first.

**Comment by Harmon758** [comment]
I'm unable to reproduce this now, and the setup has been updated since this issue was opened.
Feel free to create a new issue if you're still experiencing this issue.
