### ISSUE TITLE
Stream is not disconnected in case of using async=True and restarting Stream

### ISSUE THREAD

**Issue by Ignalion** [tweepy/tweepy#453]
Hi, I'm using tweepy==2.3.0

I'd like to restart streaming when list of keywords to track is changed.
So I'm calling Stream.disconnect() method.

The issue is the following:
When I do so, the self.running variable is setting to False.
However after this I run filter() again with new keywords and it's setting self.running (in _start method) back to True.

As per my opinion the loop in _run method has not enough time to end and make a condition test in while loop, so it started new thread but the first one remains running because self.running is True.

Maybe I do something wrong, the first solution I came up with is to add some sleep() before calling the second filter() method
However I'd like to have some way to wait till _run is actually ends (maybe some threading.Event() or something like this).

**Comment by paulherman** [comment]
The issue is still not resolved. In 3.3.0 the only thing disconnect() does is to set self.running to False. This has to be fixed by using an event.

**Comment by GreenVars** [comment]
The issue is still not resolved.

**Comment by Ignalion** [comment]
In fact, for the moment there is Stream._thread variable that represents current thread running, you can join it before doing anything, so it should work correctly.

**Comment by rossgales** [comment]
This is still an issue. I delete the Stream object before each loop iteration which then creates a new stream with updated filter terms.
