### ISSUE TITLE
Cursor object has no attribute 'self'

### ISSUE THREAD

**Issue by oxisc** [tweepy/tweepy#481]
Hi,

I've been using Tweepy for some weeks and all was working fine but when I installed it in a new computer it gives me this error trying to call a cursor:

Traceback (most recent call last):
  File "TwitterAPI.py", line 62, in <module>
    t.getPhotos(100)
  File "TwitterAPI.py", line 46, in getTw
    for tweet in tweepy.Cursor(self.api.user_timeline,q=self.u.name,screen_name=self.u.screen_name, include_rts=True).items(maxt):
  File "build/bdist.linux-x86_64/egg/tweepy/cursor.py", line 181, in next
  File "build/bdist.linux-x86_64/egg/tweepy/cursor.py", line 101, in next
AttributeError: 'function' object has no attribute '**self**'

Seems something of dependencies, but I cannot stablish what :( Still working in the old computer.

Many thnks

**Comment by Harmon758** [comment]
This should have been fixed with https://github.com/tweepy/tweepy/commit/0661dbf59c36a8d84fddb78b7592dc630cc61d55 (#507), which was released with Python v3.0.0.
Feel free to make a new issue with a full traceback if you can still reproduce the issue.
