### ISSUE TITLE
allow tweepy requests to use a proxy

### ISSUE THREAD

**Issue by brianmichelich** [tweepy/tweepy#5]
Here's a changeset with one approach:
http://github.com/brianmichelich/tweepy/commit/5cd1b3d1ce5d760e6c4e08af353c4c1ce406b475

This allows you to set a proxy_host and proxy_port on the API() and have binder.py pick them up when creating a connection.

**Comment by xermiz** [comment]
I don not how to config proxy in tweepy, somebody cant helpmy ;)

**Comment by PGryllos** [comment]
Is this issue considered resolved? I am trying to use the proxy option but it doesn't seem to work without producing any error codes. What about the forks that are supposed to add the functionality?
