### ISSUE TITLE
Stream: Not verbose on_error handler

### ISSUE THREAD

**Issue by JulienPalard** [tweepy/tweepy#503]
Hi,

I'm trying the stream API but the on_error handler gives me only the integer 401, that is clearly not verbose and it does not helps.

**Comment by Harmon758** [comment]
This is an HTTP status code. See https://developer.twitter.com/en/docs/twitter-api/v1/tweets/filter-realtime/guides/connecting for Twitter's HTTP Error Codes reference for streaming.

This should also be clearer now for Tweepy, with https://github.com/tweepy/tweepy/commit/fe3bb8bbbea880b4629206a7d542f71a96991e30 and https://github.com/tweepy/tweepy/commit/18a6059e7980de7759be126ffe39836494cc4f23.

**Comment by JulienPalard** [comment]
Thanks!
