### ISSUE TITLE
How to show if someone follows me?

### ISSUE THREAD

**Issue by jorgicio** [tweepy/tweepy#506]
I noticed the method exists_friendship is removed, and now I don't know how to know if someone is following me (by the screen name). I noticed show_friendship may help, but I didn't find some documentation about that, or the object Friendship.

Thanks.

**Comment by Harmon758** [comment]
From the following, you can see that the Friendship model just parses the relationship data from Twitter's API:
https://github.com/tweepy/tweepy/blob/cc3c8e7cae73d28b9a75edb7342f89f04da99702/tweepy/models.py#L223-L239 For an example for what that looks like when returned by the friendships/show endpoint, you can see Twitter's API documentation at https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friendships-show.html.

What you're interested in is accessible through `friendship[0].following`/`friendship[1].followed_by` or `friendship[1].following`/`friendship[0].followed_by`, depending on which direction the follow is between source and target.

Alternatively, you can use `API.lookup_friendships` for relationships of the authenticating user:
https://github.com/tweepy/tweepy/blob/cc3c8e7cae73d28b9a75edb7342f89f04da99702/tweepy/api.py#L518-L533 See https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friendships-lookup.
