### ISSUE TITLE
API.exists_friendship(user_a, user_b) not exists?

### ISSUE THREAD

**Issue by Zeokat** [tweepy/tweepy#525]
I´m trying to use this functions but seems that not works... :/

It's documented here. http://tweepy.readthedocs.org/en/v3.1.0/api.html#API.exists_friendship

But i can't make it works.

**Comment by efflicto** [comment]
Late but here is a possible solution:

https://github.com/tweepy/tweepy/blob/master/tweepy/api.py#L473-L475

The exists_friendship method has been removed due changes on the Twitter api.

**Comment by Harmon758** [comment]
As explained, `API.exists_friendship` was removed in #290 (Also see #288). This change was released as part of Tweepy 2.1. The corresponding documentation was removed with https://github.com/tweepy/tweepy/commit/38b4503c7d38558becdf4c26838d66e3ceae040a (#862), and this change was released as part of v3.6.0.

Instead, you should use [`API.show_friendship`](https://tweepy.readthedocs.io/en/latest/api.html#API.show_friendship).
See https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friendships-show.

Alternatively, you can use `API.lookup_friendships` for relationships of the authenticating user:
https://github.com/tweepy/tweepy/blob/cc3c8e7cae73d28b9a75edb7342f89f04da99702/tweepy/api.py#L518-L533 See https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friendships-lookup.
