### ISSUE TITLE
error wnen running the program apriori.py

### ISSUE THREAD

**Issue by monika21089** [tweepy/tweepy#527]
File "H:\python1\apriori.py", line 51, in getItemSetTransactionList
    for record in data_iterator:
TypeError: 'AsyncStream' object is not iterable
help

**Comment by Harmon758** [comment]
See the responses to your issue at https://github.com/asaini/Apriori/issues/4.
This is not an issue with Tweepy.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python or other libraries.
