### ISSUE TITLE
Mutes not supported

### ISSUE THREAD

**Issue by struct78** [tweepy/tweepy#528]
When can we expect muting to be integrated into the API wrapper?

https://dev.twitter.com/rest/reference/post/mutes/users/create

**Comment by bradenericson** [comment]
+1

**Comment by antoinemcgrath** [comment]
Ability to mute has been added https://github.com/tweepy/tweepy/pull/1055
I hope my addition will be approved by admin with write access.

**Comment by Harmon758** [comment]
`API.create_mute`, `API.destroy_mute`, and `API.mutes_ids` have been added with https://github.com/tweepy/tweepy/commit/e6616fed65e75bbb93633290eadd5940c41772e7 (#1055) and released with Tweepy 3.7.0.
