### ISSUE TITLE
Getting IncompleteRead(0 bytes read, 2 more expected)', IncompleteRead(0 bytes read, 2 more expected)

### ISSUE THREAD

**Issue by vbmade2000** [tweepy/tweepy#536]
Hi 

When I run script, after some time I get following exception.
IncompleteRead(0 bytes read, 2 more expected)', IncompleteRead(0 bytes read, 2 more expected)

I have found that it is related to httlib or urllib.

Can anyone please suggest any solution ?

Thank you.

**Comment by Harmon758** [comment]
Duplicate of #237
