### ISSUE TITLE
Document API.lookup_users

### ISSUE THREAD

**Issue by compston** [tweepy/tweepy#539]
It appears that the client supports the /users/lookup method, but it's just not referenced in the documentation. Is that intentional?

**Comment by ppawlak** [comment]
I am adding the /statuses/mentions_timeline.json endpoint that is present here: https://github.com/tweepy/tweepy/blob/a192de35d56f758de799ee4460a19ea085e0e39c/tweepy/api.py#L123 but not documented here: http://tweepy.readthedocs.org/en/v3.1.0/api.html

**Comment by Harmon758** [comment]
@ppawlak Documentation for [`API.mentions_timeline`](https://tweepy.readthedocs.io/en/latest/api.html#API.mentions_timeline) has now been added with https://github.com/tweepy/tweepy/commit/4870918dfeff0a7dd39af2bb30599131b52aa077 (#740) and released with Tweepy v3.6.0.
