### ISSUE TITLE
api.statuses_lookup() returning error

### ISSUE THREAD

**Issue by kialam** [tweepy/tweepy#546]
I am receiving an attribute error when I try to call the statuses_lookup method specified in the api docs:
http://docs.tweepy.org/en/latest/api.html#API.statuses_lookup

version: tweepy-2.3.0

```
File "./signmytweet.py", line 14, in get_single_tweet
    single_tweet = api.statuses_lookup(id = id, include_entities = True)
AttributeError: 'API' object has no attribute 'statuses_lookup'
```

**Comment by yprez** [comment]
From a quick look at the docs, it seems that 2.3.0 didn't have `statuses_lookup`

http://docs.tweepy.org/en/v2.3.0/api.html

**Comment by kialam** [comment]
ah thank you. Will update!

**Comment by Harmon758** [comment]
> From a quick look at the docs, it seems that 2.3.0 didn't have `statuses_lookup`

This is correct. `API.statuses_lookup` was added in v3.0.0 with https://github.com/tweepy/tweepy/commit/c149dda4e221fac3da78ab7b6b2b8ec193c9d444.
Feel free to close your issue since it seems to have been resolved.
