### ISSUE TITLE
UnicodeDecodeError stopping the stream

### ISSUE THREAD

**Issue by security-first** [tweepy/tweepy#549]
My streaming works really well for about 200 tweets and then streaming.py throws a UnicodeDecodeError 4 times before all execution stalls.

```
Stream exception: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128) trace: Traceback (most recent call last):
  File "myFile.py", line 450, in <module>
    stream.filter(track = trackList)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 421, in filter
    self._start(async)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 338, in _start
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 278, in _run
    raise exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)
```

I am also getting a Twitter status code 420, which I understand is the rate limiting response code, but I have slowed everything down and sleep between every request to make sure I don't hit that limit, and this traceback still happens every time.

I actually don't mind if I get rate limited, but I would like to be able to sleep for a bit and then resume. But these errors seem to completely stop all streaming and execution.  Here is the code segment where I try to continue processing:

``` python
        print 'Starting...'
        l = StdOutListener()
        auth = OAuthHandler(consumer_key, consumer_secret)
        auth.set_access_token(access_token, access_token_secret)
        api = tweepy.API(auth)
        stream = Stream(auth, l)
        trackList = getList(listname, customer)  #gets the list of filter terms
        print 'Len(tl): {}'.format(len(trackList))
        while True:
                try:   
                        stream.filter(track = trackList)
                except Exception, e:
                        import traceback
                        print 'Stream exception: {} trace: {}'.format(e, traceback.format_exc())
                        print '\tWe think we are getting rate limited. Sleeping for 2 minutes'
                        time.sleep(120)
                        continue
```

Any ideas? Thank you

**Comment by 7diracseas** [comment]
Could you post your event handlers?

**Comment by ryankicks** [comment]
Were you able to resolve this? Having similar issues with Tweepy.

**Comment by serk1** [comment]
I'm having a similar error. Here is the trace:

```

Traceback (most recent call last):
  File "A01_get_tweets_every_five_minutes.py", line 312, in main
    stream_status, tweet_lines = fetchsamples(twitterstream_length)
  File "/Users/kris/developer/pythontwitter/pythontwitter/tweepy_stream.py", line 46, in fetchsamples
    stream.filter(locations = [-179.99, -89.99, 179.99, 89.99])
  File "/Users/kris/anaconda/lib/python2.7/site-packages/tweepy/streaming.py", line 428, in filter
    self._start(async)
  File "/Users/kris/anaconda/lib/python2.7/site-packages/tweepy/streaming.py", line 346, in _start
    self._run()
  File "/Users/kris/anaconda/lib/python2.7/site-packages/tweepy/streaming.py", line 255, in _run
    self._read_loop(resp)
  File "/Users/kris/anaconda/lib/python2.7/site-packages/tweepy/streaming.py", line 307, in _read_loop
    next_status_obj = buf.read_len(length)
  File "/Users/kris/anaconda/lib/python2.7/site-packages/tweepy/streaming.py", line 161, in read_len
    self._buffer += self._stream.read(read_len).decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1929: ordinal not in range(128)

```
Other bytes are 0xe2, but it is mostly 0xc3

These errors seem to occur infrequently, sometimes every hour or so, sometimes once a day

**Comment by nomeyer** [comment]
I had similar issues and after a bit of digging it looked like it was happening when I restarted the stream without creating a new Stream object.

Try moving 
stream = Stream(auth, l)
inside your try block, before
stream.filter(track = trackList)

No promises, but it might solve your issue (if you're still looking for a solution).

**Comment by tacass** [comment]
I'm seeing exactly what @natshere saw. I was already creating a new Stream object each retry (per @nomeyer).  This is after an upgrade to 3.2.0.  Any further learnings on this?

Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mycode/foo.py", line 333, in run
    self.stream.filter(follow=self.tweeters)
  File "/usr/lib/python2.6/site-packages/tweepy/streaming.py", line 421, in filter
    self._start(async)
  File "/usr/lib/python2.6/site-packages/tweepy/streaming.py", line 338, in _start
    self._run()
  File "/usr/lib/python2.6/site-packages/tweepy/streaming.py", line 278, in _run
    raise exception
UnicodeDecodeError: 'ascii' codec can't decode byte 0x8b in position 1: ordinal not in range(128)

**Comment by 7diracseas** [comment]
Most likely [this](https://github.com/tweepy/tweepy/blob/master/tweepy/streaming.py#L161) and [this] (https://github.com/tweepy/tweepy/blob/master/tweepy/streaming.py#L171) needs to be changed. I'll create a pull request this weekend.

**Comment by tacass** [comment]
In my case it happens right away after a new call to Stream.filter(), but I have not seen it happen once regular data is properly flowing from twitter.  Just on the initial start up as if the very first POST request to twitter generates a response format unexpected by Tweepy.

**Comment by 7diracseas** [comment]
I've opened a pull request for a potential fix [here](https://github.com/tweepy/tweepy/pull/606).

**Comment by tacass** [comment]
I was incorrect in my comment above (which did not create anew the Stream object in the implementation generating that stack trace). In fact when I recreated a new Stream object before calling Stream.filter() the problem went away, lending more evidence to @nomeyer 's solution.  Sorry for the misstatement.
So it appears that the solution to this issue may just be some initial cleanup of the Stream object's buffers or internal state upon a new call to Stream.filter() in cases of reusing the existing Stream object.

**Comment by riccardoklinger** [comment]
still have a similar issue for collecting streams vie filter on location: 
````Traceback (most recent call last):
  File "C:/Users/rikl/.qgis2/python/plugins\geotweet\geotweet.py", line 318, in run
    stream.filter(locations=geobox)
  File "build\bdist.win-amd64\egg\tweepy\streaming.py", line 428, in filter
    self._start(async)
  File "build\bdist.win-amd64\egg\tweepy\streaming.py", line 346, in _start
    self._run()
  File "build\bdist.win-amd64\egg\tweepy\streaming.py", line 255, in _run
    self._read_loop(resp)
  File "build\bdist.win-amd64\egg\tweepy\streaming.py", line 307, in _read_loop
    next_status_obj = buf.read_len(length)
  File "build\bdist.win-amd64\egg\tweepy\streaming.py", line 161, in read_len
    self._buffer += self._stream.read(read_len).decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1792: ordinal not in range(128)````

**Comment by Harmon758** [comment]
This should now be fixed with https://github.com/tweepy/tweepy/commit/0279a4e911db0bf54268366a0cb6ae65ad5f8988 (#606) as part of Tweepy v3.4.0.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
