### ISSUE TITLE
Api.update_status broken

### ISSUE THREAD

**Issue by TylerGlaiel** [tweepy/tweepy#554]
api.update_status('Testr')

results in error code 400

api.update_status(status='Test')
posts the status correctly

**Comment by aBathologist** [comment]
I am experiencing the same problem. I am only encountering on a freshly installed version of
tweepy (==3.2.0) I'm running on Ubuntu 14. `api.update_status` works fine with  tweepy==3.1.0 on OS X.

**Comment by fitnr** [comment]
I'm experiencing a media_ids error when I try to run `api.update_status('test')`. It appears that f99b1da5 has made a breaking change to the API such that naming the status parameter (`api.update_status(status='test')`) is required.

(Python 2.7.6, tweepy 3.2.0, OS X and CentOS)
```
tweepy.error.TweepError: [{u'message': u'media_ids parameter is invalid.', u'code': 44}]
```

**Comment by Metztli** [comment]
Niltze!

In a new Debian Jessie/Sid instance, after:

apt-get install python-oauth
pip install tweepy

[summoning test tweepy-enabled app from command line]:

"Traceback (most recent call last):
  File "/usr/local/bin/tweepy-enabled-app", line 15, in <module>
    api.update_status(sys.argv[1])
  File "build/bdist.linux-x86_64/egg/tweepy/api.py", line 193, in update_status
  File "build/bdist.linux-x86_64/egg/tweepy/binder.py", line 239, in _call
  File "build/bdist.linux-x86_64/egg/tweepy/binder.py", line 189, in execute"

Also tried:

apt-get install python-setuptools
git clone https://github.com/tweepy/tweepy.git
cd tweepy
python setup.py install

Same error result.

However,

apt-get install python-tweepy

WORKED!

Version of Tweepy/Oauth in Debian repos is: python-tweepy_2.3-1_all.deb & python-oauth_1.0.1-4_all.deb

Cheers!

**Comment by volnt** [comment]
(author of the https://github.com/tweepy/tweepy/commit/f99b1da52aecdeaedb75d23390c41f0865ed4b81 commit here)
I did not think about people using it this way (I've always used `update_status(status="tweet")`) and it looks like there is no test to check this. 

Maybe we should make a failing test for this and work on a solution from there ?

**Comment by ngandhy** [comment]
If you do a pip install tweepy you'll get a version of tweepy that has this bug. 

As this is a breaking change out to the mass public, I would suggest either pulling back the code or updating the docs. http://docs.tweepy.org/en/latest/api.html#API.update_status

**Comment by wjt** [comment]
This API break mysteriously broke my low-posting-frequency Twitter bot after I upgraded to pick up some other bug fixes, and I was sad. Given that calling `update_status` with a single positional argument is documented not only in its API documentation, but also in the [authentication tutorial](http://docs.tweepy.org/en/latest/auth_tutorial.html), I think fixing the API rather than changing the docs and requiring every library user to update their code is the kinder option.

**Comment by ashleydw** [comment]
+1 for the docs, or revert this

**Comment by volnt** [comment]
I made a pull request with the fix : https://github.com/tweepy/tweepy/pull/581

**Comment by wjt** [comment]
@volnt: I already attached a pull request with a similar fix last week…

**Comment by volnt** [comment]
@wjt oops, didn't see.

**Comment by cjerdonek** [comment]
I also hit this today with previously working code.

Another issue here is that the error info ("Twitter error response: status code = 400") is generic and gives no indication that the error has to do with not supply kwargs to `update_status()`.

**Comment by yuvadm** [comment]
:+1: on this. Current error looks like some sort of authentication error, I spent way too much time debugging my keys and secrets instead of fixing this small API inconsistency.

**Comment by Karlheinzniebuhr** [comment]
having the same issue

**Comment by T-Norimaki** [comment]
this issue is still present in the current Version. (Win7)

**Comment by aBathologist** [comment]
@Srifox the work around, for the time being, is to use the keyword when passing your argument to `update_status`. I.e., try like this:

```
api.update_status(status="hi")
```

**Comment by Srifox** [comment]
@aBathologist ohh ya...thanks a lot..it worked :)

**Comment by Srifox** [comment]
I accidentally connected 5V of Rpi to GND :(...
my pi is restarting every 10-15 seconds..is there any way to set it right?
