### ISSUE TITLE
tweepy Stream does not return any data

### ISSUE THREAD

**Issue by Cutuchiqueno** [tweepy/tweepy#556]
I am using the example script streaming.py from this repository. When I run the script no data is returned at all, no error code, nothing.

Usingthe REST API with the same credentials I did not experience any problem. All the things I tested returned a result. It's just not working with the streaming api.

I am using Python 3.4 in a virtualenv. I tested with the version from PyPi as well as from the Github Repository by cloning it.

UPDATE: I tried with the same credentials and on the same machine/virtualenv by using twython and got no problems here. Thus, it must relate to tweepy, but I don't know where to look further. I also found a post on StackOverflow with the same isue (http://stackoverflow.com/questions/27910383/tweepy-not-working-no-error-message)

**Comment by ohnorobo** [comment]
I'm having the same issue, it seems specific to python 3 and filtering only. To replicate I pulled up a new ubuntu VM

    uname -a
    Linux tweepy-test 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

and got tweepy installed for python 2 and 3

    python --version
    Python 2.7.6
    python3 --version
    Python 3.4.0

Then added my keys to the streaming.py example file.

When I run

    python streaming.py

I get the usual output

    {"created_at":"Mon Feb 16 05:58:22 +0000 2015","id":567201301377724416,"id_str":"567201301377724416", ... etc

But if I run

    python3 streaming.py

It just hangs forever. 

If I kill the process the traceback is always

Traceback (most recent call last):
  File "streaming.py", line 35, in <module>
    stream.filter(track=['basketball'])
  File "/usr/local/lib/python3.4/dist-packages/tweepy/streaming.py", line 421, in filter
    self._start(async)
  File "/usr/local/lib/python3.4/dist-packages/tweepy/streaming.py", line 338, in _start
    self._run()
  File "/usr/local/lib/python3.4/dist-packages/tweepy/streaming.py", line 247, in _run
    self._read_loop(resp)
  File "/usr/local/lib/python3.4/dist-packages/tweepy/streaming.py", line 290, in _read_loop
    line = buf.read_line().strip()
  File "/usr/local/lib/python3.4/dist-packages/tweepy/streaming.py", line 167, in read_line
    self._buffer += self._stream.read(self._chunk_size).decode("ascii")
  File "/usr/local/lib/python3.4/dist-packages/requests/packages/urllib3/response.py", line 186, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.4/http/client.py", line 500, in read
    return super(HTTPResponse, self).read(amt)
  File "/usr/lib/python3.4/http/client.py", line 529, in readinto
    return self._readinto_chunked(b)
  File "/usr/lib/python3.4/http/client.py", line 614, in _readinto_chunked
    chunk_left = self._read_next_chunk_size()
  File "/usr/lib/python3.4/http/client.py", line 552, in _read_next_chunk_size
    line = self.fp.readline(_MAXLINE + 1)
  File "/usr/lib/python3.4/socket.py", line 371, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.4/ssl.py", line 746, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.4/ssl.py", line 618, in read
    v = self._sslobj.read(len, buffer)

so this might turn out to be an issue in the the different response/client/ssl libraries between python 2 and 3.

**Comment by Cutuchiqueno** [comment]
I can confirm that it is related to python version. Python 2.7.6 under the same environment (Arch + virtualenv) works fine

**Comment by ohnorobo** [comment]
Debugging... 

I've printed out the StreamListener Object for both python and python3 requests right before [this line](https://github.com/tweepy/tweepy/blob/master/tweepy/streaming.py#L421)

python

{'session': <requests.sessions.Session object at 0x7f1fdf16c250>,
 'body': 'track=basketball',
 'retry_time_cap': 320.0,
 'snooze_time': 0.25,
 'api': <tweepy.api.API object at 0x7f1fdf16c1d0>,
 'verify': True,
 'chunk_size': 512,
 'host': 'stream.twitter.com',
 'auth': <tweepy.auth.OAuthHandler object at 0x7f1fdf23fd50>,
 'listener': <__main__.StdOutListener object at 0x7f1fe1d13b50>,
 'retry_count': None,
 'running': False,
 'retry_time_start': 5.0,
 'url': '/1.1/statuses/filter.json',
 'timeout': 300.0,
 'retry_420_start': 60.0,
 'retry_time': 5.0,
 'snooze_time_step': 0.25,
 'snooze_time_cap': 16}


python3

{'retry_420_start': 60.0,
 'retry_time': 5.0,
 'snooze_time_step': 0.25,
 'timeout': 300.0,
 'retry_time_cap': 320.0,
 'api': <tweepy.api.API object at 0x7fe0a140dc50>,
 'retry_time_start': 5.0,
 'url': '/1.1/statuses/filter.json',
 'body': 'track=b%27basketball%27',
 'snooze_time_cap': 16,
 'snooze_time': 0.25,
 'chunk_size': 512,
 'retry_count': None,
 'listener': <__main__.StdOutListener object at 0x7fe0a44c8668>,
 'session': <requests.sessions.Session object at 0x7fe0a140dcc0>,
 'running': False,
 'auth': <tweepy.auth.OAuthHandler object at 0x7fe0a44c8d30>,
 'host': 'stream.twitter.com',
 'verify': True}


The difference that stands out to me is
     'body': 'track=basketball',
vs
     'body': 'track=b%27basketball%27',
Some sort of mis-encoding seems like just the sort of problem to sneak in between python 2 and 3 given all the str/unicode changes.

**Comment by joshthecoder** [comment]
The culprit is this bit of code: https://github.com/tweepy/tweepy/blob/master/tweepy/utils.py#L61

So in Python 3 str.encode() now returns a bytes type. Previously in Python 2 you would get back a string type. The above code now breaks since when given a bytes string it formats it like: `b'basketball'`

Not sure yet what the correct solution is without breaking anything. Any input would be appreciated.
I'll research some more and see what I can come up with. I'm rusty on Python 3 semantics.

**Comment by joshthecoder** [comment]
Opened a pull request to resolve the bug. Removing the usage of our urlencode_noplus utility
since Requests can encode the body given a dict for us correctly.

If a few of you could review that and if possible test it that would be appreciated.
I'll merge it shortly and push out a release with the fix ASAP.

Thanks

**Comment by Cutuchiqueno** [comment]
I patched streaming.py with your modifications and can confirm that **it works**
