### ISSUE TITLE
count parameter in search API is ignored when result_type is 'popular'

### ISSUE THREAD

**Issue by Bekt** [tweepy/tweepy#560]
Hi, for some reason the number of results is 15 (default) when using the search API with `result_type='popular'`.

``` py
query='lebron'
limit=50
r = api.search(q=query, count=limit, result_type='recent') # or result_type='mixed'
len(r)
>>> 50
r = api.search(q=query, count=limit, result_type='popular')
len(r)
>>> 15 # Woah
```

Cursor works just fine, however:

``` py
r = list(tweepy.Cursor(api.search, q=query, result_type='popular').items(limit))
len(r)
>>> 50
```

Edit:

``` py
limit=100

r = list(tweepy.Cursor(api.search, q=query, result_type='recent').items(limit))
len(r)
>>> 100
r = list(tweepy.Cursor(api.search, q=query, result_type='popular').items(limit))
len(r)
>>> 75 # Woah 2
```

**Comment by Bekt** [comment]
I have tested similar code with other Twitter API clients - seems like it is an issue with Twitter itself, not the library.

**Comment by Harmon758** [comment]
`count` is an upper limit, and there are many factors on Twitter's end that could cause you to receive fewer results than your specified `count`.
See https://twittercommunity.com/t/why-when-i-ask-for-100-tweets-less-than-100-are-returned/10789.

If you want to control exactly how many results to process, you can do so by iterating over the paginated results using a Cursor.
