### ISSUE TITLE
Language filter for streamListener not working

### ISSUE THREAD

**Issue by WilsonChiang** [tweepy/tweepy#567]
Python 3.4.2 on Tweepy 3.3.0
 StreamListener language filter no longer seems to be working.

stream.filter(languages='en')

No error, but nothing happens.

**Comment by preems** [comment]
You must pass languages as a list. 

```
stream.filter(languages=['en'])
```

**Comment by Typhon0** [comment]
error 406 when you only user the parameter languages=['en'],  if yout add track it will work

stream.filter(track=['tweet'], languages=['en'] work

**Comment by Harmon758** [comment]
As explained, `languages` should be an iterable of language identifiers, and one of the `follow`, `track`, and/or `locations` parameters needs to be specified.
In your case, you're passing 'e' and 'n' as invalid language identifiers.

See https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/basic-stream-parameters and https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter.
