### ISSUE TITLE
Proxy problem

### ISSUE THREAD

**Issue by joaomeirelles** [tweepy/tweepy#568]
Hi, facing some problems to use under proxy (v.3.3)
I've my http_proxy and https_proxy environmental variables already set
But still: (Caused by ProxyError('Cannot connect to proxy.'

does anyone know what could it be?

thanks,
JM

**Comment by gtors** [comment]
Try HTTP_PROXY and HTTPS_PROXY (in upper case)

**Comment by pike007** [comment]
@joaomeirelles @gtors please help to make this code work under proxy
If you have some code or steps to solve this problem. will be great help

**Comment by diptabhas** [comment]
Hello All
     any solution to this yet. Any updates on how we can make Tweepy work behind proxies. I have attached a snippet of my code. Would really appreciate any guidance or direction on this.

Thanks
Diptabhas


![image](https://user-images.githubusercontent.com/30348320/39583368-93439046-4eb5-11e8-8ff3-0c11a03fe948.png)

**Comment by Harmon758** [comment]
Are you able to connect to the proxies at all through other means?
[Connecting to proxies is handled by requests](https://docs.python-requests.org/en/stable/user/advanced/#proxies), so this is unlikely to be an issue with Tweepy.
