### ISSUE TITLE
OAuth problems with new account

### ISSUE THREAD

**Issue by scififacts** [tweepy/tweepy#572]
I am using tweepy for a bot that I have written. The code is simple but I am receiving 401 errors when it posts the status. I have regenerated my keys and even deleted the app on Twitter. Failures occur whether I'm running Python 2.7 or 3.4.

I have followed many threads already, with no luck. Any suggestions would be greatly appreciated.

The code:

import tweepy, datetime, sqlite3

CONSUMER_KEY = ‘xxxxx’
CONSUMER_SECRET = ‘xxxxx’ # Make sure access level is Read And Write
ACCESS_KEY = ‘xxxxx’
ACCESS_SECRET = ‘xxxxx’
auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.secure = True  # This was not in the original script, but seems to make no difference.
auth.set_access_token(ACCESS_KEY, ACCESS_SECRET)
api = tweepy.API(auth)

now = datetime.datetime.now()

dbconn = sqlite3.connect(‘/pathname/db’)
dbconn.row_factory = sqlite3.Row
c = dbconn.cursor()
c.execute('SELECT * FROM tweets ORDER BY RANDOM() LIMIT 1')
r = c.fetchone()
tweet = r[2]

api.update_status(tweet)

The error:

Traceback (most recent call last):
  File "/pathname/script.py", line 35, in <module>
    api.update_status(tweet)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tweepy/api.py", line 193, in update_status
    )(post_data=post_data, *args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tweepy/binder.py", line 239, in _call
    return method.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/tweepy/binder.py", line 223, in execute
    raise TweepError(error_msg, resp)
tweepy.error.TweepError: Twitter error response: status code = 401

**Comment by syndbg** [comment]
Could you try to do the same thing, using the https://dev.twitter.com/rest/tools/console ? Are you still getting 401'd?

**Comment by scififacts** [comment]
Anton,

I fixed the problem. The update_status() call was formatted incorrectly. Maybe I was looking at old documentation.

Thanks,

Michael

**Comment by BigxMac** [comment]
This issue can be closed.
