### ISSUE TITLE
Search API operators order affecting search results

### ISSUE THREAD

**Issue by syndbg** [tweepy/tweepy#575]
Not directly an issue with tweepy but a bug I mentioned in https://twittercommunity.com/t/order-dependent-search-api-operators-possible-bug/33922 that's not described in the docs.

We could (somewhat) gracefully handle it by introducing operators priority while building the `query`. This would handle the bug in the `Search API` until it's officially fixed.

What do you think about it ? @joshthecoder 

Also fixing #560 and related if we do so.

**Comment by Harmon758** [comment]
I'm unable to reproduce this.
Also, there were no responses to your post and the image(?) links in it seem to be dead now.
Aditionally, #560 was unrelated.
Feel free to create a new issue if you can still provide a reproducible example, although reporting it to Twitter would still be more apt.
