### ISSUE TITLE
Add additional allowed parameters to API.friends

### ISSUE THREAD

**Issue by jasonab** [tweepy/tweepy#577]
Friends/list claims to allow these parameters:
:allowed_param:'id', 'user_id', 'screen_name', 'cursor'

But the twitter docs show count, skip_status, and include_user_entities as well

**Comment by Harmon758** [comment]
`skip_status` and `include_user_entities` have now been added as allowed parameters to `API.friends` with https://github.com/tweepy/tweepy/commit/a6e27c9e74779ac26a6226cc9199510952349fbf (#629) as part of Tweepy v3.4.0:
https://github.com/tweepy/tweepy/blob/d240f2083ae1f47f6e6a3c047042ae8eadc0f925/tweepy/api.py#L547-L557  `count` is still missing, but for now, you can simply specify it as a kwarg.

The relevant documentation for the endpoint: https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friends-list

**Comment by Harmon758** [comment]
`count` has now been added with https://github.com/tweepy/tweepy/commit/a8e85263bd20e95322a874344a4776f2b9e7726c.
