### ISSUE TITLE
list.members?

### ISSUE THREAD

**Issue by cryptid11** [tweepy/tweepy#586]
I search here https://github.com/tweepy/tweepy/blob/f8fa8ec8109e5455a6d5823dfbf3ac876e1e6c64/tweepy/api.py for "https://dev.twitter.com/rest/reference/get/lists/" but I find only 4 result and not https://dev.twitter.com/rest/reference/get/lists/members that is the one I'm looking for, did you plan to implement it or there is a work around I don't see? 

I also try to use the suggested library on twitter:
https://dev.twitter.com/oauth/overview/single-user
That to me seems a real shit from a first view.
Now I find these:
https://github.com/litl/rauth (seems perfect)
https://github.com/idan/oauthlib
from the official website: http://oauth.net/code/

But onestly I prefer to have a complete tweepy solution or I will implement my own function in few lines :dash:

**Comment by wjt** [comment]
[api.list_members(…)](https://github.com/tweepy/tweepy/blob/f8fa8ec8109e5455a6d5823dfbf3ac876e1e6c64/tweepy/api.py#L1054) ?

```python
for user in api.list_members(owner_screen_name='resiak', slug='miaow'):
    print user.screen_name
"""
GenerateACat
procatinator
Cat_ebooks
…
"""

**Comment by cryptid11** [comment]
Uhg, if I only search for only "get/lists/members"... I'm so blind I can't even realize well this fact... thanks a lot :D
