### ISSUE TITLE
`List` doesn't set `_json` attribute like other models

### ISSUE THREAD

**Issue by gduverger** [tweepy/tweepy#590]
It looks like most models set an attribute named `_json` which allows access to a JSON object of an instance (e.g., `User` https://github.com/tweepy/tweepy/blob/master/tweepy/models.py#L137, and `Satus` https://github.com/tweepy/tweepy/blob/master/tweepy/models.py#L78) with this line:

```
setattr(user, '_json', json)
```

But not the `List` model (https://github.com/tweepy/tweepy/blob/master/tweepy/models.py#L287-L297)? Am I just missing it? Is there another way to access the JSON object of a `List` instance?

**Comment by acompa** [comment]
I have the same issue, and can't find any way to access the jsonified `List` payload either. 

Were there any issues trying to save the JSON payload as an instance attribute?

**Comment by acompa** [comment]
Still curious if this functionality hasn't been implemented for some reason. Happy to submit a pull request with a fix if not.
