### ISSUE TITLE
streaming.py example needs a try catch on filter

### ISSUE THREAD

**Issue by akirashimosoeda** [tweepy/tweepy#594]
When Twitter's queue overloads, it cut out the connection with your application. stream.filer() should be inside a while True with a try catch. Check out colditzjb's solution in this section https://github.com/ryanmcgrath/twython/issues/288
```python
#import sys #Do this if you want to log error output

while True:  #Endless loop: personalize to suit your own purposes
    try: 
        stream.statuses.filter(track='foo bar,foobar,more search strings here')
    except:
        #e = sys.exc_info()[0]  #Get exception info (optional)
        #print 'ERROR:',e  #Print exception info (optional)
        continue
```

**Comment by Gitju** [comment]
I guess your error message is the same as 
https://github.com/tweepy/tweepy/issues/576
if so please close this ticket here and continue in the other thread
