### ISSUE TITLE
Return more data in TweepError

### ISSUE THREAD

**Issue by geransmith** [tweepy/tweepy#599]
Trying to troubleshoot some response codes I am seeing, along with come up with code to handle some of those codes better. When I am using the `except tweepy.TweepError as e` to catch TweepErrors, the only thing that comes in as an argument in e is _('Twitter error response: status code = 403',)_. This was captured via `print(e.args)`

I'd like to see some extra arguments sent in. Perhaps a response argument so we can look at that directly. In addition, it would be great if the http headers were being sent down in the exception as well. Twitter should be returning some headers to better detail the issue: https://dev.twitter.com/rest/public/rate-limiting

**Comment by Harmon758** [comment]
This should be resolved with https://github.com/tweepy/tweepy/commit/cd5f696d09530f86ac0edf1ec0fe0a02578a3920.
