### ISSUE TITLE
update_with_media - windows - image/x-png

### ISSUE THREAD

**Issue by JonathanKyuby** [tweepy/tweepy#603]
Hello,
When using update_with_media method on windows i got an invalid file type problem while giving him a valid png. Turns out on windows mimetypes.guess_type(my_image) gives back 'image/x-png' type (on linux i get a simple image/png with the same image). 

My question : Twitter does not accept image/x-png file type at all ? or update_with_media is a little bit too restrictive for this windows use case ? If twitter is so restrictive, how can i solve this ? any idea ?

(I have the same probleme with window and image/pjpeg media)

Thx for your work and your answer.

**Comment by JonathanKyuby** [comment]
anybody ?

**Comment by yprez** [comment]
Tweepy only allows  `['image/gif', 'image/jpeg', 'image/png']` (https://github.com/tweepy/tweepy/blob/master/tweepy/api.py#L1291), so x-png would raise an error there.

What version of Python are you using? There was a fix for the winows mimetypes issue:
https://bugs.python.org/issue15207
I think it went into Python 2.7.8 as well as 3.2, but not sure (and too lazy to check).

**Comment by JonathanKyuby** [comment]
Thx ! after my python bug fix updates it works fine. Latest 2.7 python bug fix are needed to avoid this.
