### ISSUE TITLE
Installation from github failed

### ISSUE THREAD

**Issue by hj91** [tweepy/tweepy#607]
sudo python setup.py install
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    install_reqs = parse_requirements('requirements.txt', session=uuid.uuid1())
TypeError: parse_requirements() got an unexpected keyword argument 'session'

do i need to login as root?

**Comment by 7diracseas** [comment]
Looks like someone messed up [here](https://github.com/tweepy/tweepy/commit/9b4cb9eb123be05a925c1c6deaf0141699853644#diff-2eeaed663bd0d25b7e608891384b7298).

**Comment by Harmon758** [comment]
Duplicate of #564
