### ISSUE TITLE
tweepy.error.TweepError: Failed to send request: local variable 'auth' referenced before assignment

### ISSUE THREAD

**Issue by computersarecool** [tweepy/tweepy#613]
When I try the exact example ```user = tweepy.api.get_user('twitter')``` in Python 3 I get  ```Failed to send request: local variable 'auth' referenced before assignment```

Even when the ```home_timeline example works```

Does this mean that I can only get my own tweets when I authenticate using my own access token?

**Comment by obskyr** [comment]
When using `tweepy.api` (note it's not the same as `tweepy.API`!), you're using an unauthenticated instance of Tweepy. This unauthenticated instance can basically do nothing. I agree the example should probably be changed, but it shouldn't work - Twitter doesn't allow for unauthenticated API access.

**Comment by computersarecool** [comment]
But the ```home_timeline``` still works? Also, is there any mention of the difference between ```API``` and ```api```?

**Comment by obskyr** [comment]
Does `tweepy.api.home_timeline()` really work, though? Or have you authenticated an API instance (`tweepy.API(<OAuthHandler>)`) and you're using that? Because if it's the latter, it's not the same.

The difference between `tweepy.api` and `tweepy.API` is apparent, since Python is case-sensitive. That line in the documentation, however, may need to be changed.

**Comment by computersarecool** [comment]
I realize there is a difference between `tweepy.api` and ```tweepy.API``` I just don't know what that difference is (because it is not documented).

To clarify, I am doing precisely this:

```import tweepy

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

public_tweets = api.home_timeline()```

Which works for my own timeline but no others (even public accounts)

**Comment by obskyr** [comment]
`API.home_timeline` only gets your own timeline, with the people you follow.

Are you saying the following doesn't work?

```python
import tweepy

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

public_tweets = api.get_user('twitter')
```
'Cause if you're doing *that*, and that doesn't work, something's up.
