### ISSUE TITLE
Retweet with comment

### ISSUE THREAD

**Issue by gonedjur** [tweepy/tweepy#618]
Since April retweet with comment (http://techcrunch.com/2015/04/06/retweetception/) has been available but I can't find it supported. Am I just lost?

**Comment by fitnr** [comment]
To get this effect, mention the full url of the "retweeted" tweet in the content of your new tweet:
```
api.update_status("My reaction https://twitter.com/screenname/status/123456789")
```

**Comment by johnkw** [comment]
I have a patch for this, but I can't upgrade due to the blocker issue #620.  What version of tweepy are you on?

**Comment by mitsest** [comment]
Hey @johnkw ,
any news on this?

Care to explain why is it being blocked by #620?

Thanks!

**Comment by johnkw** [comment]
Bug #620 blocks doing anything using the newer tweepy versions. It's a complete blocker to all usage (for certain with caching enabled, which is a must), so I can't rebase to the latest for any patches for other bugs, such as this one. I don't understand how anyone is able to use the newer tweepy versions at all, given the tremendous severity of #620.

**Comment by mitsest** [comment]
Ah OK, I see. Thanks for the info. Then, I guess whoever is using it, it's for dev/fun purposes not for production environments. :)

**Comment by Harmon758** [comment]
As explained, this can simply be done by using [`API.update_status`](https://tweepy.readthedocs.io/en/latest/api.html#API.update_status) and including the URL for the Tweet you want to Retweet in the text of your new Tweet.

No patch is necessary, and it shouldn't matter what version of Tweepy you're using.

#620 has been fixed, but it's worth noting that it is and was completely unrelated to this issue and wouldn't have been a "blocker" for a fix for this issue, even if one was required, as caching *is not* mandatory and the library should be fully functional without using it. I'm also pretty sure that issue did not affect initial requests to an endpoint, but rather just returned incorrect results for requests afterwards with different arguments.
