### ISSUE TITLE
cache returns incorrect data, resulting in crashes or worse

### ISSUE THREAD

**Issue by johnkw** [tweepy/tweepy#620]
It appears this was broken at https://github.com/tweepy/tweepy/commit/3acb3b6c3831aba11f981b859a2ca3c8ad5cc41f

This results in incorrect data being returned for any cached request where the parameters differ.  The breakage is so severe, and has been in place for so long, that I'm baffled as to how this has not been noticed before.

Here's a change that seems to fix it, but given the tremendous severity of this bug (which, for example, results in a memory-usage crasher for anything involving pagination, since the wrong original page just keeps being returned and appended), I'm suspicious this might not be the best fix.

```
--- ./binder.py 2015-06-08 11:32:27.000000000 -0500
+++ ./binder.py 2015-06-08 11:32:27.000000000 -0500
@@ -9,6 +9,7 @@

 from six.moves.urllib.parse import quote
 import requests
+import urllib

 import logging

@@ -132,7 +133,7 @@
             # Query the cache if one is available
             # and this request uses a GET method.
             if self.use_cache and self.api.cache and self.method == 'GET':
-                cache_result = self.api.cache.get(url)
+                cache_result = self.api.cache.get('%s?%s' % (url, urllib.urlencode(self.session.params)))
                 # if cache result found and not expired, return it
                 if cache_result:
                     # must restore api reference
```

**Comment by e-dorigatti** [comment]
Still no fixes, and other 2 hours of dev time wasted for this. BTW I think the same change should be made when result is stored, too ([here](https://github.com/tweepy/tweepy/blob/master/tweepy/binder.py#L236)):

```
            # Store result into cache if one is available.
            if self.use_cache and self.api.cache and self.method == 'GET' and result:
                self.api.cache.store(url, result)
```

**Comment by johnkw** [comment]
Yes, my patch was on an older version of the binder.py file.  It's been so long now that I don't recall which one, however later I changed my patch to the following:

```
@@ -127,7 +113,8 @@

             # Build the request URL
             url = self.api_root + self.path
-            full_url = 'https://' + self.host + url
+            if len(self.parameters):
+                url = '%s?%s' % (url, urllib.urlencode(self.parameters))

             # Query the cache if one is available
             # and this request uses a GET method.
```

In order to be able to update to the latest tweepy (and develop on multiple environments), I completely abandoned the tweepy cache, and implemented my own cache layer on top of tweepy. This critical crasher bug indicates that the tweepy cache is not be used/tested, so should be avoided for now.

**Comment by Aaron1011** [comment]
Sorry for the super long delay - this library has been umaintained for a while, and I've just started to take a look at it again. I'll push up a fix for this today.

**Comment by Aaron1011** [comment]
Fixed in https://github.com/tweepy/tweepy/commit/2734d0778068ac458b45690c8f031b0588fe3b17.
