### ISSUE TITLE
Can't encode Non-BMP character

### ISSUE THREAD

**Issue by atyryshkina** [tweepy/tweepy#624]
I get an error saying 

"UnicodeEncodeError: 'UCS-2' codec can't encode character '\U0001f308' in position 0: Non-BMP character not supported in Tk", 

when doing a simple print of tweets from my home page. 

So, the '\U0001f308' character can't be encoded and the entire code breaks off. I don't have an issue with any other characters. Does anyone know how to fix this?

The '\U0001f308' character is a rainbow, by the way.

**Comment by johnkw** [comment]
Sounds like you're printing non-ASCII to an improperly configured terminal.  This is almost certainly not a bug in tweepy. Run a python script in the same way that just does "print u'\U0001f308'" and you should see the same thing.

**Comment by Satyam-Bhalla** [comment]
`import tweepy

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

public_tweets = api.home_timeline()
for tweet in public_tweets:
    **print(tweet.text.encode('UTF-8').decode('UTF-8'))**
`
Try to use this it will encode all the bmp characters to utf-8 and then decode them.

**Comment by Harmon758** [comment]
As the error says, Tk does not support characters outside the [Basic Multilingual Plane](https://en.wikipedia.org/wiki/Plane_(Unicode)#Basic_Multilingual_Plane).
Emoji are an example of such characters, so you'll be unable to print that character using Tk.
If you're encountering this issue when using IDLE, Tk is the GUI toolkit that it uses.
This is a limitation of Tk/IDLE, and the solution is simply not to use Tk/IDLE.

This is not an issue with Tweepy.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
