### ISSUE TITLE
search_users Error

### ISSUE THREAD

**Issue by gios91** [tweepy/tweepy#625]
## search_users (Missing or invalid url parameter, code 47) Error

Hi, 
I'm facing with a TweepyError coming from this lines of code:

``` python
try:
    twapi = tweepy.API(auth,retry_count=10,retry_delay=60,retry_errors=['104','47'],
                                   wait_on_rate_limit=True,wait_on_rate_limit_notify=True) 
    users_stream = twapi.search_users(q=users_loginname_list)
except tweepy.error.TweepError, ex:
    print ex
```

The error arisen is this:

``` python
[{u'message':u'Missing or invalid url parameter.', u'code': 47}]
```

The strange thing is that the Tw Search method works properly until a random call, in which this 
error is arisen. I really don't know right know if there is a way to fix it; I hope to receive a fast 
reply, because I'm working on Twitter for Data Mining purpose, so I should have some 
results in few days. Thank you for your future help!

**Comment by johnkw** [comment]
That message is from twitter, not tweepy.

**Comment by gios91** [comment]
Ok, thanks. How do you think it can be fixed? Or, at least, are you aware about what can arise this Twitter Error? (maybe it is from wrong input passed to user_search method). Thanks.

**Comment by Harmon758** [comment]
As explained, this is an error response from Twitter and unlikely an issue with Tweepy.
Regardless, I'm unable to reproduce this, as this is likely just `users_loginname_list` being an invalid query.
Unless you can provide a reproducible example, this isn't actionable.
