### ISSUE TITLE
Malformed exception when parsing protected or suspended accounts

### ISSUE THREAD

**Issue by caspii** [tweepy/tweepy#628]
When trying to parse a timeline which is proteced (e.g. https://twitter.com/tollabox) or suspended, the exception that is thrown does not contain any useful information.

Accessing the exception in the normal way ``e.message[0]['messsage']`` causes a new exception:

**Comment by johnkw** [comment]
This is now a tweepy bug.  That's the correct behavior, because twitter's exception for that case is simply 'Not authorized.'

**Comment by caspii** [comment]
But can't you put the 'Not authorized' in the message field of the exception? This way, I have to write extra code to take care of it.

**Comment by johnkw** [comment]
Your complaint is that twitter's exceptions are a bit unusual. That argument could perhaps be made. But if you believe that, it's not a tweepy bug, it's a twitter API bug. Either way this bug should be closed because there's no change that should be made to tweepy to address that.

**Comment by caspii** [comment]
Ok
