### ISSUE TITLE
Parsing direct messages?

### ISSUE THREAD

**Issue by Oliver2213** [tweepy/tweepy#632]
Hello
I see parsers.py and models.py, and can't help but wonder:
Is tweepy parsing the direct messages received through the streaming API into a python list or dict that I could use? Example code:
# Small utility to stream for the user that's authenticated
# Triggers and other stuff coming later

import tweepy
from secrets import \* # import app keys
from keys import \* #import our user keys
# do auth stuff

auth = tweepy.OAuthHandler(c_key, c_secret) 
auth.set_access_token(token, token_secret)
api = tweepy.API(auth) # Get our API object

class StdOutListener(tweepy.StreamListener):
    def on_connect( self ):
        print("Connection to twitter established!!")

```
def on_disconnect( self, notice ):
    print("Connection to twitter lost!! : ", notice)

def on_status( self, status ):
    print ("Status update received.")
    print(status)
    return True

def on_direct_message( self, status ):
    print("Direct message received.")
    try:
        # This needs to be able to pull the name, screenname, and message into variables, not sure how
        #Now it's just printing raw JSON, but I'm sure tweepy is doing some parsing...
        print(status.text)
        return True
    except BaseException as e:
        print("Failed to parse direct message. "str(e))

def on_error( self, status ):
    print(status)
```

def main():

```
try:
    print "Starting userstream for "+api.me().name
    stream = tweepy.Stream(auth, StdOutListener())
    stream.userstream()

except BaseException as e:
    print("Error in main function", e)
```

if **name** == '**main**':
    main()

**Comment by diggi05** [comment]
Does the data still go to on_direct_message OR do we need to parse it from the on_data ?

**Comment by Harmon758** [comment]
This seems to have been a question regarding User Streams, which have now been deprecated and retired.

See:
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/building-the-future-of-the-twitter-api-platform.html

https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746
https://twittercommunity.com/t/reminder-site-streams-user-streams-and-legacy-dm-endpoints-will-be-sunset-august-16th/109482
https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736
https://twittercommunity.com/t/date-for-full-deprecation-of-user-streams-site-streams-and-legacy-direct-message-api-endpoints/98734
