### ISSUE TITLE
Install Tweepy Error

### ISSUE THREAD

**Issue by kphaneuf** [tweepy/tweepy#634]
C:\users\phaneuf_k\desktop\tweepy>python setup.py install
Traceback <most recent call last>:
    File "setup.py", line 4, in <module>
        from setuptoools import setup, find_packages
ImportError: No module named setuptools

**Comment by mojo706** [comment]
I also get a ton of errors that I do not understand
The picture shows both through trying to install via pip
![screenshot from 2015-07-26 19 52 51](https://cloud.githubusercontent.com/assets/908380/8894899/f1ddd78c-33cf-11e5-81c3-9da3c11956df.png)

**Comment by mojo706** [comment]
okay I solved my issue by upgrading my version of pip. so its not really an issue now

**Comment by rdelro** [comment]
I get, Traceback (most recent call last):
  File "setup.py", line 4, in <module>
    from setuptools import setup, find_packages
ImportError: No module named setuptools
very strange..I used git instead of pip btw.

**Comment by Harmon758** [comment]
Simply install setuptools first.

@mojo706 This was an unrelated issue. See #564.
