### ISSUE TITLE
API._pack_image raise UnicodeDecodeError

### ISSUE THREAD

**Issue by zhaoguixu** [tweepy/tweepy#642]
``` python
API._pack_image(u'/home/xx/føø', 700)
```

UnicodeDecodeError: 'ascii' codec can't decode byte 0xe4 in position 66: ordinal not in range(128)

**Comment by Harmon758** [comment]
I'm unable to reproduce this now, and directly calling a private method isn't supported.
Feel free to open a new issue if you can still reproduce this by calling a public method and can provide a full traceback.
