### ISSUE TITLE
Tweep Error when pulling Followers

### ISSUE THREAD

**Issue by andrewshamlet** [tweepy/tweepy#645]
I've been using tweepy to pull follower information. After about 8 or 9 pulls, or around 2000 followers, tweepy throws and error, that reads:

TweepError: Failed to send request: ('Connection aborted.', ConnectionResetError(54, 'Connection reset by peer'))

How might I write the script to ignore this error and continue pulling followers?

**Comment by orliesaurus** [comment]
I believe it is because a rate limit imposed by Twitter's API

**Comment by Dawny33** [comment]
This looks like a fix which worked for a lot of people in #617 :  https://github.com/tweepy/tweepy/issues/617#issuecomment-142272290

A [pull request](https://github.com/tweepy/tweepy/pull/675) have also been submitted with this fix, but haven't been pulled though!

**Comment by Harmon758** [comment]
@Dawny33 #675 involves streaming and isn't relevant to this issue.

**Comment by dheeman00** [comment]
For this purpose. I have included the extraction in the try/except block and the whole block is included in a while loop. I was able to extract max about 80M followers ID but when you hit this error the extraction starts from the beginning again :(

**Comment by adeelirshad440** [comment]
> For this purpose. I have included the extraction in the try/except block and the whole block is included in a while loop. I was able to extract max about 80M followers ID but when you hit this error the extraction starts from the beginning again :(

Omg, Is it possible to share that piece of code where you get 80M followers_ids, I am trying since 4 months, But haven;t succeeded yet

**Comment by Harmon758** [comment]
Closing this in favor of #1606
