### ISSUE TITLE
gevent support in streaming.py ReadBuffer

### ISSUE THREAD

**Issue by alexjc** [tweepy/tweepy#651]
Tweepy's custom implementation of a read buffer without using sockets doesn't work using gevent's cooperative scheduling. gevent normally patches sockets and can handle code that uses its patched sockets transparently. However, Tweepy circumvents this.

Is there a way to make this work? Has anyone tried?

**Comment by Harmon758** [comment]
This should now be resolved with https://github.com/tweepy/tweepy/commit/37e701e2193dcf617e7235d3b004f790c5ff784e.
