### ISSUE TITLE
Error when sending GIF with Tweepy

### ISSUE THREAD

**Issue by shevabam** [tweepy/tweepy#657]
Hi,

I want to send a GIF with Tweepy but I've an error whereas with an JPG or PNG, it's ok.
Here is the simple script:

``` python
#!/usr/bin/python

import tweepy

CONSUMER_KEY = ""
CONSUMER_SECRET = ""
ACCESS_TOKEN = ""
ACCESS_TOKEN_SECRET = ""

auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)

api = tweepy.API(auth)

api.update_with_media(filename="/root/image.gif")
```

The error encountered :

```
Traceback (most recent call last):
  File "./test.py", line 15, in <module>
    api.update_with_media(filename="/root/image.gif")
  File "/usr/local/lib/python2.7/dist-packages/tweepy/api.py", line 231, in update_with_media
    )(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/binder.py", line 243, in _call
    return method.execute()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/binder.py", line 189, in execute
    raise TweepError('Failed to send request: %s' % e)
tweepy.error.TweepError: Failed to send request:
```

tweepy 3.4.0
python 2.7.9
debian 8.2

Any idea ?
Thanks

**Comment by canardleteer** [comment]
Does the user running the script have read access to read files in /root?

**Comment by shevabam** [comment]
Yes, I run the script as root.

**Comment by canardleteer** [comment]
Hmmm... Can you attach a .gif that is failing? The failure is coming all the way from binder.py, which is pretty much the last place it can fail, so I have to run it locally to see what's going on.

**Comment by shevabam** [comment]
I took a Gif in giphy.com :

```
wget https://media.giphy.com/media/10fiEGSRm19UIM/giphy.gif
```

**Comment by canardleteer** [comment]
Worked for me.

https://twitter.com/canardleteer/status/658739783716352000

--- setup ---
debian 7.9
python 2.7.3
tweepy (latest cloned from github) version from tweepy/__init__.py - '3.4.0'

--- code ---

from settings_local import *
def main():
    # prepare our tweepy instance
    tweepy_auth = tweepy.OAuthHandler(tweepy_consumer_key,
                                      tweepy_consumer_secret)
    tweepy_auth.set_access_token(tweepy_access_token,
                                 tweepy_access_token_secret)
    tweepy_api = tweepy.API(tweepy_auth)

    tweepy_api.update_with_media(filename="image.gif")

if __name__ == "__main__":
    main()

**Comment by shevabam** [comment]
Debian 8.2
Python 2.7.9
Tweepy 3.4.0 (with `pip list | grep tweepy`)

```python
#!/usr/bin/python

import tweepy

CONSUMER_KEY = ""
CONSUMER_SECRET = ""
ACCESS_TOKEN = ""
ACCESS_TOKEN_SECRET = ""

auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)

api = tweepy.API(auth)

api.update_with_media(filename="image.gif")
```

The script and image.gif has 777 rights.

Error : 

```
Traceback (most recent call last):
  File "./test_tweepy.py", line 15, in <module>
    api.update_with_media(filename="image.gif")
  File "/usr/local/lib/python2.7/dist-packages/tweepy/api.py", line 231, in update_with_media
    )(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/binder.py", line 243, in _call
    return method.execute()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/binder.py", line 189, in execute
    raise TweepError('Failed to send request: %s' % e)
tweepy.error.TweepError: Failed to send request: [('SSL routines', 'SSL3_WRITE_PENDING', 'bad write retry')]
```

**Comment by canardleteer** [comment]
A note about my packages installed in my virtualenv in a working version. Good luck tracking it down! 

```bash
$ pip freeze
oauthlib==1.0.3
requests==2.8.1
requests-oauthlib==0.5.0
six==1.10.0
tweepy==3.4.0
wheel==0.24.0
```

**Comment by shevabam** [comment]
Thanks!
Here are the versions of these packages that I have :

```
oauthlib==1.0.3
requests==2.8.1
requests-oauthlib==0.5.0
six==1.10.0
tweepy==3.4.0
wheel==0.26.0
```

I upgraded all packages but I still have the previous error :/

**Comment by shevabam** [comment]
I tried with an other virtual machine on Debian 7.9 with a fresh install of python-pip / tweepy and it works...

**Comment by canardleteer** [comment]
That's an odd one. May take me a little time to get a Jessie ISO to try it out (I'm on a satellite link).

**Comment by meereeum** [comment]
```api.update_with_media``` uses a deprecated method. Instead, use ```api.media_upload``` and include the list of returned media_id(s) in a new ```api.update_status``` request.

See: https://dev.twitter.com/rest/reference/post/statuses/update_with_media & https://dev.twitter.com/rest/reference/post/statuses/update

**Comment by canardleteer** [comment]
I'm thinking about adding more warnings about deprecated warnings to tweepy.

**Comment by thomaslawn** [comment]
@meereeum I'm running into new issues using the method you described:

`pic = api.media_upload('PBR.gif')`
`media = pic.media_id`
`api.update_status(status='test', media_ids=media)`

returns the following error:

Traceback (most recent call last):
  File "test.py", line 28, in <module>
    api.update_status(status='test', media_ids=media)
  File "/usr/local/lib/python2.7/site-packages/tweepy/api.py", line 185, in update_status
    post_data["media_ids"] = list_to_csv(media_ids)
  File "/usr/local/lib/python2.7/site-packages/tweepy/utils.py", line 58, in list_to_csv
    return ','.join([str(i) for i in item_list])
TypeError: 'int' object is not iterable

Have you been able to get this working in 3.5.0?

**Comment by meereeum** [comment]
@thomaslawn try:
```.py
pic = api.media_upload('PBR.gif')
api.update_status(status = 'test', media_ids = [pic.media_id_string] )
```

I think the media_ids kwarg expects a list (or other iterable).

**Comment by thomaslawn** [comment]
@meereeum thanks! that worked perfectly (and saved me from having to mess around with Twython)

**Comment by jluers** [comment]
I just ran into this same problem, and for me it boiled down to an issue with PyOpenSSL 0.15.1 and requests 2.8.1, see [here](https://github.com/shazow/urllib3/issues/717).

The issue seems to be with large POSTs.

If anyone is still having issues, upgrading to requests 2.9.1 should solve it.

**Comment by sjehutch** [comment]
I know its late but worked perfect thanks . 

pic = api.media_upload('PBR.gif')
api.update_status(status = 'test', media_ids = [pic.media_id_string] )

**Comment by airjump** [comment]
Hello,

i have the same problem.

My Script:

`#!/usr/bin/env python2.7

import tweepy
import time
 
# Consumer keys and access tokens, used for OAuth
consumer_key = 'geheim'
consumer_secret = 'geheim'
access_token = 'geheim'
access_token_secret = 'geheim'
 
# OAuth process, using the keys and tokens
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
 
# Creation of the actual interface, using authentication
api = tweepy.API(auth)
 
# Sample method, used to update a status
# api.update_status('Hello world from tweepy! It\'s %s' % (time.strftime("%H:%M:%S")))
pic = api.media_upload('test.gif')
api.update_status(status = 'Hello World', media_ids = [pic.media_id_string] )`

Error

`:~/Pictures/Screen$ python test.py 
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    pic = api.media_upload('test.gif')
  File "/usr/lib/python2.7/dist-packages/tweepy/api.py", line 212, in media_upload
    )(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tweepy/binder.py", line 245, in _call
    return method.execute()
  File "/usr/lib/python2.7/dist-packages/tweepy/binder.py", line 189, in execute
    raise TweepError('Failed to send request: %s' % e)
tweepy.error.TweepError: Failed to send request: 'ascii' codec can't decode byte 0xf7 in position 114: ordinal not in range(128)
`
Can someone help me?
Thanks

Bye

**Comment by Harmon758** [comment]
As pointed out, this seems to have been an issue with large POST requests with requests and urllib3 (https://github.com/urllib3/urllib3/issues/717).

> I think the media_ids kwarg expects a list (or other iterable).

That's correct, although unrelated to this issue.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

@airjump That's not related to this issue.
However, that also seems to have been an issue with requests. See #687.
