### ISSUE TITLE
Update_status fails silently when status starts with "@ing" anyone

### ISSUE THREAD

**Issue by meereeum** [tweepy/tweepy#661]
After a long debugging session, pinpointed our issue with the discovery that:

 ```api.update_status( status = "@<user>" )```

does not update status..but raises no errors, while

 ```api.update_status( status = "oh hey, @<user>" )```

works fine.

[Tweeting directly from Twitter website, ```"@user"```  also works fine. ]

**Comment by meereeum** [comment]
If anyone else is a Twitter novice: this is actually a feature of @ replying on Twitter.... (;

**Comment by yprez** [comment]
Those should be visible in "Tweets & Replies": https://twitter.com/<twitter-id>/with_replies
