### ISSUE TITLE
I keep getting error 401 yet im pretty sure everything with my code is correct

### ISSUE THREAD

**Issue by Ropa94** [tweepy/tweepy#668]
I am trying to stream tweets using my application based on certain filter words. But i keep getting an erro of 401 on the terminal yet I have verified that my aunthentication details are correct.

**Comment by Ropah** [comment]
this is the code that Im using:

**Comment by Ropah** [comment]
#!/usr/bin/env python
# -*- coding: utf-8 -*-

#Import the necessary methods from tweepy library
import tweepy
import time
from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream

#Variables that contains the user credentials to access Twitter API
access_token = "XX"
access_token_secret = "XX"
consumer_key = "XX"
consumer_secret = "XX"

start_time = time.time() #grabs the system time

#This is a basic listener that just prints received tweets to stdout.This class 'Listener' is inherited from the StreamLister class
class Listener(tweepy.StreamListener):
    
    def __init__(self, start_time, time_limit=60):
        
        self.time = start_time
        self.limit = time_limit
    
    #on_data method of a stream listener receives all messages and calls functions according to the message type
    #he on_data method of Tweepy’s StreamListener conveniently passes data from statuses to the on_status method
    def on_data(self, data):

        print data
        return True
    
    def on_status(self, status):
        print status.text
    
    # We can use on_error to catch 420 errors and disconnect our stream.
    def on_error(self, status):
        if status == 420:
            return False
        print status


if __name__ == '__main__':
    
    #create an object of the Listner class which was inherited from the StreamListener class
    myStreamListener = Listener("Ropa")
    
    #This handles Twitter authetification and the connection to Twitter Streaming API
    #create an OAuthHandler instance
    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    api = tweepy.API(auth)
    #create the stream object calles stream
    
    
    stream = tweepy.streaming.Stream(auth, myStreamListener)
    
    #Streams will not terminate unless the connection is closed, blocking the thread. Tweepy offers a convenient async parameter on filter so the stream will run on a new thread
    #This line filter Twitter Streams to capture data by the keywords: 'python', 'javascript', 'ruby'
    stream.filter(track=['python', 'javascript', 'ruby'], async = True)

**Comment by awlamb** [comment]
I can't recreate your issue. I used your code and my own credentials and it worked for me.

**Comment by kyledef** [comment]
The 401 can also occur when the clocks between the client and server are not in sync: https://twittercommunity.com/t/401-fixing-server-time-differences/803

**Comment by mayorityz** [comment]
> The 401 can also occur when the clocks between the client and server are not in sync: https://twittercommunity.com/t/401-fixing-server-time-differences/803

4 years later! And this is still correct, my system's time was incorrect, hence the error!

**Comment by ByBilal** [comment]
@kyledef im having a sim issue -so i have to change the clock of my MacBook? to iceland time? lol
thanks

**Comment by Harmon758** [comment]
Please don't necrobump old closed issues.
See https://developer.twitter.com/en/docs/twitter-api/v1/tweets/filter-realtime/guides/connecting for more information.
