### ISSUE TITLE
Make stream run forever

### ISSUE THREAD

**Issue by datomnurdin** [tweepy/tweepy#671]
How to make sure it's run forever without any interruption even i close my terminal.

Please advice. Thank you.

**Comment by kentdome** [comment]
Try run as a background task by putting a '&' at the end of the command line i.e. 
python tweepy.py &

**Comment by johnkw** [comment]
Probably also want `nohup` and redirection of std pipes - however this is not a tweepy issue, please mark this closed.

**Comment by kenara** [comment]
Try Supervisor: http://supervisord.org/
