### ISSUE TITLE
Fastest way to download last image of a twitter account 

### ISSUE THREAD

**Issue by davboc** [tweepy/tweepy#679]
Hi!
I have two questions for you:
What is the fastest way to download last image of a twitter account?
There is a way to download only an image from a twitter account where, in the tweet, is present a particular hashtag?

Thank you everybody.

**Comment by Harmon758** [comment]
> What is the fastest way to download last image of a twitter account?

I'm not sure what exactly you mean by this.
Do you mean the most recent image in a Tweet from a specific account or the previous profile picture of an account?

For the former, you'd need to search through Tweets with the [statuses/user_timeline endpoint](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline) using [`API.user_timeline`](https://tweepy.readthedocs.io/en/latest/api.html#API.user_timeline).
Each Status/[Tweet object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object) contains an [Entities object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object) that you can use to check for a [Media object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object#media) with a "photo" type. Then, you can use the URL of that Media object to download the image.
Note: "Media type will always indicate ‘photo’ even in cases of a video and GIF being attached to Tweet."
So if you don't want to be downloading a thumbnail of a video or GIF, you'll need to check the [Extended Entities object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/extended-entities-object) of the Tweet instead.
For your second question, you'd just need to check for a [Hashtag object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object#hashtags) in the Entities object instead.

For the latter, Twitter's API doesn't provide a way to access previous profile images, but for the most recent one, you can use the `profile_image_url_https` attribute of a [User object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/user-object), e.g. one obtained with the [users/show endpoint](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-show) by using [`API.get_user`](https://tweepy.readthedocs.io/en/latest/api.html#API.get_user).
