### ISSUE TITLE
The search_user api can only return 20 users.

### ISSUE THREAD

**Issue by MullKun** [tweepy/tweepy#680]
I use search_user to find some users. When I tried to test this api, I used the following code:

def Search(query): {
    users = Tweeapi.search_users(q=query, per_page=20, page=3)
    print len(users)
}
Search('John')
(Sorry the indent is not shown here. So I use {} to indicate the body of the Search method.)
John is a very common key word on twitter and I'm sure there are definitely more than 20 users containing this word. However, the length of the users list is only 20, that is, only 20 users are extracted. How can I store more users?

**Comment by ttz21** [comment]
From here: https://dev.twitter.com/rest/reference/get/users/search it looks like they limit results for search by user to 20 at time.  If you make multiple requests and specify a page number, it will give you all the results e.g. Tweeapi.search_users(q=query, page=1), Tweeapi.search_users(q=query, page=2)....etc

I would love to open a pull request on this, but I'm having trouble with the testing environment (see issue #681)

**Comment by Harmon758** [comment]
The [users/search endpoint](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-users-search) has a maximum of 20 potential user results to retrieve per page.
You can use a [Cursor](https://tweepy.readthedocs.io/en/latest/cursor_tutorial.html) to iterate through the paginated results.
Note, however, that only the first 1,000 matching results are available for that endpoint.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
