### ISSUE TITLE
Invalid JSON format

### ISSUE THREAD

**Issue by panosangelopoulos** [tweepy/tweepy#683]
When i used **tweety** and trying to store JSON data i get an error json format (i double check it with jsonlint.com and jsoneditoronline.org ). 

In more details i got the following error :
_Error: Parse error on line 77: ..."1449418853091"}{ "created_at": "Su -------------------^ Expecting 'EOF', '}', ',', ']', got '{'_

It seems that when the first object finished something missed. :-1: 

Below i put the code used to get json data.

`from tweepy.streaming import StreamListener`
`from tweepy import OAuthHandler`
`from tweepy import Stream`

`access_token = 'MY TOKEN'`
`access_token_secret = 'MY TOKEN'`
`consumer_key = 'MY TOKEN'`
`consumer_secret = 'MY TOKEN'`

`class StdOutListener(StreamListener):`

```
def on_data(self, raw_data):
    print (raw_data)
    return True

def on_error(self, status):
    print (status)`
```

`if __name__ == '__main__':`
    `l = StdOutListener()`
    `auth = OAuthHandler(consumer_key, consumer_secret)`
    `auth.set_access_token(access_token, access_token_secret)`
    `stream = Stream(auth, l)`
    `stream.filter(track=['test'])`

**Comment by Harmon758** [comment]
It's unclear what exactly the error is in the format and how you're storing and/or processing the data beyond printing it.
I'm unable to reproduce any issues with the JSON format returned by stream listeners.
Can you provide the relevant invalid JSON data and how you stored it?

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
