### ISSUE TITLE
statusus_lookup() enpoint not recognizing keyword args id and map

### ISSUE THREAD

**Issue by skinney6** [tweepy/tweepy#686]
I can't use the 'id' or the 'map' keyword arguments. The call works if I just pass a list of tweet ids, like api.statuses_lookup(id_list) but if I call api.statuses_lookup(id=id_list, map=True) I get an error: statuses_lookup() got an unexpected keyword argument 'id'. What am I doing wrong?

**Comment by fitnr** [comment]
The correct keyword is `id_` (since `id` is a builtin function in Python). The following will work:
````python
api.statuses_lookup(id_=id_list, map=True)
````

**Comment by skinney6** [comment]
Thanks for getting back to me so fast! That doesn't work either. `statuses_lookup() got an unexpected keyword argument 'map'` but i suspect map is the same deal so I tried calling it like
```
api.statuses_lookup(id_=id_list, map_=True)
```
but it throws exception `'unicode' object has no attribute 'items'`

**Comment by Harmon758** [comment]
The parameters in question for [`API.statuses_lookup`](https://tweepy.readthedocs.io/en/latest/api.html#API.statuses_lookup) are indeed `id_` and `map_` instead of `id` and `map`.
As for your `'unicode' object has no attribute 'items'` exception, see #598.
