### ISSUE TITLE
Documentation – outdated bits

### ISSUE THREAD

**Issue by keikoro** [tweepy/tweepy#690]
Two things I just noticed regarding your documentation:
- the "Read the Docs" menu on the start page of the [Tweepy website](http://www.tweepy.org/) links to https://tweepy.readthedocs.org/en/v3.2.0/ where the user is displayed a message saying "You are not using the most up to date version of the library. 3.5.0 is the newest version.". It would make sense to link to the most up-to-date version https://tweepy.readthedocs.org/en/v3.5.0/ from the start page.
- for the Lists Methods on the [User Methods](https://tweepy.readthedocs.org/en/v3.5.0/api.html#user-methods) page, it says "Creates a new list for the authenticated user. Accounts are limited to 20 lists.". This is very outdated info as that list limit was changed in 2013. (!) I would've submitted a PR but the "Edit on GitHub" link at the top right of the page leads to [this file](https://github.com/tweepy/tweepy/blob/v3.5.0/docs/api.rst) in your repo which doesn't actually reflect the text of the documentation...

**Comment by thomaslawn** [comment]
It appears that the documentation for 3.5.0 also has not changed to reflect the deprecation of update_with_media: https://dev.twitter.com/rest/reference/post/statuses/update_with_media and inclusion of media_ids in update_status, despite these being included in the [3.2.0 release notes.](https://github.com/tweepy/tweepy/releases/tag/v3.2.0)

**Comment by Harmon758** [comment]
Regarding the first issue, the Default Version for Read the Docs is now set to `latest`. See #1134.

As for the issue about the documentation for `API.create_list`, I've just updated it with https://github.com/tweepy/tweepy/commit/7e1aba026163a024b43a481f68be700eb9cd4f92, which should now be reflected at https://tweepy.readthedocs.io/en/latest/api.html#API.create_list.

@thomaslawn The former should now be resolved by https://github.com/tweepy/tweepy/commit/805ed5c7a43e391a2b92b92887e0eae0c1545841 (#1028) and the latter by https://github.com/tweepy/tweepy/commit/292505d03b3f242ff5ee3afba9d30037ff1ea53f (#1176).
See https://tweepy.readthedocs.io/en/latest/api.html#API.update_with_media and https://tweepy.readthedocs.io/en/latest/api.html#API.update_status.
