### ISSUE TITLE
ProtocolError: IncompleteRead

### ISSUE THREAD

**Issue by kmario23** [tweepy/tweepy#691]
When streaming the tweets, I get the following issue, even though I try to fetch the tweets in `try` `except` block.

`File "build/bdist.linux-x86_64/egg/tweepy/streaming.py", line 445, in filter
  File "build/bdist.linux-x86_64/egg/tweepy/streaming.py", line 361, in _start
  File "build/bdist.linux-x86_64/egg/tweepy/streaming.py", line 294, in _run
requests.packages.urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(0 bytes read, 512 more expected)', IncompleteRead(0 bytes read, 512 more expected))`

Suggestions to nullify this?

**Comment by lluisrojass** [comment]
getting this too, check out this thread: http://stackoverflow.com/questions/26638329/incompleteread-error-when-retrieving-twitter-data-using-python , it might help.

**Comment by Harmon758** [comment]
Duplicate of #237.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
