### ISSUE TITLE
Deserialize Return User Object

### ISSUE THREAD

**Issue by jmgamboa** [tweepy/tweepy#692]
First, great module. I've used this many times already for different projects and even did a write up on this. Moving along, I'm trying to save user profiles to a json-text field in my postgres table.  Is there a way to serialize the user obj from API.get_user(screen_name/id) to either a json or a native python dictionary. Thanks

**Comment by jmgamboa** [comment]
nvm found the ._json attribute. closing the issue

**Comment by alexellis** [comment]
This is non-obvious.. I also found my way to this page, can the docs be improved?
