### ISSUE TITLE
Using tweepy with GAE - Enable Billing

### ISSUE THREAD

**Issue by flyingg** [tweepy/tweepy#702]
I have everything set up for tweepy on GAE, libraries are fine. But when making calls I get: 

TweepError: Failed to send request: The Socket API will be enabled for this application once billing has been enabled in the admin console.

The application already has billing enable at the admin console and yet I still keep getting this call. Are there workarounds to remove the use of sockets? I have no need for streaming.

**Comment by Harmon758** [comment]
Duplicate of #639 
Sending requests to and receiving responses from Twitter's API requires the use of sockets.
For more information, see #425.
