### ISSUE TITLE
Retweeted quote statues does not parse correctly

### ISSUE THREAD

**Issue by entron** [tweepy/tweepy#703]
I found tweepy does not parse it correctly if a quote status is retweeted. For example this statue id: `701159606064705536`. The status object I get with: 

```
s = api.statuses_lookup([701159606064705536])[0]
```

gives `s.retweeted` as `False` and `is_quote_status` as `True`.

**Comment by shaunagm** [comment]
I also find that is_quote_status does not behave how I'd expect.

**Comment by Harmon758** [comment]
The `retweeted` attribute of a Status/[Tweet object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object.html) indicates whether the Tweet has been Retweeted by the authenticating user.
Instead, to check whether the Tweet itself is a Retweet, you should check for the existence of `retweeted_status` attribute, which should exist for that Tweet.
For more information, see the linked Twitter API documentation on Tweet objects.
