### ISSUE TITLE
create_friendship does not raise exception if same user_id is used twice

### ISSUE THREAD

**Issue by matecsaj** [tweepy/tweepy#705]
```
    user_id = 952148677
    try:
        self._api.create_friendship(user_id)
    except tweepy.error.TweepError as e:
        print('failed because of %s' % e.reason)
    try:
        self._api.create_friendship(user_id)
    except tweepy.error.TweepError as e:
        print('failed because of %s' % e.reason)    #this should fail, but it doesn't
```

**Comment by fitnr** [comment]
You shouldn't expect an error. From the [Twitter docs](https://dev.twitter.com/rest/reference/post/friendships/create): 

<i>If you are already friends with the user a HTTP 403 may be returned, though for performance reasons you may get a 200 OK message even if the friendship already exists.</i>

**Comment by matecsaj** [comment]
Neil, 

Thanks for advising.

John.
