### ISSUE TITLE
Logging message with Params shows nothing when using lookup_users

### ISSUE THREAD

**Issue by joshusre** [tweepy/tweepy#706]
I noticed that when I call lookup_users, the params aren't in my log like other functions.

Code:

`
def get_info(master_acct, tweepy_conn, friends_list):
    """
    Takes list of ids and looks up info for each one, writing results to db as it goes
    :param master_acct:
    :param tweepy_conn:
    :param friends_list:
    :return:
    """
    # Break friend list into chunks the twitter API can work with
    chunked_list = utils.chunk(friends_list, 100)
    processed_counter = 1
    logging.info("Processing {0} chunks.".format(len(chunked_list)))
    user_data_list = []
    chunk_counter = 0
    #look up users in batches
    while chunk_counter < len(chunked_list):
        user_list = []
        chunk = chunked_list[chunk_counter]
        # Get user daata for sqlite
        logging.info("Processing Chunk {0} of {1}".format(int(chunk_counter) + 1, len(chunked_list)))
        for result in tweepy_conn.lookup_users(user_ids=chunk):
            logging.info("Processing #{0} of {1}: {2}".format(processed_counter, len(friends_list), result.screen_name))
            #do cool shit
            user_data_list.append(user_data_dict)
            logging.info("Added #{0} of {1}: {2}".format(processed_counter, len(friends_list), result))
        chunk_counter += 1
    return user_data_list
`
Log:

[22:06:18] {C:\VM_Gateway\demo_code\app\bin\tw_func.py:194} INFO - Processing 37 chunks.
[22:06:18] {C:\VM_Gateway\demo_code\app\bin\tw_func.py:202} INFO - Processing Chunk 1 of 37
[22:06:18] {C:\Python27\lib\site-packages\tweepy\binder.py:107} INFO - PARAMS: {}

Using usertimeline:

[22:06:19] {C:\Python27\lib\site-packages\tweepy\binder.py:107} INFO - PARAMS: {'count': '200', 'include_retweets': 'False', 'screen_name': 'INF1N1TEMUSIC'}

Am I doing something wrong?

**Comment by Harmon758** [comment]
This is a side effect of how the actual bound method for `API.lookup_users` is called indirectly, without directly passing the parameters:
https://github.com/tweepy/tweepy/blob/1a2fa720f16abeb1035b25d46ef8b904a691e1b0/tweepy/api.py#L326-L352
