### ISSUE TITLE
How to get notified when a tweet is posted in a private list 

### ISSUE THREAD

**Issue by gullyy** [tweepy/tweepy#707]
Hi,
Considering I am a member of the private list and I want to be notified(via api/or streaming ) when a new tweet is shot at the group.How do I achieve this with tweepy?

**Comment by Harmon758** [comment]
Use OAuth to get [authentication](https://tweepy.readthedocs.io/en/latest/auth_tutorial.html) with user context.
Then, you can use the [standard search API](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets) using [`API.search`](https://tweepy.readthedocs.io/en/latest/api.html#API.search) with a query that uses the `list:` [standard search operator](https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators).
Note, however, that the [standard search API](https://developer.twitter.com/en/docs/tweets/search/overview/standard)
> is focused on relevance *and not completeness*. This means that some Tweets and users may be missing from search results. If you want to match for completeness you should consider the [premium](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets) or [enterprise](https://developer.twitter.com/en/docs/tweets/search/api-reference/premium-search) search APIs.

In the past, you could use a User Stream, but those are now deprecated and retired in favor of the Account Activity API, which Tweepy does not currently support yet.
