### ISSUE TITLE
Stream filter list with hashtag symbol

### ISSUE THREAD

**Issue by manelmadeira** [tweepy/tweepy#709]
Hi,

When i add to stream track list keywords with the hashtag symbol (example "#car"), the streamer doesn't find anything.

Is supposed to find tweets like [this one](https://twitter.com/AbiAutoParts/status/707208393648377856)?

Thanks

**Comment by czpython** [comment]
AFAIK the hashtag symbol is not parsed and will be used as an exact match, so you have to use `car` and then parse the tweet to see if `car` is in the hashtags list.

**Comment by Harmon758** [comment]
I'm unable to reproduce this now.
Tracking "#car" with a stream listener properly returns Tweets using that hashtag.
