### ISSUE TITLE
Tweet.py search method does not support pagination

### ISSUE THREAD

**Issue by stanzheng** [tweepy/tweepy#711]
I was reading over the pagination docs and it sounds great. From the tweetpy documentation `page` is a supported parameter. Am I doing something incorrect when I expect this behavior to work? 

http://docs.tweepy.org/en/v3.5.0/api.html#API.search

However when I try 

```
 for status in tweepy.Cursor(t.API.search("#twitter")).pages():
     print(status)
```

I get 
```
TweepError: This method does not perform pagination
```

Is this a missing feature?

same goes for `.items()`

**Comment by stanzheng** [comment]
After I just tried using the page parameter directly I got 
```
API.search(q="#twitter", page=2)
```
> : [{u'message': u'page parameter is invalid.', u'code': 44}]

from the twitter documentation it looks like they took out page and replaced it with `max_id` and `since_id from the 1.0 to 1.1 upgrade. At first glance under the 1.1 API, pagination or item counts can be implemented using the `1.1` 
API endpoint.

https://dev.twitter.com/rest/reference/get/search/tweets

Going to take a look at this ...

**Comment by franckbrignoli** [comment]
Cursor takes a callable as a parameter, so you should call it like that:

```python
for status in tweepy.Cursor(client.api.search, q="#twitter").items():
    print(status)
```

**Comment by stanzheng** [comment]
my mistake, this is where its reference in the docs, I was definitely passing it as a param

http://docs.tweepy.org/en/latest/cursor_tutorial.html
