### ISSUE TITLE
AttributeError: 'module' object has no attribute 'OAuthHandler'

### ISSUE THREAD

**Issue by jweinst1** [tweepy/tweepy#715]
So, I just installed Tweepy after I found this script on a website: http://www.dototot.com/how-to-write-a-twitter-bot-with-python-and-tweepy/ and tried to run it, and got this error:

```
Joshuas-MacBook-Pro:TweetGenerator Josh$ python tweepy.py postcron.csv
Traceback (most recent call last):
  File "tweepy.py", line 6, in <module>
    import tweepy
  File "/Users/Josh/TweetGenerator/tweepy.py", line 15, in <module>
    auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
AttributeError: 'module' object has no attribute 'OAuthHandler'
```

I am running an identical script to what's in the link, and I have my auth tokens from my Twitter app set up. Why is this occurring? I saw a previous issue on this but apparently I guess this isn't fixed.

**Comment by fitnr** [comment]
You've named your script `tweepy.py`, so it's trying to import itself. Change the file's name to `helloworld.py`, as in the example, and it should work.

**Comment by jweinst1** [comment]
Awesome! works now thx

**Comment by Degow** [comment]
I had the same problem

**Comment by jcalcada** [comment]
Me too - doh!
