### ISSUE TITLE
Model documentation missing

### ISSUE THREAD

**Issue by marcoms** [tweepy/tweepy#720]
Documentation for the different models supplied by tweepy such as `Status` and `User` are missing, which makes it hard for me to understand how to use these objects (which are often referred to in the docs)

**Comment by marcoms** [comment]
The documentation says to see "ModelsReference" but I can't find anything with that name in tweepy

**Comment by chuckoy** [comment]
Were you perusing the readthedocs reference? As it says at the beginning, it is a work in progress. I checked their [API reference page](http://tweepy.readthedocs.org/en/v3.5.0/api.html) and indeed it doesn't yet have documention for `Status` and `User`. You can either wait for someone to make a pull request on the documentation amending this, do it yourself, or make do with looking at the source code for those models [here (Status)](https://github.com/tweepy/tweepy/blob/master/tweepy/models.py#L73) and [here (User)](https://github.com/tweepy/tweepy/blob/master/tweepy/models.py#L134).

**Comment by marcoms** [comment]
Thank you for your reply and linking the source code. As I understand it now, tweepy just uses the same structure as the API result. At the moment I'm in the last stages of my school, so hopefully in a few months I'll be able to take a look at documenting this myself, if it's not done already.

**Comment by chuckoy** [comment]
Yeah no problem! I actually just submitted a pull request making documentation for `tweepy.parsers` with 0 idea what they do. I just studied the code and winged it lol.

**Comment by marcoms** [comment]
Wow that's great, I can't say for sure I'll be able to make a PR but I'll definitely try if I have the time!

**Comment by educastro** [comment]
Next week I'll try to reserve some time to make the ModelsReference. I was looking for it right now and didn't know it was still missing, let's solve it to help new developers.

**Comment by Braintelligence** [comment]
It is still missing, please add it.

**Comment by wadefletch** [comment]
I'd be willing to take this on.

**Comment by Falliatcom** [comment]
I am a journalist and presenter of programs and events I previously wish to verify my health.  I am curious as to why some regional journalists and colleagues have been verified and others are not?

**Comment by xandymelo** [comment]
please, add it, still missing

**Comment by henry-merrilees** [comment]
Still missing

**Comment by Ailothaen** [comment]
Agreed, this would be *really* useful.

**Comment by HunterZ** [comment]
New user, bouncing off of this lack of documentation...

**Comment by DefiDebauchery** [comment]
Happy New Year! Please increase the priority of this. It doesn't have to be elegant, just documented.

**Comment by Harmon758** [comment]
Tweepy's documentation is generally supplemented by the documentation for Twitter's API.
In this case, Tweepy's models usually mirror that of the API's, for which the documentation can be found at https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/overview.
This issue is for tracking including that documentation within Tweepy's documentation as well.

**Comment by Harmon758** [comment]
This should be resolved now, with https://github.com/tweepy/tweepy/commit/78a0c22fb67ca3d190e9dd95baab142aa2960ff9.
See https://tweepy.readthedocs.io/en/latest/models.html.
