### ISSUE TITLE
Request feature update_with_media more than one image

### ISSUE THREAD

**Issue by jrovegno** [tweepy/tweepy#724]
I need to upload two images, like this:

`tweet = api.update_with_media(['image1.png', 'image2.png'], status=msg)`

Is it possible?

Thanks

**Comment by fitnr** [comment]
The `update_with_media` endpoint is deprecated by Twitter. To post multiple images, you should use [`media_upload`](https://dev.twitter.com/rest/reference/post/media/upload). It will looks something like this:
````python
images = ('image1.png', 'image2.png')
media_ids = [api.media_upload(i).media_id_string for i in images]
api.update(status=msg, media_ids=media_ids)
````

**Comment by jrovegno** [comment]
" api.update_status " works for me.  INSTALLED: 3.5.0

```
images = ('image1.png', 'image2.png')
media_ids = [api.media_upload(i).media_id_string for i in images]
tweet = api.update_status(status=msg, media_ids=media_ids)
```

**Comment by amywoodehy** [comment]
You should include this snippet to examples.

**Comment by bogALT** [comment]
> The `update_with_media` endpoint is deprecated by Twitter. To post multiple images, you should use [`media_upload`](https://dev.twitter.com/rest/reference/post/media/upload). It will looks something like this:
> 
> ```python
> images = ('image1.png', 'image2.png')
> media_ids = [api.media_upload(i).media_id_string for i in images]
> api.update_status(status=msg, media_ids=media_ids)
> ```
> 
> edited: typed update/update_status typo

This gives the following error to me:

```
Traceback (most recent call last):
  File "/home/bog/2test.py", line 31, in <module>
    status = api.update_status_with_media(status=tweet, media_id=media_ids)
  File "/home/bog/.local/lib/python3.9/site-packages/tweepy/api.py", line 46, in wrapper
    return method(*args, **kwargs)
TypeError: update_status_with_media() missing 1 required positional argument: 'filename'
```
here is the code:
```

# create tweet
tweet = "Test con img"
pics = ("ninja.jpg", "ninja2.jpg")
media_ids = [api.media_upload(i).media_id_string for i in pics]

status = api.update_status_with_media(status=tweet, media_id=media_ids)
```

Any advice?

**Comment by Harmon758** [comment]
Please don't necrobump old closed issues.
This is unrelated to this issue, and as the error says, [`API.update_status_with_media`](https://tweepy.readthedocs.io/en/v4.4.0/api.html#tweepy.API.update_status_with_media) requires a `filename` argument.
If you want to create a Tweet with media IDs, you can use [`API.update_status`](https://tweepy.readthedocs.io/en/v4.4.0/api.html#tweepy.API.update_status) instead.

**Comment by LucEast** [comment]
> " api.update_status " works for me. INSTALLED: 3.5.0
> 
> ```
> images = ('image1.png', 'image2.png')
> media_ids = [api.media_upload(i).media_id_string for i in images]
> tweet = api.update_status(status=msg, media_ids=media_ids)
> ```

I get an error:
`'Media' object has no attribute 'media_id_str'`

**Comment by Harmon758** [comment]
Again, please don't necrobump old closed issues.
And again, this is unrelated to this issue.
As the error says, there is no `media_id_str` attribute. Your error does not match that code, which uses the `media_id_string` attribute. See Twitter's API documentation on [uploading media](https://developer.twitter.com/en/docs/tutorials/uploading-media) and for the [POST media/upload endpoint](https://developer.twitter.com/en/docs/twitter-api/v1/media/upload-media/api-reference/post-media-upload).
