### ISSUE TITLE
i want list of all users participated in a hash

### ISSUE THREAD

**Issue by isoftmaster** [tweepy/tweepy#725]
If i want to see how many users participate in a trend or hash
or top 100 users list
how to do that using REST api
i am asking about Trending topic which has minimum 20k tweets in 5hours 
how to count number of users participated in that hash?

**Comment by Harmon758** [comment]
You'll have to use the [standard search API](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets.html) with [`API.search`](https://tweepy.readthedocs.io/en/latest/api.html#API.search).
However, note that:
> the Search API is not meant to be an exhaustive source of Tweets. Not all Tweets will be indexed or made available via the search interface.

> The Twitter Search API searches against a sampling of recent Tweets published in the past 7 days.
> 
> Before digging in, it’s important to know that the standard search API is focused on relevance _and not completeness_. This means that some Tweets and users may be missing from search results. If you want to match for completeness you should consider the [premium](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets) or [enterprise](https://developer.twitter.com/en/docs/tweets/search/api-reference/premium-search) search APIs.

https://developer.twitter.com/en/docs/tweets/search/overview/standard
