### ISSUE TITLE
since_id and max_id not working

### ISSUE THREAD

**Issue by JMathiszig-Lee** [tweepy/tweepy#728]
I'm currently trying to write a twitter scraper using tweepy which has been fantastic to use till now until trying to use since_id and max_id in the user_timeline api as suggest by twitter here: https://dev.twitter.com/rest/public/timelines

currently my code at the moment is 

'for row in cursor2:
    twitacct = row[0]
    dbid = row[1]
    sinceid = row[2]
    maxid = row[3]

```
statuses = api.user_timeline(id=twitacct, since_id=sinceid)
for status in statuses: # get a thousand tweets
    tweet = status.text
    tweet = tweet.replace('\n','') #strip out all the line breaks that make text file horrible
    print tweet`
```

this is one of several variations i've tried including using the cursor. I can happily to get it pull a number of tweets using .items() but i'd like to make sure i scrape unique tweets in the future in the way twitter suggests.

**Comment by claymullis** [comment]
Yeah I'm having tons of issues with this as well.

**Comment by Harmon758** [comment]
I'm unable to reproduce any issues with either parameter, and you don't seem to be using the `max_id` parameter.

What do you mean by "not working"? Is there an exception? If so, can you provide a full traceback?
Can you show the relevant parameters you're passing?
As it is, this issue isn't actionable, as your code as is without the specific value of the parameters passed provides no information.

I'm also unable to reproduce any issues with using a Cursor with this method with either parameter.
Again, can you elaborate on the specific issue you're encountering?

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by comrademaggie** [comment]
Hello, I am having trouble getting max_id to work with tweepy.Cursor. Does this parameter not work? Example below:

`max_id = '1052556944068755456'
trumpold = tweepy.Cursor(api.user_timeline, id='realdonaldtrump', tweet_mode='extended', max_id=max_id).items(3200)`

**Comment by Harmon758** [comment]
Per [the documentation for the statuses/user_timeline endpoint](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline):
> This method can only return up to 3,200 of a user's most recent Tweets.

Currently, the ID for @​realdonaldtrump's 3200th most recent Tweet is 1056184390684995584, which is greater than the `max_id` you're attempting to use.
Hence, that Cursor will return no items, which is working as intended.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
