### ISSUE TITLE
Adding date and time to python script

### ISSUE THREAD

**Issue by mrcrocodile556** [tweepy/tweepy#730]
import tweepy

Hi everyone, i would like to add a date and time function to my codes.
May i know how i can do it? 
I am new to python coding.

Below are my codes:

```
import tweepy

def get_api(cfg):
  auth = tweepy.OAuthHandler(cfg['consumer_key'], cfg['consumer_secret'])
  auth.set_access_token(cfg['access_token'], cfg['access_token_secret'])
  return tweepy.API(auth)

def main():
  cfg = {
    "consumer_key"        : " ********************* "
    "consumer_secret"     : " ********************* "
    "access_token"        : " ********************* "
    "access_token_secret" : " ********************* "
    }

  api = get_api(cfg)
  tweet = "Motion detected!"
  status = api.update_status(status=tweet)

if __name__ == "__main__":
  main()

```

Did some research and I'm aware that i can print time by doing this:

```
import time 

now = time.strftime("%c")

## Display current date and time from now variable
print ("Current time %s"  % now )


```

However i do not know how to add into my tweet.

Thank you in advance!

**Comment by Aaron1011** [comment]
You can use the result of `time.strftime("%c")` as part of the `status` parameter to `api.update_status`. For example:

`api.update_status(status="Date: " + time.strftime("%c"))`
