### ISSUE TITLE
Twitter Amplify Videos do not contain extended_entities

### ISSUE THREAD

**Issue by nathanmedz** [tweepy/tweepy#731]
when retrieving tweets using the user_timeline call, tweets containing Twitter videos hosted on pbs.twimg.com properly contain the extended_entities attribute which holds a direct reference to the mp4 file. Tweets containing twitter videos hosted on amp.twimg.com do not contain this extended_entities and have no reference to the mp4 file.

**Comment by arpwal** [comment]
bumping this up. Any update on this? Did we get around supporting extended entities on Twitter yet?

**Comment by Harmon758** [comment]
@guilhermeadsf This doesn't seem to be related to this issue. Even in extended mode, if a Classic Tweet (<= 140 characters) doesn't have any hidden text (e.g. leading @​replies or attachment URLs), it will not have an `extended_entities` field. See https://developer.twitter.com/en/docs/tweets/tweet-updates.html.

@nathanmedz This is a limitation of Twitter's API and not an issue with Tweepy. For more information, see https://twittercommunity.com/t/twitter-videos-returned-api-do-not-contain-extended-entities/95556 and https://twittercommunity.com/t/unable-to-determine-if-a-tweet-created-from-twitter-ads-composer-includes-a-video/110444.
