### ISSUE TITLE
maxId fetches the same tweet

### ISSUE THREAD

**Issue by ayushidalmia** [tweepy/tweepy#742]
I have the following snippet of code

```
theMaxId=None

while True:
    for page in tweepy.Cursor(api.user_timeline, count=200, include_rts=True, screen_name=user, maxid=theMaxId).pages():
        for status in page:
        statusId = status.id
        print status.text.encode('utf-8')

  theMaxId=statusId-1
```

The maxid does not fetch the next set of tweets.

**Comment by Harmon758** [comment]
The name of the parameter in question for [`API.user_timeline`](https://tweepy.readthedocs.io/en/latest/api.html#API.user_timeline) is `max_id`, not `maxid`.

However, if you're using a Cursor, it should iterate over all the statuses available from the [status/user_timeline endpoint](https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline) (or possibly until you hit the rate limit).

Also, I would highly recommend not using an infinite loop with API calls, as you'll quickly hit the rate limit, and if you continue spamming the API with requests, Twitter is liable to block you.
