### ISSUE TITLE
TypeError: expected string or buffer in streaming module

### ISSUE THREAD

**Issue by jasonnorch** [tweepy/tweepy#748]
Randomly I will get this error message. Sometimes up to a week between occurrences. It causes the whole program to quit responding.

Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 294, in _run
raise exception
TypeError: expected string or buffer

Here is the section of code that is running

`
def run(self):
        auth = tweepy.OAuthHandler(ckey, csecret)
        auth.set_access_token(atoken, asecret)

        api  = tweepy.API(auth)
        sapi = tweepy.streaming.Stream(auth, CustomStreamListener(api, self.publisherSocket))
        sapi.filter(track=self.twitterFilters, async=True)

        while True:
            logger.debug('While Started')
            try:
                logger.debug('Beginning Stream')
                request = self.FilterPublisherSocket.recv()

                unpacked = msgpack.unpackb(request)

                if "GET" == unpacked['method']:
                    if "filters" == unpacked['target']:
                        response = { "filters": self.twitterFilters }

                packed = msgpack.packb(response)
                self.FilterPublisherSocket.send(packed)
            except TypeError as e:
                log.error('TypeError: {}'.format(e))
                pass
            except Exception as e:
                logger.exception(e)
                pass

        logger.debug('While Exited')
`

Versions
python 2.7.9
tweepy 3.5.0
requests 2.10.0
oauthlib 1.1.1

**Comment by jasonnorch** [comment]
Also, I changed the line
`log.error('TypeError: {}'.format(e))`
to be
`logger.exception(e)`
so hopefully it will show more detail

**Comment by remram44** [comment]
Might be duplicate of #749?

**Comment by jasonnorch** [comment]
Get this pretty much all the time now. 

Preceded by a python  2.7 threading error now as well

File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
python2[7593]self.run()
python2[7593]: File "/usr/lib/python2.7/threading.py", line 763, in run
python2[7593]: self.__target(*self.__args, **self.__kwargs)
python2[7593]: File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 295, in _run
python2[7593]: raise exception
python2[7593]: TypeError: expected string or buffer

**Comment by xofeoj** [comment]
@jasonnorch are there spaces in the keywords you are tracking?

**Comment by jasonnorch** [comment]
There are.

I believe they had them wrapped in quotes, but might not be now.

Would that cause this error?

**Comment by xofeoj** [comment]
I'm not sure if it would, but I had the same error and it seemed to disappear after I had removed any of my keywords with a space, and placed my keywords in single quotes.

**Comment by jasonnorch** [comment]
I will try that. Thanks

**Comment by jasonnorch** [comment]
Looks like wrapping the spaced keywords with quotes fixed it.

**Comment by gambolputty** [comment]
I'm still getting this error, even though I wrapped every keyword in quotes.
I'm tracking about 100 keywords.
It works for 5 – 10 minutes, but then breaks.

Output:

```
Traceback (most recent call last):
  File "/home/gregor/projects/livecorpus/stream.py", line 473, in <module>
    twitterStream.filter(track=[u'"{}"'.format(kw) for kw in KEYWORDS], languages=['en'])
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 445, in filter
    self._start(async)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 294, in _run
    raise exception
TypeError: expected string or buffer
```
