### ISSUE TITLE
AttributeError: 'module' object has no attribute 'OAuthHandler'

### ISSUE THREAD

**Issue by drizzersilverberg** [tweepy/tweepy#751]
using python 2.7.11 (32bit)
with:
tweepy 3.5.0
six>=1.7.3
requests>=2.4.3
requests-oauthlib>=0.4.1
oauthlib>=0.6.2

my code :
from tweepy import OAuthHandler
auth = OAuthHandler(consumer_key, consumer_secret)

got this error: 
AttributeError: 'module' object has no attribute 'OAuthHandler'

I tried to uninstall and reinstall tweepy, and still not change anything.

**Comment by Juliane87** [comment]
Hi there,

unfortunately, I cannot help you on this, but I am experiencing the same problem.
Would be great if someone could help us - thanks a lot!

Cheers,
Juliane

**Comment by auros132** [comment]
Hi,

Try to do the next, 

import tweepy as tw
 
    auth = tw.OAuthHandler(consumer_key, consumer_secret)  

this works in my code.

**Comment by drizzersilverberg** [comment]
Hello auros132, I try your solution, but it still not working, same error.

**Comment by Harmon758** [comment]
This should be fixed with https://github.com/tweepy/tweepy/commit/d9d5a8648d738c660fc0a457523d0083d03c2353 since v3.0.0, and I'm unable to reproduce this with 3.7.0.
Make sure you don't have another file or module named "tweepy" in the project or in your path.
