### ISSUE TITLE
Using tweepy with a proxy

### ISSUE THREAD

**Issue by neatville** [tweepy/tweepy#753]
Do many of you think tweepy should have an option for using a proxy? I don't know if this method still works but I think it would be nice to use tweepy behind Tor, since tweepy does use the requests module. https://gist.github.com/jefftriplett/9748036.

**Comment by awlamb** [comment]
Have you tried passing the proxy parameter?
`
:param proxy: Url to use as proxy during the HTTP request, default:''
`

Take a look:
https://github.com/tweepy/tweepy/blob/master/tweepy/api.py#L21-L27
