### ISSUE TITLE
Anaconda 2.5.0 shell for Python 3.5.1

### ISSUE THREAD

**Issue by thedatalass** [tweepy/tweepy#754]
I'm getting syntax errors when I type in "git clone https://github.com/tweepy/tweepy.git" in Anaconda 2.5.0 sheel for Python 3.5.1
![2016-07-08_14-33-10](https://cloud.githubusercontent.com/assets/11978048/16697695/edfbbf7a-4518-11e6-8887-3aeb5fa98893.jpg)

**Comment by fitnr** [comment]
`git clone` is a shell command, not a Python command. Try using the [Github desktop program](https://desktop.github.com) to clone `tweepy`. If you just want to use Tweepy, you may find it easier to download it with [pip](https://pip.pypa.io/en/latest/installing/).
