### ISSUE TITLE
Stream Listener stop after few second

### ISSUE THREAD

**Issue by toshiro92** [tweepy/tweepy#759]
Hi !

I did not found anything about this behavior, so I publish this "bug". The first time I wrote the simple code below, it worked perfectly, but now the Listener is stopping after few seconds, and I do not have any error code or something.

There is the simple code:

```
import tweepy
import sys
import json
from textwrap import TextWrapper
from datetime import datetime
from elasticsearch import Elasticsearch

consumer_key = "hidden"
consumer_secret = "hidden"
access_token = "hidden"
access_token_secret = "hidden"

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
ES_HOST = {"host" : "localhost", "port" : 9200}

es = Elasticsearch(hosts = [ES_HOST])

class StreamListener(tweepy.StreamListener):
        print('Starting StreamListener')
        status_wrapper = TextWrapper(width=60, initial_indent='    ', subsequent_indent='    ')

        def on_status(self, status):
                try:
                        print 'n%s %s' % (status.author.screen_name, status.created_at)
                        json_data = status._json
                        #print json_data['text']

                        es.create(index="idx_twp",
                                doc_type="twitter_twp_nintendo",
                                body=json_data
                                )

                except Exception, e:
                        print e
                        pass

print('Starting Receiving')

streamer = tweepy.Stream(auth=auth, listener=StreamListener(), timeout=3000000000)

#Fill with your own Keywords bellow
terms = ['nintendo']

streamer.filter(None,terms)
#streamer.userstream(None)

print ('Ending program')
```

And then there is the ouput (only 2 seconds);

> [root@localhost ~]# python projects/m/twitter/twitter_logs.py
> Starting StreamListener
> Starting Receiving
> Ending program

I am using Pythonn 2.7.5

**Comment by toshiro92** [comment]
After a while, I used a virtualenv with python 3.5 for testing purposes, and now it works well. This could be due to the python version ?

**Comment by Harmon758** [comment]
You're likely receiving an error from Twitter's API, and since you don't have an `on_error` method for your StreamListener, it's not handled and there's no output.
As it is, this issue isn't reproducible or actionable.
Feel free to create a new issue if you're able to reproduce this with an `on_error` method that's not called or that's called with a status code that you're not expecting.
