### ISSUE TITLE
Unable to use API.lists() api

### ISSUE THREAD

**Issue by sudharsanmit** [tweepy/tweepy#764]
Traceback (most recent call last):
  File "twitter.py", line 203, in <module>
    t.show_lists()
  File "twitter.py", line 135, in show_lists
    for i in self._api.lists():
AttributeError: 'API' object has no attribute 'lists'

**Comment by eelsweb** [comment]
The issue is with the documentation. The method in the code is `lists_all()`.
@sudharsanmit The documentation is incorrect. use `lists_all` in place of `lists`

**Comment by eelsweb** [comment]
Ideally the method should be named `lists_list()` to match the twitter endpoint.

**Comment by sudharsanmit** [comment]
Truckload of documentation errors -
Even a simple statuses_lookup is wrong.

Says -

>  API.statuses_lookup(id[, include_entities][, trim_user][, map])
>  Returns full Tweet objects for up to 100 tweets per request, specified by the id parameter.
> 

But actually is
`statuses_lookup(id_=id,include_entities=include_entities,trim_user=trim_user,map_=map)`

**Comment by Aaron1011** [comment]
Sorry about that - I've been meaning to go through and clean up the docs.
