### ISSUE TITLE
Raises an exception if a duplcate status is posted, documentation suggests otherwise

### ISSUE THREAD

**Issue by drumber-1** [tweepy/tweepy#768]
If update_status is called with a duplicate status, a TweepError is raised:

```
File "/usr/local/lib/python2.7/dist-packages/tweepy/api.py", line 194, in update_status
    )(post_data=post_data, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/binder.py", line 245, in _call
    return method.execute()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/binder.py", line 229, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{u'message': u'Status is a duplicate.', u'code': 187}]
```

Although the [documentation](http://tweepy.readthedocs.io/en/v3.5.0/api.html#status-methods) says "Statuses that are duplicates or too long will be silently ignored."

**Comment by Homerade** [comment]
I'm having the same issue. Not sure how the repeat is coming about or how to write an exception. Did you ever solve this or have an example exception to show?

**Comment by mattcanavan** [comment]
I used a try/except statement with `except tweepy.TweepError` to handle duplicate updates.

**Comment by chriskinyua** [comment]
@mattcanavan that try/except statement ignores all Tweepy errors, not the duplicate updates only. Is there a way of ignoring the duplicate updates error  and further be able to post a duplicate?

**Comment by fitnr** [comment]
You can use an `if` block inside the `except` block to specify different treatment of different error types.
```python
try:
    api.update_status(duplicate_text)
except tweepy.TweepError as error:
    if error.api_code == 187:
        # Do something special
        print('duplicate message')
   else:
       raise error
```

Twitter is preventing you from posting the duplicate text, so the only way around that is to just wait.

**Comment by Harmon758** [comment]
Resolved by https://github.com/tweepy/tweepy/commit/c0c6f166dae360d0d9ec4759928137a2b344ab8f

> so the only way around that is to just wait

I'm not sure if waiting (without creating any additional Tweets in the meantime) will do anything though.
I think it just compares it to recent Tweets, regardless of when they were.

**Comment by Nova1323** [comment]
Just change the contents of api.update_status and your program should work fine
