### ISSUE TITLE
Authentication can be done way more simply than instructions suggest

### ISSUE THREAD

**Issue by itamarst** [tweepy/tweepy#769]
Twitter UI now has button to generate the second set of token/secret pairs. So you can skip all the complex docs and jump straight to:

```
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(key, secret)
```

for many users who are just setting up their own personal twitter account with tweepy.

**Comment by Aaron1011** [comment]
That's what the oauth example shows: https://github.com/tweepy/tweepy/blob/master/examples/oauth.py#L12-L19

Were you referring to an example in a different place?

**Comment by itamarst** [comment]
I was referring to the prose docs: http://tweepy.readthedocs.io/en/v3.5.0/auth_tutorial.html

It talks about `get_authorization_url` and whatnot.

**Comment by Aaron1011** [comment]
@itamarst: The point of that tutorial is to explain how to perform OAuth in a production application, such as a website. The [Getting Started](https://github.com/tweepy/tweepy/blob/master/docs/getting_started.rst#hello-tweepy) pages goes over using your own authentication keys.

**Comment by francopiccolo** [comment]
I second this, it would be great if the authentication tutorial makes a small comment around the simple case for users, even if that is mentioned in the Getting started.

**Comment by dibrinsofor** [comment]
Hi @Aaron1011 and @francopiccolo, can I take this up?

**Comment by dibrinsofor** [comment]
> I second this, it would be great if the authentication tutorial makes a small comment around the simple case for users, even if that is mentioned in the Getting started.

hey @francopiccolo, has this been worked on already? i noticed the oauth example in the prose docs

**Comment by Harmon758** [comment]
I've rewritten the authentication documentation with https://github.com/tweepy/tweepy/commit/f9a722bae8cce368b9f8fd447c418e1034c32178, so this should be resolved now.
