### ISSUE TITLE
Bug in the code

### ISSUE THREAD

**Issue by j4ndr4** [tweepy/tweepy#770]
Hello,

I should have been more specific in the title. It's a bug in the example code of the online documentation

I noticed that there is a bug in the Streaming page ( http://docs.tweepy.org/en/v3.5.0/streaming_how_to.html )

Now:
myStream = tweepy.Stream(auth = api.auth, listener=myStreamListener())

It should be:

myStream = tweepy.Stream(auth = api.auth, listener=myStreamListener)

**Comment by Aaron1011** [comment]
This has been fixed in https://github.com/tweepy/tweepy/commit/8322cf6252db66c2288fdbf6c218f88518320cb9. Unforuntately, I'm not able to deploy new versions of the docs atm. As soon as I'm able, I'll update the site.
