### ISSUE TITLE
Streaming does not gracefully terminate if no messages are received

### ISSUE THREAD

**Issue by jusw85** [tweepy/tweepy#773]
Using tweepy==3.5.0

```
def signal_handler(signal, frame):
    print("Ctrl-C received")
    myStream.disconnect()

myStreamListener = MyStreamListener()
myStream = tweepy.Stream(auth=api.auth, listener=myStreamListener)

signal.signal(signal.SIGINT, signal_handler)
myStream.filter(track=['keywords'])
```

I would like to Ctrl-C terminate my application. Calling `stream.disconnect()` sets `running=False`. However, this variable is only tested when Tweepy receives a message. If no messages are received, it blocks while reading from the stream (specifically `self._buffer += self._stream.read(self._chunk_size)` in `read_line()`), and I have to force kill my application.

**Comment by Harmon758** [comment]
With https://github.com/tweepy/tweepy/commit/37e701e2193dcf617e7235d3b004f790c5ff784e, the stream should now be able to disconnect on the next keep-alive signal received.
