### ISSUE TITLE
'TweepError' object has no attribute 'message'

### ISSUE THREAD

**Issue by FlxVctr** [tweepy/tweepy#774]
I'm trying to retrieve the error code as described [here](http://tweepy.readthedocs.io/en/v3.5.0/api.html#tweepy-error-exceptions) but get the AttributeError above.

**Comment by KillianKemps** [comment]
The documentation seems outdated. I ran into the same issue. Fortunately, the code is easy to read so I found out this:

` tweepy/tweepy/error.py`
```
class TweepError(Exception):
    """Tweepy exception"""

    def __init__(self, reason, response=None, api_code=None):
        self.reason = six.text_type(reason)
        self.response = response
        self.api_code = api_code
        Exception.__init__(self, reason)

    def __str__(self):
return self.reason
```

So, TweepError has no message attribute but a Response object. 

To display the full response text, do something like this:

```
except tweepy.TweepError as e:
    print('Twitter error: ', e.response.text)
```

**Comment by Harmon758** [comment]
The documentation has now been updated with https://github.com/tweepy/tweepy/commit/d975b6ebba41034b801de5535dd0a11cc060728e (#1001) as part of Tweepy v3.6.0.
