### ISSUE TITLE
Discuss Forum is off

### ISSUE THREAD

**Issue by jtemporal** [tweepy/tweepy#776]
Hi guys, I was trying to access the Discuss Forum at http://discuss.tweepy.org/ and I got an Server not found page...
Is there anything going on? Maybe some change in the link idk.
If there is anything I can do help let me know =)

**Comment by Megalegacy98** [comment]
I'd like to know as well. It seems like the last time that the site was online was <a href=http://web.archive.org/web/20151230105304/http://discuss.tweepy.org/>December 30th, 2015</a> or so.

**Comment by OctoPenguin** [comment]
Same here...

**Comment by Harmon758** [comment]
That link on the website has now been replaced by [an invite link to the Discord server](https://discord.gg/bJvqnhg).
See https://github.com/tweepy/tweepy.github.com/commit/ee17f21fb379698120408d2f71295557bbd0170e
