### ISSUE TITLE
List of followers

### ISSUE THREAD

**Issue by davboc** [tweepy/tweepy#778]
Hi all,
I'm looking for a way (in python) to list all followers from one account, with username and number of followers.
Now I can obtain the list of all ids in this way:

```
ids = []
for page in tweepy.Cursor(api.followers_ids, screen_name="username").pages():
    ids.extend(page)
    time.sleep(1)
```

but with this list of ids I can't obtain username and number of followers of every id, because the rate limit exceed...
How I can complete this code?

Thank you all!

**Comment by Sam-Doran** [comment]
```python
api = tweepy.API(auth, wait_on_rate_limit=True)
```
If you put `wait_on_rate_limit=True` in the constructor tweepy will wait for Twitter's rate limit to reset.

**Comment by Aaron1011** [comment]
@Sam-Doran's solution should fix your problem.
