### ISSUE TITLE
Python 3 Unicode Error on streaming with filter

### ISSUE THREAD

**Issue by capital-G** [tweepy/tweepy#782]
Hi,

I tried to use a filter in tweepy.Stream in Python 3.5 - this is my code:

```
import tweepy

CONSUMER_KEY = 'xxx'
CONSUMER_SECRET = 'xxx'

ACCESS_TOKEN = 'xxx'
ACCESS_TOKEN_SECRET = 'xxx'

class ExampleStreamer(tweepy.StreamListener):
    def on_status(self, status):
        print(status)

auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)

api = tweepy.API(auth)

stream = tweepy.Stream(auth=api.auth, listener=ExampleStreamer())
stream.filter(follow=['14230524'], filter_level='medium')
```

and I got this error

```
xxx@xxx-ThinkPad-Edge-E540:~/xxx$ python bug.py 
Traceback (most recent call last):
  File "bug.py", line 19, in <module>
    stream.filter(follow=['14230524'], filter_level='medium')
  File "/home/xxx/anaconda3/lib/python3.5/site-packages/tweepy/streaming.py", line 442, in filter
    self.body['filter_level'] = unicode(filter_level, encoding)
NameError: name 'unicode' is not defined
```

This is the line to blame:
https://github.com/tweepy/tweepy/blob/cd46550b3ef068857f5de9c37bbdd0a72acb7462/tweepy/streaming.py#L444

I use Anaconda with Python 3.5 and installed tweepy via pip and updated before reporting this bug.
I never worked with Py2 so it's I can't make a Pull request myself, but I doubt it's an difficult task.

http://stackoverflow.com/questions/19877306/nameerror-global-name-unicode-is-not-defined-in-python-3

Best

**Comment by capital-G** [comment]
I tried to do this by myself - seems to work under  py2k and py3k
https://github.com/tweepy/tweepy/pull/783

**Comment by Hahny** [comment]
You face this problem because the unicode() method is depricated in python 3. 
Switch to python2 or just dont use the filter_level attribute. Then it works fpr python3.
