### ISSUE TITLE
Problem with media entities

### ISSUE THREAD

**Issue by davboc** [tweepy/tweepy#784]
today seems that there is a problem with media in entities; indeed seems that if a tweet contains an hashtag so tweepy can't retrieve its media. 
Strange behavior, maybe it is a problem with new decision of tweet to not include media in character count?

What can we do?

Thanks

**Comment by bitrainbow** [comment]
I think twitter changed their api today. 
We're having issues also. 
Not sure of a solution yet unfortunately.

**Comment by Sascha-Peter** [comment]
This may not help you @davboc but in (some) tweepy functions, you can pass additional arguments (such as the "tweet_mode=extended") and this will give you the "new" twitter format. 

We tested this successfully with "time_line()" as it just passes on any other arguments which it doesn't expect as kwargs.

**Comment by davboc** [comment]
@Sascha-Peter Thanks for reply! If I use extendend in the cursor I can't find status.text attribute...

**Comment by Sascha-Peter** [comment]
@davboc it's called full_text now - hope that helps.

**Comment by bitrainbow** [comment]
high five @Sascha-Peter

**Comment by davboc** [comment]
This is the solution. Thanks @Sascha-Peter, big hint

**Comment by JohnMTorgerson** [comment]
@Sascha-Peter do you happen to know if that works with get_status()? I'll try it out myself tonight when I get a chance, but I was curious in the mean time.

**Comment by Harmon758** [comment]
I've now added [a section in the documentation that covers extended Tweets](https://tweepy.readthedocs.io/en/latest/extended_tweets.html) to supplement [Twitter’s Tweet updates documentation](https://tweepy.readthedocs.io/en/latest/extended_tweets.html).
