### ISSUE TITLE
TweepError

### ISSUE THREAD

**Issue by ahsanch** [tweepy/tweepy#790]
I have anaconda3, python3.5 and tweepy3.3.0 installed on my computer.
Operating system- ubuntu 12.04.
Internet connection- proxy 172.16.24.2, port 3128.

Sir, this is the commands execution sequence, please help me in sorting out the problem.

```
TERMINAL WINDOW
$ cd anaconda3
~/anaconda3$ source bin/activate ~/anaconda3 # to activate anaconda3 as environment variable
(/home/ahsan/anaconda3) :~/anaconda3$ export TWITTER_CONSUMER_KEY="my_consumer_key"
(/home/ahsan/anaconda3) :~/anaconda3$ export TWITTER_CONSUMER_SECRET="my_consumer_secret"
(/home/ahsan/anaconda3) :~/anaconda3$ export TWITTER_ACCESS_TOKEN="my_access_token"
(/home/ahsan/anaconda3) :~/anaconda3$ export TWITTER_ACCESS_SECRET="my_access_secret"
(/home/ahsan/anaconda3) :~/anaconda3$ spyder

SPYDER
i) run twitter_client.py

ii) run below given code:

from tweepy import Cursor
from twitter_client import get_twitter_client
if __name__=='__main__':
    client=get_twitter_client()
    for status in Cursor(client.home_timeline).items(10):
        print(status.text)
```

Running this code results in-

Traceback (most recent call last):
File "", line 5, in
for status in Cursor(client.home_timeline).items(10):
File "/home/ahsan/anaconda3/lib/python3.5/site-packages/tweepy/cursor.py", line 49, in next
return self.next()
File "/home/ahsan/anaconda3/lib/python3.5/site-packages/tweepy/cursor.py", line 197, in next
self.current_page = self.page_iterator.next()
File "/home/ahsan/anaconda3/lib/python3.5/site-packages/tweepy/cursor.py", line 108, in next
data = self.method(max_id=self.max_id, parser=RawParser(), self.args, *self.kargs)
File "/home/ahsan/anaconda3/lib/python3.5/site-packages/tweepy/binder.py", line 239, in _call
return method.execute()
File "/home/ahsan/anaconda3/lib/python3.5/site-packages/tweepy/binder.py", line 189, in execute
raise TweepError('Failed to send request: %s' % e)
TweepError: Failed to send request: Missing dependencies for SOCKS support.

How it can be resolved?

**Comment by Aaron1011** [comment]
You'll need to install `PySocks` (with `pip install PySocks`). I've added this to `requirements.txt` in the latest master: https://github.com/tweepy/tweepy/commit/254c63d5f59a16b89df398f91f2e6751647946bf
