### ISSUE TITLE
Do we need an extra set of hands?

### ISSUE THREAD

**Issue by alexgurrola** [tweepy/tweepy#792]
The issues / pull requests seem to be growing and I love this library for various reasons (and am using it for a few of my own projects), so I'll put forth a push to allow a bit more progress by offering myself as an extra set of hands to maintain this project.

Get back to me when you can! @Aaron1011 @joshthecoder 

-- Alex

**Comment by fitnr** [comment]
I would also be happy to help. If you (the repo owners) are cautious about having someone commit, I would be happy to take on the task of closing duplicate issues and pull requests.

**Comment by GeorgeSaussy** [comment]
I would love to contribute where I could.

**Comment by mguida22** [comment]
I'd be happy to help contribute as well

**Comment by hugovk** [comment]
Something everyone can do already: review existing PRs.

1. Click "Files changed"
2. Click on lines to comment
3. Repeat 2
4. Click "Review changes" to finish

More info: https://help.github.com/articles/about-pull-request-reviews/

Even if it's just an "Approve", that should help the maintainers when they come along to merge.

**Comment by fitnr** [comment]
I just noticed that two days ago @joshthecoder added a "no longer supported" note to the README.

**Comment by Aaron1011** [comment]
@joshthecoder: I'd be interested in continuing the development of tweepy.

**Comment by joshthecoder** [comment]
@Aaron1011 You are more than welcome to continue working on the library. You should have access to push commits to the repo still. I'll also see if I can grant you permission to add other contributors to the project you trust.

**Comment by Shatnerz** [comment]
Regarding this, will new versions be pushed to PyPI? PyPI currently contains 3.5.0 vs 3.6.0.

I'll also go through issues and pull requests if I can spare the time.

**Comment by Aaron1011** [comment]
@Shatnerz: I'll push new versions to PyPI just as soon as @joshthecoder gives me access. For now, I'm going through and cleaning up old issues and PRS - either merging/closing them, or marking them for further review.

**Comment by Ryuno-Ki** [comment]
@Aaron1011 Labels [may come in handy](https://help.github.com/articles/creating-and-editing-labels-for-issues-and-pull-requests/) here :)

**Comment by kodeine** [comment]
@Aaron1011 can you please update the version in pip?

**Comment by Shatnerz** [comment]
@kodeine Patience my friend. Just pip install directly from github until then.

**Comment by vism2889** [comment]
As i see the last comment in this thread is about a year old... so i guess if it still applies I would be happy to do maintenance where needed, have been using Tweepy quite a bit recently, have received some help from others and have tried to give it back when i can.  Some things may be out of my league but i think i could handle something like maintaining docs.  As of recent i've seen lots of questions regarding truncated tweets -- would be cool to add documentation regarding `tweet_mode = 'extended'` param, and `full_text` attribute... possibly other information regarding twitters update to make the length of tweets longer.

**Comment by ZeerakW** [comment]
Happy to help where I can. 

Potentially there could be some people who just go over all of the documentation PRs and issues and fix those? At least that way they wouldn't clog and we only have things that are dev-centric that need updating.

**Comment by alexgurrola** [comment]
I'm not certain if there's a way for this repository to be maintained if there isn't any access to PyPi, but @Aaron1011 still looks active around here.

**Comment by ZeerakW** [comment]
@alexgurrola yeah the issue mainly seems that @Aaron1011 appears to be doing this alone and with the current backlog it'll be pretty time consuming to clear it down to things that are still unresolved.

**Comment by Shatnerz** [comment]
@alexgurrola If the PyPi access is really an issue and no one can contact the maintainer, we could always fork. Did Aaron never get access from Josh?

I haven't used tweepy in awhile, so I'm basically useless at this point.

**Comment by ZeerakW** [comment]
I only use it on/off so I'm only semi useful, but I think a fork might make sense. I'd be up for helping out with a fork.

**Comment by Harmon758** [comment]
I've closed and labeled a significant number of issues today and will continue to do so.
I'll also be going over and reviewing open PRs to be merged.
I'll close this issue when the number of open issues and PRs has been brought down to a sustainable amount.

**Comment by Harmon758** [comment]
I'm going to go ahead and close this, as I've closed 250+ issues, merged and closed 20+ PRs, and labeled a majority of all the issues and PRs now.
There's still a lot to be done, but I'll continue going through all the issues and PRs, new and old.

Specifically, @vism2889, documentation on the Tweet updates is something I plan on adding.
Once I do so, I'll close all the current open issues regarding that.

Additionally, I believe PyPI releases have been automated since https://github.com/tweepy/tweepy/commit/2ceda616694df6ed0bbcce9c1f8e11420d9011ef, so if and once necessary, I should be able to tag and push a new release to PyPI automatically.
Either way, I've been in touch with @​joshthecoder regularly, so that shouldn't be an issue.

Further feedback can be given in the [Discord server](https://discord.gg/bJvqnhg) (see #1025).
