### ISSUE TITLE
Unable to Install the Python Tweepy Module

### ISSUE THREAD

**Issue by richardgeo2** [tweepy/tweepy#793]
I downloaded the python Tweepy module from here https://github.com/tweepy/tweepy.

I extracted the contents and named the folder 'Tweepy'. I opened up Command Prompt and ran the setup.py install. Several messages show. e.g. running install running bdist_egg etc.

However, I receive some error messages then; Download error on https://pypi.python.org/simple/six/: Tunnel connection failed: 407 authenticationrequired -- Some packages may not be found! Couldn't find index page for 'six' (maybe misspelled?) No local packages or download links found for six>=1.7.3

I wonder if the errors are possibly associated with proxy settings?

**Comment by fitnr** [comment]
It sounds like you're having problems with pip, not tweepy. You should close this issue and search stack exchange for help on using pip through a proxy.

**Comment by richardgeo2** [comment]
Thank you for the information Neil.

Can you please let me know how to close the issue?

Regards,
Richard

**Comment by Peteous** [comment]
It's not pip's fault. I can't install tweepy either, though I have no problem installing anything else

**Comment by sushmashamsundar** [comment]
same error am getting
