### ISSUE TITLE
TweepError: string indices must be integers, not str

### ISSUE THREAD

**Issue by vatsalparekh** [tweepy/tweepy#794]
Hey,
I'm getting this error 
`TweepError: string indices must be integers, not str`
in calling the function `auth.get_access_token()`

I can't figure out which integer it's asking for because i passed just the verifier i got from the twitter

```
 In [6]: auth.get_access_token('JgqGic5xlhlXgqrEVsLbXV0dzb5guVtU')
---------------------------------------------------------------------------
TweepError                                Traceback (most recent call last)
<ipython-input-6-a9ca46d99f99> in <module>()
----> 1 auth.get_access_token('JgqGic5xlhlXgqrEVsLbXV0dzb5guVtU')

/usr/local/lib/python2.7/dist-packages/tweepy/auth.pyc in get_access_token(self, verifier)
    105             return self.access_token, self.access_token_secret
    106         except Exception as e:
--> 107             raise TweepError(e)
    108 
    109     def get_xauth_access_token(self, username, password):

TweepError: string indices must be integers, not str

```

**Comment by Aaron1011** [comment]
@vatsalparekh: Sorry for the long delay in getting to this. Can you please post t he code you're using?

**Comment by Harmon758** [comment]
You seem to have passed a string to `OAuthHandler.request_token`, which, as of https://github.com/tweepy/tweepy/commit/416d0d680b9690b4615c21dd0037efb5f95c906c (Part of #400), should be set to a dictionary with the OAuth token and OAuth token secret using the keys, `oauth_token` and `oauth_token_secret` respectively.
