### ISSUE TITLE
tweepy.error.TweepError

### ISSUE THREAD

**Issue by spring19940512** [tweepy/tweepy#796]
tweepy.error.TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443):
Max retries exceeded with url: /1.1/users/show.json?id=twitter 
(Caused by NewConnectionError
('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000031A8400>: 
Failed to establish a new connection: [Errno 10060] ',))
the code is
import tweepy
consumer_key=""
consumer_secret=""
access_token=""
access_token_secret=""
auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

user = api.get_user('twitter')
print user.screen_name
print user.followers_count
for friend in user.friends():
   print friend.screen_name

**Comment by Shatnerz** [comment]
Your code is running fine on my machine.

Can you see if you still have a problem? If so, what version of tweepy are you using? What version of python are you using? Are you or is anyone else in your LAN possibly using the Twitter API?

**Comment by wodim** [comment]
You somehow can't connect to "api.twitter.com", that's not a problem with this library

**Comment by Harmon758** [comment]
Please don't necrobump old closed issues.

This is an issue with your SSL certificate when connecting to Twitter's API, which is unrelated to this issue and not an issue with Tweepy.

For code block usage, see https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks.
