### ISSUE TITLE
unicode encoding error? TwitterStream cannot handle special characters

### ISSUE THREAD

**Issue by nikolassch** [tweepy/tweepy#801]
Hi,

I am using tweepy to stream tweets. However, there seems to be an encoding issue with python 3.5:

if I use this generic code the output is not properly formatted: see for example `estabilizacion` is written as `estabilizaci\u00f3n`. Is this a bug of the API? Should I encode is somehow to utf8 or so?

``` json
{"geo": null, "is_quote_status": false, "retweet_count": 0, "text": "RT @mrtorsor: Verdadero reto de la toma de Mosul: fase de estabilizaci\u00f3n posterior. Una mala gesti\u00f3n puede agravar el caos en Irak https://\u2026", "coordinates": null, "in_reply_to_user_id": null, "truncated": false, "source": "<a 
[...]
}
```

``` python
import json

from twitter import Twitter, OAuth, TwitterHTTPError, TwitterStream

ACCESS_TOKEN = 'xxx'
ACCESS_SECRET = 'xxx'
CONSUMER_KEY = 'xxx'
CONSUMER_SECRET = 'xxx'

oauth = OAuth(ACCESS_TOKEN, ACCESS_SECRET, CONSUMER_KEY, CONSUMER_SECRET)

twitter_stream = TwitterStream(auth=oauth)

iterator = twitter_stream.statuses.sample()

tweet_count = 10
for tweet in iterator:
    tweet_count -= 1
    print(json.dumps(tweet))
    if tweet_count <= 0:
        break
```

Thank you very much for any suggestions!

**Comment by neopostmodern** [comment]
I tried to dig into this for @nikolassch and it seems that the error is already present in `ReadBuffer.read_len`. I built from source. 
What baffled me is that `estabilizaci\u00f3n` is a `str`, thus - per Python3.5 - unicode and therefore what one would express as `"estabilizaci\\u00f3n"`.

**Comment by Harmon758** [comment]
This seems to be using a different library, [`twitter`](https://github.com/sixohsix/twitter), rather than Tweepy.
