### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by Pescu** [tweepy/tweepy#804]
Problem with streaming on attributes of stream.filter(track=['#python'])

**Comment by xofeoj** [comment]
Is the error originating from streaming.py? Does it work if you remove the #?

**Comment by Pescu** [comment]
Ok, i already found the problem: The twitter streaming API has been experiencing problems since the attack on DYN the 21st of October. These have been reported on the twitter developer forum, and twitter staff are aware of the issue: https://twittercommunity.com/t/issues-reported-with-streams-since-10-21/76429.
