### ISSUE TITLE
NameError: name 'OAuthHandler' is not defined

### ISSUE THREAD

**Issue by karthikapp** [tweepy/tweepy#807]
hi i am getting this error . pls help 

```
from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream
class StdOutListener(StreamListener):

    def on_data(self, data):
        print data
        return True

    def on_error(self, status):
        print status


if __name__ == '__main__':

    #This handles Twitter authetification and the connection to Twitter Streaming API
    l = StdOutListener()
    auth = OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    stream = Stream(auth, l)

    #This line filter Twitter Streams to capture data by the keywords: 'python', 'javascript', 'ruby'
    stream.filter(track=['python', 'javascript', 'ruby'])
```

**Comment by Aaron1011** [comment]
@karthikapp: How have you installed Tweepy? As I'm currently unable to push new versions to PyPI, you should install it from source for now.

**Comment by karthikapp** [comment]
hi @Aaron1011 yes it is installed. I downloaded the source code and tried again. I still get the 
NameError: name 'OAuthHandler' is not defined
error when importing tweepy

**Comment by Aaron1011** [comment]
@karthikapp: I don't think that your code is importing the proper version of tweepy. Try running `python setup.py install` from the root of your Tweepy clone. Or, ytu moving your code to the root of your Tweepy clone, and run it from there.

**Comment by karthikapp** [comment]
@Aaron1011 I had to remove "all" files installed by tweepy and then install it from source. I now have it working. Thanks buddy. It works great ! really appreciate your help !

**Comment by Aaron1011** [comment]
@karthikapp: Glad to hear that you got it working 😄

**Comment by HyperionSounds** [comment]
I've done as described above, installed and unistalled with pip, then installed from source, to no avail. I did not "remove all files insalled by tweepy" as described by karthikapp

**Comment by SudilHasitha** [comment]
just add
from tweepy import OAuthHandler

**Comment by HyperionSounds** [comment]
> just add
> from tweepy import OAuthHandler

Already had that, it didn't work and still doesn't. I have tweepy 3.9.0 installed via pip inside of a virtualenv.
Here is an example of the code I am using, ran 'python tweepy_testrun.py' from my command line inside my env:

import tweepy
from tweepy import OAuthHandler

#Add your credentials here
twitter_keys = {
        'consumer_key':        'xxxxxx',
        'consumer_secret':     'xxxxxxx',
        'access_token_key':    '1xxxxx',
        'access_token_secret': 'xxxxxxxxxxxx'
    }

auth = OAuthHandler(twitter_keys['consumer_key'], twitter_keys['consumer_secret'])
auth.set_access_token(twitter_keys['access_token_key'], twitter_keys['access_token_secret'])

api = tweepy.API(auth)

#Make call on home timeline, print each tweets text
public_tweets = api.home_timeline()
for tweet in public_tweets:
    print(tweet.text)

**Comment by Harmon758** [comment]
Please don't necro-bump old closed issues.

Make sure you don't have another file or module named "tweepy" in the project or in your path.

For code block usage, see https://docs.github.com/en/free-pro-team@latest/github/writing-on-github/creating-and-highlighting-code-blocks.
