### ISSUE TITLE
Tracking reteets with streaming api

### ISSUE THREAD

**Issue by Pescu** [tweepy/tweepy#809]
Hello, i have a problem with the tweets on a stream. I'm searching for the retweets and from the documentation, if a tweet retweet shold have the attribute 'retweeted_status'. Using the search api the attribute appears so I can extrapolate the asociated data, but when i use the stream api the attribute never appears. I'm doing something wrong, or it is a normal thing?

**Comment by Pescu** [comment]
I noticed that the stream dont contain retweeted statuses. How can I force tweepy to stream also the retweets?

**Comment by Harmon758** [comment]
I'm unable to reproduce this and am receiving Retweets as Status objects with `retweeted_status` attributes from `Stream.filter` through both providing either the `track` or `follow` parameters.
