### ISSUE TITLE
Streaming errror: "TypeError: expected string or buffer"

### ISSUE THREAD

**Issue by gambolputty** [tweepy/tweepy#812]
Hello!

Since a month or so twitter streaming with tweepy regularly breaks after 5 – 10 minutes and throws the following error:

`TypeError: expected string or buffer`

I'm tracking about 100 keywords. I also tried to wrap every keyword in quotes (as suggested in #748), but it doesn't work either.

Output:

```
Traceback (most recent call last):
  File "/home/gregor/projects/livecorpus/stream.py", line 473, in <module>
    twitterStream.filter(track=[u'"{}"'.format(kw) for kw in KEYWORDS], languages=['en'])
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 445, in filter
    self._start(async)
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/usr/local/lib/python2.7/dist-packages/tweepy/streaming.py", line 294, in _run
    raise exception
TypeError: expected string or buffer
```

Versions:
requests 2.12.1
tweepy 3.5.0

**Comment by Aaron1011** [comment]
I've made several changes to Tweepy recently, but I'm unfortunately unable to publish new versions to PyPI until @joshthecoder gives me access. For now, can you try using the current `master` branch from the github repository?

**Comment by gambolputty** [comment]
@Aaron1011 Yes! Thanks for the quick response. Will try using the `master` branch :)

**Comment by gambolputty** [comment]
I can confirm now, that the current `master` branch works perfectly.
