### ISSUE TITLE
TweepError('Failed to send request: %s' % e)

### ISSUE THREAD

**Issue by death-teaser** [tweepy/tweepy#817]
Hii``  ..i found this error in my code.plz help me to fix this
code:
`import` tweepy

consumer_key = "xyz"
consumer_secret = "xyz"

access_token = "xyz"
access_token_secret = "xyz"

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)

api = tweepy.API(auth)

public_tweets = api.home_timeline()
for tweet in public_tweets:
    print `tweet.text`
error details:
   raise TweepError('Failed to send request: %s' % e)
tweepy.error.TweepError: Failed to send request: [Errno -3] Temporary failure in name resolution

**Comment by Aaron1011** [comment]
It looks like the DNS server that your computer uses had a temporary problem. Check that you can access `twitter.com` in your browser, and try running your code again.
