### ISSUE TITLE
gzip encoding support for streaming in 3.5.0

### ISSUE THREAD

**Issue by exzhawk** [tweepy/tweepy#819]
I've noticed gzip streaming supported in #233 , but is it supported in 3.5.0? I can't find any related parameters in documents. 

Passing `gzip=True` or `compression=True` to Stream() does no help.

Passing `headers={'Accept-Encoding':'deflate, gzip','User-Agent':'tweepy'}` to Stream() results `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x8b in position 1: invalid start byte` error.

**Comment by exzhawk** [comment]
thanks to #718 , resolved

**Comment by Harmon758** [comment]
#718 shouldn't be necessary, as the requests library by default accepts gzip encoding and decompresses it automatically for each response.
