### ISSUE TITLE
Getting the accounts with the most friend followers (followers that I follow)

### ISSUE THREAD

**Issue by Mohamed3on** [tweepy/tweepy#820]
Hello, I'd like to get a list of the accounts that have the most followers I know. For example, if Barack Obama was followed by 100% of the people I follow, he'd rank first in such list.
How can I do that with tweepy?

**Comment by py3in** [comment]
I think this option can help you for a lot of your problem. The rest will be a mining operation according to your strategy.

https://github.com/ducu/twitter-most-followed

**Comment by Mohamed3on** [comment]
Thank you. Actually I already did it here:
Github.com/Mohamed3on/TwitterNetwork
The only problem is the API rate limit, which is unfortunate.
