### ISSUE TITLE
Create a file called twitter_streaming.py, and copy the code below into it. Make sure to enter your credentials obtained in the Step 1 above into ACCESS_TOKEN, ACCESS_SECRET, CONSUMER_KEY, and CONSUMER_SECRET.

### ISSUE THREAD

**Issue by LakshmiHarshini** [tweepy/tweepy#824]
Json.dump() not working

C:\Users\BARAN\Desktop\tweepy-master>python twitter_trump.py
  File "twitter_trump.py", line 35
    print json.dumps(tweet)
                            ^
IndentationError: unindent does not match any outer indentation level

**Comment by DeanF** [comment]
It seems like an indentation error in your file and not in the library, make sure your indentation is consistent (Spaces or Tabs)

**Comment by Harmon758** [comment]
As explained, this is an issue with indentation in your code rather than an issue with this library.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
