### ISSUE TITLE
receiving NameError: global name 'sys' is not defined error within 20~hours of streaming

### ISSUE THREAD

**Issue by stavnahum** [tweepy/tweepy#826]
Hey everyone,
I'm running tweepy 3.6.0 on python 2.7.9
I keep on getting this following error after a few hours of perfect traffic.

I usually get the message after 20~ hours of streaming.

Traceback (most recent call last):
  File "C:/Users/*****/twitter_research/TwitterProject/main.py", line 75, in <module>
    twitter_stream.filter(track=keywords)
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 462, in filter
    self._start(async)
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 376, in _start
    self._run()
  File "C:\Python27\lib\site-packages\tweepy\streaming.py", line 295, in _run
    exc_info = sys.exc_info()
NameError: global name 'sys' is not defined

Anyone else experienced the same error?
Thanks ! 👍

**Comment by mattcanavan** [comment]
I haven't experienced this specific error; my issue is different but possibly related. I have a twitter bot tweeting once every 24 hours and duplicate statuses are being posted. When I run the bot every hour the duplicate statuses are caught and the TweepError is raised.

Anyone else experiencing something similar?

p.s. My bot is managed by a rigid scheduler so I'm unable to send test tweets at intervals other than those listed above. Therefore I'm unable to pinpoint the exact time my error (or stavnahum's) is raised.

**Comment by smye** [comment]
@mattcanavan Why not add an exception?
except tweepy.TweepError:

**Comment by Harmon758** [comment]
I'm unable to reproduce this, and I'm not sure what version of Tweepy you're using, as v3.6.0 was released on 2018-03-02, and as far as I can tell, that statement was never on line 295 of streaming.py.
Feel free to open a new issue if you can still reproduce this with the latest development version.

@mattcanavan This is a completely unrelated issue.
As already indicated, you can simply handle the exception.
