### ISSUE TITLE
Followers

### ISSUE THREAD

**Issue by Magnus512** [tweepy/tweepy#828]
I'm trying to use the snippet
`
for follower in tweepy.Cursor(api.followers).items():
    follower.follow()
`
When I run the file .py  get this

Traceback (most recent call last):
  File "tw.py", line 54, in <module>
    follower.follow()
  File "/usr/lib/python3.5/site-packages/tweepy/models.py", line 175, in follow
    self._api.create_friendship(user_id=self.id)
  File "/usr/lib/python3.5/site-packages/tweepy/binder.py", line 245, in _call
    return method.execute()
  File "/usr/lib/python3.5/site-packages/tweepy/binder.py", line 229, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 160, 'message': "You've already requested to follow RonaldoArias_65."}]

Any idea about how to solve this ?

**Comment by py3in** [comment]
Let me understand
What are you doing with follower.follow() ?

here not understand too 
for follower in tweepy.Cursor(api.followers).items(): 

Tell me what you want to get to see if you have another alternative to help you.

sorry my poor english. My first language is portuguese.

**Comment by wodim** [comment]
You have to catch that exception.

    try:
        follower.follow()
    except tweepy.error.TweepError:
        pass

**Comment by Magnus512** [comment]
Thank you I Will do ir así soon as possible

**Comment by Harmon758** [comment]
As the error returned by Twitter says, this simply means you've already requested to follow that user.
This is not an issue with Tweepy.
GitHub issues for this repository should be used to report issues with this library.
They are not a medium for requesting help with Python.
