### ISSUE TITLE
friendship_exists still in Tweepy docs, but not in api

### ISSUE THREAD

**Issue by Forceflow** [tweepy/tweepy#833]
In the official online API documentation, the method `exists_friendship` is still listed: http://docs.tweepy.org/en/v3.5.0/api.html#API.exists_friendship

It is unavailable in the API, however. The supposed new way of finding out if you are followed by a user is using `show_friendship`, but usage of that method is pretty vague. No info on the Friendship object that is returned.

Is the latest generated API documentation published online?

**Comment by py3in** [comment]
I researched and did not find it. Although it is in the documentation. What is working is below.

b = api.show_friendship(source_id=id_account,target_id=target_f)
print b # print status followers e friend about ids.

more https://github.com/tweepy/tweepy/issues/722#issuecomment-270563807

**Comment by Harmon758** [comment]
The documentation for the now non-existent `exists_friendship` method has been removed with https://github.com/tweepy/tweepy/commit/38b4503c7d38558becdf4c26838d66e3ceae040a (#862) and was released with v3.6.0.

From the following, you can see that the Friendship model just parses the relationship data from Twitter's API:
https://github.com/tweepy/tweepy/blob/cc3c8e7cae73d28b9a75edb7342f89f04da99702/tweepy/models.py#L223-L239 For an example for what that looks like when returned by the friendships/show endpoint, you can see Twitter's API documentation at https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-friendships-show.html.

The latest documentation for Tweepy can be found at https://tweepy.readthedocs.io/en/latest/ or http://docs.tweepy.org/en/latest/index.html.
