### ISSUE TITLE
mentions_timeline() is not on the API reference doc page

### ISSUE THREAD

**Issue by brianlee99** [tweepy/tweepy#836]
I recently came across a script that a redditor made on /r/learnprogramming, and he has used the mentions_timeline() method. However, I couldn't find anything on the docs here: http://docs.tweepy.org/en/v3.5.0/api.html

So instead I did a google search and I got this.
https://dev.twitter.com/rest/reference/get/statuses/mentions_timeline

Would it be feasible to migrate some of this information to the tweepy docs? Thank you!

**Comment by Harmon758** [comment]
This was already added with https://github.com/tweepy/tweepy/commit/3ff7735b6fd767ea983516438571c4e9115151f5 (#740) and is now released as part of Tweepy v3.6.0.
