### ISSUE TITLE
Can someone fix api.rst in the docs directory?

### ISSUE THREAD

**Issue by niole** [tweepy/tweepy#838]
I do not know `rst` file syntax, but I think that there's something wrong with either how `api.rst` was written or maybe there's some weird incompatibility with how github renders `rst` files. In any case, can someone please fix this one and any other broken files in the `docs` directory? There's a whole bunch of information that isn't rendering properly

**Comment by Harmon758** [comment]
The documentation is meant to be read at https://tweepy.readthedocs.io/en/latest/ or http://docs.tweepy.org/en/latest/, where the reStructuredText directives are properly rendered when built by Sphinx.
