### ISSUE TITLE
tweet_mode=extended for statuses_lookup

### ISSUE THREAD

**Issue by vchrisb** [tweepy/tweepy#840]
I used ```statuses_lookup``` to get specific tweets. 
But with [a recent change](https://dev.twitter.com/overview/api/upcoming-changes-to-tweets) of Twitter to have also ```extended tweets``` does the REST API only return a compacted version for these tweets.

The Twitter API now supports a parameter ```tweet_mode=extended``` to return not only the compacted version but also the extended one.

#785 does reference that it is currently not possible to use this parameter with ```statuses_lookup```

What needs to be changed to add ```tweet_mode=extended``` support to ```statuses_lookup```?

**Comment by walmsley** [comment]
I've submitted a PR to resolve this: #926 - not sure who's maintaining this repo, but hope the change gets accepted soon!

**Comment by Dmon1Unlimited** [comment]
please let this be fixed <3

**Comment by ZeerakW** [comment]
I think @Aaron1011 is maintaining but don't know.

**Comment by BigMistake** [comment]
I also have this problem. Is there any chance of an update on this?

**Comment by shaharyar2643** [comment]
I'm also having the same problem. Is there a way around to have extended mode in api.statuses_lookcup

**Comment by mjs2020** [comment]
Until this PR is reviewed/approved if you need to use @walmsley 's branch you can install it in your project with: `pip install git+https://github.com/walmsley/tweepy.git@patch-1` (kudos @walmsley  for the work, it saved me a lot of time today)

**Comment by lwahedi** [comment]
@walmsley 's branch doesn't install with the latest pip. I just created a pull request to change the setup.py file so that it should work, as per here: 
https://stackoverflow.com/questions/25192794/no-module-named-pip-req

**Comment by lwahedi** [comment]
@jalperin In the terminal/Bash, first pip uninstall tweepy, then run the above in terminal. Otherwise you'll have two tweepy installs and the original will probably get imported instead when you try to use it.

**Comment by lwahedi** [comment]
Now at https://github.com/lwahedi/tweepy.git@master

**Comment by jason-lange** [comment]
Hi, I tried to install this package using what I understood of lwahedi's guidance. I uninstalled tweepy and entered in terminal: 
    pip install git+https://github.com/lwahedi/tweepy.git@master
But this gets me an error. 
     xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun 
     at: /Library/Developer/CommandLineTools/usr/bin/xcrun
     Command "git clone -q https://github.com/lwahedi/tweepy.git 
     /private/var/folders/dv/qc9vyx051kbcfy7f8zszfz8c0000gn/T/pip-req-build-_mdbezem" failed with 
     error code 1 in None
Has the link for that package changed?

**Comment by mjs2020** [comment]
@jason-lange looks like a problem on your setup, perhaps [this](https://apple.stackexchange.com/questions/254380/macos-mojave-invalid-active-developer-path)?

**Comment by jason-lange** [comment]
@mjs2020 that did it. Many thanks!

**Comment by Harmon758** [comment]
This should now be resolved in 3.7.0 with https://github.com/tweepy/tweepy/commit/c997ee7fbeecc6ecc4da387a8f4c69b72a88893f (#926).

**Comment by francis-de-ladu** [comment]
The doc is not up to date about this issue, even if it's fixed; the tweet_mode attribute is not listed as a valid argument.

http://docs.tweepy.org/en/v3.8.0/api.html#timeline-methods 

It would also be interesting to make the default use the tweet_mode arg given at the handle instantiation time instead of having to specify it explicitly when calling statuses_lookup.

**Comment by Harmon758** [comment]
Tweepy documentation for API methods does not include `tweet_mode` as an attribute for each applicable method.
Instead, there is [a designated section covering extended Tweets](https://tweepy.readthedocs.io/en/latest/extended_tweets.html).
This is correspondent with how Twitter's own API documentation handles documentation for the attribute, as otherwise, there would be a multitude of methods with the same repeated documentation of the attribute.
