### ISSUE TITLE
404 streaming api

### ISSUE THREAD

**Issue by LorraineGit** [tweepy/tweepy#843]
from tweepy import OAuthHandler
from tweepy import Stream
from tweepy.streaming import StreamListener

class MyListener(StreamListener):

    def on_data(self,data):
        try:
            with open('python.json','a') as f:
                f.write(data)
                return True
        except BaseException as e:
            print("Error on_data: %s" % str(e))
        return True

    def on_error(self,status):
        print(status)
        return True

if __name__ == "__main__":   

    auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token_key, access_token_secret)
    api = tweepy.API(auth)

    twitter_stream=Stream(auth,MyListener())
    twitter_stream.filter(track=['video'])

![image](https://cloud.githubusercontent.com/assets/23293170/22791238/a75f5cce-ef23-11e6-8d12-31a35a7c52f3.png)
a simple example about streaming api ,but always have 404 ,before running well ,i don't know why

**Comment by detorr** [comment]
Same issue with me also

**Comment by Drebbel** [comment]
If you would go to the twitter developer pages, they have a breakdown of every error code they send back to you

**Comment by YTMark** [comment]
Hi bro,have you solved this problem now?I meet the same issue like you.

**Comment by weehowe-z** [comment]
Some URLs are blocked in China, try to bypass the GFW.   
Same issue  #879

**Comment by stanpcf** [comment]
I have same issue. I trace this problem and found some problem.this problem is about stream api. when I use function `tweepy.Stream(auth, streamlistener).filter()`, tweepy will requests for url `https://stream.twitter.com/1.1/statuses/filter.json`,  however this url is 404.  I'm in china, but rest api (not stream api) is OK.

**Comment by Harmon758** [comment]
This simply means you're unable to connect to the Twitter API endpoint.
This is an issue with your connection to Twitter rather than an issue with Tweepy.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
