### ISSUE TITLE
Error in Consumer Key or Consumer Secret

### ISSUE THREAD

**Issue by Alhpa** [tweepy/tweepy#844]
Code:

```
import tweepy

consumer_key=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
consumer_secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
access_token=xxxxx-xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
access_token_secret=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

auth=tweepy.OAuthHandler(consumer_key,consumer_secret)

auth.set_access_token(access_token, access_token_secret)
client=tweepy.API(auth)
client.update_status("Its a new day")
```

I first got the error name xxxxxx not defined, referring to the consumer_key
I regenerated the consumer key and tried.
Then I got the error invalid syntax (referring to the consumer key).
I regenerated them again.
And the first error came back.
How do i get this to work?

**Comment by sullivat** [comment]
Double check that you are placing quotes around your keys and secrets, since they are strings.

I ran your code without quotes and got the same result, a syntax error. Once I added the quotes around the keys, your code worked and posted a status update: "Its a new day".

**Comment by romunov** [comment]
Also check that there are no spaces in the string. If you are double clicking the key/secret from the apps.twitter.com website, you may be introducing a space at the beginning/end of the string.

**Comment by deebaba01** [comment]
from twython import Twython
twitter = Twython(
    consumer_key,
    consumer_secret,
    access_token,
    access_token_secret
)





And am getting this error
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-3-7f641de7f943> in <module>
      1 from twython import Twython
      2 twitter = Twython(
----> 3     consumer_key,
      4     consumer_secret,
      5     access_token,

NameError: name 'consumer_key' is not defined
