### ISSUE TITLE
Replying to status doesn't work

### ISSUE THREAD

**Issue by Peteous** [tweepy/tweepy#846]
I wrote a twitter bot, and am trying to reply to a user who has tweeted with a certain hashtag. However, using the `update_status()` method with tweet id parameter just makes an original tweet, not a reply. 

Comment:
`api` is my `tweeps.api` object, and I have verified is properly authenticated (and works for other methods). `tweet

Code:
```
for tweet in tweepy.Cursor(api.search, q='#NASARMC').items(30):
	try:
		print('\nTweet with hashtag by: @' + tweet.user.screen_name)
		if not tweet.retweeted:
			tweet.retweet()
			print('Retweeted the tweet')
		else:
			print('Tweet already retweeted')
		if not tweet.favorited:
			tweet.favorite()
			print('Favorited the tweet')
		else:
			print('Tweet already favorited')
                # Reply to the tweet in question
		api.update_status("I see you're tweeting about NASA's RMC. Are you following @UNDRAPTOR yet?\nI'm a python.",tweet.id)
		print('Replied to the account')
		time.sleep(5)
	except tweepy.TweepError as e:
		print(e.reason)
	except StopIteration:
		break
```

**Comment by fitnr** [comment]
You'll find that people don't like unsolicited messages telling them to follow your account, and that Twitter tends to ban accounts that do that. I encourage you to find another way to build awareness for your bot. Folks on the #botALLY hashtag might be helpful.

**Comment by Peteous** [comment]
Thank you, @fitnr. I'll change up the reply text.

**Comment by Peteous** [comment]
To reply properly, the code should be changed to:
```
reply = "@" + tweet.user.screen_name + " Something something something reply"
api.update_status(reply, tweet.id)
```
