### ISSUE TITLE
More documentation

### ISSUE THREAD

**Issue by Peteous** [tweepy/tweepy#847]
Your documentation doesn't do a good job of explaining what is contained by each object type, both methods and variables. In particular, the `Status` object is something I can't find reference to anywhere.

**Comment by Cin316** [comment]
I second this.  I can't find any documentation on all of the objects the API methods return.  What fields and methods does the `User` class have?  Is this documented anywhere?

**Comment by fitnr** [comment]
The Twitter API docs are a great source of information over and above Tweepy's somewhat limited docs. The attributes and methods of the objects follow the Twitter API pretty closely. For instance, a `Status` object contains attributes for most or all of the top-level keys in a twitter Status object (see this [example response](https://dev.twitter.com/rest/reference/get/statuses/show/id)).

Running `help(foo)` and/or `dir(foo)` in the Python console is also a great way to get a information about an objects methods and attributes.

**Comment by Harmon758** [comment]
Duplicate of #720
