### ISSUE TITLE
"KeyError: 'status'" when sending direct messages

### ISSUE THREAD

**Issue by drgmrscb** [tweepy/tweepy#851]
Encountered repeatedly this error in tweepy/streaming.py/StreamListener, in the on_data() method`. (using tweepy==3.4.0)
Steps:
- have a stream listener running on the account which will make the tweets
- when the account posts a tweet or sends a dm, the on_data() method will be called with a parameter in the following format (this is for a tweet):
`{u'delete': {u'status': {u'user_id_str': u'123456', u'user_id': 123456, u'id': 9876554321, u'id_str': u'9876554321'}, u'timestamp_ms': u'1488186128661'}}`
In case of the `KeyError: 'status'` error, the call is for sending dms and the data passed as parameter will have the format:
`{u'delete': {u'direct_message': {u'user_id': 123456, u'id': 9876554321, u'id_str': u'9876554321'}}}`

**Comment by Harmon758** [comment]
This seems to have been an issue with User Streams, which have now been deprecated and retired.

See:
https://developer.twitter.com/en/docs/accounts-and-users/subscribe-account-activity/migration/us-ss-migration-guide.html

https://blog.twitter.com/developer/en_us/topics/tools/2018/enabling-all-developers-to-build-on-the-account-activity-api.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/announcing-more-functionality-to-improve-customer-engagements-on-twitter.html
https://blog.twitter.com/developer/en_us/topics/tools/2017/building-the-future-of-the-twitter-api-platform.html

https://twittercommunity.com/t/details-and-what-to-expect-from-the-api-deprecations-this-week-on-august-16-2018/110746
https://twittercommunity.com/t/reminder-site-streams-user-streams-and-legacy-dm-endpoints-will-be-sunset-august-16th/109482
https://twittercommunity.com/t/building-on-site-streams-user-streams-or-direct-messages-action-required-to-preserve-and-prevent-disruption-to-your-twitter-integration/105736
https://twittercommunity.com/t/date-for-full-deprecation-of-user-streams-site-streams-and-legacy-direct-message-api-endpoints/98734
