### ISSUE TITLE
How do I get latest direct messages?

### ISSUE THREAD

**Issue by cajuntechie** [tweepy/tweepy#854]
I'm building an application that requires access to direct messages. My application has the necessary permissions to access dm's. There will always be only a single dm in the inbox but I do not know what the ID of that message will be (at least initially).

I've tried this code:

direct_messages = api.direct_messages(0,1,5,True)
print direct_messages

But it's returning empty even though I know that there is indeed a direct message sitting there waiting. How do I handle this? Is there a way to grab a dm when you don't know its id?

**Comment by belloz** [comment]
Hi, use this pytohn lib: 
https://python-twitter.readthedocs.io/en/latest/twitter.html#module-twitter.api
There are DM's.

**Comment by Harmon758** [comment]
Twitter has now changed its Direct Message API endpoints.
I've made a branch (https://github.com/tweepy/tweepy/tree/dm-migration) and draft PR (#1228) that should fully support these changes.
Feel free to test it and report any issues you encounter.

With it, you should now be able to use the direct_messages/events/list endpoint using  `API.list_direct_messages` to do what you want.
Note though, that only Direct Messages within the last 30 days can be accessed with this endpoint.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.

**Comment by mofekayode** [comment]
is this still available?

**Comment by Harmon758** [comment]
#1228 has been merged and released as part of Tweepy v3.8.0.
