### ISSUE TITLE
Domain name has expired

### ISSUE THREAD

**Issue by eppingere** [tweepy/tweepy#856]
tweepy.org appears to have expired. 

<img width="1440" alt="screen shot 2017-03-06 at 8 12 03 pm" src="https://cloud.githubusercontent.com/assets/18016734/23637367/4e790e9a-02a9-11e7-8d98-a979e99d385b.png">

**Comment by hugovk** [comment]
Of course, same goes for http://docs.tweepy.org

**Comment by EmoryMap** [comment]
please renew domain name or post documentation on github! Thank you!!

**Comment by mwiens** [comment]
as the workaround for the docs you can look them up on [ReadTheDocs](http://tweepy.readthedocs.io)

**Comment by hugovk** [comment]
And the source of the [Read the Docs](http://tweepy.readthedocs.io/) is already on GitHub:

https://github.com/tweepy/tweepy/tree/master/docs

**Comment by Aaron1011** [comment]
Unfortunately, I still don't have full access to the project (notably, I don't control the tweepy.org registration). I'm working to get this resolved ASAP, and will update this issue as soon as I know more.

**Comment by Aaron1011** [comment]
The domain name has been renewed.
