### ISSUE TITLE
Need Documentation for Application-only authentication

### ISSUE THREAD

**Issue by sujcho** [tweepy/tweepy#857]
I found apis for Application-only authentication but there is no explanation about it. It will be helpful to add some simple explanation about **AppAuthHandler()** in Authentication Tutorial.

**Comment by ayushsharma84444** [comment]
[tweepy.pdf](https://github.com/tweepy/tweepy/files/1052353/tweepy.pdf)

**Comment by jstray** [comment]
That PDF does not have documentation for the AppAuthHandler class, which seems to be how this is implemented (according to (this thread)[https://github.com/tweepy/tweepy/issues/318] and (this code)[https://github.com/tweepy/tweepy/blob/cd46550b3ef068857f5de9c37bbdd0a72acb7462/tweepy/auth.py#L152])

**Comment by jstray** [comment]
[This post](https://cmry.github.io/notes/twitter-python) is almost like documentation. Includes the following code sample:

```
import tweepy

cons_key = 'XXXXXXXXXXXXXXXXX' # own key
cons_sec = 'XXXXXXXXXXXXXXXXX' # own key

auth = tweepy.AppAuthHandler(cons_key, cons_sec)
```
