### ISSUE TITLE
rpp no longer valid parameter

### ISSUE THREAD

**Issue by afhaque** [tweepy/tweepy#858]
For the `api.search` method, the `rpp` parameter has been replaced by `count`

![image](https://cloud.githubusercontent.com/assets/5855843/23820647/71b0610c-05eb-11e7-8d68-5816c5722391.png)

See the GET search/tweets reference on the Twitter docs:
https://dev.twitter.com/rest/reference/get/search/tweets

![image](https://cloud.githubusercontent.com/assets/5855843/23820664/f9d91506-05eb-11e7-923d-da549fa8f94e.png)

**Comment by Harmon758** [comment]
This has been updated with https://github.com/tweepy/tweepy/commit/5bd7431166a5714c0474aa69ee9f327095c3ccba / https://github.com/tweepy/tweepy/commit/069f688c1cfdb60605274c69bd1a9724732c845d (#1165).
Once there is a new Read the Docs build, the changes will be reflected in the documentation.
For that, see #1184.
