### ISSUE TITLE
how to Share a Tweet through Direct Messages?

### ISSUE THREAD

**Issue by wu860** [tweepy/tweepy#859]
how to Share a Tweet through Direct Messages?

**Comment by wu860** [comment]
share one page to people via DM private. send url to someone ,there is only url. But Share the page to people .there is some webpage description. Cannot send DM to people to be some description? How ?

**Comment by fitnr** [comment]
Sharing the tweet link `https://twitter.com/{username}/status/{tweetid}` will show a nicely formatted tweet in the recipient's DM list.

Please be careful automating DMs. It's easy to annoy and spam people with automated DMs.
