### ISSUE TITLE
How to unretweet?

### ISSUE THREAD

**Issue by Wooin** [tweepy/tweepy#867]

**Comment by r-best** [comment]
Use the destroy_status call
http://tweepy.readthedocs.io/en/v3.5.0/api.html#API.destroy_status

**Comment by Wooin** [comment]
Thanks for reply

But retweet without comment will not produce a new tweet , so I can't find the status of a retweet.

________________________________
发件人: r-best <notifications@github.com>
发送时间: 2017年4月28日 11:02:55
收件人: tweepy/tweepy
抄送: 吴青蓉; Author
主题: Re: [tweepy/tweepy] How to unretweet? (#867)


Use the destroy_status call
http://tweepy.readthedocs.io/en/v3.5.0/api.html#API.destroy_status

―

**Comment by Wooin** [comment]
Thanks for reply
But retweet without comment will not produce a new tweet , so I can't find the status id of a retweet.


________________________________
发件人: r-best <notifications@github.com>
发送时间: 2017年4月28日 11:02:55
收件人: tweepy/tweepy
抄送: 吴青蓉; Author
主题: Re: [tweepy/tweepy] How to unretweet? (#867)


Use the destroy_status call
http://tweepy.readthedocs.io/en/v3.5.0/api.html#API.destroy_status

―

**Comment by wodim** [comment]
Call `get_status` on the tweet you retweeted.

The tweet object you'll get will have a `current_user_retweet` attribute, which will have an `id` member. That's the id you have to call `destroy_status` with.

**Comment by tg12** [comment]
Doeskin work. no current_user_retweet returned.

**Comment by Harmon758** [comment]
`API.unretweet`, using the [`statuses/unretweet/:id endpoint`](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/post-statuses-unretweet-id), was added with #736 and released with Tweepy v3.6.0:
https://github.com/tweepy/tweepy/blob/cc3c8e7cae73d28b9a75edb7342f89f04da99702/tweepy/api.py#L263-L275
