### ISSUE TITLE
AttributeError: 'API' object has no attribute 'friend_ids'

### ISSUE THREAD

**Issue by sadhukhan** [tweepy/tweepy#872]
Using v3.5.0
http://docs.tweepy.org/en/v3.5.0/api.html#API.friends_ids

**Comment by bananabrick** [comment]
> friends_ids

Are you sure you just didn't mistype it?

**Comment by Harmon758** [comment]
As you linked, the method is `API.friends_ids`, not `API.friend_ids`.
