### ISSUE TITLE
api.update_status("DM") causes tweepy to try to send a direct message

### ISSUE THREAD

**Issue by iandioch** [tweepy/tweepy#873]
I was trying to send a tweet where the first word happened to be "DM", and found that the following code:

```python
api.update_status(status="dm")
```

results in the following error:

```
Traceback (most recent call last):
  File "dm_test.py", line 19, in <module>
    main()
  File "dm_test.py", line 16, in main
    api.update_status(status="dm")
  File "/usr/local/lib/python3.5/dist-packages/tweepy/api.py", line 194, in update_status
    )(post_data=post_data, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tweepy/binder.py", line 245, in _call
    return method.execute()
  File "/usr/local/lib/python3.5/dist-packages/tweepy/binder.py", line 229, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
tweepy.error.TweepError: [{'code': 151, 'message': "There was an error sending your message: You can't send a direct message without a user!."}]
```

On further inspection,

```python
api.update_status(status="dm iandioch hi")
```
results in my account receiving a direct message "hi" from this account.

This may be intended behaviour (although with strange intentions?). If so, I don't know how to go about sending a status with the first word being "dm", and [the docs](http://tweepy.readthedocs.io/en/v3.5.0/api.html#API.update_status) do not mention anything about this behaviour. What's going on?

Running python 3.5.2, and pip tells me I have `tweepy (3.5.0)` installed.

**Comment by fitnr** [comment]
This is a Twitter [text command](https://support.twitter.com/articles/14020), a relic of its origins as a texting service. There's nothing Tweepy can do about it, you'll just have to rephrase your tweets.

**Comment by iandioch** [comment]
I was wondering if there was something funny like that going on. Thanks for getting back to me!
