### ISSUE TITLE
Questions and multiple Error

### ISSUE THREAD

**Issue by shassanin** [tweepy/tweepy#876]
Hi guys!

My actual code of tweepy is:

```
from tweepy.streaming import StreamListener

from tweepy import OAuthHandler

from tweepy import Stream

import json

access_token = "CENSORED"

access_token_secret = "CENSORED"

consumer_key = "CENSORED"

consumer_secret = "CENSORED"



class StdOutListener(StreamListener):
    def on_data(self, ecbdata):



        tweet = json.loads(ecbdata)

        created_at = tweet["created_at"]

        id_str = tweet["id_str"]

        text = tweet["text"]

        coordinates = tweet["coordinates"]

        obj = {"created_at": created_at, "id_str": id_str, "text": text,"coordinates": coordinates }

        tweetind = collection.insert_one(obj).inserted_id

        print (obj)

        return True

        def on_error(self, status):
            print (status)


if __name__ == '__main__':



    l = StdOutListener()

    auth = OAuthHandler(consumer_key, consumer_secret)

    auth.set_access_token(access_token, access_token_secret)

    stream = Stream(auth, l)


  

    from pymongo import MongoClient

    client = MongoClient()

    client = MongoClient('localhost', 27017)

    db = client['twitter_ecb']

    collection = db['twitter_ecb']


stream.filter(track=['ecb'])
```

I collect the data in MongoDB. For programing with Python i use Python3 in combination with the IDE PyCharm by JetBrains.

When i run this code, python console collects just one tweet but then it stops with following messages:

> Traceback (most recent call last):
>   File "C:/Users/Salah/PycharmProjects/TwitterData/tweets.py", line 76, in <module>
>     stream.filter(track=['ECB'])
>   File "C:\Users\Salah\AppData\Local\Programs\Python\Python36\lib\site-packages\tweepy-3.6.0-py3.6.egg\tweepy\streaming.py", line 450, in filter
>   File "C:\Users\Salah\AppData\Local\Programs\Python\Python36\lib\site-packages\tweepy-3.6.0-py3.6.egg\tweepy\streaming.py", line 364, in _start
>   File "C:\Users\Salah\AppData\Local\Programs\Python\Python36\lib\site-packages\tweepy-3.6.0-py3.6.egg\tweepy\streaming.py", line 297, in _run
>   File "C:\Users\Salah\AppData\Local\Programs\Python\Python36\lib\site-packages\six.py", line 686, in reraise
>     raise value
>   File "C:\Users\Salah\AppData\Local\Programs\Python\Python36\lib\site-packages\tweepy-3.6.0-py3.6.egg\tweepy\streaming.py", line 266, in _run
>   File "C:\Users\Salah\AppData\Local\Programs\Python\Python36\lib\site-packages\tweepy-3.6.0-py3.6.egg\tweepy\streaming.py", line 323, in _read_loop
> tweepy.error.TweepError: Expecting length, unexpected value found
> 
> Process finished with exit code 1

What am i doing wrong? Or is it just a tweepy bug which needs a workaround to fix it? And if yes: How do i fix it?

My second question is how i search for combinations in tweets. I try to look for tweets which contain for example: ecb and exit. Is this the right code? 

`stream.filter(track=['ecb exit'])`

And if i search for multiple combinations, will this code do it?
`stream.filter(track=['ecb exit', 'ecb taper', 'ecb tapering', 'draghi taper', 'draghi tapering', 'draghi exit'])
`

best regards

**Comment by ime38** [comment]
Same issue when I use filter by keyword (aka track[...]) but when I only filter by locations (aka locations=[...]), I get NO problems.

Why?

**Comment by Harmon758** [comment]
Closing in favor of #892 

Regarding your question:
> My second question is how i search for combinations in tweets. I try to look for tweets which contain for example: ecb and exit. Is this the right code?
> 
> `stream.filter(track=['ecb exit'])`
> 
> And if i search for multiple combinations, will this code do it?
> `stream.filter(track=['ecb exit', 'ecb taper', 'ecb tapering', 'draghi taper', 'draghi tapering', 'draghi exit'])`

Yes.
See https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators for more information.
