### ISSUE TITLE
404 stream api 

### ISSUE THREAD

**Issue by YTMark** [tweepy/tweepy#879]
#when I use the tweepy stream api  below, it returns 404 .

#Import the necessary methods from tweepy library
import tweepy
from tweepy.streaming import StreamListener
from tweepy import OAuthHandler
from tweepy import Stream

#Variables that contains the user credentials to access Twitter API 
access_token = “×××"
access_token_secret = "×××"
consumer_key = "×××"
consumer_secret = "×××"

class MyStreamListener(tweepy.StreamListener):

    def on_status(self, status):
        print(status.text)
    def on_error(self, status_code):
        print status_code
        if status_code == 420:
                #returning False in on_data disconnects the stream
            return False

if __name__ == '__main__':

    #This handles Twitter authetification and the connection to Twitter Streaming API
    auth = OAuthHandler(consumer_key, consumer_secret)
    auth.set_access_token(access_token, access_token_secret)
    # Creation of the actual interface, using authentication
    api = tweepy.API(auth)
    myStreamListener = MyStreamListener()
    myStream = tweepy.Stream(auth = api.auth, listener=myStreamListener)
    myStream.filter(track=['python'])

**Comment by weehowe-z** [comment]
Try to bypass the GFW in China

**Comment by Harmon758** [comment]
This simply means you're unable to connect to the Twitter API endpoint.
This is an issue with your connection to Twitter rather than an issue with Tweepy.

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
