### ISSUE TITLE
retrieve replies of tweets

### ISSUE THREAD

**Issue by mar02500** [tweepy/tweepy#880]
I am using tweepy API in my python code to retrieve some tweets and replies. I used api.search to get replies of a tweet. but it only returns the replies of first tweet. I can not change the tweet id in that function, so it can retrieve replies. here is that part of my code:

`query = 'to:'+ uid
    number_of_replies=input("number of replies to retrieve:")
    for results in tweepy.Cursor(self.api.search, q=query , since_id=tid).items(int(number_of_replies)):
        if str(results.in_reply_to_status_id_str)==tid:
           print(results.text)`

how can I fix this? is there any way to add since_id to the query??

**Comment by Harmon758** [comment]
> it only returns the replies of first tweet

I'm not sure what you mean. You're printing replies to the Tweet with an ID matching whatever `tid` is.

> is there any way to add since_id to the query?

You're already using the `since_id` parameter: `since_id=tid`

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
