### ISSUE TITLE
Document how to get *pinned* Tweet

### ISSUE THREAD

**Issue by alexellis** [tweepy/tweepy#888]
The docs, code and examples repo make no mention of *pinned* or *pin* for Tweets.

Please could you document or explain the strategy for fetching a pinned Tweet from a user with Tweepy?

Thanks

**Comment by Harmon758** [comment]
This is not something that is accessible through Twitter's API.
See https://twittercommunity.com/t/access-a-pinned-tweet/93721 and https://twittercommunity.com/t/access-pinned-tweet-programatically/87440.
