### ISSUE TITLE
passing include_email parameter to verify_credentials() function

### ISSUE THREAD

**Issue by kssudheesh** [tweepy/tweepy#890]
Up on using
```
api = tweepy.API(auth)
response = api.verify_credentials(include_email=True)
``` 
 response dont have email of user in it. 

Have  checked 'Request email addresses from users' box in additional permissions tab. And authenticating user have email verified account.Tried by authenticating with different users. email is not returning for any user. But other details are returned in User object like screenname, id etc.

**Comment by tyewang** [comment]
@kssudheesh and anyone else that stumbles on this:
Do `include_email='true'`

It looks like tweepy simply sticks whatever you pass as `include_email` into the query string. Twitter will not correct respond to `True`.

**Comment by osastro** [comment]
Hello please help how can I use the verify_credencial to get users email
