### ISSUE TITLE
JSON decode issue while parsing few tweet streams.

### ISSUE THREAD

**Issue by nirajKpanda** [tweepy/tweepy#898]
Hi, I am getting following error while converting the tweet to json in few tweet streams. I have tried many fixes like enode('utf-8')/custom decode class, but unable to find a perfect fix for this issue.This issue is forcing me to avoid many valuable tweet streams, while analyzing them to calculate the business insights post stream collection logic. 

Traceback (most recent call last):
  File "sentiment_eval.py", line 70, in <module>
    tweet = json.loads(line)
  File "C:\Users\niraj.kumar.panda\AppData\Local\Programs\Python\Python36-32\lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "C:\Users\niraj.kumar.panda\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\niraj.kumar.panda\AppData\Local\Programs\Python\Python36-32\lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

It would be a great help, if this can be addressed in a quicker span.

Thanks.

**Comment by hackheera** [comment]
If that's still the case, when you generate the json file, instead of `status._json` or any `_json` attribute, use `json.dumps(status._json)`.
Which implies of course that you imported : 
`import json`

hope it helps

**Comment by Harmon758** [comment]
This issue isn't actionable without knowing what `line` is and where it's from.
Are you using the `_json` attribute of a Status object?

For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
