### ISSUE TITLE
Get Tweepy.Cursor cursor position

### ISSUE THREAD

**Issue by pabloriera** [tweepy/tweepy#899]
Hi, I wonder if there is a way to grab the current cursor position when using tweepy.Cursor,
I can start from a cursor position by passing that argument, but I don't know how to get the current position. 

`for page in tweepy.Cursor(api.followers_ids,id=uset_id,cursor=1568044909443443455).pages():
      something(page)`

The thing is that sometimes I got this exception:

> 'Connection aborted.', ConnectionResetError(104, 'Connection reset by peer')

and I want to be able to start the cursor again from the position it left over. Is this possible?

**Comment by Harmon758** [comment]
If the pagination is by cursor, then the iterator you're using is a CursorIterator returned by `Cursor.pages`:
https://github.com/tweepy/tweepy/blob/8ce6e8ce2591f3d14547851552524c624e1373a3/tweepy/cursor.py#L11-L31  In which case, you can use the `prev_cursor` and `next_cursor` attributes of the CursorIterator:
https://github.com/tweepy/tweepy/blob/8ce6e8ce2591f3d14547851552524c624e1373a3/tweepy/cursor.py#L61-L68
