### ISSUE TITLE
unable to send media on DM

### ISSUE THREAD

**Issue by bigpythonimish** [tweepy/tweepy#901]
So I successfully uploaded media using tweepy, and made a new method in API object to send media as an attachment in DM.
This is the method:
@property
    def send_media(self):
        """ :reference: https://dev.twitter.com/rest/reference/post/direct_messages/new
            :allowed_param:'user', 'screen_name', 'user_id', 'text'
        """
        return bind_api(
            api=self,
            path='/direct_messages/new.json',
            method='POST',
            payload_type='media',
            allowed_param=['user', 'screen_name', 'user_id', 'text','type','media_id'],
            require_auth=True
        )
    
I call this : 
api.send_media(user_id =status.direct_message['sender_id'], text =response, attachment={'type':'media','media_id': mediaID})

after sending message i get this response in my terminal.

Media(_api=, recipient_id_str=u'2956391868', sender={u'follow_request_sent': False, u'has_extended_profile': False, u'profile_use_background_image': True, u'default_profile_image': False, u'id': 106111046, u'profile_background_image_url_https': u'https://abs.twimg.com/images/themes/theme15/bg.png', u'verified': False, u'translator_type': u'none', u'profile_text_color': u'333333', u'profile_image_url_https': u'https://pbs.twimg.com/profile_images/839688948360216576/95sFtYJs_normal.jpg', u'profile_sidebar_fill_color': u'C0DFEC', u'entities': {u'description': {u'urls': []}}, u'followers_count': 38, u'profile_sidebar_border_color': u'A8C7F7', u'id_str': u'106111046', u'profile_background_color'.......

Whats wrong?

**Comment by Harmon758** [comment]
I'm not sure what you mean. It seems to have successfully sent and returned the Media object?
Regardless, this is issue is now stale due to #1081.
For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
