### ISSUE TITLE
Tweepy got TypeError: argument of type 'int' is not iterable

### ISSUE THREAD

**Issue by toshiro92** [tweepy/tweepy#902]
Hi !

I am experiencing an issue with the Tweepy function `search` and `search_users`: When I launch my little piece of code below:

    auth = tweepy.auth.OAuthHandler(creds["consumer_key"], creds["consumer_secret"])
    auth.secure = True
    auth.set_access_token(creds["access_token"], creds["access_token_secret"])
    
    api = tweepy.API(auth, wait_on_rate_limit=True,wait_on_rate_limit_notify=True,retry_count=10,retry_delay=5,retry_errors=5)
    #The error is the same for 'search_users & 'search'
    res = api.search_users(q="Hello",count=10)
    res = api.search(q="Hello",count=10)

It gives me the following error:

    Traceback (most recent call last):
    File "/projects/twitter/twitter/common/search.py", line 9, in searchUser
    res = api.search_users(q="Hello",count=10)
    File "/projects/twitter/lib/python3.5/site-packages/tweepy-3.6.0-py3.5.egg/tweepy/binder.py", line 250, in _call
    File "/projects/twitter/lib/python3.5/site-packages/tweepy-3.6.0-py3.5.egg/tweepy/binder.py", line 214, in execute
    
    TypeError: argument of type 'int' is not iterable

Note: I am currently using `virtualenv`, but I don't think the issue is related to.

Note 2: The issue is the same on Tweepy versions `3.2`, `3.5` & `3.6`

Note 3: I've removed the count argument just in case, without any change

Is this an issue or I did something wrong ?

Already raised a Stackoverflow for info: https://stackoverflow.com/questions/44209542/tweepy-got-typeerror-argument-of-type-int-is-not-iterable

**Comment by Prakash2403** [comment]
@toshiro92  Is this error raised instantly or some time after starting the script?

**Comment by toshiro92** [comment]
Hi @Prakash2403, this error is raised instantly

**Comment by Prakash2403** [comment]
Hey @toshiro92 , Sorry for late response. There is no error in code you posted above. I have tested it on my machine and it ran properly, returning a list of status object. 

Most probably, after this piece of code, accidentally you have assigned `res` an integer value, hence it is showing integer object is not iterable.

**Comment by Harmon758** [comment]
From the full traceback, you'll see that the line in question is:
https://github.com/tweepy/tweepy/blob/d240f2083ae1f47f6e6a3c047042ae8eadc0f925/tweepy/binder.py#L214 You set `retry_errors=5`, when initializing the [`API`](https://tweepy.readthedocs.io/en/latest/api.html#API).
`retry_errors` should instead be an iterable of HTTP status codes to retry for.
