### ISSUE TITLE
change streaming example method to "file.write(data)" then long time the RAM will be used up, computer stops working 

### ISSUE THREAD

**Issue by binghe2727** [tweepy/tweepy#903]
I use this example streaming code.https://github.com/tweepy/tweepy/blob/master/examples/streaming.py

then
in my work, i write the data to a file like this:

    def on_data(self, data):
        with open('data.txt', 'a')as f:
           
            f.write(data+'\n')
        return True

then after two days, the computer cannot work, because the ram has been used up.

Has anyone ever encountered this problem why the RAM can be used up.
Because I want to collect the tweets for a long time, but the RAM will be used up in two days,
I have to reset my computer to collect tweets.

Thanks for your viewing .Looking for your kindly solutions.

**Comment by ytho** [comment]
Try closing the file object after you write to it.
I know the `with open() as f` automatically does it, but depending on the implementation it may not close it.

**Comment by binghesam** [comment]
@ytho thanks, I will try it immediately, Again ,with many thanks.

**Comment by binghesam** [comment]
@ytho  I have tested it by adding the f.close. but, it does not work, the RAM will increasingly grow and finally the computer stops working.

**Comment by Harmon758** [comment]
This is stale now, as streaming has been significantly reworked, and streaming with Twitter API v1.1 has been deprecated.
