### ISSUE TITLE
Unfollowing people not following me ... script not working

### ISSUE THREAD

**Issue by samayo** [tweepy/tweepy#907]
So, I have been at this for days and it seems that there is no way to unfollow people who are not following me..
```python
twitter_handle = "MyTwitterName" 

friends_ids = api.friends_ids(api.me().id)

for follower in tweepy.Cursor(api.followers, id=twitter_handler).items():
    if follower.id not in friends_ids:
        api.destroy_friendship(follower)
```

I have tried many variations of the above script bit it does not work.

**Comment by Peerdix** [comment]
I saw you are using tweepy as a python lib. i spontanly wrote this using python 2.7 You don't have to seperate the dict. key from the main file, just a matter style. I did a sleep method from lib "time" to prevent twitter from spotting you as a bot. 

If you have any questions, just ask. 

#! /usr/bin/python
import tweepy
import random
from keys import keys
import time

SCREEN_NAME = keys['screen_name']
CONSUMER_KEY = keys['consumer_key']
CONSUMER_SECRET = keys['consumer_secret']
ACCESS_TOKEN = keys['access_token']
ACCESS_TOKEN_SECRET = keys['access_token_secret']

auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
auth.set_access_token(ACCESS_TOKEN, ACCESS_TOKEN_SECRET)
api = tweepy.API(auth)

followers = api.followers_ids(SCREEN_NAME)
friends = api.friends_ids(SCREEN_NAME)

for f in friends:
    if f not in followers:
        print f
        print "Unfollow {0}".format(api.get_user(f).screen_name)
        api.destroy_friendship(f)
        nsecs=random.randint(5,25)
        time.sleep(nsecs)
    else:
        continue


##keys.py

keys = dict(
    screen_name = 'Twitter handle',
    consumer_key =          '',
    consumer_secret =       '',
    access_token =          '',
    access_token_secret =   '',
)

**Comment by samayo** [comment]
Thanks, this does seem to work. I will have to see if at the end if it is removing only the people unfollowing me back or just everyone. Also, trying to randomize api requests is not really required. As long as you don't exceed the rate limit it does not matter if you follow/unfollow people at 1 sec interval. I don't think twitter cares about that

**Comment by samayo** [comment]
Okay, I just took a look at the script and it seems the script unfollowed everyone.. Both the people I am following but not following back, and those also following me

**Comment by yogeshdmca** [comment]
Take a Look Of this code , It will work for you , Tested Many times. 
[you can take a look of code at](https://github.com/yogeshdmca/twitter_bot_python)
```
import tweepy
import json
from time import sleep
from re import search
from itertools import cycle
from random import shuffle
from datetime import datetime, timedelta

CONSUMER_KEY = ""
CONSUMER_SECRET = ""
ACCESS_TOKEN = ""
ACCESS_SECRET = ""
screen_name = ""
MAX_UNFOLLOW = 10
class TwitterBot(object):
    """docstring for TwitterBot"""
    def __init__(self):
        # authorization from values inputted earlier, do not change.
        auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
        auth.set_access_token(ACCESS_TOKEN, ACCESS_SECRET)
        self.api = tweepy.API(auth)
        self.followers = self.api.followers_ids(screen_name)
        self.following = self.api.friends_ids(screen_name)
        self.MAX_UNFOLLOW = MAX_UNFOLLOW

    def unfollow_back_who_not_folow_me(self):
        # function to unfollow users that don't follow you back.
        print('Starting to unfollow users...')
        # makes a new list of users who don't follow you back.
        non_mutuals = set(self.following) - set(self.followers)
        total_followed = 0
        for f in non_mutuals:
            try:
                # unfollows non follower.
                self.api.destroy_friendship(f)
                total_followed += 1
                if total_followed % 10 == 0:
                    print(str(total_followed) + ' unfollowed so far.')
                if total_followed==self.MAX_UNFOLLOW:
                    print('unfollow 100 users now, exiting it')
                    exit()

                print('Unfollowed user. Sleeping 15 seconds.')
                sleep(15)
            except (tweepy.RateLimitError, tweepy.TweepError) as e:
                self.error_handling(e)
        print(total_followed)
```

**Comment by TechVows** [comment]
A simple script to [easily Follow | Unfollow Twitter Followers | Unfollowers at once](https://www.techvows.com/follow-unfollow-all-twitter-followers/) works like a charm.

**Comment by ChadLei** [comment]
@yogeshdmca does your script unfollow people from the bottom of the list first? meaning unfollowing people from least to most recent

**Comment by PvrpleBlvck** [comment]
Well the easiest way to do this is by using counter

counter = 0
for friend in friends:
if friend not in followers:
counter += 1
api.destroy_friendship(friend)
if counter >= 10:
break

**Comment by PvrpleBlvck** [comment]
But if you wish to use a function .This might help

def process():
    api = get_twitter_api()
 
    followers = api.get_followers_ids(user_id="Pvrpleblvck")
    print("Followers", len(followers))
    friends = api.get_friends_ids(user_id="PvrpleBlvck")
    print("You follow:", len(friends))
 
    for friend in friends:
        if friend not in followers:
            api.destroy_friendship(friend)
