### ISSUE TITLE
get tweet impression

### ISSUE THREAD

**Issue by HjlSr** [tweepy/tweepy#910]
HI all. i wanna using tweepy api in my project . now i faced with new problem.
how can get impression of each tweet with tweepy?
i couldn't find suitable api for this.

**Comment by coyote-tango** [comment]
Twitter API only provides the 'raw' data, it doesn't give you more than that.  To get a rich information such as the ones you wanted unfortunately you have to do your own calculation.

**Comment by Harmon758** [comment]
Impressions for Tweets are only available through the [Engagement API](https://developer.twitter.com/en/docs/metrics/get-tweet-engagement/overview), which Tweepy does not support.
