### ISSUE TITLE
exception on streaming

### ISSUE THREAD

**Issue by shaljam** [tweepy/tweepy#911]
`File "/home/ali/.pyenv/versions/3.6.1/lib/python3.6/si
te-packages/tweepy/streaming.py", line 50, in on_data   
    data = json.loads(raw_data)                         
  File "/home/ali/.pyenv/versions/3.6.1/lib/python3.6/js
on/__init__.py", line 348, in loads                     
    'not {!r}'.format(s.__class__.__name__))            
TypeError: the JSON object must be str, bytes or bytearr
ay, not 'NoneType'`

**Comment by shaljam** [comment]
Using master branch fixes the problem.

**Comment by Harmon758** [comment]
Duplicate of #674.
