### ISSUE TITLE
User activity within the streaming API

### ISSUE THREAD

**Issue by PaulSec** [tweepy/tweepy#914]
Hello everyone, 

First of all, great work with Tweepy, that's an impressive project. 
Second of all, I'd like to know if that would be possible to have the full user activity in the streaming API? 
I'd like to track a specific user id and retrieve tweets (already possible), likes, follows and so on. I've been trying to do so for couple of hours and I didn't succeed. 

Cheers,

**Comment by skeletalbassman** [comment]
I've only recently used this package, but from looking at the source, there is a specification for a [userstream](https://github.com/tweepy/tweepy/blob/master/tweepy/streaming.py#L370) which might fit your use case. 

It's worth keeping in mind that Twitter eventually plans on [migrating](https://dev.twitter.com/webhooks/account-activity) their streams altogether under one API.

**Comment by PaulSec** [comment]
Nice, I never heard about it. 

However, I am looking for something like this for external accounts.

**Comment by skeletalbassman** [comment]
Right now, with Python 3.4 and tweepy 3.5, I'm able to stream a single user's tweets. However, when I do this, I will also receive any mentions or retweets that include the user's handle. 

Look into the `Stream.filter()` method for more about this. You'll see it accepts a `follow` parameter, where you can pass in a list of user IDs (as `str`). Like I said; however, you'll receive some extraneous information as well.

**Comment by clanctot** [comment]
Old thread but I am currently still searching for a way to do this WITHOUT returning extraneous details. If the user is popular but does not tweet much you end up wasting a considerable about of resources.

**Comment by AlexProfi** [comment]
maybe twitter_stream.userstream(replies='all', _with='user',async=True) ??

**Comment by Git2TheChoppa** [comment]
@clanctot I believe you do it like this: 
(after authenticating yourself)...

`user = api.user_timeline(id= 'whatever the id of user is.', count = 1)

class MyStreamListener(tweepy.StreamListener):
    def on_User(self, user):
        for tweet in user: 
            print(tweet.text)

myStreamListener = MyStreamListener()
myStream = tweepy.Stream(auth = api.auth, listener=myStreamListener) #tweepy has an error in api regarding this

myStream.filter(follow=['id of your user'])
`

Working on this myself right now, waiting for my target to tweet something to verify it works. Will update when I know for sure.

**Comment by Harmon758** [comment]
Unfortunately, streaming likes and follows for an external account is not something Twitter's API supports.

Note, User Streams have been deprecated and retired in favor of the new Account Activity API.
For Account Activity API support, see #1075.

@clanctot 
Unfortunately, there's no way to exclude retweets or replies from the statuses/filter endpoint/stream.
You'd have to use the enterprise [PowerTrack API](https://developer.twitter.com/en/docs/tweets/filter-realtime/overview/powertrack-api) instead.
See https://twittercommunity.com/t/why-does-streaming-api-mostly-return-tweets-with-rt/87325/2 and 
https://twittercommunity.com/t/any-method-to-filter-exclude-retweets-and-replies-in-any-stream-api-method/89967/2.

@Git2TheChoppa This does not exclude retweets or replies from being received and processed. See above.
For code block usage, see https://help.github.com/articles/creating-and-highlighting-code-blocks/.
