### ISSUE TITLE
api.search()  How to use filters like images and links. 

### ISSUE THREAD

**Issue by zoid-anurag** [tweepy/tweepy#915]
I want to search only those tweets that contain an image. The twitter documentation mentions use of operators as filters 
Link: https://dev.twitter.com/rest/public/search

If I use twitter search through browser the filter operators works. so if i search for "puppy filter: images" I get results with tweets containing text puppy and every tweet has an image.
The search url for API HTTP request is 
Link: https://twitter.com/search?src=typd&q=puppy%20filter%3Aimages

Please suggest any solution. I want to search for relevant tweets because of the rate limit rather than downloading a whole bunch and then filtering json file.

**Comment by Harmon758** [comment]
You can simply use those [standard search operators](https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators) in the [`API.search`](https://tweepy.readthedocs.io/en/latest/api.html#API.search) qeury, e.g.:
`api.search(q="puppy filter:images")`.
Note, the standard search operator `filter:` doesn't allow a space after the colon.
See https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets.
