### ISSUE TITLE
Muting user

### ISSUE THREAD

**Issue by alceal** [tweepy/tweepy#919]
When can we expect muting to be integrated into the API wrapper?

**Comment by argysamo** [comment]
Duplicate of #528 
Is anyone working on this one? 
Shall I try implement it and create a PR?

**Comment by antoinemcgrath** [comment]
Ability to mute has been added https://github.com/tweepy/tweepy/pull/1055
I hope my addition will be approved by admin with write access.__

**Comment by Harmon758** [comment]
Duplicate of #528
