### ISSUE TITLE
Please merge `Removed unicode() in filter_level for py3k supprt` into v3.5.0

### ISSUE THREAD

**Issue by xxx7xxxx** [tweepy/tweepy#924]
Within using streaming API of `tweepy` in python3.6.2, This bug https://github.com/tweepy/tweepy/issues/782 happened. After checking the source code, I found the master got a correct implementation: https://github.com/tweepy/tweepy/blob/c8e473ed7b939e09a485d0eaa2390554f009a56b/tweepy/streaming.py#L447
but the v3.5.0 didn't : 
https://github.com/tweepy/tweepy/blob/920f5c49c059c4ea7f16c7c4f070c484161525c3/tweepy/streaming.py#L442

So with using pip3 https://pypi.python.org/pypi/tweepy, it's a bug which I can not bypass.

**Comment by twirrim** [comment]
I just ran full belt in to this one too, any chance this can be shipped to pypi?

**Comment by Harmon758** [comment]
The fix for this, https://github.com/tweepy/tweepy/commit/09818085c0f8d259fff26b09a71f103ef53dd862, was released with Tweepy v3.6.0.
