### ISSUE TITLE
API.lists_all() returns only 100 lists

### ISSUE THREAD

**Issue by Alexeyisme** [tweepy/tweepy#925]
I guess it is caused by Twitter API pagination, but how to get 101'th and 102'th lists?
Tweepy docs are not covering API.lists_all():
http://docs.tweepy.org/en/v3.5.0/api.html#API.lists

**Comment by Harmon758** [comment]
`API.lists_all` was renamed from [`API.lists`](https://tweepy.readthedocs.io/en/latest/api.html#API.lists).
The documentation hasn't been updated yet to reflect this. See #821 and #822.
This is a limitation of Twitter API's [lists/list endpoint](https://developer.twitter.com/en/docs/accounts-and-users/create-manage-lists/api-reference/get-lists-list):
> A maximum of 100 results will be returned by this call. Subscribed lists are returned first, followed by owned lists. This means that if a user subscribes to 90 lists and owns 20 lists, this method returns 90 subscriptions and 10 owned lists. The `reverse` method returns owned lists first, so with `reverse=true`, 20 owned lists and 80 subscriptions would be returned. If your goal is to obtain every list a user owns or subscribes to, use [GET lists / ownerships](https://developer.twitter.com/rest/reference/get/lists/ownerships) and/or [GET lists / subscriptions](https://developer.twitter.com/rest/reference/get/lists/subscriptions) instead.

As explained, you should use [`API.lists_memberships`](https://tweepy.readthedocs.io/en/latest/api.html#API.lists_memberships) and/or [`API.lists_subscriptions`](https://tweepy.readthedocs.io/en/latest/api.html#API.lists_subscriptions) instead.
