### ISSUE TITLE
Inconsistent HTML entity behaviour between Status.text and SearchResult.text

### ISSUE THREAD

**Issue by pennersr** [tweepy/tweepy#93]
I've posted the following Tweet:

`"test twitter <api> & test © html entities"`

If I retrieve this tweet via Tweepy's home_timeline(), status.text equals:

`"test twitter &lt;api&gt; & test © html entities"`

Whereas if retrieved via search(), it shows up as:

`"test twitter &lt;api&gt; &amp; test © html entities"`

Note that the stand-alone "&" is converted to an &amp;.  IMHO, regardless of the underlying Twitter behavior, I feel the Tweepy API should present an equal result in both cases.

**Comment by Harmon758** [comment]
I'm unable to reproduce this now.
`API.home_timeline` now retreives a Status with the HTML encoded ampersand, as `API.search` still does:
`"test twitter &lt;api&gt; &amp; test © html entities"`
