### ISSUE TITLE
Time when one account started to follow another account

### ISSUE THREAD

**Issue by olesiastetsiuk** [tweepy/tweepy#938]
Hi, I was wondering is it possible to get the exact time when one account started to follow another.
api.show_friendship shows only details around connection, but no time.

**Comment by Harmon758** [comment]
This is not something that is accessible via Twitter's API.
See https://twittercommunity.com/t/is-it-possible-to-check-when-a-user-started-following-someone/12291, https://twittercommunity.com/t/followers-date/64133, https://twittercommunity.com/t/how-to-get-followers-following-date/84409, and https://twittercommunity.com/t/how-to-get-follower-start-following-date-in-twitter-api/100048.
