### ISSUE TITLE
Tweepy no longer supports DMs

### ISSUE THREAD

**Issue by JunksFiPenny** [tweepy/tweepy#940]
Hello All --

I use tweepy to update myself via twitter DM on status of computer processing done for my work.

Since last Friday, I now get message. Is this a tweepy problem OR is this a problem with my Twitter account? Any advice would be welcome. Solutions welcome too..

AMD 

Traceback (most recent call last):
  File "C:\CODE\notification.py", line 52, in <module>
    api.update_status(status = updateMessage)
  File "build\bdist.win32\egg\tweepy\api.py", line 194, in update_status
    )(post_data=post_data, *args, **kwargs)
  File "build\bdist.win32\egg\tweepy\binder.py", line 245, in _call
    return method.execute()
  File "build\bdist.win32\egg\tweepy\binder.py", line 229, in execute
    raise TweepError(error_msg, resp, api_code=api_error_code)
TweepError: [{u'message': u'There was an error sending your message: DM commands are no longer allowed!.', u'code': 151}]

**Comment by fitnr** [comment]
The error is coming from Twitter. It looks like they're [retiring the DM command codes](https://twittercommunity.com/t/retiring-legacy-dm-commands-on-the-standard-tweet-api/86653). Try sending your direct message with `api.send_direct_message(screen_name=user, text='Hello World')`.

**Comment by coyote-tango** [comment]
Hi, I tried  @fitnr  solution and It worked, I was able to send a DM using `api.send_direct_message()`.
