### ISSUE TITLE
Add currenly missing parameter to Api.search method ---- result_type

### ISSUE THREAD

**Issue by dmpe** [tweepy/tweepy#941]
https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets

`result_type` = Specifies what type of search results you would prefer to receive. The current default is “mixed.” 

Does anybody think it is possible to add this ? Would PR be accepted ?
Thanks.

**Comment by fitnr** [comment]
It looks like the parameter is accepted in `api.search()`.
https://github.com/tweepy/tweepy/blob/master/tweepy/api.py#L1204

**Comment by dmpe** [comment]
ok, big thanks @fitnr 
but documentation is then not updated :( 
http://docs.tweepy.org/en/v3.5.0/api.html#help-methods

**Comment by Harmon758** [comment]
`API.search` has accepted the `result_type` parameter since Tweepy 1.7 (https://github.com/tweepy/tweepy/commit/c6fa5a5eaa6d22e7d01e539b4a251a1539a1ce2b).
For updating the documentation, see #1199.
