### ISSUE TITLE
Add tweet_mode enabled to live stream

### ISSUE THREAD

**Issue by Dmon1Unlimited** [tweepy/tweepy#945]
Is it possible to try and enable tweet_mode=‘enabled’ for the livestream functionality?

I.e this would generate tweets under ”full_text” not ”text”

Justification for this: due to twitters new tweet functionality, some tweets pulled will be truncated

**Comment by Dmon1Unlimited** [comment]
I believe tweet mode can be used in the non-live scripts, but then shouldn’t the same be applied for livestream too?

**Comment by Harmon758** [comment]
You should be able to use something like `status.extended_tweet["full_text"]` for the streaming APIs.
See #935 and https://developer.twitter.com/en/docs/tweets/tweet-updates.

**Comment by Harmon758** [comment]
Extended mode is only available for Twitter's standard REST APIs.

I've added [a section in the documentation that covers extended Tweets](https://tweepy.readthedocs.io/en/latest/extended_tweets.html) and supplements Twitter's documentation which should clarify the issue.
