### ISSUE TITLE
api.get_status Method miss Get Reply Count and Get Quote Count

### ISSUE THREAD

**Issue by willkwolf** [tweepy/tweepy#946]
This method is not presenting a bug, but require an update. Thank you a lot.

**Comment by Harmon758** [comment]
Tweepy's [`API.get_status`](https://tweepy.readthedocs.io/en/latest/api.html#API.get_status) method simply returns the data returned by a call to the Twitter API's [`statuses/show/:id` endpoint](https://developer.twitter.com/en/docs/tweets/post-and-engage/api-reference/get-statuses-show-id).
Per the [Tweet object documentation](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object) regarding the `reply_count` and `quote_count` attributes:
> Note: This object is only available with the Premium and Enterprise tier products.
