### ISSUE TITLE
api.update_status: 'str' object has no attribute 'apply_auth'

### ISSUE THREAD

**Issue by wormmoon** [tweepy/tweepy#950]
Unexpected error when using api.update_status
[code](https://github.com/wormmoon/randomweatherbot/blob/master/bot.py)

Error:
```Traceback (most recent call last):
  File "bot.py", line 144, in <module>
    api.update_status(status=tweet)
  File "build/bdist.macosx-10.12-intel/egg/tweepy/api.py", line 194, in update_status
  File "build/bdist.macosx-10.12-intel/egg/tweepy/binder.py", line 250, in _call
  File "build/bdist.macosx-10.12-intel/egg/tweepy/binder.py", line 177, in execute
AttributeError: 'str' object has no attribute 'apply_auth'```

**Comment by fitnr** [comment]
The error is due to the string `'auth'` being passed when the API is created.
Changing [line 21](https://github.com/wormmoon/randomweatherbot/blob/ccb60ef2b2cae0ff911392223a4ade623c1714dd/bot.py#L21) of your code should fix the issue:
```
api = tweepy.API(auth)
```

**Comment by wormmoon** [comment]
Ah, thank you yes that worked. I wrote this code a while ago and it used to work but it seems to need a few updates.

And thanks I'll check it out!
