### ISSUE TITLE
verify_credentials api

### ISSUE THREAD

**Issue by Allan-Nava** [tweepy/tweepy#952]
Hi,

is possibile set an optional parameters, **include_email**?

Thanks

**Comment by tyewang** [comment]
It looks like that was fixed in 3.4.0 (https://github.com/tweepy/tweepy/releases/tag/v3.4.0):

Allow include_email param for verify_credentials API

**Comment by Allan-Nava** [comment]
@tyewang thanks!

**Comment by Harmon758** [comment]
This was indeed already added with https://github.com/tweepy/tweepy/commit/e4a08b10fb4e441dcac6462276258d8b18064537 (#623) and released with Tweepy v3.4.0:
https://github.com/tweepy/tweepy/blob/cc3c8e7cae73d28b9a75edb7342f89f04da99702/tweepy/api.py#L637-L652
