### ISSUE TITLE
tweepy.error.TweepError: [{u'message': u'Bad Authentication data.', u'code': 215}]

### ISSUE THREAD

**Issue by nowosielsky** [tweepy/tweepy#954]
Hello.
I get this error - "tweepy.error.TweepError: [{u'message': u'Bad Authentication data.', u'code': 215}]". I would be really grateful for helping me at fixing that issue.

**Comment by fitnr** [comment]
This error means that Twitter doesn't recognize the keys you're sending. The code in the [Hello Tweepy](http://docs.tweepy.org/en/v3.5.0/getting_started.html#api) section of the docs is the simplest example of getting things set up. Also, make sure that the [twitter application](https://apps.twitter.com) you've set up has the proper permissions.

**Comment by nowosielsky** [comment]
Thank you. I will check this out.

**Comment by shriganesh-kolhe** [comment]
I had the same problem. Regenerating the Keys and tokens solved the problem.

**Comment by magdyrezk9** [comment]
> I had the same problem. Regenerating the Keys and tokens solved the problem.

how please

**Comment by Harmon758** [comment]
Please don't necrobump old closed issues.
See https://developer.twitter.com/en/docs/basics/apps/guides/the-app-management-dashboard.
