### ISSUE TITLE
Cannot convert emoji when streaming tweets

### ISSUE THREAD

**Issue by clityaw** [tweepy/tweepy#961]
I am trying to get tweets from streaming but whenever an emoji comes in, the stream stops. I've tried to encode(utf-8) but however it does not display the emoji but writes something like \xf0\x9f\x99\x83' 

Can someone help me please. I'm new to this. Really urgent!!

**Comment by erolrecep** [comment]
I hope it's not too late. Twitter streams emojis in byte format. So "\xf0\x9f\x99\x83" this is byte format of an emoji. You can check emoji's unicode conversion table [here](https://apps.timwhitlock.info/emoji/tables/unicode). I hope this can fix your issue.

**Comment by clityaw** [comment]
I got it working already by encoding it to unicode thanks!
