### ISSUE TITLE
Streaming documentation

### ISSUE THREAD

**Issue by clu8** [tweepy/tweepy#962]
Twitter appears to have taken down the documentation for the Stream API down: https://dev.twitter.com/streaming/overview (linked from http://tweepy.readthedocs.io/en/v3.5.0/streaming_how_to.html) Looking at Twitter's API docs I can't seem to find any sort of documentation on a push API. Given this, what is the future status of the Tweepy streaming component?

**Comment by matsavage** [comment]
https://developer.twitter.com/en/docs/tweets/filter-realtime/overview

Isn't this the streaming API?

**Comment by clu8** [comment]
You're right - my bad. Thanks for the clarification
