### ISSUE TITLE
best way get all followers of a user

### ISSUE THREAD

**Issue by gwuah** [tweepy/tweepy#964]
Hey,
So i've been trying to get a list of all followers of a user who has less than 600 followers.
but anytime i check the length of followers after the loop stops, i get <=320 instead of 600. 
Any help?

https://gist.github.com/gwuah/acabb5c59b2b883dd082c54feb174678

**Comment by PandaWhoCodes** [comment]
https://gist.github.com/PandaWhoCodes/46f58fdead71f4c71453d9ed1e21adf8
Try this.

**Comment by gwuah** [comment]
Thanks @PandaWhoCodes

**Comment by Harmon758** [comment]
The [followers/list Twitter API endpoint](https://developer.twitter.com/en/docs/accounts-and-users/follow-search-get-users/api-reference/get-followers-list) is paginated, with a default of 20 and up to a maximum of 200 users returned per page. You can iterate over these paginated results using the `cursor` parameter.
With Tweepy, you can also iterate over them by using [`API.followers`](https://tweepy.readthedocs.io/en/latest/api.html#API.followers) with a [Cursor](https://tweepy.readthedocs.io/en/latest/cursor_tutorial.html) object.
