### ISSUE TITLE
Tweets are being truncated to 140 symbols

### ISSUE THREAD

**Issue by iskhacov** [tweepy/tweepy#967]
Hi!

I am using tweepy to search tweets and I've just faced a problem that the tweets are being truncated to 140 symbols. Is there a way to change the behaviour or add a parameter to `api.search()` method?

**Comment by yinleon** [comment]
see: https://github.com/tweepy/tweepy/issues/935

**Comment by Flyer4109** [comment]
@iskhacov 
Hello,
Did tweet_mode="extended" work for you in the search API?

**Comment by Keramatfar** [comment]
It works for me.

**Comment by Harmon758** [comment]
Yes, you can simply use extended mode.
See [Twitter’s Tweet updates documentation](https://developer.twitter.com/en/docs/tweets/tweet-updates), supplemented by [Tweepy's documentation on extended Tweets](https://tweepy.readthedocs.io/en/latest/extended_tweets.html).
