### ISSUE TITLE
api search parameter from invalid syntax

### ISSUE THREAD

**Issue by duncangh** [tweepy/tweepy#968]
per the api.search docstring, the parameters allowed are:

```
:allowed_param:'q', 'lang', 'locale', 'since_id', 'geocode',
 'max_id', 'since', 'until', 'result_type', 'count',
  'include_entities', 'from', 'to', 'source'
```

yet from is a python reserved word, so when I call api.search with from as a kwarg, python throws a SyntaxError

```
api.search(q="BREAKING: ", from='ap')


File "<ipython-input-18-f62b69f5cbc8>", line 1
    api.search(q="BREAKING: ", from='ap')
                                  ^
SyntaxError: invalid syntax
```

Query in the advanced search on twitter website:

"BREAKING:" from:ap

How can I replicate this via tweepy?

**Comment by fitnr** [comment]
Use the '**' [argument unpacking operator](https://docs.python.org/3.6/tutorial/controlflow.html#unpacking-argument-lists) as a workaround:
````python
params = {'q': 'BREAKING', 'from': 'ap'}
api.search(**params)
````

**Comment by duncangh** [comment]
This works -- thanks for clarifying!
