### ISSUE TITLE
Non complete results

### ISSUE THREAD

**Issue by Keramatfar** [tweepy/tweepy#969]
When i use Tweepy to search Tweets it get for me some number much smaller than real results can be seen in search of Twitter itself. I use cursors but it get me for example 122 tweets while there are a lot of tweets in reality. What is the problem?

**Comment by Harmon758** [comment]
If you're using the standard search, note, from Twitter's API documentation:

> The Twitter Search API searches against a sampling of recent Tweets published in the past 7 days.
> 
> Before digging in, it’s important to know that the standard search API is focused on relevance _and not completeness_. This means that some Tweets and users may be missing from search results. If you want to match for completeness you should consider the [premium](https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets) or [enterprise](https://developer.twitter.com/en/docs/tweets/search/api-reference/premium-search) search APIs.

https://developer.twitter.com/en/docs/tweets/search/overview/standard

> Please note that Twitter's search service and, by extension, the Search API is not meant to be an exhaustive source of Tweets. Not all Tweets will be indexed or made available via the search interface.

> Keep in mind that the search index has a 7-day limit. In other words, no tweets will be found for a date older than one week.

https://developer.twitter.com/en/docs/tweets/search/api-reference/get-search-tweets.html

> The Search API is not complete index of all Tweets, but instead an index of recent Tweets. The index includes between 6-9 days of Tweets.

https://developer.twitter.com/en/docs/tweets/search/guides/standard-operators
