### ISSUE TITLE
how to get Full text using tweepy

### ISSUE THREAD

**Issue by bilalbutt044** [tweepy/tweepy#974]
i'm using [This](https://github.com/agalea91/twitter_search) script to get tweets. But the problem is that it is not giving full Text. what changes i need to make in this script to get full text ?

**Comment by shuuji3** [comment]
After [this Twitter API update](https://developer.twitter.com/en/docs/tweets/tweet-updates), if you want to get full-text on Twitter response, you need to add a keyword `tweet_mode='extended'` when calling API like this: 
```python
api.search(q='<something to search keyword🔍>', tweet_mode='extended')
```

By adding this keyword, you can get `full_text` field in the response from the API, instead of `text` field. See the example response below:

```python
{
...
 'favorited': False,
 'full_text': 'long tweet text *****************************************************************************************************************************************************************************************************',
 'geo': None,
 'id': 943553795270643712,
 'id_str': '943553795270643712',
...
}
```

**Comment by shuuji3** [comment]
Great! I'll see the question you referred to.

**Comment by converge** [comment]
how can I have ```full_text``` at the Listener ?

```python
    def on_data(self, data):
        data = json.loads(data)
        print(data['extended_tweet']['full_text'])
```
this raises KeyError exception

**Comment by EmmanuelObo** [comment]
I think it's just data['full_text']. Try that out

**Comment by converge** [comment]
@EmmanuelObo thanks mate, unfortunately it didn't work out.

I see on the json output that it's at 
```python
['extended_tweet']['full_text']
```
but I don't know why, I'm not able to catch it.

**Comment by shuuji3** [comment]
@converge Maybe you'd better define `on_status()` method instead of `on_data()`. It enables us to handle status as ordinary `Status` object same as using REST API and not need to parse JSON string by hand.

I could access `full_text` value by following code:

```python
class StreamListener(tweepy.StreamListener):
    def on_status(self, status):
        print('full_text:', status.extended_tweet['full_text'])

stream = tweepy.Stream(auth=api.auth, listener=StreamListener())
stream.filter(track='python -RT')
```

**Comment by Flyer4109** [comment]
Can anyone help me?

I have changed my tweet_mode to 'extended' and I have replaced all instances of '.text' to '.full_text' but there are still tweets that are being truncated. 

My code:

```python
tweets = api.search(q="#gameofthrones", lang="en", count=100, tweet_mode="extended")

for tweet in tweets:
    print("--------------------")
    print(tweet.full_text)
    print("--------------------\n")
```

Example result: 

-----------------------------------------------------------------------------
RT @WiCnet: Time for some news about filming on #GameofThrones season 8. We've got some intriguing new shots of the massive King's Landing…
-----------------------------------------------------------------------------

**Comment by vism2889** [comment]
@Flyer4109 it appears the truncated tweet in the example above is a retweet, which i don't think are affected by the `full_text` unless called unpon specifically for retweets.  so technically the `full_text` you are calling is correct but for the `status` object, not the `retweeted_status` object.

code below is from this link if you wanna browse it a bit:
[twitter community](https://twittercommunity.com/t/retrieve-full-tweet-when-truncated-non-retweet/75542/18)

```python
for tweet_info in tweepy.Cursor(api.search, q=query, lang = ‘en’, tweet_mode=‘extended’).items(100):
if ‘retweeted_status’ in dir(tweet_info):
    tweet=tweet_info.retweeted_status.full_text
else:
    tweet=tweet_info.full_text
```

hope this is helpful.

**Comment by Flyer4109** [comment]
@vism2889 This has worked! Thank you so much I didn't even think about that!

**Comment by vineetjoshi92** [comment]
@numan619 Thanks! This worked like a charm! 👍

**Comment by lovekesh13** [comment]
Hi Guys,

Thank you for putting up this post and helping us beginners.
Can someone also tell me how to put multiple keywords for search. I tried something like this:-
api.search(q=['texas', 'austin'],tweet_mode = 'extended', lang='en', count=200)
but its giving me 0 results. I think it is concatenating everything i put in "q".

**Comment by noufmbrk90** [comment]
I am using this script where shall I add the full text, please help

for tweet in tweepy.Cursor(api.search,q="#موبايلي_ترفع_سعر_شرائح_البيانات",count=10000,
                           lang="ar",
                           since="2017-04-03").items():

**Comment by ValnirJr** [comment]
> try this out. I guess you have to consider the retweeted_status attribute for retweets.
> You have to use the try and except block for both the cases because status object has no attribute extended_tweet for tweets less than 140 characters long.
> 
> ```
> class Stream2Screen(tweepy.StreamListener):
> 	def on_status(self, status):
> 		if hasattr(status, 'retweeted_status'):
> 			try:
> 				tweet = status.retweeted_status.extended_tweet["full_text"]
> 			except:
> 				tweet = status.retweeted_status.text
> 		else:
> 			try:
> 				tweet = status.extended_tweet["full_text"]
> 			except AttributeError:
> 				tweet = status.text
> ```



> try this out. I guess you have to consider the retweeted_status attribute for retweets.
> You have to use the try and except block for both the cases because status object has no attribute extended_tweet for tweets less than 140 characters long.
> 
> ```
> class Stream2Screen(tweepy.StreamListener):
> 	def on_status(self, status):
> 		if hasattr(status, 'retweeted_status'):
> 			try:
> 				tweet = status.retweeted_status.extended_tweet["full_text"]
> 			except:
> 				tweet = status.retweeted_status.text
> 		else:
> 			try:
> 				tweet = status.extended_tweet["full_text"]
> 			except AttributeError:
> 				tweet = status.text
> ```

Thank you very much! You are the only one who has solved my problem about the full text using the Streaming API! You are amazing! THANK YOU!

**Comment by Harmon758** [comment]
I've added [a section in the documentation that covers extended Tweets](https://tweepy.readthedocs.io/en/latest/extended_tweets.html) to supplement [Twitter’s Tweet updates documentation](https://tweepy.readthedocs.io/en/latest/extended_tweets.html).
@converge @Flyer4109 @noufmbrk90 

@converge 
> this raises KeyError exception

That is because `extended_tweet` is not a field in the case that the Tweet is not an extended Tweet.

> I see on the json output that it's at
> 
> ```python
> ['extended_tweet']['full_text']
> ```
> 
> but I don't know why, I'm not able to catch it.

You should be able to use the `extended_tweet` field for extended Tweets.
I'm not sure what you mean by "catch it."

@emmanuelobo 
> I think it's just data['full_text']. Try that out

That is not the case for streams.

@lovekesh13 That's not relevant to this issue.
However, I'm unable to reproduce your issue. I'm getting results with that exact line of code.

**Comment by s2t2** [comment]
https://github.com/tweepy/tweepy/issues/974#issuecomment-383846209 works sometimes, but if `status.retweeted_status.truncated == True` there is no way of getting the original text besides looking up the original tweet separately

**Comment by Harmon758** [comment]
You can simply use the `extended_tweet` attribute of the original Tweet, as the comment you linked does.
See https://tweepy.readthedocs.io/en/latest/extended_tweets.html#handling-retweets.

**Comment by MohammedAlghazi17** [comment]
<img width="672" alt="Capture" src="https://user-images.githubusercontent.com/55874486/143270220-04fb7788-01a8-43e7-b99c-4d8b8df41700.PNG">
 
i am trying to get twitter sentiment using python and i keep getting this error, anyone know why??

**Comment by Harmon758** [comment]
Please don't necrobump old closed issues.
That's also unrelated to this issue. You're most likely using invalid credentials.
