### ISSUE TITLE
Doesn't Refollow a User after Unfollowing

### ISSUE THREAD

**Issue by EmmanuelObo** [tweepy/tweepy#975]
Directly after programmatically following a user and then unfollowing them on the web app, when I re-run the script it doesn't follow the user anymore.

`lebron = api.get_user('KingJames')`
`api.create_friendship('{}/{}/{}'.format(lebron.id, lebron.screen_name, lebron.user_id))`

**Comment by fitnr** [comment]
Try using keyword arguments:
````python
api.create_friendship(user_id=lebron.id, screen_name=lebron.screen_name)
````

Also, Twitter might prevent an identical re-follow within a short time as part of a anti-spam measures.

**Comment by EmmanuelObo** [comment]
I tried keyword args and got this

`AttributeError: 'User' object has no attribute 'user_id'`

I think it may be Twitter preventing re-follows within a short time span.

**Comment by fitnr** [comment]
In this case, the `User` object is `lebron` and `AttributeError` is a local error based on how you're handling it. Try following the code snippet I gave above.

**Comment by EmmanuelObo** [comment]
Yes that’s what I did. But it’s not recognizing one of the attributes either user_id or screen_name. Maybe a typo or something

**Comment by fitnr** [comment]
The `User` object doesn't have a `user_id` attribute. Don't use the `user_id`, do this:
```
api.create_friendship(user_id=lebron.id, screen_name=lebron.screen_name)
```
The important difference is `lebron.id`, not `lebron.user_id`.

**Comment by EmmanuelObo** [comment]
Oops got it. Thanks.
