### ISSUE TITLE
How to filter only tweets from original user with  `stream.filter(follow=['12345'])`

### ISSUE THREAD

**Issue by avloss** [tweepy/tweepy#981]
it looks like `stream.filter(follow=['12345'])` includes tweets at someone and RT, what's the way to get tweets solely from that user?

**Comment by sman-dk** [comment]
I am seeing this too. This is not what I expected. I would be great if only feeds from the user was included (alternatively if one could set it as a parameter (e.g. followRestrict=True etc.)). If I want all the feeds to a given user I could just use the track parameter.

For example if I want the tweets for a very popular user on Twitter this bug is the difference between 10 tweets per seconds instead of one tweet every ten hours.. :-)

**Comment by neilharris123** [comment]
I too am experiencing this. Did anyone find a solution?

**Comment by sman-dk** [comment]
I had to write a few lines of code to filter it out my self. I did not find a solution for this in tweepy.

**Comment by n0pe-sled** [comment]
What did you do to filter it out yourself?

**Comment by nelvintan** [comment]
Looking at Twitter's API it seems like it is not possible to filter tweets from original user out.

**My work around method:**
1. I created a function that checks whether the status object is from original creator or not.
2. I will only print/save tweet if it is from the original creator.

```
def from_creator(status):
    if hasattr(status, 'retweeted_status'):
        return False
    elif status.in_reply_to_status_id != None:
        return False
    elif status.in_reply_to_screen_name != None:
        return False
    elif status.in_reply_to_user_id != None:
        return False
    else:
        return True
```
```
class MyStreamListener(tweepy.StreamListener):

    def on_status(self, status):
        if from_creator(status):
            try:
                # Prints out the tweet
                print(status.text)
                # Saves tweet into a file
                with open("Test.txt", 'a') as file:
                    file.write(status.text)
                return True
            except BaseException as e:
                print("Error on_data %s" % str(e))
            return True
        return True

    def on_error(self, status_code):
        if status_code == 420:
            print("Error 420")
            #returning False in on_error disconnects the stream
            return False
```

**Comment by mathemaphysics** [comment]
If the API key I'm using for OAuth is linked to my personal Twitter account, I seem to only get tweets from users my account is following. How do I stream all tweets filtered globally, and not just the from the users my account follows?

**Comment by Harmon758** [comment]
In short, this isn't possible natively to Twitter's API.
The only parameter the [statuses/filter endpoint](https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter) has for following a specific user is `follow`, which:

> For each user specified, the stream will contain:
> 
> - Tweets created by the user.
> - Tweets which are retweeted by the user.
> - Replies to any Tweet created by the user.
> - Retweets of any Tweet created by the user.
> - Manual replies, created without pressing a reply button (e.g. `@twitterapi I agree`).

See https://developer.twitter.com/en/docs/tweets/filter-realtime/guides/basic-stream-parameters.

You'll have to filter out other Tweets yourself.

@mathemaphysics That is not related to this issue, but I'm unable to reproduce this using `Stream.filter`.
The [statuses/filter endpoint](https://developer.twitter.com/en/docs/tweets/filter-realtime/api-reference/post-statuses-filter) is not limited to a specific user context like the now deprecated and retired User Streams used to be.
