### ISSUE TITLE
stream.filter(async=True) does not work with coroutines

### ISSUE THREAD

**Issue by NNTin** [tweepy/tweepy#983]
Doing the following is not possible:

```
async def createstream(self):
  self.stream.filter(follow=self.twitterids, async=True)
```
with `self.stream` being an object from the class tweepy.Stream.  

The interpreter is confused. There are 2 `async`'s used differently. Once as a keyword for a coroutine and once as a parameter name. The interpreter does not recognize the latter as a parameter name.

async is a keyword. And thus you cannot set the parameter to true since it's not interpreted as an parameter. You need to create an inherited Stream class and overwrite stream.filter() where you have set async to true. Then it works.

**Comment by Harmon758** [comment]
You're correct that [async is now a reserved keyword in Python 3.7](https://docs.python.org/3.7/whatsnew/3.7.html).
This was fixed in https://github.com/tweepy/tweepy/commit/18dad6f818c377fdfc0d4f8cf0fb131dec958bb5 (#1042) as part of Tweepy 3.7.0 by simply changing the name of the kwarg.
