### ISSUE TITLE
how many tweets can i get from one screen_name with user_timeline?

### ISSUE THREAD

**Issue by SuperYm** [tweepy/tweepy#986]
i can only get about 3100 tweets from one screen_name,tweepy has a limit or my api auth has a limit? 
how can i get all tweets from one screen_name?
some one help please!!!!!

**Comment by ZeerakW** [comment]
The Twitter API has a limit of serving at most the last 3200 tweets from any given user. See https://twittercommunity.com/t/tweet-index-limits/49653

**Comment by mrgloom** [comment]
Any way to overcome this limitation?

**Comment by ZeerakW** [comment]
No. Even when you view on the web interface you’re only presented with the latest 3200 tweets (to the best of my knowledge), so there is no way to get around it programmatically. 

You can ask users in question to request their full tweet history and send it to you though. That will give you all that they have ever written.

**Comment by mrgloom** [comment]
For example from https://twitter.com/schwarzenegger I grabbed 3219 tweets(last tweet is at 16-01-2013), but he have 5746 tweets in total.
But surprisingly manually scrolling down I can get only at this 2016 year post:
https://twitter.com/Schwarzenegger/status/741006919805079552

**Comment by Harmon758** [comment]
This is a limitation with Twitter's API:
> This method can only return up to 3,200 of a user's most recent Tweets.

See https://developer.twitter.com/en/docs/tweets/timelines/api-reference/get-statuses-user_timeline.

Currently, the only way to get older Tweets is via the [premium](https://developer.twitter.com/en/docs/tweets/search/overview/premium) or [enterprise](https://developer.twitter.com/en/docs/tweets/search/overview/enterprise) search APIs.
