### ISSUE TITLE
How to access the media?

### ISSUE THREAD

**Issue by vae9211** [tweepy/tweepy#990]
with tweepy i can get a json dict has a media url
like 'https://twitter.com/twitter/statuses/951433614029475844'
but how can i access the media?

**Comment by Harmon758** [comment]
Twitter provides the media in a Tweet using an [Entities object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object#entitiesobject). 
You would access the [Media object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/entities-object#media) in Tweepy using a Status/[Tweet object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/tweet-object.html) with something like `status.entities["media"][0]`.
You can then use the Media object to get its URL, e.g. `status.entities["media"][0]["media_url"]` or `status.entities["media"][0]["media_url_https"]`.

This is what Twitter's API provides and what you can access through Tweepy, and you can go to that URL to access the media. If you're asking about how to programmatically access the media itself, you can use the given URL and a library like requests, but that's currently outside the scope of this library.

Note, for videos and GIFs, the Media object only provides the thumbnail in the Entities object.
For those media types, you'll have to use the [Extended Entities object](https://developer.twitter.com/en/docs/tweets/data-dictionary/overview/extended-entities-object) to get the URL for the video or GIF.
You would access it in Tweepy using a Status object with something like `status.extended_entities["media"][0]["video_info"]["variants"][0]["url"]`.

For more information, see the linked Twitter API documentation.

**Comment by KezangLoday** [comment]
ok
