### ISSUE TITLE
Is tweepy still actively maintained?

### ISSUE THREAD

**Issue by ZeerakW** [tweepy/tweepy#991]
Considering the number of open issues and PR's, and the number of trivial ones to accept (updates to documentation, etc.) that haven't been dealt with, I'm just wondering if it's still being actively maintained or if it would be better to switch to another library? Right now it seems like there's one active maintainer @Aaron1011. It might make sense to add more to help deal with the number of issues and PR's.

**Comment by fitnr** [comment]
See #792 for several offers to help.

**Comment by Harmon758** [comment]
I've closed and labeled a significant number of issues today and will continue to do so.
I'll also be going over and reviewing open PRs to be merged.
