### ISSUE TITLE
Having trouble using list_timeline() lately

### ISSUE THREAD

**Issue by ssp0929** [tweepy/tweepy#998]
```python
for status in tweepy.Cursor(api.list_timeline, owner_screen_name=list_owner, slug=list_name, since_id=last_run_id).items():
```

Keeps raising 404 exceptions. This code has worked in the past, I made sure the list I was scrubbing from didn't change in terms of the slug name or the list owner handle.

I also isolated list_timeline() away from a Cursor call and it still didn't work on its own. Tried adding other lists, public lists, private lists, nada. All don't work.

Did Twitter mess with their endpoints or something?

**Comment by michaelgodshall** [comment]
@ssp0929 Did you find a solution for this?  I've been seeing 404 exceptions as well and haven't been able to track down the source of the problem.
